### ISSUE TITLE
Get robolectric tests to verify that Service pointers for NULL are properly checked

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1024]
We can instantiate activities and services with robolectric test cases. 

The testcase should emit intents against MainApp and verify that NPE are not triggered.

**Comment by crankycoder** [comment]
This should mitigate problems like #1023 in the future and give us a template for how to make sure other services do not suffer from runtime NPE.

**Comment by garvankeeley** [comment]
Remove from 1.0 milestone?
