### ISSUE TITLE
Get F-Droid build updated to 0.40.x

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1025]
F-Droid currently only has 0.30, we should get this updated to get some testing from F-Droid users prior to the play store release

**Comment by crankycoder** [comment]
So a couple things:

We need to get binaries of our fork of osmdroid and simplekml uploaded into JCenter.  I've opened an account, but have yet to upload binaries.

Notes for myself - docs to upload binaries are here:

https://bintray.com/docs/uploads/uploads_howdoiuploadmystufftobintray.html

The osmdroid fork we have will need to be manually packaged up and uploaded into jcenter.

**Comment by crankycoder** [comment]
osmdroid is now pulled directly into our sourcetree as we've had to make nontrivial changes.

SimpleKML is being pulled from the Mozilla Services ivy repository now.

**Comment by ghost** [comment]
I suppose the 1.0 milestone indicates that publishing on F-Droid is planned for 1.0 as well?

**Comment by cimm** [comment]
I always look on F-Droid first, downloaded the application from F-Droid and noticed the screenshots are different in the Play Store. Ah, right, F-Droid is on v0.30 and the latest release here is v0.102. Are there any plans to keep the F-Droid repo in sync?

**Comment by crankycoder** [comment]
I just cut release tag v1.2.1 - which is basically the same as the 1.0.0.0 build.

The main change is that we now support doing builds for F-Droid.  A merge request is pending in gitlab, after that - we should be live on the F-Droid store.

https://gitlab.com/fdroid/fdroiddata/merge_requests/338

**Comment by crankycoder** [comment]
We haven't got into F-Droid quiet yet, keeping this open until we show up there.

**Comment by crankycoder** [comment]
F-Droid build output gets emitted to a wiki.  v1.2.1 should appear sometime on Sunday Nov 2. https://f-droid.org/wiki/page/org.mozilla.mozstumbler

**Comment by hannosch** [comment]
Well, the build log at https://f-droid.org/wiki/page/org.mozilla.mozstumbler/lastbuild says:

"no space left on device"

which sounds like a general problem.

**Comment by crankycoder** [comment]
Breaking the build box > breaking the build. 

I think we deserve points for this one. 

I'll contact the fdroid folks. 

@hannosch,  you do PTO badly. :-)

**Comment by crankycoder** [comment]
Woot! 

We're live on F-Droid.

https://f-droid.org/repository/browse/?fdfilter=mozstumbler&fdid=org.mozilla.mozstumbler

Note that the rev 1.2.1 is virtually identical to the v1.0.0 release on Google Play.  

The next stable release will have the same version and tag across Google Play, F-Droid and Github.
