### ISSUE TITLE
Ensure that string length in metrics will survive L10n

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/MozStumbler#1028]
The layout of the metrics table is a little tight. What will happen when longer strings are introduced?

**Comment by WhiteHatTux** [comment]
This actually happens in german. shortly after an upload it says 
"Letzer upload: vor einem Augenblick" (Last upload: a moment ago)
Now the second part of that string is to long and interferes with the next line, when the automatic line break is applied after "einem".

**Comment by Djfe** [comment]
@elsuggo I'm volunteering for updating the German translation, I've just waited for some if the latest issues to be fixed (lots of string changes)

String that would fit better in this case:
"Gerade eben"

**Comment by WhiteHatTux** [comment]
Great then. Probably easier to use a shorter string if possible than to change the whole layout. :-) 

Am 20. Oktober 2014 10:52:51 MESZ, schrieb Felix Baumann notifications@github.com:

**Comment by cascheberg** [comment]
The metrics layout was improved in #1091. The width of the metrics columns is not fixed and will adjust to the string length, as long as the row width does not exceed the width of the drawer. Additionally, in that case, strings can now be multiline without breaking the layout.
Translation problems regarding the upload time are discussed in #1066.

**Comment by garvankeeley** [comment]
Closing, various UI bugs addressed this.
