### ISSUE TITLE
Reduce collection frequency on stumbler

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1039]
We need to reduce the collection frequency on the stumbler down to ~30m.  We don't want ichnaea to keel over on initial google playstore release.

cc/ @hannosch

**Comment by cascheberg** [comment]
A note here: currently WiFi is set to only scan every 5 seconds. That is ~42m at 30km/h.

**Comment by hannosch** [comment]
I think there are two thresholds. We only collect data if you have at least moved X meters (currently 10m, proposed to be increased to 30m). And additionally only collect data at most every X seconds (which I thought was currently 1s).

**Comment by garvankeeley** [comment]
GPSScanner.java currently has 10m and 1sec

**Comment by cascheberg** [comment]
I was referring to `WifiScanner` that has a scheduler to run `getWifiManager().startScan()` every 5 seconds only. When that is finished, it sends a `ACTION_WIFIS_SCANNED` intent to the `Reporter`. That means that if you travel fast, currently only every ~4th observation contains WiFi data at all.
The cell scanner is scanning every 1 second.

**Comment by garvankeeley** [comment]
The android wifi layer actually seems to scan closer to every minute. That
5 second scan does not trigger the hardware to scan any faster.

**Comment by cascheberg** [comment]
I really do not know anything about Android (hardware) internals.
But: when I change the MozStumbler WiFi scanner to scan every second, it happens that the number of WiFis displayed in MozStumbler even changes within that time, and the native Android WiFi listing then also updates at that frequency (on my Nexus 4).

**Comment by Djfe** [comment]
even though this got closed:
in 0.40.4.0 I recognized that if I ran/drove too fast then I often got points without wifi data (cell only report: blue square)

**Comment by crankycoder** [comment]
Marking this as a duplicate of #1042
