### ISSUE TITLE
Display of drifting location fix 

### ISSUE THREAD

**Issue by billmaggs** [mozilla/MozStumbler#1047]
Mozstumbler (0.40.4.0) shows track of locations while stationary, as what looks like GPS fix rifts. Confusing feedback to user. Should just move a single location dot  as fix shifts. Attachment shows me sitting on my butt but a trail of movement: 

![screenshot_2014-10-20-12-38-11](https://cloud.githubusercontent.com/assets/798731/4707941/a4f6c83e-5892-11e4-9c4b-187c4baf4968.png)

**Comment by garvankeeley** [comment]
Related to https://github.com/mozilla/MozStumbler/issues/763

**Comment by garvankeeley** [comment]
This effect is reduced by https://github.com/mozilla/MozStumbler/pull/1042

**Comment by garvankeeley** [comment]
I have no upcoming plans for GPS filtering (if the GPS says you have moved 30meters, the app doesn't do further verification of that). But if someone wants to take this on, or knows of out-of-the box GPS filtering algorithms that are available, we would add it in.

**Comment by Djfe** [comment]
it's just that the GPS needs some time at the start of the stumbling to get more accurate, if you move further it will get full accuracy

you could use another GPS app walk around a bit and then start MozStumbler and this effect won't occur, because the GPS was/is in use already...

**Comment by hannosch** [comment]
I blame the constant earthquakes in San Francisco for this, maybe it's the building that's moving ;)
