### ISSUE TITLE
Crash on low battery

### ISSUE THREAD

**Issue by narfg** [mozilla/MozStumbler#1048]
I got the message "MozStumbler has stopped" right when the battery level gets low (<15%) on two occasions in the last few days. The app was in the background and not actively scanning. This error seems to be intermittent and I can't reproduce it consistently. I'm sorry I can't provide more detailed logs.
Version 0.40.4.0 on Android 4.4.4

**Comment by garvankeeley** [comment]
Yeah, that is the bug, it is fixed in the next release.

**Comment by narfg** [comment]
Oh, I missed that this was already reported and fixed in #1026. Great work!
