### ISSUE TITLE
Opening developer dialog stops scanning

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1061]
Opening the developer dialog stops the scanning process. @garvankeeley you already added a TODO about moving this. Now that the dialog contains the map tile options, it would be nice to have that fixed. (Is it easy to fix?)

**Comment by garvankeeley** [comment]
good point, i'll fix now, its quick to change...

**Comment by garvankeeley** [comment]
Is fixed in 0.41 build
