### ISSUE TITLE
unused translations

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1064]
values-bn-rBD/strings.xml:6: Error: "action_upload_observations" is translated here but not found in default locale [ExtraTranslation]
values-bn-rBD/strings.xml:10: Error: "view_map" is translated here but not found in default locale [ExtraTranslation]
values-bn-rBD/strings.xml:13: Error: "wifi_disabled" is translated here but not found in default locale [ExtraTranslation]
values-es/strings.xml:16: Error: "wifi_info" is translated here but not found in default locale [ExtraTranslation]
values-es/strings.xml:19: Error: "cells_info" is translated here but not found in default locale [ExtraTranslation]
values-bn-rBD/strings.xml:19: Error: "coordinate" is translated here but not found in default locale [ExtraTranslation]
values-es/strings.xml:21: Error: "num_used" is translated here but not found in default locale [ExtraTranslation]
values-es/strings.xml:22: Error: "num_visible" is translated here but not found in default locale [ExtraTranslation]
values-es/strings.xml:44: Error: "about_legal_icons8" is translated here but not found in default locale [ExtraTranslation]
values-bn-rBD/strings.xml:49: Error: "upload_observations_button" is translated here but not found in default locale [ExtraTranslation]
values-bn-rBD/strings.xml:50: Error: "upload_observations_dialog_title" is translated here but not found in default locale [ExtraTranslation]
values-bn-rBD/strings.xml:56: Error: "upload_observations_data_size" is translated here but not found in default locale [ExtraTranslation]
values-es/strings.xml:59: Error: "drawer_map_option_show_observation_type" is translated here but not found in default locale [ExtraTranslation]

**Comment by Djfe** [comment]
We wouldn't have this kind of hassle with L10n/Crowdin...

**Comment by Djfe** [comment]
I have time to do that tomorrow ;)
Easy but takes some time.
Will resort the English strings then as well.

**Comment by rodmoreno** [comment]
Would you be useful Commits (7ab3aae & 1ac300e) within my pull #1033 ? I reversed since the Travis-CI threw me some errors because the file activity_main.xml these strings were used.

**Comment by Djfe** [comment]
I don't know how to just append two commits, so I will just try to sync every strings.xml with the source one

**Comment by Djfe** [comment]
@garvankeeley are there any references in the old main_xml to these unused strings so that I cannot delete them without getting compliation errors?

I haven't tested it, yet. But @rodmoreno has, and if he is correct then there are still some bits of pieces left from the old main GUI/map GUI concept (where the map GUI was another activity from the main one)

**Comment by cascheberg** [comment]
@Djfe The old main GUI `activity_main.xml` still exists (although I do not know why). You can find all unused translations really quick (fix in less than 10 min) if you use Android Studio (for example), it has a built-in function to find them.

**Comment by Djfe** [comment]
can you do it for me then? I don't have Android Studio installed.
I guess there should be a bigger cleanup that removes unused files of the old gui

**Comment by garvankeeley** [comment]
that old main activity xml should be deleted yes
