### ISSUE TITLE
Last Upload Time displaying a time in zh-CN script in zh-TW locale (l12y?)

### ISSUE THREAD

**Issue by petercpg** [mozilla/MozStumbler#1066]
Hi, 
I just found the time in "Last Upload Time:" are not localizable so it displays values as "never", "片刻之前", "19 小时 前" (19 hours ago in Simplified Chinese) rather than strings fully localized in Traditional Chinese. Probably a library issue?

Screenshot: http://imgur.com/dUA1sHq

Tested in 0.41.0.0 on Asus Zenfone 5 LTE (Android 4.4.2 KOT49H) and Nexus 7 2013 (Android 5.0 LPX13D)

**Comment by cascheberg** [comment]
That is a library named `PrettyTime`.
There is a problem with the German translation as well.
I prefer an accurate date to figure out the time diff myself, so I think one might just as well remove that formatting. @garvankeeley ?

![bug](https://cloud.githubusercontent.com/assets/3845150/4734865/f5267222-59d8-11e4-8274-0c63ab37eaa8.png)

**Comment by garvankeeley** [comment]
I like the PrettyTime, and we should investigate the translation issue, both for missing translations and for  fitting the translation better. For now I am just going to do:

if (Locale.getDefault().getLanguage().equals("en")) {
                    lastUploadString = new PrettyTime().format(new Date(lastUploadTime));
 } else {
                    lastUploadString = DateTimeUtils.formatTimeForLocale(lastUploadTime); 
 }

**Comment by petercpg** [comment]
I read the time messages used by PrettyTime at [Here](https://github.com/ocpsoft/prettytime/tree/master/core/src/main/java/org/ocpsoft/prettytime/i18n) and it seemed no problem. 
Could that be a locale fallback issue?

**Comment by garvankeeley** [comment]
We should ensure we are using the latest version. The version we get is from the Maven repo, which is not always up-to-date.

**Comment by cascheberg** [comment]
Wouldn't it be just a few lines of code to check for
- x seconds
- x minutes
- x hours
  else: display just the date

**Comment by cascheberg** [comment]
@petercpg "Last Upload Time" strings should now be fully localizable. Please check the translation and close this issue.

**Comment by petercpg** [comment]
Will close this issue as soon as #1373 is merged. :)
