### ISSUE TITLE
Investigate name change to Mozilla Stumbler

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1068]
Branding is against shortening Mozilla to Moz on actual products. Let's see if this is do-able.

**Comment by garvankeeley** [comment]
On 2.3.3 480 px wide screen: 
https://www.dropbox.com/s/pcd4a6pby5tf1q0/Screenshot%202014-10-22%2015.41.34.png?dl=0
https://www.dropbox.com/s/m3p18y6v2r7giqy/Screenshot%202014-10-22%2015.41.24.png?dl=0

**Comment by garvankeeley** [comment]
On 4.4.4 540px wide Nexus 5:
homescreen (not cut off, 2 lines)
https://www.dropbox.com/s/zdcd28hraqsxujf/_20141022_154345.JPG?dl=0
ActionBar (not cut off)
https://www.dropbox.com/s/s7th7ege5j0pb6n/_20141022_154450%20%281%29.JPG?dl=0
App listing screen:
https://www.dropbox.com/s/ivcvh9fnyx1u9d3/_20141022_154427.JPG?dl=0

**Comment by garvankeeley** [comment]
2-line action bar title works on a wide range of APIs:
https://www.dropbox.com/s/nmfy1ffuuljnqmy/Screenshot%202014-10-22%2016.05.53.png?dl=0

**Comment by cpeterso** [comment]
"Mozilla Stumbler" looks much better.

**Comment by garvankeeley** [comment]
Any ideas about scenarios I should check (screen sizes, API levels, etc.) and I'll try set up emulators accordingly.

**Comment by gpoo** [comment]
@garvankeeley Possibly the one that has "Mozilla Stumbler" and the "Start Scanning" button, rather than the icon with pause.

Update: In my phone currently reads as "MozStu...    Start Scanning".

**Comment by gpoo** [comment]
I should have mention Android 2.3.7 (API level 10).  The "START SCANNING" appears only the first time I run the application, after that it switches between the icons for play and pause.

I guess it would say "Mozill..." or "Mozilla..." followed by "START SCANNING". Maybe the uppercase might not help to save some space with the kerning (if it were an issue).

Nevertheless, Mozilla Stumbler sounds much better.
