### ISSUE TITLE
Disable "keep screen on while in map" when in low power situations

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/MozStumbler#1069]
When keep screen on while in map is selected and the device is under 15% battery the display never turns off and since it is the foreground application the current location is still requested. Allowing the screen to sleep when in low power mode seems to disable the location requests.

**Comment by garvankeeley** [comment]
Good catch. Under 15% we should shut off the screen.

**Comment by garvankeeley** [comment]
Changed this pref to 'Keep screen on while scanning', no reason to keep it on otherwise.
