### ISSUE TITLE
Getting HTTP 400 errors in log

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1076]
![screenshot_2014-10-22-23-29-20](https://cloud.githubusercontent.com/assets/5495083/4747944/64488f32-5a65-11e4-871e-2949dbb2907b.png)

**Comment by garvankeeley** [comment]
@hannosch no doubt the radio:0 is the problem in the stumble. I recall there was an old bug about how to handle this, I'll have to take a look

**Comment by hannosch** [comment]
Indeed, for the submit API, radio needs to be a string and one of "gsm", "umts", "cdma" or "lte". If it is something else, just drop the entire cell record, as it's too incomplete for us to make any sense of.
