### ISSUE TITLE
0.40.4.0 upload errors

### ISSUE THREAD

**Issue by httpless** [mozilla/MozStumbler#1081]
This is a follow on for #989 which I did not spot was closed when I comment

I can confirm that some data is not being uploaded fully from anecdotal evidence. Following a recording session only some of my data was recorded, despite witnessing mozstumbler recording data in areas which are unmarked in the map.

https://location.services.mozilla.com/map#14/53.3295/-6.2122

In this map, I did Sandymount strand and the main roads of the area marked Irishtown Nature Park. Prior to the mapping neither areas had been recorded. This was done as one continuous mapping

On an aside, I have driven the road marked "Sandymount Strand" several times now and this is the first time that the road was added to the map.

I am running similar specs to grrrrr: Samsung Galaxy S4 with Cyanogen Mod 11 M11 and Mozstumbler 0.40.4.0

**Comment by garvankeeley** [comment]
Could it be https://github.com/mozilla/MozStumbler/issues/1076
You would need to run 0.41.0.0 to see the log message clearly.

**Comment by crankycoder** [comment]
Upload issues should be sorted out as we weren't handling HTTP 400 errors properly before.

**Comment by httpless** [comment]
@crankycoder  yes, so far so good but does this also explain why certain roads need to be driven many many times to be recorded?
