### ISSUE TITLE
disable MLS location layer for cell-only reports

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1088]
it would be nice to be able to disable red dots for cell-only reports because they are so inaccurate that they draw lines all over the screen which doesn't look to good (-> maybe another checkbox setting)
![2014-10-23 14 36 14](https://cloud.githubusercontent.com/assets/5685512/4756961/8cb9a412-5ad1-11e4-888b-7f0e809cb768.png)

**Comment by garvankeeley** [comment]
It is intended to look bad, in a sense, since the coverage is bad. It provides feedback to the user of where the cell towers are, where coverage can be improved by re-stumbling, and give an indicator of the value of your contribution as those lines improve over time.

**Comment by Djfe** [comment]
ok, will close this now
