### ISSUE TITLE
Max zoom out level should be dependant on screen size

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1089]
why did the lowest zoom level get reduced so much? I cannot scroll through countries efficiently anymore now (takes too long)

**Comment by garvankeeley** [comment]
It loads too much tile data, consuming network bandwidth. The app isn't intended for general viewing of worldwide coverage (the website is better for that, maybe we should link to it in some way), only for the local area where the user will be stumbling.

**Comment by Djfe** [comment]
ok, will close this now

**Comment by Djfe** [comment]
Actually I think you should still leave this to the user
The user ist still able to disable the map

And it consumes less bandwidth the further you drive
I'm riding a train at the moment and the zoom level is far to small to see the complete route and going through all recorded points takes far more bandwidth than on another zoomlevel where i can see more... (only a few big tiles need less bandwidth than a lot of small ones, it would only take more bandwidth if I would switch the zooming level all the time...)

**Comment by garvankeeley** [comment]
I see the bug. We should configure this based on the screen size.  On the Nexus 5 zoom out shows 25x25 km, on a small screen device (the Samsung Duos 320 x 480 I have) it shows 5x5 km.

**Comment by VolMi** [comment]
On my S4 mini (540 x 960) and using version 0.99.0.0, my max Field of View is at most about 5x5 km. This is really unpleasant. I used to peek nation- continent- and even worldwide quite regularly and liked it.

**Comment by garvankeeley** [comment]
Did you notice _any_ difference with the new build? Maybe we aren't checking screen size in a portable way.

**Comment by Djfe** [comment]
People complaining about too much data consumption should know that scrolling through the map needs to load new tiles...

That's like people in the ios app store that complain in their reviews about swiftkey that it needs full access to what you type in.
I was like WTF when I read that :D , I mean it was like this forever on Android and I never heard anyone complaining because it just makes sense that it needs to know what you type in to give you proposals what you might want to type in. And now that the app came out on IOS this is what new users are complaining about lol.
(sorry for a topic but it's a fitting example)

As a dev you should at least expect users that have common sense... (especially for such a specific app like this one)
you already have tiles that are only 25% as big as before. Pls let us the choice what we want and what not.
I don't have always the time to check the online map to see what the world looks like...
And I have wifi to it doesn't consume data to load an endless number of tiles for me.

People that have newer used the app will see the ocean at 0,0 without being able to scroll out far enough to see where they are exactly (if GPS is off/if there isn't any GPS fix, yet.)

I will check the new build tomorrow if the size is at least bigger than before ;)

**Comment by garvankeeley** [comment]
The map view suits the primary use case of the app, to stumble from the current location. 
If the user is in one part of the world, and needs to check the MLS coverage some large distance away (certainly more than can be stumbled from the current location), then the website is a better place to check.
That said, a setting for the minimum zoom level would be fine by me if someone wants to add that.

If someone has never used the app, then I don't see why they would see 0,0. The map view has no geolocation filter, so if the device has ANY form of geolocation (even geoip), then it should show their vicinity.

**Comment by VolMi** [comment]
@garvankeeley: Nothing has changed with 0.99.0.0.

I also agree to every word by Djfe. I don't see the compelling reason to hide the world in the app. The online map is no fun on mobile but the Stumbler view is actually great, apart from the arbitrary limitation.

**Comment by garvankeeley** [comment]
I just re-read and saw you are a 540px screen, sorry, no change for that screen size, didn't realize your viewport would be quite that small.

**Comment by VolMi** [comment]
With the new release I can confirm a slightly larger max field of view.

**Comment by crankycoder** [comment]
The 1.0 release should be slight better with this commit: https://github.com/mozilla/MozStumbler/commit/9085648786b4a0a2ae111b303c0e4449f6db0ac6
