### ISSUE TITLE
log errors cut off by dots

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1090]
similar to #695 
I think log errors should an independent counter
->it could be helpful to be able to read the full error log entry

they are not as long as normal entries that contain reports and they are not occuring as often

I think they should get an independent counter that reaches up to 50
1st error to 50th error gets displayed fully the following ones get cut off by dots

another approach that could work out better:
only cut off duplicated errors:
if a similar log entry exists in the last 10 log entries -> then cut it off by dots
-> you can see the full error but if you have 10 http errors with the same code in a row 9 of them will get cut off by dots and only the first one will be displayed fully ;)

**Comment by Djfe** [comment]
To show what I'm talking about:
![2014-10-23 14 40 30](https://cloud.githubusercontent.com/assets/5685512/4757861/81434ad0-5ada-11e4-8c70-eb4d780ae2cf.png)

**Comment by Djfe** [comment]
Another example:
![2014-10-24 22 19 04](https://cloud.githubusercontent.com/assets/5685512/4777780/2073f1e8-5bd7-11e4-81fe-c22148c8564d.png)

it doesn't make sense to increase the truncating counter for such short logs, they are fully shown
pls make it only increase and be used for log entries above a certain number of characters

**Comment by garvankeeley** [comment]
Closing, I think this ok for now. Re-open if there is more we should look at here
