### ISSUE TITLE
Batch upload measurements

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#11]
Depends on AP database issue #3.

We should not upload measurements so frequently. We should save the scans to a local DB and batch upload them after X unique new APs (1000?) or Y hours (24?), whichever comes first.

When batch uploading, we should preserve the groups of APs seen at the same time (to aid server gridding), not just a big flat list of APs.

The submit API docs:
https://mozilla-ichnaea.readthedocs.org/en/latest/#service-1

**Comment by dougt** [comment]
i just merged a fix for this.
