### ISSUE TITLE
Hook accelerometer to enable/disable wifi/cell scanning

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1107]
We should really try to minimize battery consumption.

If we hook the accelerometer to enable the wifi and cell scanning for a small fixed window of time, we can reduce the power consumption of the stumbler when the application is running but the device is not actually moving.

**Comment by garvankeeley** [comment]
Battery-Saving related items seems like it could be a category.

**Comment by Djfe** [comment]
This is a part of #333

**Comment by garvankeeley** [comment]
#1270 fixes this
