### ISSUE TITLE
Battery Saving: minimum battery level setting (currently hard-coded to 15%)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1109]
Have an option to set the minimum level to any value, for me, it would be 50%. 
I charge my phone daily, and don't mind committing the first 50% of consumption to the app, but after that, I want the rest of the charge for other purposes.

**Comment by Djfe** [comment]
Thx, was hoping for this!
Finally a feature that allows me to disable the battery limit ;)
0% -> it stops only while my device is shutting down

I stumble only actively
So this was a bit stupid if I was charging my device in my car while stumbling and my device was low on battery (after a day of work/studying/whatever)
-> stumbling stopped when charging stopped
Scenario:
I connect my device to the charging cable
I start the engine of my car, which briefly connects and disconnects the power source so thaf I have to start stumbling manually again (listener:is on battery && is battery% below 15%)

**Comment by garvankeeley** [comment]
#1261 fixes this
