### ISSUE TITLE
Map not updating with scanned locations

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/MozStumbler#1129]
Using v0.42.0.0 on a Galaxy S5

I have seen times when the map displays scan locations spottily. Locking the phone and unlocking the phone displays the scan locations correctly.
![screenshot_2014-10-25-16-19-39](https://cloud.githubusercontent.com/assets/250273/4799280/3c7931e6-5e1b-11e4-9790-22fe4f1a31e7.png)
![screenshot_2014-10-25-16-19-46](https://cloud.githubusercontent.com/assets/250273/4799281/3c796c06-5e1b-11e4-8ef5-4b3116b45f93.png)
![screenshot_2014-10-27-09-22-47](https://cloud.githubusercontent.com/assets/250273/4799282/3c7aeae0-5e1b-11e4-984e-5fb9a68cdb17.png)
![screenshot_2014-10-27-09-22-56](https://cloud.githubusercontent.com/assets/250273/4799279/3c78fe9c-5e1b-11e4-845b-f82a17b2a700.png)

**Comment by garvankeeley** [comment]
I assume zooming in and out didn't trigger a redraw?

**Comment by kbrosnan** [comment]
I did not try that.

**Comment by garvankeeley** [comment]
Zooming triggers a full point redraw, or panning so the points aren't shown and then panning back. Actually those are two different drawing paths, so it would be cool to know if that behaves differently, but I am guessing this is tricky to repro.

**Comment by crankycoder** [comment]
I'm still getting this on the dev branch after #1135 was merged.  I'm seeing exactly the same behavior as @RexWheeler describes in https://github.com/mozilla/MozStumbler/issues/1087#issuecomment-60713970 

When I'm centered, the map moves with my position remaining centered, but no new dots are drawn.

Zoom in and zoom out do not seem to affect dots from showing up until I hit a threshold where the hashing of multiple dots comes into play.

**Comment by crankycoder** [comment]
~~I'm pretty sure that this bug and #1087 are the same bug.~~

Nope, this ended up being a pixel grid hash bug.

**Comment by garvankeeley** [comment]
@kbrosnan I think you'll see this fixed now, looks ok?

**Comment by garvankeeley** [comment]
I'll be optimistic and close for now, please re-open if it happens again
