### ISSUE TITLE
Consider reverting new collection rates.

### ISSUE THREAD

**Issue by ferongr** [mozilla/MozStumbler#1139]
(Image removed)

In this example, the stumbling area is a densely populated urban location with multiple apartment blocks each having anywhere from 5 to 50 apartments, Every segment of the main road (Αγίων Πάντων) between intersections can potentially have up to 60 access points evenly distributed. The lower sampler rates may potentially cause the stumbler miss many of them (also taking in account that wireless signals do not penetrate the brick and concrete structures well, reducing the window a device can capture the APs).

**Comment by hannosch** [comment]
My plan was to revert back to the 10m threshold (from the now 20m), once we have the app in the play store and got an idea of what kind of traffic and users we are getting from that. It's a temporary measure to help reduce the potential traffic we are getting on the service end.

**Comment by ferongr** [comment]
Okay, thanks for the heads up.
