### ISSUE TITLE
Errors while saving tiles running on Galaxy Nexus

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1140]
![2014-10-27](https://cloud.githubusercontent.com/assets/4829/4812629/1a6a1294-5ec2-11e4-9809-fe55c3bfe6e8.jpg)

**Comment by garvankeeley** [comment]
If we can't repro, don't worry about this for now. I saw it once, on 1 device. No negative side effects.

**Comment by garvankeeley** [comment]
Closing, can't repro
