### ISSUE TITLE
nexus 7 2013 lte: can't install play store, make android.hardware.telephony required=false

### ISSUE THREAD

**Issue by edt-xx** [mozilla/MozStumbler#1150]
I have a nexus 7 2013 lte.  The Updated Stumbler app will not install.  Build issue?  or is there another reason?

**Comment by garvankeeley** [comment]
From the play store, or from github?

**Comment by edt-xx** [comment]
playstore

**Comment by garvankeeley** [comment]
This is a bug, will look into this. Is there any info in the message you see?

**Comment by edt-xx** [comment]
"This item is not compatible with your device" in the drop down to select the device then when I try to install in via play in chrome.

**Comment by garvankeeley** [comment]
Ok, I assume I missed a checkbox in the play store listing, i'll dig through the settings and find it

**Comment by edt-xx** [comment]
The device is up to date with 4.4.4, is unlocked and rooted.

**Comment by edt-xx** [comment]
This is the fastest I've even got support after opening a bug.
Thanks!

**Comment by edt-xx** [comment]
Just to confirm that v0.102 seems to work fine when sideloaded from github

**Comment by garvankeeley** [comment]
I am stumped. We have no nexus devices excluded. 

Our play store listing of nexus devices supported:
![screenshot 2014-10-29 13 05 30](https://cloud.githubusercontent.com/assets/5495083/4830423/d6fbd2be-5f8d-11e4-85b5-f14bedeb70b8.png)

**Comment by garvankeeley** [comment]
I see, our manifest:
uses-feature android:name="android.hardware.location.gps" 
should have  android:required="false"

**Comment by garvankeeley** [comment]
Oh my brain. Of course we have this, we only accept pure-GPS locations.

I assume your device is missing hardware GPS?

**Comment by edt-xx** [comment]
No.  It has a hardware gps.  It works too.  I use it often.

**Comment by garvankeeley** [comment]
I am sure it relates to the app manifest, but I can't see what the problem is, searching...

**Comment by edt-xx** [comment]
This is probably another issue but, even though my tablet has lte enabled and other apps see cell towers, stumbler does not look to be collecting cell tower info (I sideloaded the app).

**Comment by Djfe** [comment]
are you using stock android? or have you switched to a custom rom? this might be an issue of your rom not telling the play store of your hardware gps correctly so that it knows that all of the apps requirements are complied.
(this is only an assumption)

**Comment by edt-xx** [comment]
I am stock using xposed.  I'll try tomorrow with xposed modules disabled and see...  Suspect that its the app though - I have seen the same behavior on a few others (GSAM Battery monitor comes to mind) and they have a switch to force the app to recognize you have a cell radio.  But this is the exception.  Most apps just work (Llama and a few apps to locate cell towers).

**Comment by garvankeeley** [comment]
@edt any more info?

**Comment by kparal** [comment]
I have Nexus 7 2013 Wifi (no 3G or LTE) and I also can't install the app from the play store (it says "not compatible"). I have stock Android 4.4, non-rooted. I assume you don't need mobile networks functionality to work, right? I'd like at least to submit wifi data.

**Comment by garvankeeley** [comment]
A GPS chip is required.

**Comment by edt-xx** [comment]
All nexus tablets have GPS chips.

**Comment by kparal** [comment]
Yes, I have GPS in the tablet.

**Comment by garvankeeley** [comment]
Wow, even the wi-fi-only. I'll try find out if _anyone_ has installed on a Nexus 7 from the play store.

**Comment by garvankeeley** [comment]
this one should be an optional requirement, will fix in the next update:
  uses-feature android:name="android.hardware.telephony"
