### ISSUE TITLE
notify when gps is disabled

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#1151]
Can we can a feature added so that MozStumbler notifies you if your GPS is disabled.

Doing a stumble, I opened MozStumbler and it auto started and I assume all was well or it would be once it got satellite lock not knowing that it was disabled.

I think this used to be a feature in older version but when I try on 0.4x and up no notificat

**Comment by Djfe** [comment]
If the app never got a GPS fix (a concrete position(lat/lon)) then the icon is red
once it gets a position it turns black, but it never turns red again if the satellite fix gets lost again...

**Comment by grrrrr** [comment]
@Djfe  the problem there is that I don't wait to see if it gets a fix, I assume that it will and put it on dash but as gps is disabled that never happens.

At least if gps is disabled (not no fix) and I get a warning I know to enable it.

**Comment by Djfe** [comment]
that's pretty much the same for me, the thing is, that if it loses the GPS fix/the GPS gets disabled manually then it will still keep on showing the black GPS icon and the numbers of the previously connected GPS satellites

**Comment by crankycoder** [comment]
Marking this as won't fix as we have the icon that goes red already.   If someone wants to contribute an actual buzzing notification that's great, but I'd like to triage a bunch of these bugs to get our issue list under control.
