### ISSUE TITLE
Add a preference to not autostart stumble.  Default to yes. 

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#1152]
Can we have feature so that MozStumbler do not start recording when app get opened but instead only when user decided

**Comment by Djfe** [comment]
What are you starting Mozilla Stumbler for if not for stumbling?

I think it's easier this way.

**Comment by VolMi** [comment]
```
What are you starting Mozilla Stumbler for if not for stumbling?
```

Just watching the map, maybe? I also happen to do the sequence `open Stumbler → deactivate stumbling → play with the map → close` quite often. I never got why I am forced to deactivate the stumbling every time.

**Comment by grrrrr** [comment]
> What are you starting Mozilla Stumbler for if not for stumbling?

useful for when I need to submit tickets and have to checking logs or check version installed or just checking the map to see where I want to go.

**Comment by Djfe** [comment]
sounds legit, but that's not the normal use case, so I'm not sure whether it makes to set this too default
@garvankeeley / @crankycoder What are your opionions on this topic?

**Comment by VolMi** [comment]
The default does not need to be changed. As grrrrrrrrrrrrrrrrr said: "Can we have feature [...]?"
I think the current default does indeed make sense. Just for a few of us it would be nice to have an option for that.

**Comment by SteveALee** [comment]
I have found that when I **switch back** to Stumbler (Android) it turns back on. This is not good and I would say a bug

By switching I mean using the android recent apps button, not starting again from home screen

Steps
- Launch stumbler
- turn off
- switch to another app
- turn off display and wait a while
- Turn on display and switch back to stumbler

Result: after switching it turns back on
Expected: stays switched off

I assume you get different events for start up and activate by switch but I notice Fennec reloads the web page every time I switch back to it (which is also REALLY annoying and makes cut and paste in segments a real pain)

**Comment by Djfe** [comment]
That's normal Android behavior, it freezes the app and restarts it with the old values, but MozStumbler just starts fresh instead because there are no values to save (except maybe what you are looking for)

the devs made it so that MoStumbler gets closed when it isn't used, so that you don't need to close it using some kind of task manager (if you have a device without much memory)

**Comment by SteveALee** [comment]
So I thought normal Android behaviour was that it multitasks so apps are expected to run when in background. I expected Stumbler to carry on when I switch to another app. Are you saying that is wrong? It seems to carry on if I simply switch back and forth between apps

If I switch apps I don't expect them to change state. The stop watch does not stop when you switch away. Switching away does not mean I am not using it, rather, I have a higher priority foreground task to work on. This is how it seems to work.

Perhaps I miss understand Android after using desktop OSs for so long? I know you don't use a task manager to kill apps so they must be suspended to free up resources at some point. I just don't know when. It seems that if you blank the display and wait a while that is when stumbler turns on when switched to, so perhaps that is when Android decides to suspend tasks. Time for me to research how it works.

Thanks

I expect iOS to not multitask - though I think it does now.

**Comment by SteveALee** [comment]
So android docs _do_ say activities should be restored. 

If an activity is paused or stopped, the system can drop the activity from memory by either asking it to finish, or simply killing its process. When it is displayed again to the user, it must be completely restarted and restored to its previous state.

http://developer.android.com/reference/android/app/Activity.html

Stumbler doesn't do this if it always turns on. I assume it doest loose unsent data.

Fennec doesn't do thus as it reloads the page, which may be in a different state. It also loses any highlight but that's arguably more of an edge case, though annoying.

**Comment by crankycoder** [comment]
I've changed the title of this bug as it's just about a preference

**Comment by SteveALee** [comment]
I don't think it should switch to 'on when reactivating as opposed to starting. Though I will accept a preference give your comments on most common use case. :)

**Comment by grrrrr** [comment]
closing as project is no longer active - https://discourse.mozilla.org/t/retiring-mozilla-stumbler/75206
