### ISSUE TITLE
Automate installation of the android SDK to get a buildserver setup

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1162]
Setting up the Android enviroment is a pain.  Let's wrap that up in a script that also checks that all the paths and enviroment variables are correct.

**Comment by crankycoder** [comment]
We basically need to scrape the output from: `android list sdk --all --extended`, grab the name of the package and then issue : `android update sdk -u -a -t <package>`

**Comment by khernyo** [comment]
You can use https://github.com/JakeWharton/sdk-manager-plugin for automated SDK install/update.

**Comment by crankycoder** [comment]
Thanks @khernyo !  I've finally gotten around to doing this.  I'm hoping to get more contributors in now that we have a one step build.
