### ISSUE TITLE
Wifi scanning not reported, cell scan ok

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1165]
This seems to be odd behavior, I'm not entirely sure what's going on.

My brother is running a Galaxy S5 in NYC and doesn't seem to be getting wifi dots in his stumble, but you can clearly see the wifi count @ 20 here.

He said the wifi count doesn't seem to change at all, and it looks like there is no actual wifi data in the collection data if you look at the bottom screen shot.

![pasted_image_2014-10-29__8_47_pm](https://cloud.githubusercontent.com/assets/4829/4837015/6bb88f92-5fce-11e4-8f71-69be3c7f28cf.png)

![pasted_image_2014-10-29__9_02_pm](https://cloud.githubusercontent.com/assets/4829/4837132/7ce29536-5fd0-11e4-9470-421218fedabc.png)

**Comment by edt-xx** [comment]
In my case it reports wifi and misses the cells (nexus 7 2013 lte rooted with xposed factory image).  

If I use xposed to enable SMS then stumbler detects the cells.  This leads me to believe that the test being used to checkif the device has mobile data is flawed.  Maybe you could just supply a user set able switch that can be used to override the check when it gets the wrong answer.

**Comment by Djfe** [comment]
If you are not moving at all then new Wi-Fi points that the Android device needed some time to detect for, should be added to the current report, too IMO (maybe that fixes this issue)

btw.: does your brother see any Wi-Fi aps in his logs (at the top where they aren't truncated)?
maybe you could add further logging to the part of the ap that excludes wifis, which tells you why they don't get added to the list.

**Comment by crankycoder** [comment]
Wifi was disabled on the device. After wifi was enabled, all dots when green.

**Comment by Djfe** [comment]
Why did you leave this bug open then?

**Comment by cascheberg** [comment]
This case of visible wifi count without active wifi scanning probably occurred because of the bug described in #1218
