### ISSUE TITLE
Map tiles keep reloading

### ISSUE THREAD

**Issue by SteveALee** [mozilla/MozStumbler#1167]
The caching of map tiles could do with some improvement. I find they keep reloading - ie reset to course quality and have to wait for details to load again.

**Comment by garvankeeley** [comment]
The low quality tiles switch happens with no wi-fi, is this happening then? This feature needs work, but it uses 10x less bandwidth, which was the initial concern and why the feature was added.

This bug describes some of the problems I have seen:
https://github.com/mozilla/MozStumbler/issues/1102

Is it similar to that?

**Comment by SteveALee** [comment]
Yes, I was just about to add tha to the issue. So the cycling I saw between low and high res would be as WiFi dropped in and out ?
I guess it looked worse as I was zoomed right in.

**Comment by crankycoder** [comment]
I need to add a proper unit test to verify tile reloads are behaving correctly.

**Comment by crankycoder** [comment]
Closing this as it's related to cycling between low and high res maps and has been addressed in #1406
