### ISSUE TITLE
Cleanup UI for wifi-only devices

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1200]
Things that can be optimized if cell scanning is not available:
- hide wifi only upload preference
- hide map legend
- do not display cell metrics
- indicate in map view that cell scanning is not available
- adjust notification text

**Comment by garvankeeley** [comment]
This is a small set of users, I'm not sure we want to target this audience too heavily in terms of the UI.

**Comment by crankycoder** [comment]
I agree with @Garvankeeley.  Optimizing this UI is going great to mostly
affect tablets which are a very small single digit percent age of our user
base.

Maintaining the UI modification over the lifespan of the application seems
like a poor use of very constrained engineering resources.

I would only reconsider this if we have automated verification of UI
elements across both phone and tablet layouts.
