### ISSUE TITLE
release_check needs 2 updates

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1208]
Monsieur Cranky, deux fix for you: 
- is looking for ACRA in the props file
  and
- maybe fix this (github and playstore have the same properties file)
  traceback (most recent call last):
  File "./release_check.py", line 6, in <module>
    for line in open('android/properties/private-%s.properties' % sys.argv[-1]):
  IOError: [Errno 2] No such file or directory: 'android/properties/private-github.properties'

**Comment by crankycoder** [comment]
patched in 37b7a14798acdde1adb10adf630bc8404027d28e

I've since cut a v1.3.0 release and put the APK up in the v1.3.0 release tag here: https://github.com/mozilla/MozStumbler/releases/tag/v1.3.0
