### ISSUE TITLE
Another messed up version code

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1209]
I downloaded 1.3.0 from the github repo, but the version android reads out of the .apk file is 1.2.0.
And at the first start Mozilla Stumbler asks for an update again already -> loop.

**Comment by garvankeeley** [comment]
@crankycoder I'll generate one from the build machine now

**Comment by garvankeeley** [comment]
@djfe I updated it with a build from our build box, which should be corrected. Checking now... looks good

**Comment by crankycoder** [comment]
Ugh.  Bug in the rename_release.sh script. 

Sorry.

**Comment by garvankeeley** [comment]
np, closing, i think it is all good now

**Comment by Djfe** [comment]
No for me. This didn't cause any issues since the version wasn't up for too long.

It's more amusing for me to see how often the build system contains bugs because it gets changed so often ^^
