### ISSUE TITLE
updater dialog gets drawn before first run

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1211]
I don't know if this is an issue but the updater dialog gets drawn above the first run dialog.

I noticed this because I needed to uninstall Mozilla Stumbler yesterday because of the sign key change.
After installing 1.3.0 the first run dialog popped up
and then directly after that the update dialog because of the bug in the build system (version 1.2.0 instead of 1.3.0).

**Comment by garvankeeley** [comment]
It worked ok otherwise?

It is on the github (a.k.a. our beta channel) so I think users will be ok with it.

**Comment by Djfe** [comment]
everything worked fine, and it' probably a rare case that a user uses the app for the first tim and an update is available at the same time
