### ISSUE TITLE
play store issue: it says: "optimized for phones"

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1214]
the play store says: optimized for phones:
why shouldn't it be optimized for tablets, too?

since the map got integrated into the main activity the whole space is filled
the only thing I could think of are the settings and leaderboard pages, which maybe could be optimized further, but that is minor IMO.

**Comment by Djfe** [comment]
added a screenshot:
![2014-11-05 13 30 25](https://cloud.githubusercontent.com/assets/5685512/4917676/d53881f2-64e7-11e4-954b-ac7c12c52cf4.png)

**Comment by cascheberg** [comment]
This [post](https://plus.google.com/+AndroidDevelopers/posts/LHKmeL5x7LN) has all the details and gives links that tell you how to fix/improve that.

**Comment by garvankeeley** [comment]
Without tablet-specific layouts, we will see this

**Comment by crankycoder** [comment]
I'm just closing this.  It's been over a year and we are not going to get the UX resources to tackle this one.

**Comment by Djfe** [comment]
could you maybe tag this so that it gets fixed later on?

the layout works almost fine on tablets and only needs a few adjustments
for example the colored points on the map are far too small (the size is not relative but absolute or something)

maybe the settings can be adjusted

and some more buttons could be placed on the top bar over the map

but that should be it
