### ISSUE TITLE
MLS only geolocation mode.

### ISSUE THREAD

**Issue by ferongr** [mozilla/MozStumbler#1217]

**Comment by ferongr** [comment]
It would be neat if there was a mode where instead of stumbling, the client would track the user's location on the map using MLS as the sole information provider.

**Comment by garvankeeley** [comment]
Have you tried the feature to show MLS locations on the map? It is quite similar to that.

**Comment by ferongr** [comment]
![screenshot_2014-10-28-18-32-46](https://cloud.githubusercontent.com/assets/544658/4939121/78945e32-65d0-11e4-9d78-e989356b2afd.png)

Right. I never figured that the red points were MLS responces to queries. Thanks, this works.
