### ISSUE TITLE
Not possible to install 1.3.0 in 2.3.7

### ISSUE THREAD

**Issue by gpoo** [mozilla/MozStumbler#1219]
I tried to upgrade from 0.102.0.0 to 1.3.0, it downloaded the package, but it cannot be installed (the message from the package manager is "Application not installed".

I have not been able to try with Play Store because it does not offer any update.

If the newer version does not work with old Androids, it might worth to release a new version that does not bring a pop-up window saying there is a new version (that can't be installed).

On Android 4.3 it works as expected.

**Comment by garvankeeley** [comment]
Can you try uninstall first? We changed the signing key of the gihub releases as of 1.3 to match the play store, so those builds can be used interchangeably.

**Comment by gpoo** [comment]
Yes, that fixed it. Thanks!

**Comment by Djfe** [comment]
normally .102 should show a dialog directly before the update stating that you need to uninstall the app first
