### ISSUE TITLE
Change wording of title "Previous sessions" in metrics

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1240]
The title "Previous sessions" is not quite accurate, since in fact it shows the number of reports uploaded, and you can already upload reports multiple times within the current session.
Changing the title to e.g. "Already sent" (or "Sent (total)") would give a clear distinction between current session data and uploads (sent/ready to send).
I can create a PR if the change is ok.
![metrics](https://cloud.githubusercontent.com/assets/3845150/4992627/90971926-69a3-11e4-997f-e22698274ec0.png)
The metrics were updated in #1221

**Comment by garvankeeley** [comment]
Makes sense. @ryanfeeley can you take a look?

**Comment by garvankeeley** [comment]
We agree 'Already sent' is a good title for this.
