### ISSUE TITLE
If no movement, stop GPS scanning

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1262]
Although we can't use non-GPS locations for data collection, we _can_ use them for basic movement detection. We should used fused+network location types to determine if the user is not moving (ex. position change <30m for 5 mins). If not moving stop the GPS. Essentially this means switching between coarse and fine location. 

Caveats: 
- if the coarse location accuracy is too low, we can't use this method (it only works in urban areas).

**Comment by Djfe** [comment]
It might be useful to keep the user's position, but the GPS although shouldn't stay on longer than a minute after the scanning got stopped (this happens when the map is on display/screen is on), or does it get turned off when the display is off?

**Comment by Djfe** [comment]
this can be closed I guess, except if you want to use MLS for the detection instead of the legacy or the other movement sensors

**Comment by Djfe** [comment]
totally overread what you wanted to say above, I didn't know what you meant with "fused+network location types" above and focussed too much on the issue title which lead me to thinking this would be about the significant motion sensor (sometimes tl;dr is not good...)

I opened a new issue with further ideas about what you said above already before I found this issue again
#1435

**Comment by crankycoder** [comment]
Pause scan with no motion detection is in now.
