### ISSUE TITLE
Uploads fail on some pre-ICS devices because some CA root certificates are missing

### ISSUE THREAD

**Issue by flaki** [mozilla/MozStumbler#127]
Forced uploads (those initiated on Stop Stumbling & Upload button-press) doesn't always seem to work and should be investigated further.

Starting Stumbling first time after app launch and then stopping for the first time (with no uploaded data yet) works as it should, and stumbling data is uploaded just fine, but restarting stumbling and trying to stop & upload then (at least, sometimes) fails to upload anything.

It would seem as a good idea to implement some kind of "debug" log in the app, so dogfooders/beta testers would see how much of data were gathered & uploaded in the current session.

Also, some kind of persistent storage/caching would be great for not-yet-uploaded stumbling data, so even if upload was unsuccessful or simply did not take place, users wouldn't lose the gathered data if they put the app in background and was garbage-collected/killed by the system (this would also contribute to fixing #102, too).

**Comment by merike** [comment]
I can't even get it to upload data once. It just stays at "Last Upload Time: -".

**Comment by cpeterso** [comment]
@merike: How many locations does the stumbler say it has scanned? To reduce network usage, the stumbler only uploads data in batches of 100 locations.

If the stumbler is still not uploading as expected, please drop by the #geo IRC channel on [irc.mozilla.org](https://wiki.mozilla.org/IRC) or post on Mozilla's [dev-geolocation mailing list](https://lists.mozilla.org/listinfo/dev-geolocation) so we can give you more technical support! :)

**Comment by merike** [comment]
I think I found the cause. I have an older phone which fails to trust some ssl certs. This is what I get:
E/org.mozilla.mozstumbler.Reporter(32717): error submitting data
E/org.mozilla.mozstumbler.Reporter(32717): javax.net.ssl.SSLException: Not trusted server certificate

I should probably be able to fix it after googling a bit.

**Comment by cpeterso** [comment]
@merike: that's a very interesting error. We ought to avoid that error or at least not crash. <:) What Android device and OS version are you using?

**Comment by merike** [comment]
To clarify: this doesn't cause the app to crash. Just that nothing happens after stopping stumbling, there's no visible clue that there was an error submitting report. So a try-catch showing visible message would already improve the situation.

I've seen this issue once before with https://bugzilla.mozilla.org/show_bug.cgi?id=732629. The root cause is that at least Android 2.2.1 which I'm using misses some CA certs: http://code.google.com/p/android/issues/detail?id=10807

I think I managed to manually import this CA into my phone some hours ago, so I'll try again tomorrow if I can get it to submit successfully.

**Comment by flaki** [comment]
Yes that is actually true, I just recently came across this certificate problem in conjunction with a facebook app/ssl project, and as it turns out, pre-ICS android versions do not include several root certificates from quite a few perfectly legitimate SSL CA-s. :(

**Comment by cpeterso** [comment]
I will investigate whether the stumbler can connect to our server without SSL.

@Flaki: I hope you don't mind, but I'm going to morph this bug from a general "forced uploads don't always work" bug to be specifically about these SSL certificate problems.

**Comment by merike** [comment]
So I was not able to make it work on my phone after all.

But https://ssltools.geotrust.com/checker/views/certCheck.jsp results suggest that it should be possible to fix server side.

**Comment by cpeterso** [comment]
@hannosch: can you add the intermediate cert to location.services.mozilla.com?

**Comment by hannosch** [comment]
@cpeterso I've added the extra intermediate cert to the server and the GeoTrust certCheck script no longer reports a warning.

**Comment by merike** [comment]
Success! I managed to upload now.

**Comment by cpeterso** [comment]
:D :cake:

@merike: thanks for reporting and testing the bug!

@hannosch: thanks for fixing the server certs! (I know you are on PTO.)
