### ISSUE TITLE
@vinitraje: Islampur stumbling pilot planning

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1280]
@vinitraje has reached out regarding @cpeterso idea regarding stumbling with garbage trucks.
Vinit is planning to approach the city about this, and Mozilla will support this effort.
This is the city:
Islampur Maharashra (pop 100K).
https://location.services.mozilla.com/map#12/17.0318/74.2847
- Mozilla to ensure device budgets are in place (Android device and in-vehicle charging cables). Aside: Vinit to check that the trucks have outlets (I would think they do) for plugging in a charger. 
- SIM cards for the devices. Likely they need to be pre-paid and activated for scanning to take place.

Student Group Stumbling
- Vinit discussed that his engineering college would make for an enthusiastic stumbling group. I'll add that item to this bug to track what Mozilla can do to support him for this initiative.
- @ppapadeas  is our MozRep who comes to mind for planning assistance

**Comment by Djfe** [comment]
I like that idea, maybe we can get some German cities into doing it as well
and it's not only garbage trucks, but also: street sweepers and winter service vehicles

and maybe we could help them improving their routes through the city regarding the traffic by writing some software to return their service

trains or trucks could be helpful, too but I'm not sure whether they would do this for "free"

**Comment by Gitschubser** [comment]
Maybe we can win contributors from openstreetmap?
If possible a short article/info for example at
http://blogs.openstreetmap.org/ or
http://blog.openstreetmap.de/
could awaken interest.

**Comment by debloper** [comment]
Awesome idea @vinitraje - this is finally happening... let's engage the community!
Feel free to send out an email to mozilla-india list, so that other interested folks can get involved.

**Comment by Djfe** [comment]
a small device that we could use in Europe (in other parts of the world, too probably, but I'm not sure about the frequencies)
The Galaxy Ace
http://www.gsmarena.com/samsung_galaxy_ace_3-5479.php

There are three variants
- 3g
- LTE
- dual SIM

both dual SIM and LTE would be interesting, because we could discover either two carriers at a time or new LTE towers

it doesn't support Wi-Fi 802.11a and ac though but other variants are more widely used anyway

it costs only about 144 bucks (Amazon)

**Comment by garvankeeley** [comment]
That reminds me, we need to fix this https://github.com/mozilla/MozStumbler/issues/178

**Comment by debloper** [comment]
@garvankeeley India doesn't have 4G (LTE) coverage as of now (experimental coverage only in 2-3 metro cities). With that in hand, we can totally skip looking for LTE capable devices.

**Comment by Djfe** [comment]
of course ;)
but I was thinking about doing something similar in Europe, where we have lots of LTE cell towers already

**Comment by garvankeeley** [comment]
@debloper good point. Is India almost completely 2G (or 2.5G) outside of the major cities?

**Comment by vinitraje** [comment]
@debloper True! 4G isn't necessary right now. But we should not ignore 3G.

@garvankeeley In rural areas 2.5G coverage is present, and in semi-rural, urban areas 3G is present too.

**Comment by Djfe** [comment]
I don't know of any devices nowadays that support only 2g
even the cheapest devices I know support 3g

**Comment by garvankeeley** [comment]
Vinit suggested: This one http://www.snapdeal.com/product/intex-aqua-star-powerblack/1605443260
$115 USD
4.4 Android

**Comment by garvankeeley** [comment]
This issue doesn't capture all the work that has gone on thus far, but it is progressing rapidly, next week we will put the details here. 
Shout-out to @debloper (MozRep India) for helping out on this, very appreciated!

**Comment by Djfe** [comment]
that device looks well suited for the desired needs

**Comment by rabimba** [comment]
If the phone is solely for collecting data then I don't think we even need to go that far. This one (and several others) http://www.flipkart.com/karbonn-smart-a12-star/p/itmduwgksjf7r4ss?pid=MOBDUWGCFEZJFENZ&srno=b_14&ref=a7deeddf-1c4f-4fa4-96a1-1b8003833ad7

Should come in almost at half price as well with 3g capability (also capable of running the stumbler app).

And I have seen Flame and other devices perform pretty well too.

**Comment by garvankeeley** [comment]
I look for Android 4.4 or higher and more than one SIM, so that one LGTM.

**Comment by rabimba** [comment]
This one is 4.4.2 and Dual sim as well. 
But is multisim relevant for stumbler? I use it in my S2 with PA and it works pretty well.

But of course I don't know if there is any other specific things are needed which is not in this device. I just compared price point.

**Comment by garvankeeley** [comment]
Oh yeah, we haven't hooked up multi-SIM scanning yet :). Should really try to do that ASAP

**Comment by rabimba** [comment]
And I remember scanning even without a sim in my Flame and S2. Worked pretty well (I was connected to wifi when uploading the data though)

**Comment by vinitraje** [comment]
@rabimba We chose that Intex phone because of its battery. I don't think Karbonn would sustain a day of scanning with GPS on.

**Comment by Djfe** [comment]
can't you charge the devices in the cars/trucks? -> 12V charger

**Comment by rabimba** [comment]
@vinitraje no phone would last a day of scanning without battery or a car charger. Take any phone (other than Droid MAXX) and it will run out in 5-6 hours max if stumbler is always on. Not even with my Nexus,S2 or Flame.
@Djfe by default NO. But if they agree to this proposal, this should be a trivial matter to install a car charger in the truck. (I say "should" be since everything is hypothesis, I am not in the field...hence...don't know the real challenges)

Like you know even when navigate via gps in cars, they always plug in the mobile for this very reason.

**Comment by vinitraje** [comment]
@rabimba Droid MAXX has battery capacity of 3500mAh while the Intex mobile I suggested has battery of 4000mAh.

Plus it has WVGA screen, so less battery consumption than Droid MAXX. I had a Lenovo P780 with 4000mAh battery and it used to give straight 40 hours backup on moderate use.

@Djfe We are exploring all possibilities.

**Comment by rabimba** [comment]
@vinitraje Oh really? My mistake in that case(and apologies). I thought I saw in the snapdeal page @garvankeeley mentioned it's written as 3000mAh. And from my 2100 mAh N4 I can pretty much assume how a quad core phone would perform on battery. I won't even go into N4 and Intex/karbonn/others battery performance comparison though (standby times touted as 390 and 350/300 hrs)

I just did the value for money with the feasibility of deploying car chargers+cheap phone and did that comment keeping in mind with the goal here (stumbling)

**Comment by vinitraje** [comment]
@rabimba Snapdeal changed the link, I recommended Intex Aqua Power not Intex Aqua Star Power. There's difference. http://www.intexmobile.in/product_detail.aspx?PID=220&PCatID=3

**Comment by garvankeeley** [comment]
One more item. We need devices that support the significant motion sensor. This is in Android API 4.3 and newer, but it doesn't mean that devices actually have it. With this sensor the battery efficiency is much better, and the devices are very unlikely to drain the battery when this sensor is not being triggered.

The Log screen on the stumbler will state if a device has this sensor.

**Comment by vinitraje** [comment]
### Update:
- We got the administrative permission from municipal council
- Number of trucks available are 7 mini trucks and 1 large truck
- The link to documentation folder is - http://1drv.ms/1AhsTs9
- I am going to upload daily scanning reports in the same folder above

**Comment by debloper** [comment]
@vinitraje great going... cheers! Can you please confirm if the trucks will have any power options to keep the devices charged? This will be very helpful in selecting the best phones for the purpose.
