### ISSUE TITLE
fix version naming (broken as of 1.4.0)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1281]
is it correct that an ip is attached to version 1.4.0?
![2014-11-21 18 28 52](https://cloud.githubusercontent.com/assets/5685512/5149223/ec19d588-71c6-11e4-9a7a-2d6e77477de1.png)

**Comment by garvankeeley** [comment]
uh no, that is not correct.

**Comment by crankycoder** [comment]
It's just the private IP of the buildbox.  It's not public facing.  In anycase, the buildhost addition breaks fdroid.
