### ISSUE TITLE
Error on opening empty username/email in settings activity (adb log)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1299]
11-25 00:19:41.796  22380-22380/org.mozilla.mozstumbler E/SpannableStringBuilder﹕ SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length

**Comment by cascheberg** [comment]
I do not see this. According to [this](http://stackoverflow.com/questions/13670374/android-span-exclusive-exclusive-spans-cannot-have-a-zero-length), the error might be caused by Samsung TouchWiz or another 3rd party keyboard, so it would be outside the scope of this project.

**Comment by Djfe** [comment]
ok, strange that it shows up for the application instead of for the keyboard application

I'm using Swiftkey and a CustomRom
