### ISSUE TITLE
Acquire WakeLock and WifiLock to prevent sleeping when stumbling

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#13]
Do we need to acquire a WakeLock and a WifiLock to avoid sleeping when stumbling?

https://developer.android.com/reference/android/os/PowerManager.html

https://developer.android.com/reference/android/net/wifi/WifiManager.WifiLock.html

**Comment by dougt** [comment]
bug 45 (issued a pr for this)
