### ISSUE TITLE
'Locate me' doesn't work

### ISSUE THREAD

**Issue by whimboo** [mozilla/MozStumbler#130]
I scanned my area a couple of times and also send the reports but whenever I click on 'Locate me' my position is always reported as being in the middle of the Atlantic Ocean. When I hit the button GPS is also turned on and satellites are available.

**Comment by cpeterso** [comment]
@whimboo: Our server's location database is very limited, so many areas are not covered yet. We should probably add some better error messages to the MozStumbler to differentiate between the server could not find your location and network errors. That said, I too have seen cases where the "Locate Me" map can't find my location, even though my neighborhood is (very) well scanned. :)

**Comment by whimboo** [comment]
I'm in Dresden (Germany) which is about 200km south of Berlin. I have started yesterday to collect information with mozstumbler.

**Comment by sole** [comment]
Ah, I hit that error too! But I have done GPS stuff before and I'd be 90% sure that the "point in the middle of the Atlantic ocean, quite close to Africa" point is actually 0, 0. :-)

**Comment by cpeterso** [comment]
@hannosch: do you have any theories why the search API might fail to locate the client, even though the person has stumbled the same neighborhood before? Does the server have search restrictions other than needing at least two neighboring APs?

**Comment by gentooboontoo** [comment]
I hit the exact same issue (GPS on and fixed). MozStumbler locates me in the atlantic ocean (probably at 0,0)

**Comment by hannosch** [comment]
I tried this on my own device. In my case the stumbler never actually sends a request to the server. I've tried various combinations of activating scanning first, waiting for a GPS fix or doing immediate lookups. But none of them have lead to the server receiving a search request.

I do see successful search requests in the servers access log for MozStumbler 0.7.0 (same version as mine) and 0.6.2. So this doesn't seem to be an easy problem. I have a Nexus 4 - if there's a way to access the debugging logs and look at those, I could try that.

**Comment by tialaramex** [comment]
I have looked at the logs of one of my devices using adb, and I see that it believes it successfully sent information about the location of wireless APs to the Moz.org server (getting a 204 response). When it tries to do a search API call for those same APs, it gets nothing. I believe that most likely there is a bug in your backend code.

Here's what gets POSTed to https://location.services.mozilla.com/v1/submit

{"items":[{"wifi":[{"key":"a4b1e919c9fd","signal":-44,"frequency":2412},{"key":"4c17eb4c7a01","signal":-65,"frequency":2437},{"key":"002417339003","signal":-67,"frequency":2462},{"key":"e839df668168","signal":-51,"frequency":2432},{"key":"0026442a3409","signal":-90,"frequency":2412}],"time":"2013-10-29T22:55Z","lon":-1.3858924578690872,"accuracy":64,"lat":50.9245938387533,"altitude":110}]}

Here's what gets POSTed to https://location.services.mozilla.com/v1/search

{"wifi":[{"key":"a4b1e919c9fd","signal":-46,"frequency":2412},{"key":"4c17eb4c7a01","signal":-64,"frequency":2437},{"key":"002417339003","signal":-68,"frequency":2462},{"key":"e839df668168","signal":-54,"frequency":2432},{"key":"0026442a3409","signal":-88,"frequency":2412}]}

The result, is

{"status": "not_found"}

Until you can make this work there's not much hope for building a "location service".

**Comment by tialaramex** [comment]
For anyone following at home, this should all magically start working once Hanno gets the service back up on its feet

https://groups.google.com/forum/#!topic/mozilla.dev.geolocation/Ud5xI9-AjM8
