### ISSUE TITLE
force close 1.50

### ISSUE THREAD

**Issue by HassanHeydariNasab** [mozilla/MozStumbler#1310]
I just updated to version 1.50 and it being force closed .
My device is XPERIA mini with CM11.0

**Comment by cascheberg** [comment]
Which version did you use before? Is 1.4.0 working for you?
And was crash reporting enabled previously?

**Comment by garvankeeley** [comment]
If you can install 1.4, turn on crash reporting, then upgrade, we will see the crash reports and get it fixed

**Comment by HassanHeydariNasab** [comment]
I didn't find 1.40 on f-droid

**Comment by garvankeeley** [comment]
Can you install 1.3, go to settings>developer and turn on crash reporting? Then upgrade, and we will get the crash report

**Comment by crankycoder** [comment]
1.5.0 and 1.5.1 should be live in fdroid.  If you can't see the new release,  you need to force the fdroid app store to refresh.

**Comment by garvankeeley** [comment]
Those show up ok, it is that they crash immediately. But if the prev version is installed and crash reporting turned on, the new version should inherit that setting and we will get a crash report.

**Comment by Djfe** [comment]
crash reports are only uploaded on app updates?
->we won't get any crash reports from the play store?

why aren't they uploaded along-side of the reports?

**Comment by HassanHeydariNasab** [comment]
In 1.5.2 it was solved .

**Comment by garvankeeley** [comment]
crash reports are only uploaded on app updates?
A: no, they are only uploaded if the Setting is checked on

->we won't get any crash reports from the play store?
A: typically, no.

why aren't they uploaded along-side of the reports?
A: They are uploaded when the crash happens.

**Comment by garvankeeley** [comment]
Also, thanks for letting us know it stopped crashing. Yay!
