### ISSUE TITLE
ACRA crash: MapLocationListener.java:124 Network provider not available

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1311]
Acra report:
Java.lang.IllegalArgumentException: provider doesn't exist: network at org.mozilla.mozstumbler.client.mapview.MapLocationListener.enableLocationListener(MapLocationListener.java:124)

**Comment by cascheberg** [comment]
I got this error (reproducibly) when I ran the app in an Android virtual device API level 16. But I don't know if that was logged to the server, and of course I don't know if you got more reports from other people as well.

**Comment by garvankeeley** [comment]
this should be fixed with #1312
