### ISSUE TITLE
1.5.2 drains the battery by leaving the GPS active after stop stumbling

### ISSUE THREAD

**Issue by gpoo** [mozilla/MozStumbler#1317]
After upgrading MozStumbler into 1.5.2 in my Nexus One, and after the following steps:
1. Stumble a while.
2. Got home, submit report, press the stop button
3. Leave the application

I was using an external battery, so when I stop stumbling the phone was fully charged.  Next day morning, the battery was ~25% being just inactive.  The power consumption used to be ~11% overnight, not ~%75%.

Then I noticed the GPS was still active, by looking the icon in the notification bar.  After that, I rebooted my phone, I tried running MozStumbler again, stopped it and wait if the GPS became inactive, nothing happened.

In previous versions, every time I pressed the stop button, the GPS icon became inactive after a couple of seconds.

Now, the only way to get the GPS inactive after pressing the stop button is by force closing the application (via "_Manage apps_").

I also see this behavior on my Nexus 5, but because this has better battery, it did not become apparent earlier.

According to the Changelog, from 1.5.0 it should use less battery consumption if one does not move, then MozStumble stop stumbling.  But it turns out that it consume more battery if I don't kill the app explicitly after stop using it (after the screen, the GPS consumes more battery, then the wifi).

It seems to me that a fair compromise would be:
1. If the user does not press the stop button, then try to minimize the stumbling by checking any movement.
2. If the user explicitly press the stop button, then stop using the GPS.

**Comment by garvankeeley** [comment]
If the map view is visible on the screen, and the scanning is not in a paused state, the GPS is active to show your location on the map. 

However, if I interpret this correctly: you stopped scanning, stumbler app is not the foreground app, and yet the device status bar is showing geolocation icon (which is an indication the stumbler app is using the GPS)? 
If that is correct, that is a bug for sure.

**Comment by gpoo** [comment]
Yes, I did stopped it (as I always do), and MozStumbler was not on foreground.

I can reproduce the issue on both Nexus 1 and Nexus 5 (Cyanmodgen and stock Android 4.4.4, respectively).

Moreover, on my Nexus 5, the only way to remove the GPS icon, it is by showing the active applications (with the icon in the right bottom corner), and swift the MozStumbler little screenshot out.  The downside of this approach is: when I start stumbling again, I cannot see the previous points stumbled in the previous session (which can be in the same day).  But I have to do in order to save battery... to continue stumbling.

On my Nexus 1 the only way to stop it, it is by force closing the application.

**Comment by garvankeeley** [comment]
Do you mind walking me through just the steps to repro this?
1) do this
2) do this, etc.

I can't repro, and would very much like to fix this ASAP. I think I will be a quick fix

**Comment by gpoo** [comment]
Assuming GPS is on (though not active):
1. Turn on Wifi
2. Start stumbling
3. Stumble.  I tried with 80 reports or so.
4. Stop stumbling
5. Press the button Home or Back (the ones that Android has at the bottom of the screen).
6. Do something else (for a while)
7. Go back to the phone, check the GPS icon still is there.

FWIW, If first tried the same steps, but skipping 3. but it works as expected.  I have to actually move somewhere (therefore my delay in replying).

I tried those steps on a Nexus 5 with Android 4.4.4.

**Comment by VolMi** [comment]
I saw the same on my S4 mini with Cyanogenmod 11. Sorry for being too lazy to file a bug report...
Would any kind of log be interesting for you?

**Comment by AdamHauner** [comment]
I have same experience, it was same with 1.5.1 (Android 4.0.3/Google Nexus S).

**Comment by cascheberg** [comment]
@garvankeeley I found one bug, not sure if it is exactly this one, but I will investigate a bit more and create a PR later.
