### ISSUE TITLE
ACRA crash: MainApp.getCacheDir(MainApp.java:100)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1320]
ArrayIndexOutOfBoundsException: length=0; index=0 : at org.mozilla.mozstumbler.client.MainApp.getCacheDir(MainApp.java:100)

We could catch this, and show a toast or something. But there isn't much more we plan to do, with no cachedir access, the app won't run.

**Comment by crankycoder** [comment]
We patched this a while ago - if cachedir doesn't exist, we fall back to whatever path osmdroid normally uses.  We also haven't seen any crashes of this sort for many months now.
