### ISSUE TITLE
Coverage map tiles are still not expiring correctly.

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1323]
Coverage tiles are still not expiring correctly.

I've reproduced this problem by stumbling over a new area with one device, then viewing the coverage maps on the same device, along with a separate device.

After 24 hours, the second device correctly shows the stumble path while the first device - the one used to stumble which had a copy of the old coverage tiles continued to display the old coverage tiles.  The effect is that one device shows blue dots, the other shows the area as 'unstumbled'. 

Strategy to fixing this problem is :
- Wrap the osmdroid tile downloader code with unit tests first around the conditional GET caching.
- Force tiles to expire on a hard deadline of 6 hours.

**Comment by cascheberg** [comment]
One thing I noticed in `TileDownloaderDelegate.isTileCurrent`: you request the URL and add the etag header, but  you throw away the response if the response code is not 304. But in that case, the response already contained the full requested tile, right? Wouldn't it be better to move that code to `downloadTile` and only send and check the etag there?

**Comment by crankycoder** [comment]
Crap. That's probably correct.  I was doing an HTTP HEAD before but that wasn't working consistently - so I switched to using the etag method.  I'll take a look at your PR tonight.

**Comment by cascheberg** [comment]
I tried to reproduce this bug, but so far I couldn't. Could it be that you get tiles from the `LRUMapTileCache` or so, without `isTileCurrent` ever being called? Did you kill the app and then check again?

**Comment by crankycoder** [comment]
Hrm.  The LRUMapTileCache may very well be the problem.  That would be consistent with the behavior I saw.

Here's what I saw - it was while using two separate devices.  

I had a OnePlus One running CM11s (Android 4.4.4) and a Moto G 2013 (1st gen) running Android 4.4.3.

The Moto G had a previous set of coverage maps from a couple days earlier.  The One Plus was doing a new stumble and covered previously uncovered areas where the coverage tiles should have been out of date on the Moto G.

What I saw was the OnePlus and the Moto G had differing coverage tiles, which shouldn't have happened as the code as is should do a conditional GET on all tiles all the time, but just pass in the etag to get the new data.

In general, I think the LRUMapTileCache should probably just be removed, but I think it's tightly coupled with the way the tiles are rendered into the viewport.  I remember trying to remove it months ago, but I failed and the mapview stopped rendering.

Yeah.  Just re-reading the LRUMapTileCache code now and it's tightly coupled with a BitmapPool which manages tile bitmaps. Those are stored outside of the regular heap. Ugh.

**Comment by crankycoder** [comment]
I'm closing this bug.  I'm going to assume it's the LRUMapTileCache and I really don't want to touch that code as it's created headaches with freeing GPU memory before.

If this continues to be a problem, we can open a new bug and reinvestigate this issue, but for now - let's just handwave and say "bigger problems to fix".
