### ISSUE TITLE
Get FxA accounts integrated

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1325]
We need to get FxA integrated with the stumbler.  Support for nicknames can be added to the FxA Profile server.   We'll need to talk to rfkelly to co-ordinate nickname support.

**Comment by Djfe** [comment]
What happens to the leaderboard then? 
Reset or the first one who claims a certain nickname gets the points? 
What happens to entries without an account that haven't been updated to the new system after a month or so?

About the nicknames: simply add the nickname to the ichnaea db and link it to the email address/fxa account
Will this be able to fix the unicode nickname issue? (using user ids/emails only for the nickname header of the api)

**Comment by riginoommen** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1130453

**Comment by crankycoder** [comment]
Quick update, I've grabbed the android client code and forked it  over here https://github.com/crankycoder/moz-androidfxa-client

**Comment by crankycoder** [comment]
FxA code is in, works -but Im' backing it out temporarily.

FxA android library can be found over at: https://github.com/crankycoder/fxa-android
