### ISSUE TITLE
Update Gradle version

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1327]
The recently released Android Studio 1.0 RC requires a new Gradle version.

> Error:The project is using an unsupported version of the Android Gradle plug-in (0.12.2). The recommended version is 1.0.0.

The `build.gradle` file needs some adjustments and should use:

> classpath 'com.android.tools.build:gradle:1.0.0'
> classpath 'org.robolectric:robolectric-gradle-plugin:0.14.+'

And in `gradle-wrapper.properties`:

> distributionUrl=https\://services.gradle.org/distributions/gradle-2.2.1-all.zip

**Comment by cascheberg** [comment]
@crankycoder I do not know how to update the code that rewrites the `AndroidManifest.xml` (#1016). Can you have a look at this issue?

**Comment by crankycoder** [comment]
No problem.  I'll take a look tonight.

**Comment by crankycoder** [comment]
Sorry @cascheberg, I haven't been able to look at this. I just updated my Android Studio now and I'll try to get to see what's going on.

**Comment by crankycoder** [comment]
Oh wow. everything is broken in 1.0. :(
