### ISSUE TITLE
Installed the app but doesn't sync

### ISSUE THREAD

**Issue by Skatox** [mozilla/MozStumbler#1343]
I've installed the app, it can scan and recolects data but it is not reflected at left menu, so there's nothing to upload, when i go to the log it show this:

![error](https://cloud.githubusercontent.com/assets/177008/5386008/a07b3568-8099-11e4-86c8-19fb71a57c1d.jpg)

I'm using a Nexus 4 with Android 5.0 and Cyanogen 11, tried both wifi and mobile data, currently there are no data at my city.

**Comment by garvankeeley** [comment]
It is saying there is no network connection for getting the map tiles, it isn't actually an error state (note to self, stop this message from showing up in red).
We reduced the amount of those messages in the next build.

**Comment by garvankeeley** [comment]
Are you using https://github.com/mozilla/MozStumbler/releases/tag/v1.5.3?

**Comment by garvankeeley** [comment]
- On the map view, is there a message that scanning is paused?
- Also on that screen, what numbers are beside the gps icon? You need 4 or more satellites to scan (the first number after the gps icon)
- What indicator do you have that you are collecting data? Is the report count increasing (the number after the binoculars icon)?

**Comment by Skatox** [comment]
Hi, I'm using latest version. I currently have 3 GPS satellites it might be the problem, gotta try it on a open field to test it.

There are no messages that scanning is paused, also the number at binoculars is 1 sometimes 2.

**Comment by Skatox** [comment]
It was a problem with the GPS on my device. Now it is working.

**Comment by crankycoder** [comment]
Just in case we see this issue with someone else,  what was the problem
with your GPS?

**Comment by Skatox** [comment]
My main problem is that my GPS doesn't work after some days so I've to reboot the phone. The problem with MozStumbler, is that it doesn't complain about having less than 4 GPS satelittes, it should show some error message to let you know why it is not taking reports. I live in a cloudy city and inside buildings GPS doesn't work good.
