### ISSUE TITLE
F-droid API key not registering uploads

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1349]
For reasons unknown, we are seeing zero uploads with the f-droid API key.

**Comment by crankycoder** [comment]
Crap.  We're using the same API key for fdroid as the github release.

https://github.com/mozilla/MozStumbler/blob/dev/android/properties/private-fdroid.properties#L10

@hannosch can you send me the proper API key for f-droid?

**Comment by hannosch** [comment]
Sent Victor the API key in email.

**Comment by mishari** [comment]
@crankycoder @hannosch forgive my ignorance, but does this mean I should not upload any data until a new release is on f-droid?

**Comment by crankycoder** [comment]
It doesn't matter.  It's primarily for out own record keeping to see which
distribution method for the stumbler gives us the most users.
