### ISSUE TITLE
Create an open webapp for Stumbler

### ISSUE THREAD

**Issue by whimboo** [mozilla/MozStumbler#136]
Well, we are Mozilla so why don't we create an open webapp for Stumbler? Frankly I don't want to use Android for collecting all that data. My Firefox OS device would be the best! :)

**Comment by hannosch** [comment]
We need access to low-level API's to get data about GPS, wifi and cell networks. There is no JavaScript/Web-API to access these things and to my knowledge nobody has started on the standardization process for these.

We did at some point work on some patches to get a simple MLS (Mozilla Location Service) client into Firefox OS itself on a lower level. We didn't pursue this, as we found partners to provide geo lookup for the first waves of FxOS devices.

To make any progress on this, we would need to either have special MLS code in FxOS, or get someone to create new standard API's. To my knowledge neither has been a priority for the FxOS teams working on the radio layer, as they have a lot of other important work to do.

So for now the Android route is a practical choice to actually make some progress.

**Comment by whimboo** [comment]
Hm, I see. So I have to continue using my Android device then. How un-cool. :) Thanks for the update on the WebAPI status of those components.

**Comment by hannosch** [comment]
A community member has started working on a FxOS version. Discussions began on the mailing list. As this is a separate code base, I'll close the issue here.

**Comment by whimboo** [comment]
Would you mind to give the information where this discussion and the code can be found? Thanks

**Comment by hannosch** [comment]
@whimboo the code is here https://github.com/clochix/FxStumbler, it was mentioned in https://groups.google.com/d/msg/mozilla.dev.geolocation/AdYFqck6Y1M/JFDkYwgiGcwJ

**Comment by whimboo** [comment]
Thanks!
