### ISSUE TITLE
Simulation Mode should be refactored into an injected dependency

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1365]
The current implementation of #1191 uses a ContextWrapper around the application context as a control point for all simulation events.  This is problematic as we need to manage how the contexts are passed around throughout the application.  It's very likely that we'll break the simulation mode as we make further modifications to the stumbler codebase.

We should instead have a service provided by an interface ISimulation which provides all the generators for GPS, Cell and Wifi data.  Toggling the simulation mode can then just create or destroy the simulation service and all dependant classes can just check for NULL when they request the simulation service.

**Comment by Djfe** [comment]
good idea! way easier to maintain it as an interface

**Comment by crankycoder** [comment]
This is causing #1485

**Comment by crankycoder** [comment]
Merged in #1492
