### ISSUE TITLE
MapLocationListener is too slow

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1371]
If you are traveling fast, the location updates of the `MapLocationListener` are slower than those of the `GPSScanner`. As a result, new reports are drawn on the map without the blue user position dot being updated. So it is lagging behind which looks odd.
I think an easy fix would be to make the `MapLocationListener` listen to `GPSScanner.ACTION_GPS_UPDATED` intents.

![stumbler](https://cloud.githubusercontent.com/assets/3845150/5578099/8d21f11e-9020-11e4-92ed-f0abbe02ff1d.png)

**Comment by Djfe** [comment]
saw this happening as well still

why are the updates slower btw.? are there some calculations being done at the same time or is the interval hardcoded?
