### ISSUE TITLE
MLS locations not improving for mobile only locations

### ISSUE THREAD

**Issue by SteveALee** [mozilla/MozStumbler#1382]
I'm not sure if this is a problem but I would expect all MLS locations to get more accurate with time.

I regularly walk the same route and where there is wifi the MLS locations are indeed now fairly accurate. However for those points that are blue (mobile only) the points are still a long way out and many seem to map to the same point well away from the actual location. There are usually more than 1 tower in view.

**Comment by crankycoder** [comment]
This isn't really a bug - location fixes with cell tower only are going to be pretty imprecise.  Stumbler just get's its location fixes from [ichnaea](http://github/mozilla/ichnaea).  With only cell information, you're not going to do much better than the radius of a cell tower.

**Comment by SteveALee** [comment]
Thanks. I wondered if some sort of triangulation would give better fixes. But it's not something I know anything about :)

**Comment by SteveALee** [comment]
Thought: One potential issue with cell only is if ichnaea uses the connected tower. Phones regularly hang on to old weaker signal towers when better ones become available. This appears to be happening to my records

**Comment by hannosch** [comment]
@SteveALee for cell connections, most phones don't report a proper list of neighboring cells, so the currently connected cell is the only available data point.

This depends on a lot of factors, the Android version, the chipset, radio driver, radio tech (GSM, UMTS, etc) being amongst them. If you like technical underpinnings, I wrote this up in more detail in a slightly different context at https://github.com/mozilla/ichnaea/issues/17#issuecomment-51984708.
