### ISSUE TITLE
Individual contributor app for iPhone?

### ISSUE THREAD

**Issue by Noitidart** [mozilla/MozStumbler#1385]
They have android app for individual contributors here:
https://location.services.mozilla.com/apps

What about for iPhone and if we want to contribute?

**Comment by hannosch** [comment]
Unfortunately iOS is a closed ecosystem in which Apple controls what kind of apps can run on their platform. They have chosen to disallow and prevent apps from getting access to the WiFi and cell information that we require.

So building a stumbling app for iOS is not possible.

**Comment by Noitidart** [comment]
Aw dang ok thanks
