### ISSUE TITLE
widget problem

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1389]
@lomash The widget from #1353 is nice, but I think I see a bug:
1. stop scanning
2. kill the app
3. click the stumbler icon in the widget
4. Result: the app will show up, but the main screen is black and nothing is happening

Is it intended at all that the app is launched from the widget?

Because this is working, I guess:
1. start scanning
2. kill the app (scanning process is still active)
3. click the stumbler icon in the widget (multiple times)
4. Result: it will always toggle the scanning status, but the app does not show up (or is instantly minimized)

Another use case:
1. launch and hide the app
2. clicking the stumbler icon will always toggle the scanning status and bring the app to the foreground

And in that case, it would be nice to be able to bring the app to the foreground without stopping the scan.

**Comment by Djfe** [comment]
So that's what people call fluently switching between languages ^^ (irony off)
-> the title is German ;)

**Comment by crankycoder** [comment]
The widget has been pulled entirely.
