### ISSUE TITLE
ON/OFF button is not reliable

### ISSUE THREAD

**Issue by kparal** [mozilla/MozStumbler#1395]
It happens to me very often that when I switch scanning from ON to OFF, the button:
a) either jumps back to ON again immediately (I need to switch it off a second time)
b) or it stays at OFF position, but the stumbler icon in notification area still shows that scanning is enabled (I need to press the home button, open stumbler again via the notification menu, and switch it off again).

This does not happen always - it seems it happens only if I have some new reports to upload, and even then it's still random. If I want to reproduce it willfully, I don't have too much luck. But in real world usage, I see this in like 20-50% of cases I want to turn it off.

Maybe this bug happens when Stumbler is in the process of automatically uploading results?

Mozilla Stumbler 1.5.4
Android 4.4
Motorola Moto G

**Comment by cascheberg** [comment]
The problem that the notification does not disappear (b) might have been fixed in #1356.
This does not explain the problem regarding the switch jumping back to ON (a) though.
In that case, does the number of reports actually increase if you keep moving?

**Comment by kparal** [comment]
When I see it again, I'll try.

**Comment by VolMi** [comment]
I have all mentioned oddnesses, too. On CM11 and now on CM12. I'd like to just try the next release before digging deeper. Probably @cascheberg already fixed it anyways.

**Comment by kparal** [comment]
Since I upgraded to stumbler 1.5.5, I haven't seen this. I've tried it just a few times yet, though.

**Comment by kparal** [comment]
I think this can be closed, I haven't seen it since. I'll reopen it if it occurs again.
