### ISSUE TITLE
Full Offline Map Support (2) - found a bug

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1402]
This bug concerns everyone that doesn't have a flatrate/only uses Wi-Fi/starts the app in other countries (->roaming)

No Mapdata is visible even though it got cached before.
What actually happens:
MozStumbler/OSMDroid tries to show the low zoom level map which hasn't been cached unlike the high resolution zoom levels that you just watched/preloaded using your home wifi
->you don't see anything on mobile networks without an internet connection

Reason: the option for the map resolution that depends on the current network configuration
How to fix it: treat mobile networks like wifis if there is no network connection available (also happens on roaming)
Another solution: rework OSM Code to show low level zoom in the background of the high resolution map so that you see both maps on top of each other but are able to use all cached tiles

Workaround:
Switch to high resolution map only

**Comment by cascheberg** [comment]
Currently the map type is always switched to low-res if there is no internet connection. I suggest to just not switch the current map type, which one ever it is, until some sort of internet access is available again. I think I can create a PR for that.
