### ISSUE TITLE
[Regression] MozStumbler's UI gets unresponsive after scanning a while (low end devices)

### ISSUE THREAD

**Issue by gpoo** [mozilla/MozStumbler#1409]
Since 1.5.4 (I think), my Nexus One takes several minutes to respond the UI after scanning for a while. Say for example:
- Start Mozstumbler and press Start Scanning.
- Walk for around 15 minutes
- See MozStumbler again, and try to interact with it ('stop' button, load the menu, get actual location), and it takes several minutes (possibly 5 or more) to show something.

In the meantime, Android display a dialog  to either "Force stop" or "Wait" the application.  I have to press "Wait" over and over, in spite that MosStumbler seems freeze.  But it is just slow, once it stops scanning, the UI becomes responsive again.

At the beginning I thought it could be too many points to display.  But later it happened with a clear screen, and only some dots (enough to see in a screen without panning).  I tried rebooting, nothing changed.  I tried only low resolution tiles, nothing changed.  Previously I had enabled saving data to a file", but when I disabled it, nothing changed.

No other applications are running in parallel. I use the phone only to Stumble with a different carrier.

It became responsive again once I downgraded it to 1.5.3.

**Comment by cascheberg** [comment]
I have only scanned a few times for a short while since upgrading to 1.5.5 (Update: I did not notice this using 1.5.4), but I also noticed that responsiveness was worse. After scanning for a while, pressing the stop button and scrolling the map became laggy on my Nexus 4, Android 5.0.1.

**Comment by gpoo** [comment]
@cascheberg I've heard many times that Android 5 is painfully slow (besides that drains the battery faster). Could it be that?

FWIW, in a Nexus 5, with Android 4.4.4 I don't see any issues, likely because it has better hardware (I won't upgrade to Android 5 yet :-)

**Comment by cascheberg** [comment]
@crankycoder @lomash I did some regression testing and I am pretty sure that the widget (94c77b8 #1353) is causing performance problems on my device.
I always installed a clean build, put it on a desk where it had a stable GPS fix, then started the scan. The screen was on all the time, and I manually disabled the motion detection code so that it kept scanning. After waiting for a few minutes (~ 5-10) I scrolled the map and it was laggy. Stopping the scan fixed the problem. Starting it again immediately brought back the problem. Killing and restarting the app while the service kept scanning also fixed the problem. I did not actually set up the widget on my home screen.

@gpoo Android 5 is running perfectly fine on my Nexus 4. Also, that should not be the problem because it did not happen in previous stumbler versions.

**Comment by RexWheeler** [comment]
I am seeing similar things as @gpoo on 1.5.5. Seemed to start happening after my upgrade to 1.5.5. After I have been stumbling for a bit (10-20 mins) I will see the Wait/Force Stop dialog or sometimes Mozstumber just won't be running anymore. This is on a Galaxy S4 Active (SGH-I537) running the stock AT&T 4.4.2 kernel. To my knowledge I am not using the widget (I haven't put it on my home screen.)
Update: I rolled back to 1.5.4 and the issue has gone away for me, so it seems to be a recent regression.

**Comment by cascheberg** [comment]
The call to `AppWidgetManager.updateAppWidget(provider, views)` is what causes performance problems. It's execution time somehow increases over time. At first it's only < 10ms, then after some minutes it's already > 200ms. This method currently gets called at least twice a second while scanning.
Will see if I can learn something about Android widgets later...

**Comment by crankycoder** [comment]
Ugh. 

This is probably being slowed down by checking the report counts.  This is where I'd normally say something like "we need to profile the app to make sure", but profiling in Android is painful.

I'll just pull the widget for the 1.5.6 release.  We can think about re-enabling it through a developer option later.

**Comment by cascheberg** [comment]
The rest of `MainDrawerActivity.updateWidget()`, which includes checking the stats such as `remoteViews.setTextViewText([...], service.getObservationCount())` etc., is not a problem. Only the call I mentioned above is slow. But I have no idea what it does, and if it invokes anything within the scope of the app. And I do not know anything about (how one would usually update) widgets.

**Comment by gpoo** [comment]
Excuse my ignorance: I wonder why the home widget needs to be updated if there is no widget enabled in the home screen.  Could that be avoided?

(I guess it is by Android design, but maybe not)

**Comment by Djfe** [comment]
bad code that got reviewed by people not familiar with widgets
as simple as that

the code looked good but was committed by someone else

now the code needs to be fixed/optimized ;)

**Comment by crankycoder** [comment]
Widgets really need to be on their own service - that wasn't apparent until I filed #1396.  I'm still of the opinion that all widget and notification area code should updated with intents instead of direct method calls.  We're just removing the widget for now in #1413

**Comment by VolMi** [comment]
Could you please release an update witch #1413 pretty soonish? I am currently pausing my stumbling activity altogether because of this annoyance.

**Comment by gpoo** [comment]
@VolMi You can install a previous version from https://github.com/mozilla/MozStumbler/releases in the meantime.

**Comment by garvankeeley** [comment]
We'll try to get the builds out tomorrow.

**Comment by gpoo** [comment]
It seems fixed (1.6.0).  Thanks a lot for your work!
