### ISSUE TITLE
[Feature] advanced settings

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1412]
Specific settings for rooted devices and advanced user:
- Enable GPS automatically when Scanning is started and disable it when it is stopped (as two different options)
- Change API Url and key to allow people using their own servers (based on Ichnaea)
- allow several servers for uploading data

Possible stuff (probably not possible atm.):
- get further data from the baseband
- use certain features of the xposed framework to get more data
- edit wpa_supplicants.conf to improve WiFi-scanning (maybe hardware based instead of software based scanning)

**Comment by crankycoder** [comment]
I'm marking this as won't fix.

1) GPS is used if it's available - it's how we get the lat/long location.
2) Changing the API URL doesn't provide us any benefit and if the user really needs to do this, they are free to simply update the code and recompile
3) We have no driving use case to upload data to multiple servers
