### ISSUE TITLE
Accelerometer not working with screen off

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1415]
Here is a list of devices with this problem
http://www.saltwebsites.com/2012/android-accelerometers-screen-off 

We will need to work around this for battery saving mode.

**Comment by Djfe** [comment]
wake locks might help
-> integrated list of concerned devices (that have this issue)
activated per Default for these devices

maybe it is even possible to detect a device with this issue that is not in the list above and report it through Acra

**Comment by crankycoder** [comment]
PARTIAL_WAKE_LOCK doesn't seem to help all phones, you'd need to do a SCREEN_DIM_WAKE_LOCK which is crazy.  Keeping the screen on just to run the stumbler seems like madness to me.

**Comment by Djfe** [comment]
the accelerometer function is only needed for legacy mode, right?
do other sensors work still?

how does the open-sensor plattform handle this issue? #1295

**Comment by crankycoder** [comment]
This has been 'solved' by using the standard accelerometer instead of the linear accelerometer.
