### ISSUE TITLE
Drop wifi blocklists

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1417]
Now that Firefox Android embeds the stumbler in a passive stumbling mode, the wifi blocklist does more harm than good for the server side.

We are pulling out the wifi blocklist from the stumbler so that filtering can occur on the server side.

**Comment by hannosch** [comment]
The same was true already for a while for FxStumbler and geoclue, which don't include a blocklist. But they contribute much less data, so it wasn't that big of an issue. Also different versions of Mozilla Stumbler used different blocklists, as they were only shipped as part of the releases and not dynamically updated.

All this meant that we would get moving WiFi's only from some of the apps. Other apps or versions of the software would filter those out on the client, so the service would never get the data points showing these WiFi's in different places. We actually need to get these "invalidation" data points to put them on the service wide blocklists.

A client side blocklist would only work out, if we could ensure the exact same blocklist would be used by all clients and versions thereof all the time. But even that would mean we'd not get invalidation messages for WiFi's which got newly added to the blocklist. We'd just stop receiving any data updates for them.
