### ISSUE TITLE
Submit MozStumbler to Play Store

### ISSUE THREAD

**Issue by MarkBennett** [mozilla/MozStumbler#142]
So that I receive automatic updates and can install without enabling third-party apps on my phone, I would like to be able to install MozStumbler from the Play Store.

Is there a motivation for not publishing it there?

**Comment by hannosch** [comment]
The stumbler has a built-in updater, so you should receive software updates.

As this is still an early-stage experiment, we didn't want to push it to the play store just yet. There's also an unclear question about branding. Having multiple apps in the play store under the Mozilla brand would likely cause a lot of confusion and users would install the stumbler expecting to get Firefox. For now we opted to avoid this problem by staying out of the play store.

**Comment by MarkBennett** [comment]
Thanks for the quick reply @hannosch. That makes sense to me. Especially relieved to hear that I'll still get the updates even with it not in the store.

Great to see Mozilla continuing to make the web more open. :+1:

**Comment by cpeterso** [comment]
Thanks for the suggestion, @MarkBennett. To add to @hannosch's comments, our software is still an early prototype, so we didn't want to spread it too widely quite yet. We have ideas on adding a more polished game app later. :)

**Comment by jpyper** [comment]
Same comment I replied in issue 285:

The devs could use the Play Store staged testing feature. More info here: https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

Use this feature, you don't have to worry about public branding.
