### ISSUE TITLE
improve description of "enable MLS location queries"

### ISSUE THREAD

**Issue by kparal** [mozilla/MozStumbler#1427]
In settings, I can enable "Enable MLS location queries". But the dialog that pops up doesn't really explain what an MLS location is. I can then display it on the map (I see no red dot if I enable it), and I'm still clueless about what it is.

Can you please improve the description and describe what it is exactly?
Thanks!

stumbler 1.6.1

**Comment by cascheberg** [comment]
The dialog is mostly a warning about negative impacts of this feature. The description is below the checkbox title.
@garvankeeley How about:

> Retrieve and show the Mozilla Location Service (MLS) estimated location for each report.

**Comment by garvankeeley** [comment]
@cascheberg yes, I think that is an improvement

**Comment by kparal** [comment]
I still have no idea what "MLS estimated location" is, neither from the old nor from the new description. If I enable it, I see green dots at places I went through, and some linked red dots which are quite off the path. My request was to help the users (and myself) understand what those red dots mean. I haven't found any documentation on the web that would explain it.

**Comment by garvankeeley** [comment]
I can explain and perhaps you can help me shorten the description for fitting on a dialog.

Based on the visible Wi-Fis and Cell Towers, Mozilla Location Service (MLS) can return your location. Those are the red dots on the map. To tie these dots to the actual GPS location, there is a 1 pixel line from the red dot to the GPS dot. 
The more stumbling that happens in a given area, the closer the red dots will be to the GPS dots.

**Comment by kparal** [comment]
Oh, that's interesting. So basically it shows the location precision based on previous stumbled data. Thanks for explanation.

I'm sure some native speaker will be able to provide a better suggestion, but what about:

> At the cost of a bit more energy, memory and network usage, the MLS location is shown for each report - i.e. your estimated location based on already stumbled data. This is shown as a red dot with a line to its report. The closer it is to your actual GPS location, the more reliable and precise the location service is. More stumbling in the area improves this.
> This will not work over mobile data if "Auto-upload only on Wi-Fi" is enabled.

If people understand the principle, it can motivate them to stumble more. I didn't know this, and somewhat ignored the blue-covered areas, because of "ah, already stumbled" approach. This could help them realize that more stumbling is valuable because it improves accuracy.
