### ISSUE TITLE
Won't upload 

### ISSUE THREAD

**Issue by duckworth** [mozilla/MozStumbler#143]
I have 2930 locations scanned and have tried starting and stopping several times but I have yet to have it upload anything. The "Last Upload Time" is "-".
This is on an LG G2 running Android 4.2.2

Connecting to logcat I noticed:

```
E/org.mozilla.mozstumbler.Reporter( 3587): urlConnection returned 400
E/org.mozilla.mozstumbler.Reporter( 3587): error submitting data
E/org.mozilla.mozstumbler.Reporter( 3587): java.io.FileNotFoundException: https://location.services.mozilla.com/v1/submit
E/org.mozilla.mozstumbler.Reporter( 3587):  at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:186)
E/org.mozilla.mozstumbler.Reporter( 3587):  at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
E/org.mozilla.mozstumbler.Reporter( 3587):  at org.mozilla.mozstumbler.Reporter$1.run(Reporter.java:192)
E/org.mozilla.mozstumbler.Reporter( 3587):  at java.lang.Thread.run(Thread.java:856)
```

**Comment by cpeterso** [comment]
@hannosch: Have you seen any HTTP 400 Bad Request errors in the server logs? Could this be related to the SSL certificate problem we saw on some older Android versions? Note that @duckworth is using Android 4.2.2 (Jelly Bean MR1), so that should not be this problem.

**Comment by pcdinh** [comment]
I use Galaxy Note 2, OEM ROM MozStumbler 0.7.0. 

MozStumbler refuses to upload 2000+ data points after I submit the data when the network is unavailable. When the internet connection is ready, I can not submit them again.

After restarting my phone, I see 

```
The "Last Upload Time" is "-".
```

**Comment by colinfrei** [comment]
I've had similiar problems. I wonder if this has to do with the network only being available sporadicly. I'm currently on vacation and logging everything but can't upload until I get into the hotel (and sometimes need to log into the wifi).

**Comment by hannosch** [comment]
@cpeterso I've seen some 400 errors and some new 408 errors. I cannot tell which of these are bots/spammers trying to break things and what are actual requests. The 400 errors are all reported without a user-agent or url path.

I did increase the HTTP timeouts from their default 60 seconds to 120 seconds. This in combination with using a batch size of 20 should minimize the risk of the server closing the connection before all data could be transmitted.

But without any client side error/retry handling, I'm assuming it'll try to send data even when no data connection is available. Or the phone will try to establish a data connection and the client side request might time out before the connection is actually up.

The client should probably try to re-send data until it has gotten a 204 status code back and only then clear the local data.

**Comment by cpeterso** [comment]
The client asks Android's ConnectivityManager whether there is a data connection before attempting to upload, but we still need better network error handling.

**Comment by miketaylr** [comment]
I've got the same issue on my HTC One running 4.3. Never uploads over wifi, 4G or 3G.

**Comment by duckworth** [comment]
I built and installed the HEAD build (3e2e80a14c) today and it uploaded data once, about a minute after the apps started and then stopped again. I gathered 954 locations but they won't upload. I am seeing a few errors in the logs. 

```
org.mozilla.mozstumbler.MapActivity(26315): uploaded data: {"wifi":[{"key":"10bf4853c204","signal":-61,"frequency":5805},{"key":"10bf4853c200","signal":-64,"frequency":2437}]} to https://location.       services.mozilla.com/v1/search
 33252 E/org.mozilla.mozstumbler.MapActivity(26315): urlConnection returned 200
 33253 E/org.mozilla.mozstumbler.MapActivity(26315): json parse error
 33254 E/org.mozilla.mozstumbler.MapActivity(26315): org.json.JSONException: No value for lat
 33255 E/org.mozilla.mozstumbler.MapActivity(26315):   at org.json.JSONObject.get(JSONObject.java:354)
 33256 E/org.mozilla.mozstumbler.MapActivity(26315):   at org.json.JSONObject.getString(JSONObject.java:510)
 33257 E/org.mozilla.mozstumbler.MapActivity(26315):   at org.mozilla.mozstumbler.MapActivity$GetLocationAndMapItTask.doInBackground(MapActivity.java:208)
 33258 E/org.mozilla.mozstumbler.MapActivity(26315):   at org.mozilla.mozstumbler.MapActivity$GetLocationAndMapItTask.doInBackground(MapActivity.java:154)
 33259 E/org.mozilla.mozstumbler.MapActivity(26315):   at android.os.AsyncTask$2.call(AsyncTask.java:287)
 33260 E/org.mozilla.mozstumbler.MapActivity(26315):   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
 33261 E/org.mozilla.mozstumbler.MapActivity(26315):   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 33262 E/org.mozilla.mozstumbler.MapActivity(26315):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 33263 E/org.mozilla.mozstumbler.MapActivity(26315):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 33264 E/org.mozilla.mozstumbler.MapActivity(26315):   at java.lang.Thread.run(Thread.java:856)
 33265 E/org.mozilla.mozstumbler.MapActivity(26315):
 33266 E/org.mozilla.mozstumbler.MapActivity(26315): java.lang.IllegalStateException: mStatus=not_found
 33267 E/org.mozilla.mozstumbler.MapActivity(26315):   at org.mozilla.mozstumbler.MapActivity$GetLocationAndMapItTask.onPostExecute(MapActivity.java:234)
 33268 E/org.mozilla.mozstumbler.MapActivity(26315):   at org.mozilla.mozstumbler.MapActivity$GetLocationAndMapItTask.onPostExecute(MapActivity.java:154)
 33269 E/org.mozilla.mozstumbler.MapActivity(26315):   at android.os.AsyncTask.finish(AsyncTask.java:631)
 33270 E/org.mozilla.mozstumbler.MapActivity(26315):   at android.os.AsyncTask.access$600(AsyncTask.java:177)
 33271 E/org.mozilla.mozstumbler.MapActivity(26315):   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
 33272 E/org.mozilla.mozstumbler.MapActivity(26315):   at android.os.Handler.dispatchMessage(Handler.java:99)
 33273 E/org.mozilla.mozstumbler.MapActivity(26315):   at android.os.Looper.loop(Looper.java:137)
 33274 E/org.mozilla.mozstumbler.MapActivity(26315):   at android.app.ActivityThread.main(ActivityThread.java:5168)
 33275 E/org.mozilla.mozstumbler.MapActivity(26315):   at java.lang.reflect.Method.invokeNative(Native Method)
 33276 E/org.mozilla.mozstumbler.MapActivity(26315):   at java.lang.reflect.Method.invoke(Method.java:511)
 33277 E/org.mozilla.mozstumbler.MapActivity(26315):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
 33278 E/org.mozilla.mozstumbler.MapActivity(26315):   at com.android.internal.os.ZygoteInit.main(ZygoteI
```

The app says there are still 954 locations but the last log entry says

```
 D/org.mozilla.mozstumbler.Reporter(26354): sendReports: force=true
D/org.mozilla.mozstumbler.Reporter(26354): no reports to send
```

**Comment by miketaylr** [comment]
> I've got the same issue on my HTC One running 4.3. Never uploads over wifi, 4G or 3G.

Strike that, just went for a bikeride and it's uploaded by itself: "Last Upload Time: Oct 29, 2013 1:04:10PM".

**Comment by hannosch** [comment]
@duckworth the log entries you have are actually expected. it's very verbose output for the server sending a perfectly normal {"status": "not_found"}. But those are only for the search interface (the "test the service" button).

**Comment by duckworth** [comment]
@hannosch ok, odd. I must have accidentally clicked the Test button. 
Still not sure why it isn't uploading. Let me know if there is anything specific I can do.

**Comment by cpeterso** [comment]
@duckworth: The Test (was "Locate Me" button) does start scanning without uploading. When loading the map, we should probably just scan once so we don't keep running.

**Comment by dougt** [comment]
if this is still a problem, please open.

**Comment by colinfrei** [comment]
For the record, works much better for me with the last few versions.
