### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by tjrptupr** [mozilla/MozStumbler#1431]
Add option to export scans to a .csv file for personal use.

**Comment by crankycoder** [comment]
Exporting to CSV doesn't make a lot of sense to me.  We have a JSON format which is exportable right now. I don't think that flattening out the data to CSV gives us much advantage, and it's yet one more format that we need to support, but we do not internally use.

Is there a usecase for CSV data or would JSON data be ok?

**Comment by crankycoder** [comment]
We've got JSON export already.
