### ISSUE TITLE
Provide Czech translation for MozStumbler

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/MozStumbler#1433]
Hi.

In Mozilla.cz we are interested in translating Mozilla Stumbler to Czech. What's the proper process for adding new language to Mozilla Stumbler and which files should be translated, please?

**Comment by swarnava** [comment]
You can start from here:
- https://github.com/mozilla/MozStumbler/blob/dev/android/src/main/res/values-cz/strings.xml

**Comment by cascheberg** [comment]
@MikkCZ you can find all the existing strings here

> https://github.com/mozilla/MozStumbler/blob/dev/android/src/main/res/values/strings.xml

and you should copy the translated strings into this file

> https://github.com/mozilla/MozStumbler/blob/dev/android/src/main/res/values-cs/strings.xml

(the ending "-cz" was incorrect, so the file was moved).
Then create a new PR with those changes.

**Comment by MikkCZ** [comment]
@swarnava @cascheberg Thank you both. Here https://github.com/mozilla/MozStumbler/pull/1444 is my pull request.

**Comment by MikkCZ** [comment]
Fixed by https://github.com/mozilla/MozStumbler/pull/1444.
