### ISSUE TITLE
paused mode should set gps/wifi/cell values to zero

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1436]
this is an issue that was brought up in #1322

since the device isn't scanning anything in paused mode those values probably should be set to zero to avoid confusion

**Comment by cascheberg** [comment]
My patch does not set wifi/cell values to zero in all cases properly, but I can fix that...

**Comment by Djfe** [comment]
Well reports shouldn't be set to zero :D
but if there any other cases, you want to fix with followup prs
-> sure and thx in advance for your work ;)
