### ISSUE TITLE
Leaderboard is not updating

### ISSUE THREAD

**Issue by swarnava** [mozilla/MozStumbler#1446]
I am having issue with mozstumbler, on leaderboard my point is not updating. It is also happening with other two mozillian..is it known issue?

**Comment by garvankeeley** [comment]
I'm not aware of a problem,
@hannosch any idea?

**Comment by hannosch** [comment]
I'm not aware of any problems with the leaderboard.

**Comment by Djfe** [comment]
Does the log confirm, that they get uploaded to ichnaea correctly?
Are the new dots appearing on the map?

**Comment by swarnava** [comment]
I dont know whats was wrong exactly, but after doing factory reset, leaderboard seems updating properly.
