### ISSUE TITLE
Cannot build anymore (win)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1452]
I get a german error if I try to build MozStumbler at the moment.

the following line in the build.gradle file seems to be the issue:
def gitHash = "git rev-parse --short HEAD".execute().text.trim()

It complains about not being able to find the file (I guess it's about git)

I "registered" git in Android Studio though.

Before it was the portable version that came with the Github for Windows client.
Now it's the standalone git command line tool.
But that didn't change anything at all.

Do I need to add git to my environment variables now or what is the reason?
Is this related to changes that have been made to the build file lately? I guess it is only windows related.

The exakt error line:
`Error:(40, 0) CreateProcess error=2, Das System kann die angegebene Datei nicht finden`

Pls help me.

**Comment by crankycoder** [comment]
Urgh.  I don't have access to a Windows machine over here. 

@garvankeeley - this is your call as module owner, but I think we want to officially support Windows as a build platform.  I'm not sure what to do about CI builds though as Travis doesn't support Windows.  I guess we could spin up a small long running EC2 box for that.

**Comment by lua86** [comment]
I am sorry but I don't see any reason to support W$ as a build platform. I think it is pretty unnecessary hassle

**Comment by Djfe** [comment]
It's just useful for me and others that wan't to contribute, but have only Win installed.
I wouldn't need travis for that.

And since building the app through android studio has worked before it might be only a small issue (maybe even on my side)

**Comment by garvankeeley** [comment]
We need all the contributions we can get, so we want to keep our system working on Windows. The whole tech stack should be platform neutral. I think C.I. for it is overkill, but when Windows build bugs come in we should try to fix them. 
I am trying to free up hard disk space this week to get a Windows 8.1 VM running on my system. So I'll be able to help look at bugs like this soon.

**Comment by Djfe** [comment]
Maybe I could bisect in that time to find out since when it doesn't work anymore

**Comment by Djfe** [comment]
so by testing I know for sure now that I'm not able to build anymore since version 1.5.5

the issue got introduced between version 1.5.4 and 1.5.5

v1.5.4 builds fine, v1.5.5 has the same error message as above (maybe the lines are different but the issue is caused by the same line)

**Comment by Djfe** [comment]
I guess it was this one:
https://github.com/Mozilla/MozStumbler/commit/70a4b646423cf7581be1c40a7bdb02eb2207ff73

**Comment by Djfe** [comment]
Fixed the issue by myself:
I reinstalled git and this time checked the option to make git available in the windows console as well and not only for bash (maybe a stupid issue on my side, but i thought pointing Android Studio to the git executable like before was enough, but since the gradle script itself now uses git...)

worked like a charme now

is .execute a hacky fix or the way to go normally?

EDIT: just found this
http://stackoverflow.com/questions/16614410/android-studio-checkout-github-error-createprocess-2-windows
