### ISSUE TITLE
Describe motion sensors

### ISSUE THREAD

**Issue by naoliv** [mozilla/MozStumbler#1460]
What exactly is a "legacy motion sensor" and a non-legacy?

**Comment by crankycoder** [comment]
Android provides several motion sensors that are available depending on the version of Android you're running and your hardware and chipset support. 

Legacy motion sensor refers to our wrapping of the standard accelerometer and linear accelerometer. These basically measure acceleration in 3 directions. The linear accelerometer tries to remove the force of gravity. 

Newer higher end devices support a significant motion sensor which tries to be smarter and will notify the application when Android believes the phone has moved locations. 

Performance and quality of these sensors varies across hardware and software so our current problem is trying to determine a good fall back solution  when sensor data seems to be misbehaving.

**Comment by crankycoder** [comment]
Is there an actual issue here or is this a comment that we should have some documentation around this?

**Comment by naoliv** [comment]
One doubt is that I have a Motorola Moto G 2nd generation and I don't know if my device lacks a more advanced sensor or if somehow MozStumbler is misdetecting it.
Another doubt was exactly an explanation/documentation about this.

**Comment by garvankeeley** [comment]
We are still actively refining this part of the app, so the definitions aren't fully set in stone. Currently, the legacy sensor is using the accelerometer and the non-legacy uses the significant motion sensor.

As for the Moto G, what we are finding is that certain devices are falsely reporting having a significant motion sensor. The next github release will have an attempt at fixing this.

**Comment by crankycoder** [comment]
Closing as not actionable.
