### ISSUE TITLE
Autostart option

### ISSUE THREAD

**Issue by JNKL** [mozilla/MozStumbler#1466]
I am letting MozStumbler run pretty much all the time. Autostart/dont-close option would be nice.

**Comment by crankycoder** [comment]
I'm not sure what this means. 

On the first run of the stumbler,  the application goes into an active run state. 

It remains running unless it's killed or is explicitly stopped. 

Do you mean you'd like to have the application automatically schedule itself for restart after being killed?

**Comment by crankycoder** [comment]
Not actionable.

**Comment by kolesar-andras** [comment]
I have a use case where I need autostart feature.

I ask my family and friends to collect data when they drive around. They install application and forget about it. I need the application to start automatically on boot (as a service) and collect data in the background when navigating with GPS (using passive listener, #356).

It would multiply the number of contributors.

**Comment by hannosch** [comment]
@kolesar-andras If you want your family members to contribute data, without them having to remember starting an application, you should probably install Firefox for Android on their phones and ask/help them to enable the contribution option (https://support.mozilla.org/t5/Personalize/Improve-Mozilla-Location-Services-by-turning-on-Location/ta-p/35491).

This uses the passive location provider, so if any other application turns on the GPS on the phone, Firefox for Android will also collect the cell/wifi networks and store those in the background, to later batch upload them when the phone connects to a WiFi network. This is optimized to not cause any noticeable battery drain and also avoids using any data from a cellular data plan.

The Mozilla Stumbler standalone application is aimed at very active contributors.

**Comment by kolesar-andras** [comment]
Thank you, I will install Firefox for Android. Does it work even when Firefox was not yet used since boot?

**Comment by hannosch** [comment]
@crankycoder might know for sure.

I think the stumbler in Firefox for Android registers itself as some kind of background system service and that portion of the app is woken up by the system, even when the user hasn't opened the app yet.

**Comment by kolesar-andras** [comment]
Screenshots and text do not match recent version of Firefox. I have found different name for menu: Settings / Privacy (not Mozilla).

How can I check if it works?

**Comment by hscsjk** [comment]
제3자-스토커-때문에 제대로 컴퓨터를 만질수없음  본인것과 똑같은 pc 와 스마트폰을 가지고 있는것으로 생각됩니다.  컴퓨터해킹및 스마트폰해킹  본인으로 행세함  수년간 본인의 계정과 비밀번호을 가로채서 ip를 바꿔가며  본인을 괴롭힙니다
