### ISSUE TITLE
Failure attempting to run make

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/MozStumbler#1477]
I've tried to run 'make' on the repo on two separate machines, a macbook running OSX Yosemite and an EC2 running Ubuntu 14.04 and I get the following on both:

SDK extracted at '/home/ubuntu/.android-sdk'. Writing to local.properties.
No /home/ubuntu/MozStumbler/android/properties/private-github.properties for Mozilla API Key configuration.
No /home/ubuntu/MozStumbler/android/properties/private-github.properties for TileServer configuration.
No /home/ubuntu/MozStumbler/android/properties/private-playstore.properties for Mozilla API Key configuration.
No /home/ubuntu/MozStumbler/android/properties/private-playstore.properties for TileServer configuration.
Writing custom MozAPIKey: ["c94d7d63-cb0c-4ad5-9f94-f39b1d277822"]
No /home/ubuntu/MozStumbler/android/properties/private-fdroid.properties for TileServer configuration.
Build tools 19.1.0 missing. Downloading...
Platform tools missing. Downloading...
Compilation API android-19 missing. Downloading...

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/ubuntu/MozStumbler/android/build.gradle' line: 197
- What went wrong:
  A problem occurred evaluating project ':android'.
  
  > Failed to apply plugin [id 'android-unit-test']
  > failed to find target android-19 : /home/ubuntu/.android-sdk
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 58.492 secs
make: **\* [libtest] Error 1

**Comment by crankycoder** [comment]
android-sdk-manager is misbehaving.  

I'll update the docs as I'm working on #1428 rigt now - but in the short ter - you basically need to run make twice.  Like compiling your LaTeX in the 90s.

I suggest:

`make clean; make test`

After that - things should only require a single invocation of `make`.
