### ISSUE TITLE
Limited zoom feature problems

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#1481]
@garvankeeley there are some more problems with #1463 / #1474 
- zooming out on low-res map becomes blank
- both res types do not show the MLS coverage anymore when zooming out too far
- I think the description text is not quite accurate. I suggest something like: zooming out can increase data usage (instead of conveying that the feature generally reduces data usage)

**Comment by crankycoder** [comment]
I'm confirming the first 2 problems : 
- if I use only low-res maps and zoom out all the way, maps become blank.
- MLS coverage does seem to disappear on both high-res only and low-res only maps on maximal zoom.

I think the description is ok as it is already.  The default setting is that we limit the zoom and the data usage.

**Comment by garvankeeley** [comment]
Moved this to developer activity until this is fixed.
https://github.com/mozilla/MozStumbler/pull/1491
