### ISSUE TITLE
status bar is only updated on intervals -> wrong numbers on start

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1484]
if there hasn't happened an upload the last time the app was open then the numbers in the status bar are wrong for some time
In this screenshot there aren't too many, but the status bar should use the actual numbers on app start and then start updating them periodically, I think (faster wasn't possible I think due to interface limitations)

![2015-01-30 17 26 52](https://cloud.githubusercontent.com/assets/5685512/6194557/c49ab428-b3c5-11e4-94f0-11532f396d5a.png)

**Comment by cascheberg** [comment]
I think changing the parameter [here](https://github.com/mozilla/MozStumbler/blob/dev/android/src/main/java/org/mozilla/mozstumbler/client/MainApp.java#L277) to `true` will fix the problem. But that will immediately update the notification after creation, and I do not know what that looks like in Android versions that use an animation for that.

**Comment by garvankeeley** [comment]
Is this related to #1524?

**Comment by crankycoder** [comment]
I think this is the same bug as #1524.  We aren't emitting the intent to update statistics in any case other than on `PersistedStats::incrementSyncStats`.

**Comment by garvankeeley** [comment]
This isn't fixed with 1524 landed
