### ISSUE TITLE
Shouldn't "_nomap" mean no-log as well

### ISSUE THREAD

**Issue by mvsantos** [mozilla/MozStumbler#149]
Most likely I'm missing something here, so please do correct me if I'm wrong.

Looking at the class SSIDBlockList in https://github.com/dougt/MozStumbler/blob/master/src/org/mozilla/mozstumbler/SSIDBlockList.java 
it's a simple string filter that allow networks to opt-out of the mapping by appending "_nomap" to their SSID.
And that could be done on the basis of privacy concerns and countless other reasons, which are all irrelevant to the point I'm about to raise.

Then checking line 131 of WifiScanner. After it checks SSIDBlockList, it logs the scanResult any way. 
So regardless of the reason why that Network opted-out of the mapping, the application still logs that Network scan result.
See https://github.com/dougt/MozStumbler/blob/master/src/org/mozilla/mozstumbler/WifiScanner.java#L131

My point being: if a network opt-out by using the "_nomap" then the app should respect that at all levels and not log anything about that network.
It looks like the "_nomap" means: Hey, we won't plot your network in a map nor make it searchable for third-parties, but we'll still store data about it regarless of your opt-out instruction.
Surely verbose logging eases debugging, but the user's options should be respected, don't you think?

**Comment by cpeterso** [comment]
@mvsantos: not logging `_nomap` SSIDs even to debug logs is a good idea. As you pointed out, the stumbler client logs the `_nomap` SSID name locally, but doesn't upload it.
