### ISSUE TITLE
Accelerometer Motion sensor gaps in scanning

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1490]
Been testing the latest accelerometer-based power savings on the S5, and results are very good overall. 
I ran into one case where the scanning stayed paused, not sure why just yet. The blue arrow is where the scanning stopped at a streetlight and did not restart. One possibility is a GPS problem.
![screenshot 2015-02-15 12 18 22](https://cloud.githubusercontent.com/assets/5495083/6230679/80aa4d88-b68f-11e4-8b70-ba16adbeed4e.png)

**Comment by garvankeeley** [comment]
For comparison, this is a correct gap in the data, where I was driving and stopped for 2 mins:
![screenshot 2015-02-15 12 15 28](https://cloud.githubusercontent.com/assets/5495083/6230712/c5eed7f6-b68f-11e4-96ac-15201e283cd0.png)

**Comment by crankycoder** [comment]
I've seen the same behavior on the Nexus 4 and Moto G devices while riding the bus back to Newmarket.  I'm in agreement that this is probably some problem with losing the GPS fix.

**Comment by garvankeeley** [comment]
Here is a deceleration that should have triggered the sensor and did not:

![screenshot 2015-02-20 12 05 33](https://cloud.githubusercontent.com/assets/5495083/6305378/d64e3e00-b8f8-11e4-9eeb-7c800c29e7ad.png)

**Comment by garvankeeley** [comment]
I am no longer getting this behaviour after #1502 landed.
