### ISSUE TITLE
Significant motion sensor doesn't wake up when current location dot indicates movement

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1496]
The significant motion sensor doesn't seem to always be hooked into the GPS location.

I think we need to do some work here to capture a delta between the last 2 known GPS locations and force a wakeup.  Here - I'm on a train that is accelerating slowly.  The phone clearly knows that I"m moving - the map centering appears to be correct, but you can see the overlay that indicates that the stumbling has been put into a pause state.

![2015-02-20 07 10 40](https://cloud.githubusercontent.com/assets/4829/6308667/2b60f73c-b914-11e4-8655-350633353a17.png)
![2015-02-20 07 13 23](https://cloud.githubusercontent.com/assets/4829/6308671/3a28d8b6-b914-11e4-9bda-8b298b333118.png)

My accelerometer indicated that I was accelerating @ 1.7m/s^2 on the train - not sure off hand if that's just below the threshold of waking up or not.

This was observed on my OnePlus One phone.   Screen was on (obviously).

**Comment by garvankeeley** [comment]
I would have thought the wifi-based location changes would have triggered the sig. motion sensor. I assumed that was one of the things it was watching as a trigger.

**Comment by garvankeeley** [comment]
Updated the title to reflect that the current position dot may be updating based on wifi positioning.

The MapLocationListener.java has both a GPS and a network location listener. It is likely the latter that is changing. And yes we should have that trigger that motion is occurring.

**Comment by crankycoder** [comment]
dmesg shows

```
<6>[360665.764745] wlan: WCNSS software version MSM8974-PR_1_4_c2-00125
<6>[360665.764791] wlan: WCNSS hardware version WCN v2.0 RadioPhy vIris_TSMC_3.0 with 48MHz XO
```

which looks like a Motorola chip.

The accelerometers are on the QC chipset, so it seems pretty reasonable that the significant motion sensor isn't seeing the wifi location.

**Comment by crankycoder** [comment]
Hrm.. the snapdragon 801 should have wifi on board.

https://www.qualcomm.com/products/snapdragon/processors/801

but who knows. Maybe the wifi location lookups aren't fed back into the chipset.
