### ISSUE TITLE
Stumbler doesn't exit anymore since 0.7.1

### ISSUE THREAD

**Issue by whimboo** [mozilla/MozStumbler#150]
Today I have installed version 0.7.1 and now stumbler doesn't exit anymore. The tray icon is still around all the time. If it is a service now, can we at least add a menu entry to fully quit stumbler?

Thanks

**Comment by cpeterso** [comment]
@whimboo: did you open the stumbler's map view? The map starts scanning (so it has WiFi access point names to ask the server about). After viewing the map, you may need to go back to the app's main UI and press the "Stop Scanning" button to be sure. When loading the map, we should probably just scan once.

**Comment by whimboo** [comment]
No, I didn't. But while stumbler was running I got an upgrade notice and upgraded the application to the latest version. Seems like that this caused the problem. When I again click start and stop the notification area entry is gone.

**Comment by dougt** [comment]
closing.  PR #206
