### ISSUE TITLE
NPE HTTP response client (log)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1505]
I dunno if this is a bug but I saw this in the log:
![2015-02-23 16 01 28](https://cloud.githubusercontent.com/assets/5685512/6367921/f6b5a6a0-bcd7-11e4-9810-c6757da429c6.png)

it says that this shouldn't have happened (NPE)

the reason that it happened was a bad connection to a cell tower, so maybe you can somehow fix something there (the npe is already being catched, I guess -> else the log entries wouldn't be there)

**Comment by garvankeeley** [comment]
This is saying there is no network connection. We should remove these messages. They are benign and part of normal operation.
EDIT: Confirm this assumption with @crankycoder

**Comment by garvankeeley** [comment]
The message in red can definitely be removed from the log. The other message I am not so sure about.

**Comment by crankycoder** [comment]
@djfe - which stumber version is this?  

Hrm. I was going to say that this is a synchronization bug, but it looks like a plain old network failure.

I'll clean up the networking code so that we really never return NULL.  We can just wrap it with a bogus HTTP 5xx error like 598.

**Comment by Djfe** [comment]
I think this was either version 1.7 or version 1.6.1, not too sure.
