### ISSUE TITLE
unlimited map zoom bug (tiles not visible)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1506]
we don't get MLS tiles above the limited zoom level (pls fix this) (I just see the map without the coverage tiles

-on the low resolution mode you don't see any map at all at a certain zoom level (just the circles on the map)

**Comment by Djfe** [comment]
#1481

**Comment by Djfe** [comment]
I closed this because it's a duplicate, but ok

**Comment by garvankeeley** [comment]
If someone picks this up as a 'good first bug', ping me and I can point you in the right direction. I think.

**Comment by cascheberg** [comment]
The problem appears to be that the map does not scale existing tiles when zooming out (while it apparently does this when zooming in). So the overlays disappear when the zoom is lower than the configured `aZoomMinLevel`, which is 10 for the `CoverageOverlay` and 11 for the `LowResMapOverlay`.

These two overlays only have two fixed zoom levels. Would it be okay to have coverage tiles with the full possible min max zoom level range in high resolution mode instead?
