### ISSUE TITLE
Allow Offline Maps

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#1513]
A feature request.  It would be good to have the ability for users to download their own offline maps, at the moment I must use Mozstumbler with maps disabled as my data plan is too small for able to have maps downloaded as I stumble.

A solution like c:geo which allows user to download maps and manually install like from http://download.mapsforge.org/ or OSMAnd which allows you to install offline maps from with in the app would be good options

**Comment by Djfe** [comment]
I'm not sure how the situation is, but map caching should prevent that from happening (if you are not deleting the big looking cache of mozstumbler manually (it's sometimes 50-100mb cache on the sd card)

there were a lot of issues with it in the past -> that the cache got deleted far to early and stuff

partially it's fixed already

@crankycoder what is the status on this?

and apart from that offline map support would be great!
I would like to see support for reusing the map of osmand (maybe)

**Comment by cascheberg** [comment]
Using the stumbler offline has been improved recently, see my comment in #1210. Another helpful and certainly easier to implement feature is #1408.

**Comment by grrrrr** [comment]
@Djfe  @cascheberg 

The problems is that I do not know where I am necessarily going from day to day so I am unlikely to have cached where I will be going.  My data is very limited - 250mb for 1 month.

Maybe #1408 is one solution but it mean that I have to scroll around map on wifi caching a city / country. unlike just downloading a precompile map like I suggest and having it ready to go no planning needed

**Comment by grrrrr** [comment]
to also add it means that with an offline map a user does not have to cache tiles at various levels

**Comment by crankycoder** [comment]
If you don't know where you are going,  we need a way to specify what maps to download.  If someone can sketch out a UI that would help to move this bug forward.

**Comment by Djfe** [comment]
The first question IMO is:
What would we want to cache:
tiles or vector maps?

and what is smaller in the end?

**Comment by grrrrr** [comment]
closing as project is no longer active - https://discourse.mozilla.org/t/retiring-mozilla-stumbler/75206
