### ISSUE TITLE
wrong changelog after update

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1521]
Changelog after updating to 1.7.2 shows the 1.6.1 changelog

![2015-02-27 18 40 07](https://cloud.githubusercontent.com/assets/5685512/6419634/108b9dbc-bebf-11e4-8d34-4000ca00b40b.png)

**Comment by RunningDroid** [comment]
Happened to me too
![screenshot_2015-02-28-12-41-02](https://cloud.githubusercontent.com/assets/486393/6427204/97e41072-bf47-11e4-9e6f-a09ccb0934db.png)

**Comment by garvankeeley** [comment]
Note, we should fix this for play store release, or switch to the link to the notes #1489

**Comment by garvankeeley** [comment]
This should be in sync for 1.7.4

**Comment by cascheberg** [comment]
@garvankeeley You should delete the translated changelogs so that they show the up-to-date English version instead of the outdated translated version.

**Comment by crankycoder** [comment]
We just dropped the changelog entirely.  We don't have a formal translation process which allows us to update all the translation before every point release.
