### ISSUE TITLE
MozStumbler preemption.

### ISSUE THREAD

**Issue by pepyakin** [mozilla/MozStumbler#153]
Sometimes MozStumbler resets all stuff that is displays. 
This usually happens when I launch something heavy besides MozStumbler.

For example, im walking on street and scanning is turned on. Then I scan a lot and I want to see where Im on leader board, so I start browser (which is heavy app), see some stuff and go back to MozStumbler and see that all counters are zero and big button prompts me to "start scanning", but MozStumbler icon in notification area is still there!
Also, I noticed that just before such "preemption" GPS icon dissappears.

Galaxy Nexus, 
version 4.3
0.7.1

UPDATE:
Im not sure, and dont have much time to investigate, but brief look at logcat and dumpsys output says that your service is not foreground and freely can be killed, so that happens after host activity dies.

**Comment by cpeterso** [comment]
I think this bug is related to issue #7, where we leak the MainActivity and end up running two MainActivities.

**Comment by pepyakin** [comment]
hm, I think it isn't.
Process hosting only service can be freely killed.
Consider to use Service#startForeground method.
30 окт. 2013 г. 20:44 пользователь "Chris Peterson" <
notifications@github.com> написал:
