### ISSUE TITLE
Can't be toggled off at all

### ISSUE THREAD

**Issue by kparal** [mozilla/MozStumbler#1554]
After today's update (stumbler 1.7.5), I can't disable scanning **at all**. Every time I put the slider to OFF, it jumps back to ON instantly. I tried it like 20 times, it happens every time. I had to kill Stumbler from the list of running applications to make it stop scanning. Can anyone reproduce?

Android 4.4
Motorola Moto G 4G

**Comment by crankycoder** [comment]
Duplicate of #1550. Patched in #1553

**Comment by crankycoder** [comment]
@kparal I just pushed out 1.7.6 now to google play, fdroid and the github release.  Can you give this a try again?

Sorry for this regression - it slipped through.  Gah.

**Comment by sshvetsov** [comment]
Appears to be fixed for me.

**Comment by kparal** [comment]
Seems to work properly now.
