### ISSUE TITLE
Geolocate JSON request is inconsistent with API specification

### ISSUE THREAD

**Issue by sshvetsov** [mozilla/MozStumbler#1556]
StumblerBundle.toMLSGeolocate() generates JSON that is not consistent with geolocate request format specified in https://mozilla-ichnaea.readthedocs.org/en/latest/api/index.html#geolocate (which points to https://developers.google.com/maps/documentation/business/geolocation/#requests)

JSON specified by the geolocate API document looks like this:

```
{
  "homeMobileCountryCode": 310,
  "homeMobileNetworkCode": 410,
  "radioType": "gsm",
  "carrier": "Vodafone",
  "cellTowers": [
    "cellId": 42,
    "locationAreaCode": 415,
    "mobileCountryCode": 310,
    "mobileNetworkCode": 410,
    "age": 0,
    "signalStrength": -60,
    "timingAdvance": 15
  ],
  "wifiAccessPoints": [
    "macAddress": ...,
    "signalStrength": ...,
    "age": 0,
    "channel": 11,
    "signalToNoiseRatio": 40
  ]
}
```

JSON generated by toMLSGeolocate() looks like this:

```
{
  "latitude": ...,
  "longitude": ...,
  "timestamp": ...,
  "cellTowers": [
    "cellId": 42,
    "locationAreaCode": 415,
    "mobileCountryCode": 310,
    "mobileNetworkCode": 410,
    "radioType": "gsm",
    "signalStrength": -60,
    "timingAdvance": 15,
    "psc": ...,
    "asu": ...
  ]
  "wifiAccessPoints": [
    "macAddress": ...,
    "frequency": ...,
    "signalStrength": ...
  ]
}
```

Either Ichnea API description needs to be updated to reflect the actual request format, or MozStumbler generates incorrect geolocate request to MLS.

**Comment by hannosch** [comment]
We need to update the ichnaea docs here. This is a purposeful deviation from the GLS API. Or rather we support putting radioType both in the top-level and in the per-cell entry.

The use-case here are multi-sim devices, which can have two cell connections, for example one for a 2G GSM network and one for a 3G WCDMA network at the same time. A radioType at the top would mean you'd only be able to send one of those cells to the service.

**Comment by sshvetsov** [comment]
What about "psc" and "asu" properties in the "CellTowers", which aren't present in GLS spec, do they have effect on the request?
What about "age" property in "CellTowers", in GLS spec, is it supported by MLS?
What about the format differences in "WifiAccessPoints"?

Perhaps it is time to fully define the "geolocate" API in MLS?

**Comment by hannosch** [comment]
@sshvetsov, yes it is time to have our own complete spec. Especially now that combain has adopted many of the small changes we made to the GLS API as well (and added a couple of their own).

**Comment by sshvetsov** [comment]
So should this issue be moved to Ichnaea project then?

**Comment by hannosch** [comment]
@sshvetsov yes, this is actually an ichnaea issue, would you mind copying it over? Doesn't look like github has a feature to do this in a nicer way.

**Comment by sshvetsov** [comment]
@hannosch done, created new issue in Ichnaea project (mozilla/ichnaea#419). @crankycoder I think this ticket can be closed now.

**Comment by hannosch** [comment]
Thx!
