### ISSUE TITLE
geolocate is including radioType in the wrong place in the JSON blob

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1557]
Geolocate includes the radioType in the wrong location.  Ensure that we do _not_ affect the radio field for geosubmit when we make this change.

See: https://github.com/mozilla/ichnaea/issues/416

**Comment by sshvetsov** [comment]
I also created #1556, since it seems like other property names and placement in the JSON blob are not quite consistent with geolocate API.

**Comment by hannosch** [comment]
The client code is correct here and does what I thought the API was. Turns out there's another bug on the service end.

**Comment by crankycoder** [comment]
@hannosch I've just added the radioType as per the Google spec in #1558 to work around the problem where cell-only geolocate calls were returning geo-ip only.  The per cell tower records contain the radioType field still as well.
