### ISSUE TITLE
Intermittent failure to have a persistent "Last upload date".  Occasionally resets to 'never' 

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#1568]
MozStumbler: 1.7.7
CyanogenMod CM11 

Following an update to MozStumbler 1.7.7, the application is no longer reporting results in the `Already Sent` section.

`Last uploaded` is always listed as `never` despite successful uploads according to the logs. Previously this would show the last uploaded date
`Roports` is left blank, previously this would show the number of records uploaded since install

**Comment by crankycoder** [comment]
How is this bug reproduced?   1.7.7 had a fix specifically for this
problem.

**Comment by grrrrr** [comment]
I am not sure how to reproduce from my end other than, record data and upload and note neither field changes.  

It's possible that it was broken before 1.7.7 but it is certainly still here for me in 1.7.7

**Comment by sshvetsov** [comment]
I also see it in 1.7.7, but it seems intermittent, so exact steps to reproduce are hard to formulate at the moment.

**Comment by cascheberg** [comment]
I noticed that I still sometimes see this issue as well.

**Comment by grrrrr** [comment]
so a bit more recording today and it has for the most part has displayed the problems above.   However once I did upload while the stumbling was on (usually done when off) and it recorded the date and the number of records uploaded as is the expected behavior unfortunately I could not replicate this a second time

**Comment by sshvetsov** [comment]
I think I figured out the pattern:
1. stop and kill MozStumbler by removing it from the recent/running apps
2. open MozStumbler
    \* it will start stumbling on start (switch moves to ON)
    \* the metrics drawer shows sent observations
3. turn stumbling OFF and press back button to (soft) exit the app
4. re-open the MozStumbler from the recent/running apps
    \* the metrics drawer is reset

![screenshot_2015-03-17-23-45-45](https://cloud.githubusercontent.com/assets/2501176/6692710/e8124958-cd00-11e4-8d21-d5442d8c04f5.jpeg)
![screenshot_2015-03-17-23-45-50](https://cloud.githubusercontent.com/assets/2501176/6692711/e8141ba2-cd00-11e4-9b88-6dc0caef0700.jpeg)
![screenshot_2015-03-17-23-48-43](https://cloud.githubusercontent.com/assets/2501176/6692712/e817114a-cd00-11e4-83b0-4099e9286dc2.jpeg)

**Comment by crankycoder** [comment]
Thanks!  I've reproduced the bug following those exact steps.

**Comment by hbogner** [comment]
This issue is continued issue i reported some time ago : https://github.com/mozilla/MozStumbler/issues/1536
