### ISSUE TITLE
Still getting seemingly geoip, both cell-only and cell+wi-fi on 1.7.7

### ISSUE THREAD

**Issue by lua86** [mozilla/MozStumbler#1569]
![screenshot_2015-03-15-20-58-27](https://cloud.githubusercontent.com/assets/6490233/6657821/7b21b19e-cb57-11e4-9be0-b9b083ed429d.png)
This is a little village which has cell service gaps.
I apparently am the only one stumbling here.
Wiko BLOOM(dual-sim) with Android KitKat.
Do I need to provide any more info? I think this is a duplicate bug, though I cannot find the 'original'
EDIT: New screenshot. 
![screenshot_2015-03-15-21-17-18](https://cloud.githubusercontent.com/assets/6490233/6657886/d7b4f0fa-cb58-11e4-8e4b-975dc95ed597.png)

**Comment by crankycoder** [comment]
This looks like a bug in ichnaea as I'm getting pretty ok cell-only fixes (~1km accuracy).  @lua86 can you file a bug in Ichanea?  I'm closing this on the client side as there is nothing that the stumbler can do about this.

**Comment by sshvetsov** [comment]
@lua86, please reference this issue # in the ichnaea ticket once you create it, so others with the same issue can follow the back link.

**Comment by lua86** [comment]
@sshvetsov I don't even know how to do that referencing.

**Comment by crankycoder** [comment]
@lua86 you should be able to just drop a hyperlink to this bug in the other ticket.

**Comment by garvankeeley** [comment]
I filed in Ichnaea.

**Comment by lua86** [comment]
I did more city testing. Tried disabling the dead SIM, which is the first one, and the wi-fi. Result: no cells are being seen and no reports are being gathered. So now I think it is a cell scanner bug.
