### ISSUE TITLE
GPSScanner has locale dependant code 

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1583]
GPSScanner checks for fused locations by looking for the substring 'gps' within the provider name.

This should be changed to something that is not locale specific.  https://github.com/mozilla/MozStumbler/blob/a1066db7047b138cc8fbfd6e8fbfeb0de8ae70fc/libraries/stumbler/src/main/java/org/mozilla/mozstumbler/service/stumblerthread/scanners/GPSScanner.java#L168

``` java
String provider = location.getProvider();
if (!provider.toLowerCase().contains("gps")) {
  sendToLogActivity(logMsg + "Discard fused/network location. Provider ["+provider+"]");
  // only interested in GPS locations
  return;
}
```

**Comment by cascheberg** [comment]
I think the only existing location provider names in Android are `LocationManager.GPS_PROVIDER` ("gps") and `LocationManager.NETWORK_PROVIDER` ("network"). I ran the Stumbler in passive mode (see my PR) to try to confirm that. Do you think there are/could be any exceptions?

**Comment by crankycoder** [comment]
There shouldn't be any exceptions to this, but we really shouldn't be using the string literal "gps".  Just grab the LocationManager constants.
