### ISSUE TITLE
1.7.8 force closes immediately

### ISSUE THREAD

**Issue by VolMi** [mozilla/MozStumbler#1593]
I can't launch the new release. Log:

http://pastebin.com/MbFJb9AV

**Comment by stripTM** [comment]
Idem.
My info:
https://groups.google.com/forum/#!topic/mozilla.dev.geolocation/NOel77QSGZY

**Comment by garvankeeley** [comment]
1.7.9 is up and working, and we should be able to avoid this in future with #1594
