### ISSUE TITLE
proguard is a piece of garbage

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1594]
We hit a crasher with v1.7.8 and Proguard related to enums.

The Wordpress folks saw the same bug over here:
https://github.com/wordpress-mobile/WordPress-Android/issues/854

Proguard performs some optimisations which are incorrect. It's difficult to predict when things will break as the documentation is poor and vague.

We've decided to remove proguard entirely as the byte savings is negligible.  A Proguard optimised version of Stumbler v1.7.8 vs an unoptimised release build is 1.3MB vs 2.1MB.

**Comment by garvankeeley** [comment]
Lets toss it to preserve our sanity.

**Comment by crankycoder** [comment]
Proguard was removed as two commits.
- afaa03d74 removed optimisation of enums to address the crash.
- 3d05e64ff We then decided to just turn proguard off entirely as it provides no advantage in
