### ISSUE TITLE
The accuracy circle isn't updated by events/intents (map)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#1622]
The accuracy circle around your position on the map isn't updated by changes. It's only updated if the map is refreshed (by moving around the map with your finger)

**Comment by garvankeeley** [comment]
Interesting, we need to trigger a map.invalidate() when this info changes.

**Comment by Djfe** [comment]
Wouldn't it be easier to update that circle every time mozstumbler gets a new GPS fix?
Or if the gps doesn't get a position then everytime the app gets a new network position.
