### ISSUE TITLE
App crashes when opening Settings

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#164]
On my Samsung Galaxy S (the really old one, Android 2.3.5), version 0.7.2 crashes when I try to open "Settings". The screen goes black and after a moment the "Force close" dialog comes up.

One time the entire phone locked up.

**Comment by denevell** [comment]
Hmm. I'll move to the deprecated version of settings. Android normally complains if you do.

Will you be able to pull and build from my branch later? Otherwise I'll just do a pull request.

**Comment by denevell** [comment]
I've tested it myself on an older phone. Confirmed the problem.

We're now using an older version of the preferences activity.

**Comment by ghost** [comment]
I've never built this project (or used gradle) before and may not find the time to try it this week. If the fix is mostly harmless, it might be faster to send the pull request.

**Comment by denevell** [comment]
I've done it myself now. Tested the fix.

It is indeed a problem on older phones.

Thanks for the report!

**Comment by cpeterso** [comment]
Fixed by PR #165.
