### ISSUE TITLE
Force SSLv3 to go away

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1645]
Android < 4.4 has a bug that tries to use SSLv3 when falling back from TLSv1.

There's a code snippet here that should force that problem to go away

http://stackoverflow.com/questions/26649389/how-to-disable-sslv3-in-android-for-httpsurlconnection/29946540#29946540

**Comment by crankycoder** [comment]
We should prioritize this bug as we seem to be getting them quite frequently now.

**Comment by hannosch** [comment]
As a reference, we are using the latest AWS ELB SSL policy on the service end, the supported protocols and ciphers are listed at http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-security-policy-table.html

But we have stopped supporting SSLv3 sometime last year. Do you actually see acra reports for failed SSL connections? If so, that must be proxies / captive portals getting in the way. I wonder if we are really forcing certificate validation checks, to make sure the service we are communicating with is indeed location.services.mozilla.com and the certificate is valid for that.

**Comment by crankycoder** [comment]
Alrighty, the Fennec folks have a new DEFAULT_CIPHER_SUITE defined in their TLSSocketFactory in this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1061273 

We need to get that ported into the stumbler and then back ported into the fork that is in Fennec.  We don't use the TLSSocketFactory so we'll have to duplicate the DEFAULT_CIPHER_SUITE.

**Comment by Djfe** [comment]
What is the current status here?

**Comment by crankycoder** [comment]
Working on it in a branch right now.  This is ending up to be trickier than expected.

**Comment by crankycoder** [comment]
Verified fixed on Android 2.3.6 

I/Stumbler_HttpUtil(  927): Negotiated HTTPS ciphers: TLS_RSA_WITH_AES_128_CBC_SHA
