### ISSUE TITLE
Mozilla Stumbler for Android not collecting any data

### ISSUE THREAD

**Issue by mahmud2011** [mozilla/MozStumbler#1656]
I am using Huwaei ascend p6-u06. I installed Mozilla Stumbler for Android but it does not collect any data. I checked GPS and Wifi. Everything is working fine.

**Comment by crankycoder** [comment]
What ROM are you using?  Do you have privacy guards running?  

Did all the icons at the top of the screen change from red to black?

**Comment by mahmud2011** [comment]
1. Jelly Bean 4.2.2.
2. No.
3. The leftmost icon, the satellite one, it stays red. But all other icons change to black.

**Comment by garvankeeley** [comment]
Red sat icon-> you need more GPS sats to get a fix, 3 or 4 at least. Are you indoors? Seems odd that you wouldn't get a GPS fix outdoors, although if you are surrounded by tall buildings it can happen.

**Comment by gpoo** [comment]
@mmhyamin IIUC, the left icon tells you how many satellites are being used and how many are visible.

From 3 to 4 it changes to black, although it does not mean you are getting a position. It might depend on other factors, like if you are moving it will need more satellites.to triangulate your coordinates.

I think it also depends on the location, if there are tall buildings nearby.(as @garvankeeley says), the GPS in your phone, etc.  For example, sometimes my Nexus 5 sees 23 satellites, and in the same position my Nexus 1 only sees 8. Similarly, in the west coast -open space- in Canada my phones can see more satellites than they did when I was recently in Italy (I could rarely get more than 10).

In addition, it is possible you might have an application blocking the location for MozStumbler, as an user could do with Cyanomodgen.

**Comment by mahmud2011** [comment]
I use endomondo when I go for a ride. It works fine. I started Mozilla Stumbler in my Xiaomi Redmi 1S and Huwaei ascend p6-u06 at the same time. But the stumbler is working fine in Xiaomi not in Huwaei. I'll upload the screenshot shortly.
