### ISSUE TITLE
When the user changes his/her username , Stumbler application generates his points with new user name instead of adding the existing points to the username using the email id.

### ISSUE THREAD

**Issue by anupkumarmishra** [mozilla/MozStumbler#1677]

**Comment by hannosch** [comment]
Yes, the email is not actually what uniquely identifies a user, but the nickname is. You can change the email address, keep the nickname and still contribute as the same "user account".

But you currently can't change the nickname, without effectively becoming a new user with zero points.

This doesn't make it lot of sense, except that it historically has grown this way. We are working on fixing this by switching over to a real user accounts system based on Firefox accounts. That work is still going on.

**Comment by anupkumarmishra** [comment]
We, the Mozilla community from North India are running a Stumbling campaign and to check the users who are contributing as part of the campaign , we asked them to provide their name as Mozpacers_Username , some of them could not understand that at the first time and they changed their username after earning 3k points . The current way we are handling it is not correct and we should be linking with email id , email id doesn't changes , user name is more volatile . ANyhow, is it possible for user to get their data from old user name ?

**Comment by hannosch** [comment]
@anupkumarmishra I think for past community events, people used a spreadsheet where the nicknames of the contributing users were written down. If you'd do that, you could allow a person to write down two nicknames for their own person, and sum those points up yourself.

The new leaderboard service should allow for time-limited and geographically-limited leaderboards, so hopefully once that is working, it'll be easier to run these events. We are hoping to get this up sometime later this quarter, at which point the existing leaderboard will be retired.

**Comment by crankycoder** [comment]
@anupkumarmishra  - I'm going to close this bug and move it over to the new leaderboard-server code.

You should be able to find it over at: https://github.com/JaredKerim-Mozilla/leaderboard-server/issues/4
