### ISSUE TITLE
Change "GPS Satellites Visible" count to a descriptive string

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#168]
such as "GPS Status: Searching" then maybe "GPS Status: latitude,longitude". This UI change should reduce user confusion about whether their phone has a GPS fix and what is the "correct" number of satellites.

**Comment by merike** [comment]
Please keep the count too or at least differentiate between no satellites and a few.. It it very useful to know if it is 0 satellites (terrible weather or otherwise poor conditions, might want to use battery for other things than stumbling) and 3-4 satellites visible (likely to get a gps fix soon).

**Comment by cpeterso** [comment]
Fixed by PR #126. :)
