### ISSUE TITLE
Sailfish app

### ISSUE THREAD

**Issue by Mikaela** [mozilla/MozStumbler#1683]
I learned about https://location.services.mozilla.com/ today and the [apps](https://location.services.mozilla.com/apps) page only lists this project and [community projects](https://wiki.mozilla.org/CloudServices/Location/Software).

There is no Sailfish app, so Sailfish users are closed out unless they use the Android version which again requires aliendalvik/Jolla phone and aliendalvik drains battery.
- [Jolla Harbour (submitting apps to Jolla Store)](https://harbour.jolla.com/)
- [Sailfish OS homepage](https://sailfishos.org/)
  - [Developing apps](https://sailfishos.org/develop/)

**Comment by crankycoder** [comment]
We don't currently have resources internally to apply engineering effort to a Sailfish application.  

I don't foresee anytime in the near or intermediate future when that will change - so I'm going to just close this bug for now.  

@Mikaela if you'd like assistance with building a Sailfish MLS client - we'd be happy to help guide you.  

We're available on irc.mozilla.org in the #geo channel and there is the dev-geo mailing list over here https://lists.mozilla.org/listinfo/dev-geolocation where we can provide technical assistance.

**Comment by Mikaela** [comment]
> @Mikaela if you'd like assistance with building a Sailfish MLS client - we'd be happy to help guide you. 

I would if I had any coding skills :(.

> We're available on irc.mozilla.org in the #geo channel 

I am idlling there as Mikaela.
