### ISSUE TITLE
Allow user to access the data he has uploaded

### ISSUE THREAD

**Issue by jidanni** [mozilla/MozStumbler#1692]
After uploading with Tower Collector, the user can always retrieve his data from the opencellid.org database. MozStumbler should offer or document a means for a user to access the data he has uploaded too. E.g., I want to retrieve a copy of all the points I uploaded last week.

**Comment by crankycoder** [comment]
You can currently download cell data from here:

https://location.services.mozilla.com/downloads

Releasing a raw dump of all wifi data has some privacy issues around it - more details can be found on the downloads page.  If you just want your own wifi data, you should just enable logging output in the developer options.
