### ISSUE TITLE
Multiple users with same nick show in leaderboard with combined reports

### ISSUE THREAD

**Issue by CuriousLearner** [mozilla/MozStumbler#1697]
If anyhow two or more person have same nick in the app, their reports are combined and updated in the leader board with the common nick.
A proper authentication system is needed for this. May be persona or a similar system would be better.

**Comment by cascheberg** [comment]
This will be fixed with the release of #1325, but I do not know any details about the status.

**Comment by hannosch** [comment]
Work is happening on the FxA integration. The new leaderboard system is being worked on over at https://github.com/JaredKerim-Mozilla/leaderboard-server and we are aiming to switch over to it sometime this quarter.

**Comment by crankycoder** [comment]
The new leaderboard is being launched now, so this isn't a problem anymore.  Users are now unique based on their Firefox Accounts login.
