### ISSUE TITLE
Reports not being uploaded

### ISSUE THREAD

**Issue by rishabhbanga** [mozilla/MozStumbler#1700]
Automatic upload isn't happening, and whenever I try to manually upload the reports, the button changes to refresh button and back to upload within a second.

NOTE: This happened suddenly. It was working fine till Sunday evening.

**Comment by Djfe** [comment]
Is it still happening?
If so: are you sure you have a working internet connection when it happens?

**Comment by crankycoder** [comment]
The 1.7.13 release had a bunch of datastorage manager changes that were
incomplete.   I backed out all of those for 1.7.14.

The v1.7.14 release is just 1.7.12+TLS fixes so it _should_ be ok now.

**Comment by crankycoder** [comment]
Nothing actionable here.
