### ISSUE TITLE
Integrate Stumbler with new Leaderboard Dev Instance

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/MozStumbler#1703]
There is a new dev instance for the leaderboard available here:

http://leaderboard-dev.jaredkerim.com/

It implements the leaderboard whose API spec can be found here:

https://github.com/JaredKerim-Mozilla/leaderboard-server

The FXA client_id for this instance is:

86cd25bed2c63936

You should be able to point the stumbler to that dev URL with that FXA client_id and walk through a successful full login flow and then submit data to it.

**Comment by garvankeeley** [comment]
So the FXA client_id gets set as a header on our submission to ichnaea? I thought ichnaea then submitted this data to the leaderboard-server.

**Comment by garvankeeley** [comment]
I just started removing the leaderboard file storage. I just need to know if I continue. I would like to pull it and cleanup the code.

**Comment by crankycoder** [comment]
Hmm.. The FxA login seems broken here. 

I've set the client ID to 86cd25bed2c63936 and the callback URL is set to http://leaderboard-dev.jaredkerim.com/ but I'm getting a 500 error code.

Any ideas?

It's pretty hairy for me to try and dig out URLs that the embedded Android Webview is hitting in the Android Studio debugger - I really need to be able to just SSH into the leaderboard server to see what's happening.

**Comment by hannosch** [comment]
This was all done in the meantime.
