### ISSUE TITLE
Move application data to dedicated location

### ISSUE THREAD

**Issue by agilob** [mozilla/MozStumbler#1707]
What do you think about moving location of the folder with data from default user-location to `./Android/data/`? Currently the folder is easily accessible by users, can be deleted/modified by accident by user or cleaning applications.

Android supports 'private' data folders by design, current implementation of MozStumbler doesn't follow those 'guidelines' (not really guidelines, or I can't find them, but it's a good practice). Personally I find it annoying when apps mess with my folders, when they have their dedicated location to store data. Screenshots and link will tell you more.

> [All apps (root or not) have a default data directory, which is /data/data/<package_name>. By default, the apps databases, settings, and all other data go here. If an app expects huge amounts of data to be stored, or for other reasons wants to "be nice to internal storage", there's a corresponding directory on the SDCard (Android/data/<package_name>)](http://android.stackexchange.com/questions/47924/where-android-apps-store-data/47951#47951)
> [more info](http://android.stackexchange.com/questions/46926/android-folder-hierarchy/46934#46934)

Example usage:

```
Log.i(TAG, getExternalFilesDir(STORAGE_SERVICE).getAbsolutePath());
Log.i(TAG, getExternalFilesDir(null).getAbsolutePath());
Log.i(TAG, getDataPath());

/storage/emulated/0/Android/data/app.id/files/storage
/storage/emulated/0/Android/data/app.id/files
/storage/emulated/0/Android/data/app.id/files/download/
```

I make the same issue for every project that stores data in user location instead in dedicated location. If you want to quickly copy some code I wrote to solve this issue for another project feel free to take it from a commit that fixed it for AIMSICD: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/f3e8161539dd6b98c0d4ea879a103632ed445a02

**Comment by crankycoder** [comment]
The client code stores data using the ContextWrapper::getFilesDir() method call as a root path where map tiles, preferences, JSON logs other bits of data go.

Using getExternalFilesDir() will break older devices which have external SDCARD slots which are empty.

**Comment by agilob** [comment]
Why not make it API dependent like notification manager? My file manager crashes when I select MozStumbler by accident due to huge number of files in there.

**Comment by crankycoder** [comment]
Making it API dependant and changing the location of the file storage would have no impact on your file manager crashing.
