### ISSUE TITLE
Target Android API 23

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#1712]
Please target Android API 23

**Comment by crankycoder** [comment]
Our current build process breaks horribly with SDK 23.  I'm not sure yet if it's the jakewharton android sdk deployer tools, or the Android-Gradle plugin or what.  It's a mess.

Are you asking for us to explicitly target SDK so that we an compile or to add features that utilize SDK 23?

**Comment by ghost** [comment]
Because Android M is coming and there are benefits to targeting like App Data Backup and also Permissions have changed in Android M.

And yes I can't build a new apk at all it seems like your gradle is messed up plus your using a API 21 library but targeting API 19.

**Comment by crankycoder** [comment]
SDK versions don't work that way.

The application is compiled with the `compileSdkVersion` which specifies which version of the SDK the code should be compiled with.

targetSdk specifies : 

> This attribute informs the system that you have tested against the target version and the system should not enable any compatibility behaviors to maintain your app's forward-compatibility with the target version. The application is still able to run on older versions (down to minSdkVersion). 

http://developer.android.com/guide/topics/manifest/uses-sdk-element.html

The build should work from command line as the Travis CI system shows.

FWIW - I'm trying to upgrade the build to android-gradle plugin 1.3.1 today.

**Comment by crankycoder** [comment]
I've upgraded the build to play nice with Android SDK 23 in #1713 and it seems to work in Android Studio 1.3.2 for me.

I'm closing this bug as 'targetting' Android M doesn't mean anything.  If there are discrete features that are useful, please file separate bugs.
