### ISSUE TITLE
Report an atomicity issue

### ISSUE THREAD

**Issue by baigd** [mozilla/MozStumbler#1718]
Hi, Developers of MozStumbler, 

I am writing to report an atomicity issue. I would very appreciate if you could check below for details and confirm with us whether it is a real problem. 

File: mozilla/MozStumbler/android/src/main/java/org/mozilla/osmdroid/tileprovider/util/CloudmadeUtil.java
Location: Line 128
Description:
Data race may manifest if thread_1 happen to set mToken.length==0 in 128, which assign "mToken" a new memory address, then thread_2 and thread_3 synch on the new "mToken" address, which is different from what thread_1 is locked on. They may simultaneously modify mToken.

**Comment by crankycoder** [comment]
It's possible that the CloudMade code is broken.   That code branch is actually a form of osmdroid.  We've deleted all the CloudMade related code (CloudMadeTileSource,  HttpClientFactory, etc) on Aug 28th.

https://github.com/mozilla/MozStumbler/commit/050eeda0ea3ed5eaa27eacb1ad692034e5a5db58

None of this is obvious though as we've been swamped and haven't cut a new release in far too long.  I really need to get on that.
