### ISSUE TITLE
Add runtime warning when GoogleAPIKey is unset that map view will be blank

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#172]
As per my idea in issue #167, we should add a runtime (and build time?) warning when `GoogleAPIKey` is unset or is `FAKE_GOOGLE_API_KEY` so people will know why the map view is blank. logcat and toast messages would be good.

**Comment by ghost** [comment]
Maybe just disable the button if key is fake?

**Comment by cpeterso** [comment]
Disabling the button is a good idea, though some users will probably wonder why the button is disabled. :)

In another issue, we might consider disabling the button if the Google Play Services library is not installed. Offhand, I'm not sure how we would check that.

**Comment by ghost** [comment]
@cpeterso, ok, all done.

**Comment by cpeterso** [comment]
Fixed by PR #174.
