### ISSUE TITLE
UnknownHostException

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#1721]
Seeing this Stumbler_HttpUtil: post error:java.net.UnknownHostException: Unable to resolve host "fill me in please": No address associated with hostname

In 1.7.13

**Comment by crankycoder** [comment]
I've removed 1.7.13 as it introduced a bunch of bugs due to my incorrect cherry-pick of patches.

v1.7.14 is a simple v1.7.12 build with some TLS security patches applied.

**Comment by Clonewayx** [comment]
Same error from me. With 1.7.13 (last version on F-droid). Android 4.1.2 Sony ST26i
