### ISSUE TITLE
MozStumbler tracking data but showing no reports ready 

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#1722]
MozStumbler in 1.7.13 is finding new locations and wifi but when I look at the side pane it shows no reports ready to upload and the most recent upload ways days ago.

Nothing useful in logs as to why its not generating reports to send

**Comment by ghost** [comment]
Actually I take that back this may be caused by #1721 it looks like when its hitting that exception it doesn't have any place to send them so is discarding them?

**Comment by crankycoder** [comment]
I've removed 1.7.13 as it was far too buggy. Sorry!
