### ISSUE TITLE
 The MLS android app abruptly stops generating reports even though the GPS is set.

### ISSUE THREAD

**Issue by amaneight** [mozilla/MozStumbler#1724]
No MLS reports were generated along an 8 miles stretch even though the GPS was working perfectly fine.

Steps to reproduce it : 
1. Switch on the Mozilla Stumbler app and GPS on android phone.
2. Stumble around for over an hour, ensure that you are constantly moving.
3. Also Stumble in those areas where you are unable to find cellular network on phone.

At some point of time the app stops generating reports even though the GPS is set.

Actual result :
No reports were generated even though the GPS was working perfectly fine.

Expected result :
MLS reports should have been generated.

Sometimes because of the app stops working too and the user is unaware of it.

I also suggest adding one more map legend which indicates that no reports are being generated for a given stretch.

Screenshot : https://bugzilla.mozilla.org/attachment.cgi?id=8627132&action=edit

**Comment by crankycoder** [comment]
There's a number of reasons the stumbler may stop related to Android power management, Stumbler power management, buggy GPS, accelerometers and motion sensors, lack of wireless antennas, and bugs specific to some android+hardware pairs.  

@amaneight Can you provide the version of Stumbler you were using as well as the device and Android version you are running?

It looks like the gap you have is related to the motion sensor thinking you're not moving or perhaps you've lost GPS signal during that stretch.

I'm not sure what it means to generate a legend when no reports are being generated.  A report point would require a GPS lat/lon and some wifi+cell tower signals.  If we're missing GPS, we can't plot a point.  I guess we could plot points where we have lat/lon data but no wireless data.  That would at least mark out areas explicitly where stumblers have gone but have been unsuccessful.

**Comment by crankycoder** [comment]
Nothing actionable here.
