### ISSUE TITLE
Filter for own mobile hotspot

### ISSUE THREAD

**Issue by TLBM** [mozilla/MozStumbler#1733]
Hi!

Mobile personal hotspots aren't really helpful for building a geolocation-map as they move with the user. 
So it would be really nice if one could filter out his/her own ones to make the map more accurate and keep the "data pollution" down.
Or are there algorithms serverside to detect this?

**Comment by hannosch** [comment]
On the service end we detect moving networks and filter them out. "Moving" means any network that is seen in different enough places over time, and which keeps being seen in different places. The detection isn't particularly sophisticated, but seems to be working well enough.

I don't think a device would see its own hotspot in the list of available networks to connect to. So a device shouldn't continuously capture itself.

**Comment by breversa** [comment]
But what about my wi-fi only tablet using my smartphone's hotspot, when I carry both around when in the car, bus or train ?

(My tablet has GPS + GLONASS, while my phone only has GPS)

**Comment by lua86** [comment]
Filtered sever-side because moving spot
