### ISSUE TITLE
Incorrect MLS location 

### ISSUE THREAD

**Issue by RaymondFanch** [mozilla/MozStumbler#1737]
I am not sure if anything (either cell ID database or algorithm) goes wrong but I guess this is not simply an accuracy problem. Please have a look at the attached snapshots which shows the incorrect MLS location reported for either Cell only or WiFi + Cell report (as marked in a yellow oval). Actually, it reports a location 200Km away. Would it be possible to check this? Thanks.

![screenshot_2015-12-23-12-02-57-marked](https://cloud.githubusercontent.com/assets/16408756/11971803/d26c481a-a97d-11e5-8f92-9c742abf6358.png)

![screenshot_2015-12-23-12-02-15](https://cloud.githubusercontent.com/assets/16408756/11971811/ef4f05f8-a97d-11e5-8200-fd16e3c61ad5.png)

![screenshot_2015-12-23-13-55-25](https://cloud.githubusercontent.com/assets/16408756/11971827/082a4d4e-a97e-11e5-9d36-1cc846ad1434.png)

**Comment by lua86** [comment]
Are you using a double sim device?
Also, please go into dev settings and enable logs, they will be handy for troubleshooting.

**Comment by RaymondFanch** [comment]
Nope. This is Samsung Galaxy S6 (single SIM device). The log is attached as below. It is not exactly the same as the attached snapshots but is very similar. Let me know if you moe information.

[MLS_Log.txt](https://github.com/mozilla/MozStumbler/files/71474/MLS_Log.txt)

**Comment by crankycoder** [comment]
I'm not entirely sure why this would happen.  It looks like those areas have high density wifi routers.

The only thing I can think of is that this is a case where you may have picked up new wifi routers that were never seen before, but your device also didn't pick up any previously known wifi routers.  This would cause MLS to return a cell based location.

This seems pretty unlikely though.

**Comment by crankycoder** [comment]
We've dropped IP based fallbacks to prevent this from happening.  

https://github.com/mozilla/MozStumbler/issues/1751

Technically - this isn't a 'problem' so much as it's confusing to people as IP geolookups are very imprecise.
