### ISSUE TITLE
App reports the same location for 30+ km.

### ISSUE THREAD

**Issue by divlv** [mozilla/MozStumbler#1749]
Hi, All!
I've started collecting data with Mozilla Stumbler about a week ago, but, all the time I've got the similar picture:

![screenshot](http://screenspic.appspot.com/pic?gid=agxzfnNjcmVlbnNwaWNyFQsSDFVwbG9hZGVkRmlsZRjJ26EEDA)

It's definitely wrong, to have this only location during all my 30+ kilometers trip.
What it could be?
And, **how fast my collected data will get to work?** (will be used for location calculation)

P.S.
I've got single SIM, Nexus 5, Android 6 device.

**Comment by crankycoder** [comment]
These are IP based fallback lookups.  We've disabled it as it's confusing to users.  https://github.com/mozilla/MozStumbler/issues/1751
