### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by jeremy447** [mozilla/MozStumbler#1773]
The v. 1.8.3 F-Droid build failed :

https://f-droid.org/wiki/page/org.mozilla.mozstumbler/lastbuild_1080300

Is it possible to fix it please ?

Thanks !

**Comment by crankycoder** [comment]
I've got a branch to fix this, but it breaks travis.  Still resolving conflicts.

**Comment by jeremy447** [comment]
Ok thank you.

**Comment by crankycoder** [comment]
@paviluf - sorry - I forgot to include a link to the branch so you can track progress.  https://github.com/crankycoder/MozStumbler/pull/2

I'm closing this ticket for now as release to the F-Droid app store is a major bug for us and we're actively working on it.
