### ISSUE TITLE
Need API17 guard around Location.getElapsedRealtimeNanos

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1792]
getElapsedRealtimeNanos() is only available on API17 and up.  Stumbler supports lower API levels.

**Comment by kyl416** [comment]
Can you push out a new release build with this fix? It fixes the crashes I get on my Galaxy S II which is on API 16 (4.1.2).

**Comment by crankycoder** [comment]
@kyl416 - sorry - I just pushed a release out yesterday.
