### ISSUE TITLE
Cant see my name in Leaderboard :(

### ISSUE THREAD

**Issue by proton555** [mozilla/MozStumbler#1796]
For my country there is relatively less Stumbler data (esp of my region). There are only 20 users for my country at link https://location-leaderboard.services.mozilla.com/
So i want to help out the project. 
I installed stumbler and sent some 20 reports since yesterday, but my nick (which i entered in stumbler app) is not showing up there

Let me know what can be the issue like so that i start stumbling more
Thanks

CC @crankycoder @garvankeeley

**Comment by crankycoder** [comment]
If you're using a nick - it sounds like you're using an older build of the stumbler.

Are you logged into Firefox Accounts?  If not, can you give the github 1.8.6 build a try?

**Comment by proton555** [comment]
NO i see nick entering only. No Firefox accounts. 
Can we get apk of it from github? or i have to compile (thats a long process of downloading software etc)
if yes, can i have the link?
Thanks

@crankycoder

**Comment by crankycoder** [comment]
Try this: https://github.com/mozilla/MozStumbler/releases/tag/v1.8.6
