### ISSUE TITLE
Allow user to enter a nickname

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#18]
Client should allow a user to enter a nickname. Client should only include the user token in submissions iff nickname is defined. This makes the leaderboard tracking opt-in because the user must manually enter a nickname to be listed on the leaderboard.

**Comment by hannosch** [comment]
Corresponding server-side issue is: https://github.com/mozilla/ichnaea/issues/9

**Comment by hannosch** [comment]
The nickname should be at least 3 characters long and at most 128 - at least that's the validation I currently put on the server side. This struck me as a reasonable length range.
