### ISSUE TITLE
MapQuest does not provide the OpenStreetMap-Tiles anylonger

### ISSUE THREAD

**Issue by Funatiker** [mozilla/MozStumbler#1800]
MapQuest discontinued their free/anonymous access to their OpenStreetMap-tiles. This means that Mozilla Stumbler will always show a grey grid rather than the OpenStreetMap.

The only free plan by MapQuest only includes 15,000 requests per month. Since this is not enough for Mozilla Stumbler, a new (maybe Mozilla-hosted?) tiles provider is required.

As @lua86 mentioned: It is also possible not to use tiles at all and render the raw map data live.

See also:
http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

**Comment by razor7x** [comment]
Confirm, the map doesn't show anymore. Also it has eaten ~750mb of my 3g traffic in a half an hour while trying to load the tiles :/

**Comment by lua86** [comment]
What's the problem with vector map data? Can get from openstreetmap, right?

**Comment by Funatiker** [comment]
@lua86 Exactly. OpenStreetMap could provide raw/vector map data that would be rendered live by the phone. That's the way how OsmAnd works. However, this consume quite a bit of CPU time which might be okay if you want an exact map telling you where you have to go. It's probably not the kind of solution one would like to have to get a quick overview where Mozilla Stumbler has collected data.

Yet, it is a possible solution.

**Comment by garvankeeley** [comment]
This appears to be an unlimited use basemap: https://carto.com/

**Comment by breversa** [comment]
Satstat had the same issue and found a solution : https://github.com/mvglasow/satstat/issues/86

**Comment by crankycoder** [comment]
Just a note that this doesn't affect the production releases of the stumbler, only the dev builds which use the free unlicensed maps.

**Comment by Funatiker** [comment]
> Just a note that this doesn't affect the production releases

It does affect the version on f-droid.

**Comment by DocSniper** [comment]
I'm using the latest F-Droid version (1.8.6 since 2016-06-30) and I have this issue too, gray background and no map is shown.

**Comment by marco-c** [comment]
GNOME Maps switched to Mapbox (http://jonasdn.blogspot.com/2016/07/maps-has-tiles-again.html).

**Comment by breversa** [comment]
Any plan to sort this out and bring maps back ?

**Comment by Ryuno-Ki** [comment]
Any updates? Installed the app from F-Droid today.

**Comment by rugk** [comment]
Please fix this. MapBox might be a good choice…
Currently all FDroid users are affected.

**Comment by Marwe** [comment]
Mapbox has support for open data projects. Can you check with their support, if this is a use case which they support with their tiling-service? It might not apply, since the collected data itself is not openly available.

**Comment by hannosch** [comment]
@garvankeeley If you want to have a look at this, it would be appreciated.

We currently have two problems:
1. The MAPQUESTOSM tiles provider used in dev and f-droid is no longer available.
2. The custom styled mapbox tiles we use in Play Store releases are years old (they are a dump of styled png files and not updated based on changes to the underlying OSM data).

I think we should just use the same Mapbox tiles provider for all builds. The amount of traffic here is low, so we can re-use the same Mapbox account we use for the MLS website and mozilla.org.

The URL pattern for this would be:
```
https://a.tiles.mapbox.com/v4/mapbox.streets/2/1/1.png?access_token=pk.eyJ1IjoibW96aWxsYS13ZWJwcm9kIiwiYSI6ImNqMml4MXNhaTAwMjgzM28yYXRqbjlmZmkifQ.OfL6NY7noQth9mbbN_tDbA
```

The access token is a new one, so we can monitor and rotate it, in case someone abuses it for a different app or website.

**Comment by garvankeeley** [comment]
agreed on your approach using mapbox tile provider, i'll try get this in if no one beats me to it

**Comment by ernesst** [comment]
You can see with the developer of Unav, a Gps navigator for ubuntu phone based on tiles. http://unav.me/
The app offers to select different tile providers after MapQuest discontinued their tile.
I think Gnome map switched also to something else.

**Comment by rugk** [comment]
They used MapBox.

**Comment by ernesst** [comment]
What about mapzen, providing free tile service up to 50 K/months requests, would it be enough regarding the use of this app ?
