### ISSUE TITLE
Q: How to reduce the accuracy?

### ISSUE THREAD

**Issue by rodmoreno** [mozilla/MozStumbler#181]
For five consecutive days I scanned my neighborhood, I've done every street possible (up from both sides of the sidewalk).

I have used Location Services Mozilla, place me pretty well, but ... They have an accuracy of 500 meters and when I use Google Location Services I have only 31 meters of accuracy. What should I do to reduce the accuracy?

**Comment by cpeterso** [comment]
hi, @rodmoreno! Thanks for your help!

@hannosch: How does the Mozilla Location Service estimate the accuracy radius?

**Comment by hannosch** [comment]
@rodmoreno Hi, we are currently at a very early stage and do only the most minimal analysis of the incoming data. At this point we are only averaging all reported locations for a cell tower / WiFi AP and report that as the location. The accuracy is currently hard-coded to 500 meters for WiFi and 35km for cell networks (https://github.com/mozilla/ichnaea/blob/master/ichnaea/service/search/views.py#L48 and L79).

We'll extend the service to take into account signal strengths readings and use better algorithms in the future. But this hasn't been high on our priority list. We are currently focusing on getting data and being able to cope with the load that creates.

**Comment by rodmoreno** [comment]
@hannosch  Ok, I understand. Then I will keep collecting as much data for my city (Mexico City), we are doing well, a week ago there was not a single data and today on the map appears a beautiful 148 on the map.

Just another quick question, I have seen on the Statistics (https://location.services.mozilla.com/stats) unique cell that have not changed in several days ... Is this correct? Is it a mistake? Or if it has changed? I, for example yesterday I could go a lot of the city (which is huge) so that minimum should increase only slightly, but hey, I'm not alone in the world scanning...

**Comment by hannosch** [comment]
@rodmoreno I've updated the stats page today, to display a more helpful error message. We are still catching up with processing all the new data. While we do so, the `unique` stats are wrong - they haven't changed in the last week, so I disabled them. They'll probably be back sometime this week.

**Comment by rodmoreno** [comment]
@hannosch Ok, thanks! I will continue collecting data in my city and I hope to travel to more cities soon to help. I'm really excited about this great project and I hope to help as much as possible.
