### ISSUE TITLE
No longer uploading reports

### ISSUE THREAD

**Issue by JonnyTech** [mozilla/MozStumbler#1811]
A couple of days ago, the app stopped uploading reports. I have many to send but no way to do so. Backed up the reports then uninstalled and reinstalled the app. Still not even sending new reports. Any suggestions?

**Comment by JonnyTech** [comment]
I found the log section in settings. Host mqcdn.com cannot be reached. How can I copy log text to upload it here?

**Comment by hscsjk** [comment]
본인것과똑같은 기기가있읍니다  ip조작으로
본인을  수년간 괴롭히고 있읍니다

**Comment by JonnyTech** [comment]
Can anyone else confirm if https://location.services.mozilla.com/ is offline please?

**Comment by hannosch** [comment]
There's a couple internet services for uptime checking around. The site is reachable for me and https://isitup.org/location.services.mozilla.com says the same.

Regarding your logs, I don't know what mqcdn.com is, but it's certainly not something that is used by the Mozilla Stumbler app. If something weird like that shows up, I'd suspect some other application on the phone is interfering with network communications. Could be a tool that claims to improve security.

**Comment by JonnyTech** [comment]
OK, I think that I have figured things out:

- location.services.mozilla.com was being blocked by an AdAway update, it is working now, but I had to delete several thousand reports as the server rejected them as corrupt when putting the back and trying to upload them

- mqcdn.com is the mapquest tile server which had now been discontinued, looks like the build from F-Droid has not been updated to use an alternative service - any chance of someone fixing this for us non Play Store users?

**Comment by hscsjk** [comment]
본인의 스마트폰과 pc의 mac을 탈취해서  수년간 사용하며 본인을 괴롭히는 사람이 있읍니다.
본인의 기기와 똑같은 것을  만들어 -좀비 pc -좀비 스마트폰-본인의 사생활을 감시하고있읍니다
소통을하고 싶어도  할수가없네요.  스마트폰에도 파이어폭스를 설치하고 싶어도 설치하면 가로채고 
pc에도 설치할라치면 가로채고  사용자 정보도 없는 ip를 여러개 쓰면서 사람을 괴롭히고 있는 실정입니다
