### ISSUE TITLE
Leaderboard not updating

### ISSUE THREAD

**Issue by JonnyTech** [mozilla/MozStumbler#1822]
The leaderboard has not updated in a while and I suspect that my device has stopped uploading again. How can I check if my contributions are being received?

**Comment by txjockey** [comment]
Hi Johnny, I too am having the problems and its such a shame as I travel an awful lot. I dont mind doing this but it has to be supported. Developers please fix.

**Comment by JonnyTech** [comment]
You do indeed, number one in the UK :) I just discovered the solution: uninstall then reinstall the app then log back in. Looks like a unique id is generated by doing that which forms some sort of cookie that is sent with our contributions. It goes stale after a while and the server stops accepting it. Simply clearing data or logging out then back in is not enough.
