### ISSUE TITLE
We should allow retries if the MLS times out or returns an error

### ISSUE THREAD

**Issue by mcomella** [mozilla/MozStumbler#1833]
From bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1132247:

For a discussion, see https://bugzilla.mozilla.org/show_bug.cgi?id=1116217#c8

Right now, SearchEngineManager will save an empty countrycode/region on failure. We should not save anything, and allow a retry attempt.

**Comment by garvankeeley** [comment]
Are you sure this is related this repo? AFAIK, the search code is using the https://github.com/mozilla/ichnaea backend to serve up GeoIP. GeoIP data is unrelated to Mozilla Stumbler.

**Comment by mcomella** [comment]
I don't know – I pushed it back to Fennec's triage queue.
