### ISSUE TITLE
Make a new release so F-Droid works again

### ISSUE THREAD

**Issue by infinity0** [mozilla/MozStumbler#1841]
#1818 was fixed in git but not in a released tag. The latter is what F-Droid uses to build versions from. Can you push a tag, so that F-Droid can build a new release with the fix?

The version on Google Play is even older, at 1.8.5.

**Comment by sylvestre** [comment]
1.8.8 has been tagged. afaik, Mozilla doesn't manage the f-droid version. So, I will close this issue
https://github.com/mozilla/MozStumbler/releases/tag/v1.8.8

**Comment by tuxayo** [comment]
@sylvestre Thanks a lot, the only need was a tag so there could be a version number. No worries for F-Droid.

**Comment by githubetc** [comment]
The F-Droid version still cannot display map as of today (10-Mar-2019).
Who is responsible for pushing the new version into F-Droid ?
Can a non-programmer (like me) help in anyway ?

**Comment by Iey4iej3** [comment]
There is [a post](https://forum.f-droid.org/t/there-are-new-releases-of-mozilla-stumbler-call-for-new-builds/5696) in the forum.
