### ISSUE TITLE
leaderboard removed

### ISSUE THREAD

**Issue by 532910** [mozilla/MozStumbler#1849]
What was the reason to drop the leaderboard and Firefox Account 
association?

**Comment by crankycoder** [comment]
We're deprecating the leaderboard because of overall inactivity.

**Comment by tuxayo** [comment]
@crankycoder 

Thanks, I understand, if the project get very few resources, it's normal to narrow the scope.
I'm thankful that there is still minimal maintenance of MLS even after the stop of Firefox OS development.

I'm using MLS for network based location with microG on Android. And trying to make a much people as I can use it via LineageOS for microG. Thanks for your work.

Is there actually a way to donate while (at least symbolically) relate these donations to MLS?
