### ISSUE TITLE
Don't force exit if GPS isn't turned on

### ISSUE THREAD

**Issue by cskau** [mozilla/MozStumbler#189]
With 216672f it is no longer possible to open the app without turning on GPS.
This is unfortunate because it prevents the use case of opening the app, and for instance View'ing the Leaderboard, or Test'ing Mozilla Location Service; neither of which _require_ the use of GPS, as far as I can tell?

A simple fix would be to have the No button on the pop-up dialog simply close the dialog, and not the app.

**Comment by cpeterso** [comment]
@cskau: Good suggestion!

@freekzy: Can the `checkGps()` alert's `setNegativeButton()` handler just return without calling `finish()`?
