### ISSUE TITLE
Show current nickname when opening the Leaderboard

### ISSUE THREAD

**Issue by cskau** [mozilla/MozStumbler#190]
The Leaderboard is much too big to quickly look up one's current position - especially on a small mobile device.

If the Leaderboard was annotated with for instance tag IDs for each nickname the View Leaderboard button could be made to point to a user specific fragment, like:
https://location.services.mozilla.com/leaders#nickname-CaveJohnson

**Comment by rodmoreno** [comment]
I think this applies more to the project Ichnaea (https://github.com/mozilla/ichnaea/) ... cc: @hannosch

**Comment by cskau** [comment]
Well, I think it would require a combined effort on both projects to be useful.

I was unaware that the server project was also on GitHub, so my apologies for only opening an issue here.
An issue should probably be opened over there too.

**Comment by cpeterso** [comment]
@cskau: no worries. Like you said, this feature would need code changes on the client and server. :)

**Comment by Djfe** [comment]
Can be closed now since #561 was closed.

**Comment by Djfe** [comment]
@garvankeeley you can close this ;)
