### ISSUE TITLE
Show the number of cell towers scanned

### ISSUE THREAD

**Issue by marco-c** [mozilla/MozStumbler#194]
At the moment only the AP number is shown.

**Comment by cpeterso** [comment]
We used to display the number of cell towers scanned, but users found it confusing. But it would be straightforward to bring it back.

**Comment by marco-c** [comment]
It'd be interesting for me, maybe you could add an optional indicator that could be enabled in the settings.

**Comment by CupIvan** [comment]
yes, it will be very usefull to display all collected data: total and per interval (for example 5-10 minutes)

**Comment by Djfe** [comment]
can be closed, right? :)

**Comment by cpeterso** [comment]
Yep! Fixed by PR #320.
