### ISSUE TITLE
Graphical representation of scrambled locations

### ISSUE THREAD

**Issue by marco-c** [mozilla/MozStumbler#195]
If you stored the scrambled APs and cell towers locally, it'd be interesting to see them on a map.

**Comment by cpeterso** [comment]
Yes, this map feature is definitely on our roadmap! :D

**Comment by Djfe** [comment]
Can be merged with #336, I think.

**Comment by Djfe** [comment]
@garvankeeley this can be closed since it's a duplicate

**Comment by garvankeeley** [comment]
Agreed
