### ISSUE TITLE
add button "send report"

### ISSUE THREAD

**Issue by CupIvan** [mozilla/MozStumbler#196]
for force send current data, becose when there are no internet on phone and next time it will be available, stored data can't be transfered
I try to push stop/start button, but it often not start transfer mode

**Comment by cpeterso** [comment]
When you press the "Stop Scanning" button, MozStumbler tries to upload your data. If the network is not available, it is supposed to try again later. Do you see your points on the leaderboard web page increasing?

**Comment by CupIvan** [comment]
yes, but on last three updates I have only a few points, but later I score over 3000 for two times...
I don't know how it works, maybe programm transfer only several start coordinates, when internet connection was available
maybe for simplify show current score on the main window? and update it when data will be transfer

**Comment by marco-c** [comment]
I may have the same problem. Should the "Reports sent" number be the same as "Locations scanned"? Sometimes I scan 2000+ locations and 2000+ APs, but when I get home only one report is sent.

**Comment by cpeterso** [comment]
Each report uploaded to the server includes all the locations that have been scanned since that last report was uploaded.

**Comment by CupIvan** [comment]
@cpeterso, sometimes, I went to home and count of locations not one, about ~100-200. maybe, if many data collected, it send several reports with some limit? I don't know all data transfered or not alltime and click button start/stop two-three times for reliability. I think, there is need text with count of transfered _records_ and total _records_ on the phone. If thats numbers are equal, that is good and I can close application. but if are different I will push "send" button.

**Comment by marco-c** [comment]
Good to know. Maybe a visual indication that all the locations were sent would be useful.

**Comment by Djfe** [comment]
there should be an indication that the app is uploading reports right now
so that you won't close the application too early

and another option would be helpful, too:
send reports automatically
which should send reports, if there have been 10 (just an example) or more new locations detected or if a certain amount of time went by
and you should be able to use/not use mobile networks for uploading data

**Comment by Djfe** [comment]
My last comment seems to be described in this issue as well: #250 
The best indication that this issue prevents a lot of people from stumbling are the over 100 entries at the end of the leaderboard containing mostly 1 goes up to 5

People start scanning, think it's interesting, stop it again but only see one (to five) reports being send and they think all data has been delivered or they are wondering whether is still uploading data

If this issue and #250 will get fixed the number of those uploading pretty much nothing will get less in comparison to the ones enjoying the experience of contributing to this awesome project

**Comment by Djfe** [comment]
can be closed now -> implemented with v0.13.0

**Comment by cpeterso** [comment]
Yep! Thanks, @Djfe.
