### ISSUE TITLE
Allow to pause scanning

### ISSUE THREAD

**Issue by marco-c** [mozilla/MozStumbler#198]
I don't have a mobile internet connection, so I'd like the data to be stored and then sent when the phone is connected (for example if the battery is low).
At the moment, I have to stop the scanning and hope Android doesn't kill the application.

**Comment by cpeterso** [comment]
MozStumbler saves scanned data to the app's private Preferences database. When MozStumbler restarts, its onscreen counters are reset to zero, but your scanned data should still be saved and uploaded when the network is available again.

There is active development of a proper database and a data export feature.

**Comment by marco-c** [comment]
Great, as there was no visual indication I thought I did lose my entire scanned data.
