### ISSUE TITLE
save temporary data to SD

### ISSUE THREAD

**Issue by CupIvan** [mozilla/MozStumbler#199]
I collect many data, but programm can't send it to server, when I start it again after some time - there are no my data :-(
I offer save it on SD card, and delete temp data only then will be transferred to server successfully.

**Comment by cpeterso** [comment]
MozStumbler saves scanned data to the app's private Preferences database. When MozStumbler restarts, its onscreen counters are reset to zero, but your scanned data should still be saved and uploaded when the network is available again.

There is active development of a proper database and a data export feature.

**Comment by CupIvan** [comment]
@cpeterso, I think program should show count of saved data in order to don't worry for it :-)

**Comment by cpeterso** [comment]
Absolutely! We plan to display better stats when we implement the local database.
