### ISSUE TITLE
Installing Stumbler crashes Aurora and Nightly

### ISSUE THREAD

**Issue by dhylands** [mozilla/MozStumbler#200]
So my android phone (Nexus 4) is running Android 4.3.

I had both Nightly and Aurora running.

I visited: https://github.com/dougt/MozStumbler/releases in Aurora and clicked on the MozStumbler-v0.7.3.apk button to start downloading.

Once the download was complete, I clicked on the download in my notification bar. This started the installation of MozStumbler and Aurora and Nightly both immediately crashed.

**Comment by cpeterso** [comment]
@dhylands: can you check about:crashes on Aurora and Nightly to see where they crashed? That Aurora, Nightly, and MozStumbler all crashed simultaneously sounds like an OOM issue.

**Comment by dhylands** [comment]
Unfortunately, Nightly shows no crashes at all, and the latest crash from Aurora was from yesterday.

They both popped up with the "Unfortunately Aurora/Nightly has stopped" (or however android words that particular message). It just seemed odd to me that they both did this (and 

My phone is currently showing 526 Mb free (30%), and it hasn't been rebooted since the crash.

I tried uninstalling and reinstalling and they didn't crash. I've never seen them crash like this ever in the past.

Having said that, Aurora and Nightly are the 2 largest memory consumers (sitting at 178Mb for Aurora and 122 Mb for Nightly right now).

**Comment by dhylands** [comment]
My dmesg log only goes back an hour, and my logcat starts about an hour after I reported this. Sigh
