### ISSUE TITLE
 Stumbler crash on Samsung galaxy pop plus (GT-S5570i)

### ISSUE THREAD

**Issue by amiad** [mozilla/MozStumbler#204]
I installed Stumbler on my phone (Samsung galaxy pop plus GT-S5570i with Android 2.3.6). The old version work fine but the application updated (to version 0.7.3) and since the update it crash in startup.
When I try to start it I get message "The application has stopped unexpectedly" with button "Force Close".

**Comment by cpeterso** [comment]
@amiad: thanks for the bug report. We fixed some MozStumbler crashes on Gingerbread. You can use an older stumbler version until we release a new build later this week.

**Comment by amiad** [comment]
Thanks. Version 0.7.2 working fine.

**Comment by amiad** [comment]
Version 0.7.2  crashing when I click on settings in menu.

**Comment by cpeterso** [comment]
@amiad: I think you are seeing settings crash #164. I will push a new v0.7.4 release very soon with these bug fixes! :)

**Comment by cpeterso** [comment]
@amiad: If the new MozStumbler v0.7.4 release does not fix your crashes, please reopen this bug! <:)

**Comment by amiad** [comment]
I updated and the problem is solved. Thanks.
