### ISSUE TITLE
Use OpenStreetMap for "Test MLS" screen

### ISSUE THREAD

**Issue by tyrasd** [mozilla/MozStumbler#209]
You could use [osmdroid](http://code.google.com/p/osmdroid/) to have [OpenStreetMap](http://switch2osm.org/why-switch/) instead of proprietary maps on the "Test Mozilla Location Service" screen.

**Comment by hannosch** [comment]
We are planning to use the same mapbox account we already have for the website. mapbox currently doesn't have a native Android SDK, so we'd stick with a web view and some JavaScript.

**Comment by rodmoreno** [comment]
I think I can make the port of Google Maps to MapBox, I can start tomorrow and spend my weekends full time to develop.

**Comment by hannosch** [comment]
@rodmoreno wow, that would be really cool! :)

**Comment by dougt** [comment]
It looks like mapbox is working on a "mapbox-android-sdk"

**Comment by hannosch** [comment]
I have a contact at mapbox, who also pointed me at http://code.google.com/p/osmdroid/ for the time being, but said that a web view would work as well. If anyone runs into problems here, some of the folks at mapbox might be able and willing to help. Ping me if you need a contact there.

**Comment by dougt** [comment]
i'll take this.

**Comment by dougt** [comment]
Started here:
    https://github.com/dougt/MozStumbler/compare/osmdroid_map_support

Hannosch, let me know what tile server I should use against mozilla and what keys to use. (out of band of course).
