### ISSUE TITLE
Enable both active and passive stumbling modes for the Client

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#21]
Client should have separate "turbo" and "background" modes to reduce battery drain.

The background mode could limit its scans to a longer interval, a larger location delta, only when another app has woken up the CPU or turned the screen on, or use Android's passive location provider (that only receives location updates when another app geolocates the device).

https://developer.android.com/reference/android/location/LocationManager.html#PASSIVE_PROVIDER

**Comment by gregeh** [comment]
Perhaps even multiple modes for different movement speeds: walking (5 km/h), cycling (20 km/h), driving (60 km/h).

**Comment by elkos** [comment]
@gregeh good idea, although I guess the sampling rate frequency could change depending on the speed on the device since we already have the GPS location data to do so.

**Comment by cpeterso** [comment]
Android's geolocation API allows you to register for location events when the device most a minimum (application-specified) distance and maximum frequency. For example, an app can ask for location events when the device moves more than 10 meters, but not more frequently than 4 events per second. Android would send location events as the user moved faster (even 10 meters), but max out at 40 meters/second.

**Comment by bjherbison** [comment]
My suggestion in the newsgroup:
- Keep track of the number of times per day each wifi signal is used in a data point.
- If MozStumbler sees a wifi signal that has been used in over 20 reported data points in the past week, leave off or turn off GPS monitoring and sleep for five minutes before checking again.
- If uncommon wifi signals are seen but the phone is on battery power, collect information for 30 seconds but then sleep for five minutes.
- If the phone is connected to a charger (and the battery isn't very low), run as you do today.

Then I just need to plug in the charger in the car, and if I don't plug in the charger some good information will be collected without draining my battery.

**Comment by garvankeeley** [comment]
We now have passive mode in the codebase for Fennec. A trivial way to hook this up to MozStumbler, is to have it run in passive mode when 'Start Scanning' isn't pressed. 
If this requires UI work, then not so trivial.

**Comment by crankycoder** [comment]
I'm closing this as I don't think this is important anymore considering the power consumption changes we've made to the stumbler and passive stumbling is already in fennec.  Our 'high power' mode already very conservative with power consumption while collecting as much as possible.
