### ISSUE TITLE
First scan mostly doesn't search for a gps fix

### ISSUE THREAD

**Issue by whimboo** [mozilla/MozStumbler#210]
I have seen this a couple of times meanwhile. Whenever I start the first scan, the gpxfix is not requested and no locations are logged. Stopping and starting again fixes the problem. It mostly happens when the application was not running before.

**Comment by cpeterso** [comment]
@whimboo: when you say "the GPS fix is not requested", do you mean that you don't see any related messages in logcat or that the app doesn't get a location fix right away? We know that the first GPS fix is very slow. :\

**Comment by whimboo** [comment]
In such a situation I don't see the icon at all in the notification bar. It doesn't matter how long I wait. Also I don't think it is because of a bad signal, given that it works perfectly when I restart scanning.

**Comment by cpeterso** [comment]
@whimboo: If you don't see the GPS icon (flashing or not) in the status bar, then you are right; the app did not (successfully) request a GPS fix.

The Android device and OS version are you using? Do you have Google Play Services installed?

**Comment by whimboo** [comment]
It's Cyaonogenmod 10.1 on the old Nexus S from Samsung. But as said I don't think anything on the system side is responsible for that. It's only happening the very first time. Afterward the application successfully requests the gps fix.

**Comment by colinfrei** [comment]
I've seen this happen as well every once in a while. I'm on Cyanogenmod 10.2 nightlies, on a Galaxy S2

**Comment by gabrielbauman** [comment]
Time to initial fix is dependent on the device clock being fairly accurate. The more clock skew, the longer it takes to get the fix.

On rooted devices, changing the NTP server to something geographically close by is an effective way to speed things up.

**Comment by Djfe** [comment]
MozStumbler doesn't request a A-GPS fix at all on my device (Wi-Fi-Only)
I always have to start the app GPS Status (by MobiWIA) first which makes a request as soon as GPS is available and if the A-GPS data is to old.
->this speeds up the time to get a GPS fix a lot

**Comment by Djfe** [comment]
@garvankeeley does MozStumbler use the following GPS status events?:
http://developer.android.com/reference/android/location/GpsStatus.html

these look interesting to me:
GPS_EVENT_FIRST_FIX
getTimeToFirstFix

I hope someone can implement a way to redownload the a-gps data if an internet connection is available and if the last one is too old by using these events/methods and taking a look at this:
http://stackoverflow.com/questions/14548707/android-how-to-reset-and-download-a-gps-data

**Comment by crankycoder** [comment]
This doesn't happen anymore
