### ISSUE TITLE
Doesn't find any networks on Amazon Kindle Fire without GPS

### ISSUE THREAD

**Issue by LeonNardella** [mozilla/MozStumbler#224]
MozStumbler, at least version 0.7.5, doesn't find any networks on my Amazon Kindle Fire 1st gen running CyanogenMod 10.2 nightly. 

It also keeps nagging me to enable the GPS even though it's already enabled, as well as wifi location.

I don't know how to debug this, so let me know how to generate some logs.

**Comment by cpeterso** [comment]
@LeonNardella: Does the Kindle Fire have real GPS? AFAIK, few Android tablets have GPS hardware and instead rely on Google's Wi-Fi Location Service. MozStumbler requires GPS because we want accurate locations and we don't want to inadvertently download Google's Wi-Fi location data into ours. :)

**Comment by LeonNardella** [comment]
Thanks for the quick answer, @cpeterso .

Now that you talk abou it, yeah... I think it's doesn't really have a real GPS. The thing doesn't even have a camera!

Should I delete/close/whatever this Issue?

**Comment by cpeterso** [comment]
Closing issue because MozStumbler needs real GPS.
