### ISSUE TITLE
Make sure to include attribution on OpenStreetMaps 

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/MozStumbler#239]
OSM require attribution on pages using OSM data (provided to us by Mapbox), and they've asked for it a couple times in various places[0]. We should add it to any page where we're displaying a Mapbox map. A recent PR on Bedrock [1] should show the way.

[0] https://twitter.com/OSM_Attribution/status/396443009769684992, https://bugzilla.mozilla.org/show_bug.cgi?id=944750
[1] https://github.com/mozilla/bedrock/pull/1464

**Comment by hannosch** [comment]
This will only apply once we implement #209. Currently we are using Google Maps and not OSM maps.

**Comment by dougt** [comment]
See https://www.mapbox.com/help/#attribution for requirements.

**Comment by dougt** [comment]
tracked by issue 259.
