### ISSUE TITLE
Don't force Wi-Fi always ON

### ISSUE THREAD

**Issue by vinitraje** [mozilla/MozStumbler#241]
Every time we turn on scanning MozStumbler switches on Wi-Fi, which should be optional. Because in a country like India Wi-Fi availability is very scarce. 

It consumes a whole lot of battery. Maybe a button should be introduced to turn on/off Wi-Fi when needed.

If the Wi-Fi is turned off manually MozStumbler won't send reports until its turned back on.

**Comment by cpeterso** [comment]
Good idea. Scanning cell towers but not Wi-Fi access points would be a nice feature.

**Comment by dougt** [comment]
thanks xsoh!
