### ISSUE TITLE
Map is blank

### ISSUE THREAD

**Issue by thefinn93** [mozilla/MozStumbler#251]
I downloaded 0.8.0 this morning and the map is blank, just an empty grid. I looked through logcat a bit (I'm somewhat new to android debugging) and couldn't find anything out of the ordinary (there was an unrelated error that appeared on previous versions as well). When I swipe the non-existant map around, these sort of messages show up occationally:

```
I/o*.o*.t*.LRUMapTileCac*( 5509): Tile cache increased from 35 to 48
I/o*.o*.t*.LRUMapTileCac*( 5509): Tile cache increased from 35 to 48
```

But nothing else. Inspecting the network traffic reveals that it is making requests and downloading tiles. Let me know if there are other details I've missed

**Comment by thefinn93** [comment]
Ohh nevermind, this is an issue with Cyanogenmod's Privacy Guard. Disabling it made it work fine. Disregard me

**Comment by cpeterso** [comment]
Thanks for reporting your experience, @thefinn93. We've seen some map loading problems because the sdcard was full. The OSM library caches map tiles on the sdcard.

**Comment by thefinn93** [comment]
This was not a bug with MozStumbler, that's why I closed it. My ROM (CyanogenMod) has a feature called PrivacyGuard that blocks certain apps from accessing certain functions. It accidently got turned on for MozStumbler, and that was what was causing this.
