### ISSUE TITLE
0.8.0 doesn't show the map anymore

### ISSUE THREAD

**Issue by djdeath** [mozilla/MozStumbler#253]
When testing the location service in MozStumbler, the map isn't visible anymore.
It just shows an empty grid, though the location circle is still there.
It was working well before the update.

**Comment by vinitraje** [comment]
@dougt The Map isn't showing and "Test Mozilla Location Service" won't work if the Wi-Fi is turned off. It should be independent of Wi-Fi. Please fix this.

**Comment by dougt** [comment]
what device do you have @vinitraje ?

**Comment by ghost** [comment]
The same situation with Nexus 4 and Nexus 7 (2013). Both on Android 4.4.2.

**Comment by vinitraje** [comment]
@dougt I have karbonn A21 on Android 4.0.4

**Comment by cpeterso** [comment]
@vinitraje: are you testing your own local build of MozStumbler or the apk published on GitHub? Local builds currently won't show the OpenStreetMap tiles without a registered MapBox API key. @thefinn93's PR #252 will fix that limitation.

**Comment by thefinn93** [comment]
I had this same issue, running Cyanogenmod with their PrivacyGuard feature enabled. Disabling it fixed it for me

**Comment by vinitraje** [comment]
@cpeterso I'm using version published on GitHub.

**Comment by dougt** [comment]
0.8.1 fixed a bunch of map issues.  Do you continue to see the same problems with the latest update?

**Comment by djdeath** [comment]
It works fine now, thanks!
