### ISSUE TITLE
Couldn't upgrade from 0.8.1 to 0.8.2

### ISSUE THREAD

**Issue by djdeath** [mozilla/MozStumbler#271]
I'm redownloaded the new version because it would crashing after asking if I want to upgrade from 0.8.1 to 0.8.2.

**Comment by pl6025** [comment]
Same problem for me. I've redownladed it to upgrade from 0.8.1 to 0.8.2.
No problem from 0.7.6 to 0.8.0 and from 0.8.1 to 0.8.1.

**Comment by cpeterso** [comment]
I found the source of this updater bug. It should be fixed in a day or two.

**Comment by hannosch** [comment]
There's two issues here: the move of the apk files, and the updater code crashing the app. If no apk file can be found (network errors, 404, ...) the app shouldn't just crash. But that's a much less urgent issue than the non-functioning updates.

**Comment by cpeterso** [comment]
@djdeath: have you been able to auto-update to v0.8.3 without crashing? The crash was likely due to a bug when the update apk is not found.

**Comment by djdeath** [comment]
Yep 0.8.2 to 0.8.3 worked. Thanks!

**Comment by djdeath** [comment]
Yes, 0.8.2 to 0.8.3 worked. Thanks!
