### ISSUE TITLE
Continuing problems with reporting on device with no cellular data

### ISSUE THREAD

**Issue by rtilder** [mozilla/MozStumbler#276]
I lost somewhere between 10k and 20k samples over the holiday break to upload failures.  Even after waiting for 24 hours after returning home, the 0.81 Stumbler still had only one report.  This is mostly a place holder for more investigation later.

**Comment by Djfe** [comment]
I'm experiencing similar issues right now.
Is it possible to upload the data in steps of 500 reports at a time to prevent this?
I have looked in to the reporter code
-> I hope I'm not wrong but to me it looks like as if the reset is called even if the creation of the json-array throws an error
the error variable should be checked to be empty before it deletes everything...
and there should be a for loop to try it at least 10 times and if it still fails it should display the error to the user

could somebody take a look at this pls

it's frustrating if you loose data during the upload

**Comment by tamcap** [comment]
The only time the app might discard report string outright is at load time, when MozStumbler loads a json string from prefs and if that fails, just dumps it. This might have to be adjusted. Any other time (e.g. at reporting stage) there is a 'recovery' process... @Djfe, could you provide exact steps to reproduce the error?

**Comment by Djfe** [comment]
I'm not that familiar with the code, I just looked quickly at the code and I didn't saw anything like a recovery process so I cannot show you an error

are there any log files I can upload?

probably the loading at the beginning should be adjusted then maybe that helps

**Comment by Djfe** [comment]
what I experienced was that the application was partially closed during the upload
so that I still saw the UI but the button said on/off instead of start/stop scan

I closed and opened mozstumbler again -> stats reset

**Comment by tamcap** [comment]
What version of MozStumbler are you using, @Djfe ? The newest version should never give them on/off button captions.

**Comment by Djfe** [comment]
v11, it said something like mozstumbler crashed/stopped working (only saw the German translation)
but I'm using a ram booster which maybe killed the App partially
-> probably no behaviour that can be expected
(nothing happened if I pressed the button)

(I really need to switch my custom room I think to prevent experiencing where I'm not sure if they are the system's or the app's fault...)

**Comment by illarionov** [comment]
@rtilder , Is this still relevant?
