### ISSUE TITLE
Include references to sources of SSID/BSSID material

### ISSUE THREAD

**Issue by rtilder** [mozilla/MozStumbler#277]
Either in comments in code or in a section of the README

**Comment by Djfe** [comment]
Are you talking about the ssid block list?
And do you mean a website or a github issue as a source?

**Comment by garvankeeley** [comment]
There are comments on these in block list, closing as it won't be worked on.

**Comment by Djfe** [comment]
And we can still take a look at the commit history to see where an entry came from.
