### ISSUE TITLE
MainActivity.onStop() closes ScannerService mConnection, but onStart() does not reinitialize it

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#28]
From https://github.com/dougt/MozStumbler/pull/26#commitcomment-3689366

Android calls onStop() when the activity is no longer visible. If the user navigates back to the activity, Android will call onRestart() and then onStart(). mConnection was initialized at its declaration. How will mConnection get reinitialized after onStop() sets it to null? We should probably initialize mConnection in onStart().

**Comment by dougt** [comment]
Fixed.
