### ISSUE TITLE
enable GPS message

### ISSUE THREAD

**Issue by CupIvan** [mozilla/MozStumbler#280]
when I start programm with GPS disable, there is a message on main screen.
then I disagree with it and click NO
if I go to settings or want view map and will back to main screen, there is that message again and again.

can you upgrade it, that programm will memorize my choice for current session?

or optional maybe show red text "GPS disable" and if all ok green text "GPS enable"
maybe instead of first line "GPS Satellites Visible"

**Comment by Djfe** [comment]
@crankycoder I think the new issue #1151 fits better now since the UI changed so much.
The only thing missing now is an indicator for loosing the GPS connection.
The message described above has been removed already.

**Comment by crankycoder** [comment]
No longer relevant.  GPS icons are black with a fix, red when no fix is available.
