### ISSUE TITLE
Disallow < 3 letter user names on Register page

### ISSUE THREAD

**Issue by jrconlin** [mozilla/MozStumbler#293]
Users with 2 letter nicknames do not show up on the Dashboard.

**Comment by hannosch** [comment]
The server side code in question is at https://github.com/mozilla/ichnaea/blob/master/ichnaea/service/submit/views.py#L88 - it just ignores any user names that are less than 3 or more than 128 characters long.

**Comment by hannosch** [comment]
I changed the server side code to allow 2 letter nicknames. But one letter nicknames are still filtered out. It would also be good to limit the maximum length of the nickname field. On the leaderboard we only show the first ~30 characters.

**Comment by Djfe** [comment]
Should be easy to fix
-> 2min-30max characters in the nickname field

**Comment by Djfe** [comment]
@crankycoder since you have rewritten the code already this might be easy for you to fix ;)

**Comment by crankycoder** [comment]
I'm closing this and superceding it with #1325.  We're going to target getting a new leaderboard in place for local stumbling events to get more events run in India.
