### ISSUE TITLE
CSV import

### ISSUE THREAD

**Issue by PrzemoF** [mozilla/MozStumbler#296]
It would be nice to have import option - I collected quite big database with wigle and I want to contribute it to mozilla.

**Comment by hannosch** [comment]
Thanks for considering to give us your data. We don't have an automated process yet, it's tracked under mozilla/ichnaea#28.

For now please sent an email to @cpeterso with the file and optionally your leaderboard user name.

**Comment by Djfe** [comment]
has the file been sent to @cpeterso already? then this could be closed ;)

**Comment by cpeterso** [comment]
I received the files, but this issue is a feature request so other people can import their own CSV files. On further thought, I don't think we want to support that because it would make it too easy for people to upload fake data (even though they can write scripts to do that already).
