### ISSUE TITLE
Should warn when wifi is off

### ISSUE THREAD

**Issue by tbm** [mozilla/MozStumbler#302]
I turned wifi off on my phone because my broadband connection had some issues.

I later went outside and enabled MozStumbler and was surprised that it didn't report any wifi networks... until I remembered that I had turned wifi off.  Doh.

It would be nice to print a warning when wifi is off.

**Comment by cpeterso** [comment]
@tbm: thanks for your feedback. We used to have a WiFi warning, but some people found it annoying because that they wanted to run without WiFi. Maybe we should display a WiFi warning, but not with an annoying dialog box. :)

**Comment by tbm** [comment]
Maybe you could write "wifi disabled" next to "Wi-Fi access Points Visible".

**Comment by Djfe** [comment]
same goes for the GPS dialog
which is annoying to
pls display the link to the settings next to the GPS info (how many satellites and so on)

**Comment by Djfe** [comment]
small addition: a warning if 2g - only is activated
because it probably leads to the app not recognizing all cell towers, right?

**Comment by Djfe** [comment]
#366

**Comment by guerda** [comment]
In further addition to the Wifi startup warning, it would be great to be warned, if the device turned off Wifi during the scan. This may happen manually or by apps like Llama.

**Comment by Djfe** [comment]
MozStumbler still doesn't recognize whether wifi is turned on during scanning when it was off before therefore there have to be checks for changes on  Wifi state
See #477
