### ISSUE TITLE
Bring back start/stop capture button

### ISSUE THREAD

**Issue by greatpatton** [mozilla/MozStumbler#308]
Hello,

With 0.9 the stop/start capture button is gone. This really a mandatory feature as it allows people to easily switch off capture when they want to protect their privacy (with current behavior I will just stop to use it) 

The new process requires to quit the application. This cannot be easily done while driving a car for instance.

**Comment by Valeryan24** [comment]
I agree. Now the informations are written in a smaller font than before and all the butons (test localization, see leaderboard and most important Scan / Stop) are missing and are just in the menus.
So the screen is half blank, and if there is no plan to add other text infos, putting back the Scan button would be very useful.
Also not start scanning by default (or add an option to choose). Being unable to stop without closing the app' is confusing redarding the "counts reset" and "ghost reports" as seen in issues #305 and #250.

**Comment by phrostb** [comment]
What happened to this app?? It used to be so simple and effective.. now the system tray icon shows up sporadically and there's no on/off switch. 

Why did you guys revert it back to such a primitive state????

**Comment by leogaggl** [comment]
I have to agree that .9 release seem a major regression in terms of user experience. This looks and feels like a completely different app. 

All controls for a user are gone. While it's a nice idea to have things happen automatically there still needs to be UI elements for users to intervene.

Also the activity detection simply does not work yet (Nexus 5). Just shows activity 'unknown' or 'tilted' and doesn't scan when moving.

**Comment by phrostb** [comment]
Doesn't work on my galaxy s3 with cm11 either... why can't we just go back to the way things were. Everything functioned fine before... I'm all for battery saving technology.. but this isn't helping.

**Comment by dfsmith** [comment]
The "quit" option doesn't work for me (Galaxy Nexus).  Mozstumbler immediately restarts.
I have uninstalled the app until this can be fixed.

**Comment by tamcap** [comment]
Quit function doesn't work for me. Please simply bring back the stop button. I have to manually kill the service now from system menu or it will keep restarting. A very disappointing update, I had to manually downgrade.

**Comment by keverets** [comment]
Perhaps "Power saving mode" could be renamed "Automatic Mode", and then we could still have a "Manual Mode" which brought back the Start/Stop buttons?

**Comment by cpeterso** [comment]
The name "power saving mode" is a little confusing. We don't tell users why they might want to _not_ save power.

**Comment by pl6025** [comment]
Without the start/stop button, it doesn't scan on my phone, it doesn't find any GPS satellite.
But when I try the service to find where I am, the stumbler app works and scan wifi and send reports, but no GPS functioning. So I can't scan new areas.--> I downgrade to 0.8.3

The message in the notification bar is the same when when scan and when we try the service. Perhaps it will be good to have 2 messages.

**Comment by cpeterso** [comment]
MozStumbler v0.10.0 has a start/stop button. Back by popular demand! :)
