### ISSUE TITLE
Add time delay for stopScanning after activity recognition to avoid "stoplight problem"

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#311]
To avoid the "stoplight problem" with activity recognition, we could add a time delay so the scanner doesn't try to stop and restart all the time.

**Comment by Djfe** [comment]
Is this still an issue?

**Comment by cpeterso** [comment]
This is no longer an issue. When we do implement activity recognition, we will want a timer.

**Comment by Djfe** [comment]
:runs through the next wall:
