### ISSUE TITLE
Activity recognition should not stop scanning when power-saving mode is off

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#312]
The activity recognition seems to stop scanning even when power-saving mode is off.

**Comment by illarionov** [comment]
#304 fixes this problem, but I agree that this fix is not quite good

**Comment by wronkiew** [comment]
I also noticed this problem and had to downgrade to 0.8.3. If I'm traveling through the city, the app has barely enough time to get a GPS fix before the next stoplight, at which point it detects that it has stopped and loses the GPS signal.

Turning off power saving mode had no effect.

**Comment by Djfe** [comment]
can be closed, right?

**Comment by cpeterso** [comment]
Yep.
