### ISSUE TITLE
Wifi settings, wrong signature (FDroid update), test service->no visible map

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#316]
you should be able to see, how many/which cells the app detects right now
and how the detected wlans are called (atleast the bssids)->list
and you should be able to specify the amount of time how long the app will wait before scanning again

why do I only see the radius I'm in if I open the test mozilla location service (as I'm German it may be spelled differently in English) and no real maps/satellite images?

why is the version in the FDroid market not up to date -> cannot update because of wrong signature...

the app should be able to show the leaderboard by parsing the html page and displaying the table on the display

EDIT:
and there should be an option to ignore the battery state

**Comment by cpeterso** [comment]
I think this is an FDroid problem. MozStumbler should probably not be posted there. The MozStumbler version on FDroid is signed by FDroid, not Mozilla, so Android won't let our auto-updater install the Mozilla-signed GitHub apk over the FDroid-signed apk. Also, the latest version of MozStumbler relies on Google Play Services library, so I don't think FDroid will allow that version.

I'm going to contact FDroid about removing the app from their website.

**Comment by Djfe** [comment]
why have you closed this?
I had more questions than just FDroid...

**Comment by Djfe** [comment]
not questions I meant ideas
will probably make new issues tomorrow and separate the ideas I had

**Comment by cpeterso** [comment]
@Djfe: sorry about that. Please file a separate issue for each suggestion or feature request. That makes it much easier to have separate conversations about each suggestion. You can also email questions or ideas to our mailing list: dev-geolocation@lists.mozilla.org or https://lists.mozilla.org/listinfo/dev-geolocation

**Comment by keverets** [comment]
Please reconsider requesting the removal of MozStumbler from F-Droid.  There are many users who do not use the Google Play Store, but rely on F-Droid for getting access to Free Software for Android.  Those users are exactly the kind that would want to contribute to a project like MozStumbler (myself included).

A better fix would be for the F-Droid version to change the notification message to encourage the user to notify the F-Droid maintainers about a new version of MozStumbler so that their repository could be updated appropriately.

**Comment by cpeterso** [comment]
Thanks for the suggestion, @keverets. I am considering some ways to support separate builds for both F-Droid and GitHub. Or we could replace our home-grown updater and use F-Droid as our primary installation source. :)
