### ISSUE TITLE
save results to sdcard (for devices without internet connection)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#322]
you should be able to save your current captured cell towers and wifi aps to be able to load them later if you have a wlan connection (not everybody has a flatrate), so that you can close the app until then, make even restarts and prevent data loss by crashes (automatic saving to sd card would be nice, too)

**Comment by brainstorm** [comment]
+1, lost quite a big trace today after quitting the app in a foreign country without roaming :-/

**Comment by cpeterso** [comment]
@brainstorm: the good news is that I don't think you lost your big trace. The stumbler saves all measurements locally until they have been uploaded. The measurements are not yet saved to a database on the sdcard, though. We have a UI bug (issue #305) we really need to fix where the stats _displayed on screen_ are reset to zero when the app restarts, even though the actual data is still safe and will be uploaded.

**Comment by brainstorm** [comment]
Great to hear! You could just close this issue then since it's just an UI issue.

**Comment by cpeterso** [comment]
I'm closing this issue because it is covered by issues #3 and #305.
