### ISSUE TITLE
No Map Tiles/Images (Test Mozilla Location Service)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#323]
why do I only see the radius I'm in and squared paper, if I open the test mozilla location service (as I'm German it may be spelled differently in English) and no real maps/satellite images? (Version 0.8.3, because there seem to be bugs with the power-saving mechanisms in 0.9 and I don't like the new interface either)
I'm using Wifi/have an internet connection (16k DSL) but I do not see the map tiles
Can I see whether the app is loading them and just takes longer?

**Comment by tadas-s** [comment]
Same issue on Nexus i9250, Android 4.3. I'm on WiFi, location: London, area somewhat covered according the map on website.

Screenshot:

![screenshot_2014-01-22-19-14-44](https://f.cloud.github.com/assets/840454/1978047/c3be45c2-839e-11e3-8c39-17eb04f28234.png)

**Comment by cpeterso** [comment]
This looks like a problem loading map tiles from the mapbox server.

**Comment by tadas-s** [comment]
Works fine now. Thanks!

**Comment by cpeterso** [comment]
@tadas-s: did you install MozStumbler from GitHub or F-Droid? I'm just curious what differences there might be in these different builds that might affect the map.

**Comment by tadas-s** [comment]
0.8.? (cannot remember exact version) from F-Droid => map was broken
0.9 from Github => map was broken
0.10 from Github => works fine

Did you guys fixed something server side? I can't seem to notice anything map related in diff between 0.9 and 0.10.

**Comment by Djfe** [comment]
works for me again
/_closed_/

**Comment by Djfe** [comment]
@cpeterso could be related to that because the version which had problems was 0.8.3 which I have downloaded from the f-droid market

**Comment by cpeterso** [comment]
@Djfe: oh, yes, that might explain it. The F-Droid build would default to using OpenStreetMap's map tile server and their server might throttle requests.
