### ISSUE TITLE
Only show the update notification once on app start

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#324]
The update manager built into MozStumbler should only show the dialog box at the start of the app and not every time you switch to the menu/turn your device/open the map and get back.
There should be a button to press (check for updates or something like that) and a setting to disable the automatic search for updates.
Especially since version 0.9 doesn't seem to be bug free, it is a bit annoying.

**Comment by cpeterso** [comment]
This bug is related to how our activity gets stopped and restarted when the device is rotated.

**Comment by Djfe** [comment]
yeah but that is quite often if you press remind me later...
it should be hooked up to the app start at least (and the button solution from above (check for updates) would be nice as an addition)

**Comment by Djfe** [comment]
similar to #280

**Comment by Djfe** [comment]
this issue still happens, if the activity is reloaded (on device rotation or app reload (happens if you come back from the launcher or another app even though the service is running))
but it doesn't happen if you come back from the settings or the leaderboard anymore

**Comment by crankycoder** [comment]
Fixed so long ago by @cascheberg.
