### ISSUE TITLE
0.9.0 Quit Doesn't Work

### ISSUE THREAD

**Issue by drees** [mozilla/MozStumbler#326]
After the 0.9.0 update, Quit no longer works.

After hitting Quit from the menu, the application closes and it appears to exit.

But once you start moving, you will see in the notifications area that MozStumbler has started running again.

This is on a Samsung Galaxy S3.

**Comment by spindr** [comment]
Also on Sony Xperia Miro with Android 4.0.4 -- it seems to have quit then the icon reappears to show it's running.
Perhaps an event/timer is restarting it.

Also I can't quit until I reply yes/no to turn GPS on.

**Comment by cpeterso** [comment]
This is the same problem described in issue #327, which includes more details about movement tracking causing this bug.
