### ISSUE TITLE
Disabling power saving mode does not work

### ISSUE THREAD

**Issue by JanneM** [mozilla/MozStumbler#327]
I disable the power-saving mode in 0.9.0 since the movement tracking is too inaccurate. But the app ignores the setting and continues to activate and inactivate according to that detection in either case.

**Comment by Djfe** [comment]
can be closed now and maybe referenced to #333
solution for now: update (the next version removed the feature)

**Comment by cpeterso** [comment]
This should no longer be a problem with v0.10.2, as @Djfe points out.
