### ISSUE TITLE
Location tracking activates despite exiting the app

### ISSUE THREAD

**Issue by JanneM** [mozilla/MozStumbler#328]
I sometimes do not want to have location tracking enabled. But with 0.9.0 there is no way to disable tracking. With power-saving mode off, and exiting the app, it still starts up again and starts tracking when I move about.

This is sometimes annoying, but it is a real issue at work, where I am pretty sure I should not be broadcasting AP info of any kind to other places. As it is I need to disable the app in the settings to make it stay off.

**Comment by cpeterso** [comment]
@JanneM: this problem should be fixed in MozStumbler v0.10.0.
