### ISSUE TITLE
Wishlist: bring back the manual on/off button

### ISSUE THREAD

**Issue by JanneM** [mozilla/MozStumbler#329]
Sometimes the app doesn't correctly detect that you're moving, so you want to turn it on manually. Sometimes the time is not appropriate for tracking (sensitive area; doing something network intensive; want to save battery life) and you want to turn it off manually.

The only way to control it in 0.9.0 is to go into settings/apps and kill it manually, then start it from your app list again when you want to enable it.

**Comment by cpeterso** [comment]
@JanneM: this problem is fixed in MozStumbler v0.10.0.
