### ISSUE TITLE
Write our own movement detection library as an alternative to Google Play Services' Activity Recognition

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#333]
Depending on Google Play Services prevents MozStumbler from being included in free software app stores like F-Droid. We don't need most of the advanced functionality of the Activity Recognition API; we just want to know if the device is moving or still.

We can roll our own movement detection code using standard Android sensors like TYPE_ACCELEROMETER, TYPE_GRAVITY, TYPE_LINEAR_ACCELERATION, and/or TYPE_ROTATION_VECTOR:

https://developer.android.com/guide/topics/sensors/sensors_overview.html

**Comment by Djfe** [comment]
just found this using Google:
https://www.cs.cmu.edu/afs/cs.cmu.edu/Web/People/ishafer/pubs/localization-mswim10.pdf

could be very informative ;)

**Comment by cpeterso** [comment]
Thanks, @Djfe. That's an interesting paper.

**Comment by garvankeeley** [comment]
#1270 addresses this. The AOSP 4.3 and up has this in the form of the significant motion sensor.
