### ISSUE TITLE
MozStumbler >= v0.9.0 no longer scans WiFi very well on BlackBerry 10.2.1

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#340]
A user on the mailing list reported this problem:

Latest working Version on BlackBerry 10.2.1 was MozStumbler 0.8.3. The newly MozStumbler 0.9.0, 0.10.0 and 0.10.1 don't get any WiFi anymore. The 0.10.0 got 2 WiFi points, but that are the only one it got (scanned 8 locations). Seems broken, there must be more visible (check 0.8.3).

Seems like BlackBerry 10.2.1 is compatible with Android 4.2.2: http://devblog.blackberry.com/2013/11/prepare-yourself-an-android-runtime-update-is-coming/

**Comment by cpeterso** [comment]
MozStumbler v0.9.0 required Google Play Services, so I would not be surprised if it was not supported by BlackBerry's Android emulation. But I removed Google Play Services from MozStumbler v0.10.0, so that is no longer an issue. If v0.10.0 scanned at least 2 WiFi APs, then we must have a different issue on BlackBerry.

**Comment by SunboX** [comment]
Hey Chris, I tried MozStumbler v0.10.2 today on a long way (~ 40 km) and it seems to work now. But I thought with v0.8.3 I did scan more access points. Have to check this again on the same way (maybe next friday).

![bb_stumbler_0 10 2](https://f.cloud.github.com/assets/83344/2002108/e9b87028-85e1-11e3-8b24-b2085fc7f826.jpg)

**Comment by Djfe** [comment]
actually your screenshot shows pretty good that it is broken on blackberry:
40km should equal a LOT more than just 26 locations ("Standorte")
and you don't even have GPS (have you deactivated it/are you in a building?)
or is this not the screenshot of the direct result of the 40kms drive?

maybe mozstumbler scans only scans a few times every x minutes/very slowly (if 40km ends up in only 26 locations)

**Comment by SunboX** [comment]
I tried MozStumbler v0.11.0 yesterday on a longer trip. I had two devices, a Android v4.1.1 (HUAWEI G510) and my BlackBerry Z10 running on BB OS v10.2.1 (with Android 4.2.2 Emulator).

The Screenshots below are showing the result. It seems like MozStumbler on BlackBerry doesn't track any location if the Screen/Display of the Device is locked. If I had unlocked it, it tracked fine. After the screen goes black, it's stopped.

And it seems like on BlackBerry it doesn't track any GSM Stations at all.

![bb_stumbler_0 11 0](https://f.cloud.github.com/assets/83344/2048994/04097a64-8a59-11e3-9bf3-ea2948296c0d.jpg)
![android_stumbler_0 11 0](https://f.cloud.github.com/assets/83344/2048995/04a78af6-8a59-11e3-9ff8-4b3f3cdec65c.jpg)

**Comment by Djfe** [comment]
your second screenshot (Android) shows another problem I have experienced as well:
Mozstumbler doesn't scan cells if the screen is off
#367

your blackberry seems to be different though as it doesn't scan cells at all

**Comment by SunboX** [comment]
I've googled today a little bit, and it seems that the android emulator on blackberry get's stopped if the screen goes off. :( don't seem to be a mozstumbler issue

**Comment by Djfe** [comment]
then there should be at least an advice for blackberry users that the app gets disabled if the screen is off

strange blackberry bug as it is impossible then to send notifications to the user if the device is off
probably an exptemporary measure to save power which won't get changed
What about a native blackberry app? Is it too expensive (licenses)/doesn't it make sense?

**Comment by cpeterso** [comment]
Closing because this is apparently an issue with BlackBerry's Android emulator pausing MozStumbler when the screen is off.
