### ISSUE TITLE
Integration of the coverage map.

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#342]

**Comment by Djfe** [comment]
Sry, pressed enter to early on my smartphone
here comes the description ;)

the coverage map should be integrated into the apps interface so that you can see which areas are uncovered
newly found wifi aps (maybe cell towers, too) should be calculated and drawn onto the map
(maybe the devices could render the map tiles and upload them -> faster updates and no cron job on the server is needed) 

maybe newly found aps get a different color then (red for example)

further details (scanned aps) would be accessible by pressing menu
->customized menu which gets pushed over the map from the bottom

and if you rotate the device (landscape) the menu would be pushed from the right

**Comment by Djfe** [comment]
can somebody merge this with #336 pls ;)

**Comment by cpeterso** [comment]
Covered by #336.
