### ISSUE TITLE
No longer scanning since 0.10.2

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#350]
no longer scanning locations it scans WiFi and cells but never locations and also not reporting.

**Comment by Djfe** [comment]
Which device/OS are you using?
do you get a GPS signal?

**Comment by pl6025** [comment]
Same problem for me.
No problem to collect data with the 0.10.1 but with the 0.10.2 it doesn't find a location (no gps satellite detected).

Sony Ericsson Xperia X8 rooted, with GingerDX (based on cyanogen mod 6) - Android 2.3.7

**Comment by ghost** [comment]
Nexus 5/Android 4.4.2

and 

Samsung Galaxy Nexus/Android 4.2

and Moto X/Android 4.3

all three got update and stopped tracking locations

**Comment by ghost** [comment]
Nexus 5/Android

**Comment by ghost** [comment]
FWIW, If I tap start/stop many times every once in awhile it will scan but most of the time its not scanning so something in the previous release is causing some sort of issue since it has worked flawlessly for every previous release.

I wish we had a way to debug :)

**Comment by pl6025** [comment]
The 0.11.0 is working for me. It solves the problem.

**Comment by ghost** [comment]
I can confirm 0.11.0 is working fine and solves the issue too.
