### ISSUE TITLE
battery empty -> scan button doesn't switch from on to off state

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#352]
if the battery of phone is almost empty and mozstumbler stops scanning to save on battery it doesn't switch the buttons light
![screenshot_2014-01-27-14-37-50](https://f.cloud.github.com/assets/5685512/2010134/b3e7f84a-8769-11e3-9d7a-c8a709e7fb00.png)
![screenshot_2014-01-27-14-38-01](https://f.cloud.github.com/assets/5685512/2010135/b4e28a94-8769-11e3-8d52-b80d64b81084.png)

**Comment by Djfe** [comment]
the blue color on the button doesn't appear if you start scanning by opening the map, too.

**Comment by tamcap** [comment]
I believe my commit should fix the latter problem. No idea why updateUI() is not invoked in the first case.

**Comment by Djfe** [comment]
thx ;)

**Comment by tamcap** [comment]
Don't close it just yet - I do not think the fix will be appropriate for the first part of your problem. I have honestly not been able to experience it myself (but I am an obsessive battery charger).

Edit: Actually, let's test it. It seems updateUI() should do the job after all.

**Comment by Djfe** [comment]
works thx for the easy fix ;) (tested with v0.11.0
