### ISSUE TITLE
Add option to configure stumbler's low battery limit

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#353]
there should be an option to ignore the battery state and just keep on scanning

**Comment by cpeterso** [comment]
This could be configurable.

**Comment by Djfe** [comment]
A checkbox similar to wifi only is probably enough.
You could provide a "scrolling" field (similar to the clock settings where you can scroll) in addition to let the user switch between 1 and 50% battery state (more than 50% doesn't make sense in my oppinion)

Setting will be checked by using a global variable similar to the wifi-only option

**Comment by cpeterso** [comment]
I think a slider control would be preferable to a checkbox because it is a more general solution. It handles the 0% case you would like plus all other values. :)

**Comment by Djfe** [comment]
I had this in mind when I talked about scrolling:
http://developer.android.com/design/building-blocks/pickers.html
Or:
http://stackoverflow.com/questions/7633343/android-dialog-number-picker

But a slider could work as well
(it may be a bit annoying to achieve your exact number then though...(less accurate))

**Comment by Djfe** [comment]
This is being worked on at the moment.
