### ISSUE TITLE
ignore moving wifi aps

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#365]
mozstumbler should ignore all moving wifis which signal strengths' barely changes and are available over a bigger amount of locations (will only work for moving wifis next to you (Bus, train) and not for busses/trains which are driving next to you)

**Comment by evilpie** [comment]
We have various block-lists where we try to mitigate this problem, but that approach might not actually scale.

**Comment by tamcap** [comment]
right now the client stores very little information; a lot of it can be done on the server later

**Comment by cpeterso** [comment]
The client does have a list of some SSIDs that are known to move (like popular phones and public transit). That is just one level of protection, so the server must do its own checks for moving APs. Detecting APs that move with the client as the client's own position is moving is a clever idea, though the server will still need to do something similar.

**Comment by Djfe** [comment]
should I close this issue and open it again on the server project page?

**Comment by cpeterso** [comment]
@Djfe: you can leave this issue open. The server already has some code for detecting moving APs, but you've described a way that the client might be able to do something similar (thus providing another filter for potentially useless measurements and reducing the amount of the data the stumbler needs to upload).

**Comment by gabrielbauman** [comment]
One interesting case - there's a ferry service nearby that provides wifi. The two ships meet halfway across the water, and for a brief moment we detect the access points on the other ship.

So from one ship's point of view, the other ship's access points look like they are stationary in the middle of the Georgia Strait.

**Comment by Djfe** [comment]
well I said already that this option only filters out wifi aps that move in your direction and not in the opposite one

If you remember the aps name than it can be added to the block list ;)

why should somebody use mozstumbler or the Mozilla location service on a ship? ;D

EDIT:
you are not only able to tell whether a wifi is moving in your direction but also if a wifi ap is moving while you are standing still independently of the direction it is heading to
(you stand at a cross, a bus with a wifi ap is driving by)

further stuff (driving against you direction) needs at least 2 or 3 measurements to determine whether it is moving or not (interpolating the signal strengths to determine wether the signal strength got greater/lesser than expected by your movement)

**Comment by Djfe** [comment]
This discussion will be continued in #1106
