### ISSUE TITLE
cell scan not working if screen off

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#367]
don't know whether this is device related (the Rom I'm using right know is not completely stable) but mozstumbler seems to scan only for cell towers if the screen is on

**Comment by Djfe** [comment]
device: Sony Xperia Arc S
rom: Paranoid Android 2.57.3

**Comment by Djfe** [comment]
maybe this is only an UI - bug that causes the number to stop updating while the screen is off

I was driving 2km with screen off and mozstumbler showed only the 20 cells from the start (when the screen was on) as I checked it
then I let the screen on and the number of scanned cells was immediately rising while I kept driving

I hope this bug is reproducible so that you can fix it.

**Comment by gabrielbauman** [comment]
Seeing the same thing here on a Galaxy Nexus, cells scanned does not seem to update while the screen is off.

**Comment by Djfe** [comment]
actually I noticed that the number increases over time
but a lot slower

is it possible that the number only increases if new unique cells are found so that not each scan gets added?

could possibly be fixed together with the issue that the figure displays the scan count instead of unique cells #320

**Comment by RexWheeler** [comment]
I see the same issue on a Galaxy S4 Active - If the screen goes off, cell scanning seems to stop or be greatly reduced.

**Comment by Djfe** [comment]
Just got fixed with #481, I guess.
So let's test it again once the next version is out ;)

**Comment by Djfe** [comment]
made a quick test and it is fixed ;)

**Comment by RexWheeler** [comment]
Does not appear to be fixed (0.16.0). I drove to dinner about 6 miles away and scanned 5 cells with the screen off. On the way home I set the screen not to time out and scanned 19 cells (driving the same route).

**Comment by Djfe** [comment]
Yeah but your issue is a different one.
The scanned cell count showed the number of different measurements instead of unique cells so that all visible cells got added to the scanned count each time the timer got fired -> mozstumbler would show a higher scanned count than just 19 after 6 miles of driving with the screen on in version 0.15.0.

Maybe your device is slower while the screen is off and mozstumbler needs to use wake looks to get the same amount of fired timer in comparison to when your screen is on.
Pls open a different issue for that ;).

Should be easy to see if it takes longer to fire the timer with the screen off as mozstumbler log contains all fired timers with the time they got added.
