### ISSUE TITLE
Submit Results via WiFi Only 

### ISSUE THREAD

**Issue by ghost** [mozilla/MozStumbler#370]
It would be nice if MozStumbler could store scan results even after being closed and submit when WiFi becomes available if the user so chooses in settings.

**Comment by Djfe** [comment]
it stores all informations, but the the UI has a bug so that the statistics don't show collected data anymore
it will be send the next time the phone gets an internet connection
see #305 for more information ;)

wifi only would be a nice enhancement, too (for devices without a flatrate)

**Comment by AdamHauner** [comment]
Similar to #378

**Comment by tamcap** [comment]
Can be closed, fixed by #378.
