### ISSUE TITLE
over 50 entries don't get uploaded

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#374]
it seems like mozstumbler doesn't send all locations
look at the screenshot, all 926 locations where gathered before the report was send
![locations](https://f.cloud.github.com/assets/5685512/2041222/e5febc32-89c2-11e3-9c2c-7f2c87d90bff.png)
but 40 entries are missing in this example?

do some reports send several locations (merged)?
or are the informations about these locations filtered out because of no valuable information?
or is it a connection problem (wifi connection interrupted for a short moment)?

**Comment by Djfe** [comment]
different example:
![2](https://f.cloud.github.com/assets/5685512/2054662/f2a3ff32-8ab8-11e3-8ede-0cf1b3bb7032.png)
2 more reports than scanned locations!?
I'm a little bit confused.
Is this still due to the fact that there is no database and that the UI doesn't show all entries that have been generated after the last time mozstumbler send reports?

**Comment by illarionov** [comment]
If you stand long at the same location, the data at this location may be reported several times (with different timestamps and collected data). 
Some locations may be skipped if the accuracy of positioning is not enough or if there is no collected data.

**Comment by Djfe** [comment]
Are you sure about that?
-> this is no issue but a design feature?

Because then I would love to have a send button like in #196 and a clear indication after pressing this button that all data has been send successfully like in #250

It would also help if the app shows the correct number of locations
(filter before increasing the number to show only the net count that will be send later on)

**Comment by Djfe** [comment]
Can be closed now since the database was implemented, so that you can see if locations where from stumbling the last time ;)
