### ISSUE TITLE
Better zoom on the map

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/MozStumbler#379]
One from the latest upgrades disabled  zoom 14 and higher [on the map](https://location.services.mozilla.com/map#13/49.7376/13.3803). I would like to have better zoom (maybe 14 and 15?) available because on the zoom 13 I don't see streets in the city which are good to cover (wi-fi networks).

**Comment by hannosch** [comment]
This issue is being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=961429.

**Comment by JasnaPaka** [comment]
Thanks for info. Dupe.
