### ISSUE TITLE
Possible data skew?

### ISSUE THREAD

**Issue by dougt** [mozilla/MozStumbler#38]
So, what I understand that we are doing is:

1) detect a location change
2) when a location change is seen, kick off a wifi scan
3) when we get the list is returned by the scan, bundle and send to server.

If I am traveling fast, the space time between 1 and 2 might be significant.  That is, I might detect a location change at point A and do a wifi/cell scan at point B.  If the distance between point A and point B is significant, using this data for location determination might be troublesome.

I'd like to hear solutions to this -- or some verification that it isn't a problem.

**Comment by cpeterso** [comment]
We should measure this latency so we understand how big a problem it is. Maybe we could get a second location fix (point C) and interpolate between the points A and C? That sounds uglier than the original problem.

Related problems:
- `WifiManager.startScan()` is asynchronous, but we call `getScanResults()` immediately, so our scan results are probably old. We should listen for the `SCAN_RESULTS_AVAILABLE_ACTION` intent and _then_ call `getScanResults()`. This change, however, would _increase_ the time between point A and B in your example.
- `WifiManager.startScan()` is passive: it only reports APs that happen to be broadcasting beacons. There is an undocumented `startScanActive()` API that can initiate an active scan that probes APs to respond: http://www.androidjavadoc.com/2.3/android/net/wifi/WifiManager.html#startScanActive%28%29

**Comment by dougt** [comment]
the wifi and cell blobs we send to the server need timestamps.

**Comment by hannosch** [comment]
Is there any way to get a rough estimate on how "old" the async results are? Or some way to guess the current speed?

One approach might be to ignore results, which are too "old" or rather too far away from the reported GPS position.

Another approach might be to estimate the distance to the reported GPS location and increase the reported accuracy. So if the GPS fix is from 5 seconds ago, and you are traveling at 20 meters / second (~44mph), you add 100 meters to the accuracy. On the server side we can than take this into account. A 100 meters accuracy means the wifi data is probably useless, but the cell info is still quite usable.

**Comment by cpeterso** [comment]
Android's location fixes include a speed (meters/second), but I don't trust that is very accurate or supported on all devices.

We currently ask Android to send up location events no more frequently than 1000 ms (and only if the device has moved more than 10 meters).

**Comment by cpeterso** [comment]
I measured the scan results latency (when investigating issue #40). On my Nexus 4, the time from `startScan()` to `SCAN_RESULTS_AVAILABLE_ACTION` was between 600-700 ms. 

I imagine the device starts recording AP beacons and, after a 500 ms timeout, returns those results. (APs are supposed to broadcast beacons every 100 ms.) If the user is traveling at 20 meters/second, they will hear AP beacons over a 14 meter distance from the GPS location fix.

**Comment by dougt** [comment]
Synchronizing 3 different event streams is hard.

I wonder if some of this would go away if we got around the Android APIs and talked directly to hardware.  F.e., we could just listen to the raw NMEA stream and avoid the location framework's callback.  mwu would know about the wifi scanning bits.

**Comment by Djfe** [comment]
another issue I see:
if a device tries to determine its position using the mozilla location service and is driving at a high speed as well it will be experiencing the same asynchronous behaviour but ask the server for a detailed position (is the server supposed to calculate this (then a very accurate timestamp would be needed) or the device to save privacy?)

**Comment by Djfe** [comment]
https://groups.google.com/forum/?nomobile=true#!topic/mozilla.dev.geolocation/ysjjdSMhGKQ

**Comment by garvankeeley** [comment]
Closing, as I don't see any activity on this bug, or plans to work on it. Reopen if needed.
