### ISSUE TITLE
Add support for external GPS devices

### ISSUE THREAD

**Issue by JasnaPaka** [mozilla/MozStumbler#381]
I own external GPS device which I use for mapping for OpenStreetMap project. This GPS device si better than internal GPS device on my phone. So I have connected this GPS device via bluetooth and I see data in Locus (map application on Android). But MozStumbler doesn't work with this external GPS device. I don't know how this works on Android. Maybe application must have own support for external GPS devices?

Theoretically there is no problem when MozStumbler use internal GPS devices. But only with one exception... battery live.

**Comment by tamcap** [comment]
Hi, have you tried using third party apps? There are free applications in the Android Market that will connect to a BT GPS unit and then provide this information to third party apps. While I am not sure where they will work with MozStumbler - give it a shot!

**Comment by Djfe** [comment]
maybe there is an option in your rom to choose the default gps source
I'm using CyanogenMod 10 right now and there is an option for that (I don't know whether it is a part of the original Android Source Code or a part of CyanogenMod only and whether it will recognize external antennas over bluetooth)

**Comment by JasnaPaka** [comment]
Thanks for tip! I have tried Bluetooth GPS (https://play.google.com/store/apps/details?id=googoo.android.btgps) but it doesn't work for me. Internal GPS is not activated but on the other side GPS position is not available.

**Comment by Djfe** [comment]
You need to link the GPS data in some way.
Either there is way in Android to accept the bluetooth devices as a GPS source or you need to use the the spoofing method to put in GPS positions (that aren't spoofed but that doesn't matter, it's just a way to get the GPS position)

have you tried this?:
http://support.garmin.com/support/searchSupport/case.faces?supportPage=GLO&caseId={924b5370-b8f3-11e2-4124-000000000000}&locale=en_US

**Comment by crankycoder** [comment]
Without access to this particular hardware, we don't have a good way of ensuring that any patch we make is going to work.   I can't see adding this feature benefiting more than a fraction of a percentage of our users and we're tightly constrained on engineering resources.
