### ISSUE TITLE
Quit does not Quit

### ISSUE THREAD

**Issue by RexWheeler** [mozilla/MozStumbler#385]
Quitting the application (menu, quit) does not seem to actually quit the application. When you restart the application the "current stats" (Locations reported, Wi-Fi scanned, etc) values are not reset to zero. In addition, after "quitting", the ScannerService process continues to run in the background (eating CPU and battery).

If you force close the application or reboot the phone, the "current stats" are reset (and the application stops using resources). 

I would expect that the user requesting a quit would actually quit the application, unload it from memory, stop all background processes, etc.

If the intent of "quit" from the user interface point of view is to simply exit the UI, then there needs to be another method to actually stop all processing other than doing a force close or using some other task manager. Perhaps another menu option "quit all", "quit and unload", etc.

**Comment by Djfe** [comment]
I can confirm this.

**Comment by tamcap** [comment]
OK, so:
- I thought about it
- I read [this](http://blog.radioactiveyak.com/2010/05/when-to-include-exit-button-in-android.html)

Thoughts: 
- do we need an exit button?
- is there any need to run the service when it's not scanning? why?
- ~~should we run the service in the foreground?~~ it already runs in the foreground when needed

**Comment by cpeterso** [comment]
I agree that we probably don't need a Quit button.

**Comment by cpeterso** [comment]
As of PR #403, we no longer even have a Quit button to be buggy. :)
