### ISSUE TITLE
Wait for SCAN_RESULTS_AVAILABLE_ACTION intent before calling WifiManager.getScanResults()

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#39]
This issue is forked from issue #38.

`WifiManager.startScan()` is asynchronous, but we call `getScanResults()` immediately, so our scan results are probably old. We should listen for the `SCAN_RESULTS_AVAILABLE_ACTION` intent and _then_ call `getScanResults()`.

**Comment by dougt** [comment]
I think issue #45 will address this mostly.

**Comment by cpeterso** [comment]
I still think we should investigate whether we should wait for the `SCAN_RESULTS_AVAILABLE_ACTION` intent after calling `startScan()`. The API docs say the "availability of the results is made known later by means of an asynchronous event sent on completion of the scan."

https://developer.android.com/reference/android/net/wifi/WifiManager.html#startScan%28%29

**Comment by dougt** [comment]
this was fixed by pr 49?

**Comment by cpeterso** [comment]
Yup.

**Comment by yuchuangyan** [comment]
ye
