### ISSUE TITLE
mainactivity doesn't update while scanning without gps fix

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#404]
the screen doesn't get updated while scanning if the gps is disabled

you need to reload the mainactivity/press start/stop to update the numbers of found cells/wifi aps

**Comment by Djfe** [comment]
Happens as well if you have no GPS fix but GPS is enabled

**Comment by Djfe** [comment]
this is a bug
the textfield only get updated with a working GPS connection and not by the scanner themselves if they are running.
I can force updates by reloading the main activity though and see the real count of cells/aps the scanner service recognizes.

**Comment by cascheberg** [comment]
@Djfe this is fixed and should be closed

**Comment by Djfe** [comment]
Agreed! This bug was in the old GUI still.
