### ISSUE TITLE
question about the scanning of cell towers (maybe a bug?)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#405]
I'm living in rural areas so the following thing might not be recognized in citys in the same way
my device is able to scan more cells while the option "only 2g" in my mobile settings is checked

is my device only able to scan 2g while I'm using 2g and only 3g while using 3g?
(-> more 2g cell towers in my area than 3g ones?)
or does anybody know a different/better explanation for this behaviour

**Comment by cpeterso** [comment]
I don't know. This sounds like a general question about the capabilities of Android itself. Maybe ask on Mozilla's [dev-geolocation mailing list](https://lists.mozilla.org/listinfo/dev-geolocation).
