### ISSUE TITLE
Upload compressed JSON using HTTP `Content-Encoding: gzip`

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#406]
What do you think about using a file to upload the locations?
This way the data can be compressed before the upload. (Or are mobile devices not powerful enough for good compression methods?)

This could reduce the data usage.

**Comment by cpeterso** [comment]
I thought Android's HttpURLConnection API automatically used gzip compression, but I see now that the docs only mention handling compressed HTTP _responses_, so we should really fix this. I don't think we need to implement file uploading. Compressing our HTTP POST requests and using `Content-Encoding: gzip` should give us a similar benefit.

https://developer.android.com/reference/java/net/HttpURLConnection.html

**Comment by cpeterso** [comment]
I think we will need to compress the JSON ourselves using something like `GZIPInputStream`.

**Comment by Djfe** [comment]
Could be helpful in this context:
http://java.dzone.com/articles/just-drop-binary-if-youre

**Comment by tamcap** [comment]
OK, ok. First, we need to make sure ichnaea can handle the .gzip files, only then it makes sense to implement it here...

**Comment by cpeterso** [comment]
This tutorial describes how someone used Android's [AndroidHttpClient class](https://developer.android.com/reference/android/net/http/AndroidHttpClient.html) to compress their HTTP requests:

http://arnab.ch/blog/2012/09/android-how-to-send-gzipped-json-in-http-request/

**Comment by Djfe** [comment]
In my opinion #408 should be analysed/fixed first as compression will reduce file-size so greatly that nobody will notice #408 anymore (nobody notices a few kb more or less...)

**Comment by hannosch** [comment]
The live server now supports this for all service API's.

Some of the search requests can get rather large (with 100 wifis in them), so it's worthwhile doing this for both the submit and search parts.

**Comment by Djfe** [comment]
@cpeterso this issue is not fixed, yet.
Only the submit is compressed.
as hannosch suggested it would make sense to compress the search requests as well (for requests with over 100 wifi aps).
And are only entries compressed which are uploaded by the sync adapter or the ones uploaded by the reporter as well?
Does the reporter use the sync adapter now?

Pls open it back up again

**Comment by cpeterso** [comment]
Rather than complicate this bug, I opened a new bug report (#446) specifically for compressed search requests.

All reports should be uploaded using the sync adapter, which should be using our compressed uploading code.

**Comment by Djfe** [comment]
Ok thx :)
