### ISSUE TITLE
Data usage on 0.12.1

### ISSUE THREAD

**Issue by leogaggl** [mozilla/MozStumbler#408]
There seems to have been another regression on the latest update (which I just updated yesterday).

The app chewed through 1GB of mobile data within 3-4 hours. I have used this for months on mobile data and newt had an issue with data usage. 

Since this happened while overseas - there goes the data allowance. Not happy ...

**Comment by tamcap** [comment]
I strongly recommend using the use wi-fi only option when concerned with data usage. However, 1 GB in 3 hours does sound excessive...

**Comment by leogaggl** [comment]
Thanks. Yes - I have already done that and blocked the app from mobile data.

However this has never been a problem over months. And the whole 1GB was used by the stumbler app. So it seems to me to be an issue introduced in the latest upgrade which co-incided with the problem.

Excessive is a nice way of putting it - have mumbled some stronger terms ... ;-)

**Comment by Djfe** [comment]
Have you used it in this time?
Have you opened the map
or have you only uploaded locations?

or did it always run in the background?

**Comment by cpeterso** [comment]
I wonder if this bug is related to the problem reported with the "Reports Sent" counter was surprisingly greater than "Locations Scanned". :(

**Comment by leogaggl** [comment]
&gt;Have you used it in this time?
No.

&gt;Have you opened the map
No.

&gt;or have you only uploaded locations?
Not many - mainly stationary in hotel

&gt; or did it always run in the background?
Yes.

**Comment by tamcap** [comment]
I can definitely say I consistently see approximately 2x reports sent vs location scanned. I was pretty busy and didn't have a chance to adb it yet.

**Comment by illarionov** [comment]
This is because each location is sent as 2 reports now: wifis and cells.

**Comment by cpeterso** [comment]
That must an unintended side effect from my reporter refactoring. :(

**Comment by stripTM** [comment]
0.5GB consumed me in two days, I am now working only on wifi
https://twitter.com/stripTM/status/434789779864301568/photo/1

**Comment by rfugger** [comment]
I'm having the same issue. I've been using the app as normal, but my data usage in a few days after updating to 0.12.1 has been 375 MB. I never noticed any significant data usage previously. This is a definite problem.

**Comment by gabrielbauman** [comment]
I was bitten by this recently - about 100MB an hour consumed over several hours of driving around.

Perhaps making wifi-only uploads the default would be a good idea? Data plans here in Canada are mostly in the 600MB - 1GB monthly range, so even 50MB or 25MB per hour is far too much.

**Comment by gpoo** [comment]
FWIW, before 0.12.1, my daily reports were between 300-600 to 1000-2000. Since 0.12.1 I noticed that one day I sent more than 10,000 reports (according to the leaders ranking)  I have not changed my routine that much, maybe double, but not 5-10 times.

Was there data that was not being report? Are there duplicated reports now?

In addition, in the leaders page, g@v reported almost 1,000,000 in one week or less. I cannot recall the granularity of each data point, but if it where 1 data point every 10 meters, that would be 1,000 kms (that would like crossing a couple of states or provinces).  It is possible, but it is seems there is an inflation of reports considering how fast the points have increased in the last days with respect to the previous week aggregated.

**Comment by Djfe** [comment]
Is this issue still in the app?
I guess that we could reduce data usage even more by fixing this (maybe even down to 10/20% according to the last post above mine)
The gzipping probably disguises it if mozstumbler sends to many reports.

**Comment by Djfe** [comment]
Or has it been removed by #413 and #433

**Comment by Djfe** [comment]
Would it help to write extra logging functionality to track the amount of reports that gave been sent and their size without the gzipping -> dev version with gzip disabled.

This way we could find out whether this problem is still existent

**Comment by Djfe** [comment]
@garvankeeley you can close this, I think ;)

**Comment by garvankeeley** [comment]
Thanks @djfe, it is great to clean up the issue list and get it to a manageable size
