### ISSUE TITLE
Country based fiter for leaderboard

### ISSUE THREAD

**Issue by bellayet** [mozilla/MozStumbler#411]
It would be nice if we have country based filter at the Mozilla Location Service leaderboard[1]. That will help contributors to know who are contributing from the country and their position at the leaderboard.

[1]https://location.services.mozilla.com/leaders

**Comment by Djfe** [comment]
Was mentioned in the server project already ;)
Mozilla/Ichnaea#24

**Comment by stephenjudge** [comment]
I really like this idea. I'd love to see who else in my country is contributing. Maybe even offer to link leaderboard nicknames with web profiles so we can contact each other and meetup.

**Comment by Djfe** [comment]
countrybased leaderboards should be easy to implement
but for your idea to make communication possible, we need a persona login feature for Mozstumbler mozilla/ichnaea#12

**Comment by crankycoder** [comment]
Closing this as it's a core feature in the new leaderboard.

As for https://github.com/mozilla/MozStumbler/issues/411#issuecomment-35513699, we are using Firefox Accounts (FxA) for logins.

New bug is here: https://github.com/JaredKerim-Mozilla/leaderboard-server/issues/8
