### ISSUE TITLE
Add Student Agency and RegioJet SSID to blacklist

### ISSUE THREAD

**Issue by AdamHauner** [mozilla/MozStumbler#422]
Their SSID is „ŽLUTÝ“ (or maybe "ZLUTY"):

http://regiojet.cz/cs/sluzby/index.html
Naše WiFi síť se jmenuje „ŽLUTÝ“ ...

http://jizdenky.studentagency.cz/web/autobus/servis-pro-cestujici/internet-zdarma.html
Naše WiFi síť se jmenuje „ŽLUTÝ“ ...

**Comment by cpeterso** [comment]
@AdamHauner: I can't find a reference to the „ŽLUTÝ“ or "ZLUTY" SSIDs on the pages you linked. I'm not sure how the names should be listed on our SSID blocklist.

**Comment by AdamHauner** [comment]
On http://jizdenky.studentagency.cz/web/autobus/servis-pro-cestujici/internet-zdarma.html name is clearly visible to me, but I'm not sure, if server displays you - as English speaking user - this Czech page.

On http://regiojet.cz/cs/sluzby/index.html you have to click on "Více >" near WiFi in section "Zdarma Vám nabízíme".

I sent e-mail to company to clarify, if they use „ŽLUTÝ“ as listed on the page, or ASCII-only "ZLUTY".

**Comment by tamcap** [comment]
Any update on that?

**Comment by AdamHauner** [comment]
My e-mail is without response, I sent it again.

**Comment by AdamHauner** [comment]
Still no response from Student Agency, but travelers report that SSID is "ZLUTY".

**Comment by cpeterso** [comment]
Google Translate says "ŽLUTÝ" is Czech for "Yellow". I'm concerned that might be too generic of a network name to block. Our server has code to detect moving Wi-Fi access points, so blocking SSIDs on the client is just an optimization. So I don't think we should block this particular SSID.
