### ISSUE TITLE
Add "legal blah blah blah" click-through dialog on first run

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#430]
The actual legal text is TBD, so this task mostly involves talking to Mika in Mozilla Legal.

**Comment by mikaland2** [comment]
Hi, I just commented in Bug 1007264.  LMK if you have questions.  Thanks!
Mika

**Comment by cpeterso** [comment]
Bug 1007264 is about Fennec's setting text. This bug is about MozStumbler's first run, which doesn't actually exist. :)

**Comment by garvankeeley** [comment]
This is the first-run dialog, which was based on looking at some other apps. It would be unusual to have any more content than this:
https://github.com/mozilla/MozStumbler/pull/897

**Comment by Djfe** [comment]
That actually depends from app to app.
Just take a look at the Teamviewer first run
You have to swipe through 4 screens to get to the app
