### ISSUE TITLE
Add CSAD Plzen SSIDs to black list

### ISSUE THREAD

**Issue by AdamHauner** [mozilla/MozStumbler#432]
Add SSIDs of CSAD Plzen bus hotspots to black list. Unfortunately every bus has different name of hotspot:
 "csadplzen_bus01"
"csadplzen_bus02"
"csadplzen_bus03"
"csadplzen_bus04"
"csadplzen_bus05"
"csadplzen_bus06"
"csadplzen_bus07"
"csadplzen_bus08"
"csadplzen_bus09"
"csadplzen_bus10"
"csadplzen_bus11"
"csadplzen_bus12"
"csadplzen_bus13"
"csadplzen_bus14"
"csadplzen_bus15"
"csadplzen_bus16"
"csadplzen_bus17"
"csadplzen_bus18"
"csadplzen_bus19"
"csadplzen_bus20"
"csadplzen_bus21"
"csadplzen_bus22"
"csadplzen_bus23"
"csadplzen_bus24"
"csadplzen_bus25"
"csadplzen_bus26"
"csadplzen_bus27"
"csadplzen_bus28"
"csadplzen_bus29"
"csadplzen_bus30"
"csadplzen_bus31"

From http://www.csadplzen.cz/?ob=aktuality#wifi7

**Comment by cpeterso** [comment]
That each bus has a unique name should not be a problem because MozStumbler matches SSID prefixes or suffixes, not exact SSID names. So prefix "csadplzen_bus" would match all of the SSIDs listed above. :)
