### ISSUE TITLE
0.14.0 stopped scanning and reporting

### ISSUE THREAD

**Issue by gpoo** [mozilla/MozStumbler#439]
After I upgraded to 0.14.0 on my Nexus One, MozStumbler does not show any new location scanned, neither last location (in spite that the GPS is working).  It also does not seem to be reporting.

To make the things worse, the Upload observation dialog is barely readable.  I can understand the button "upload" is greyed out if there is no observation, but except the title and the button close, the dialog it is almost black, I cannot read the information that seems to say when was sent the last report.

After a while, I unchecked "Upload only on WiFI", no new report either.  I have unchecked geofencing.

The only thing that works is "Test Mozilla Location Service" (which is quite fast)

I will try to downgrade to 0.12.1.

**Comment by cpeterso** [comment]
@gpoo: Does the "Test Mozilla Location Service" map report a close approximation of your actual location? If so, then that is a clue that MozStumbler is able to access GPS and Wi-Fi data at least some of the time. That might mean the problem is in the code that logs the reports to the local database before uploading them.

**Comment by gpoo** [comment]
Yes, it is quite accurate and fast. However, it can do it right after I load MozStumbler and before the GPS icon stop blinking.

**Comment by pl6025** [comment]
For the "Upload observation dialog which is barely readable" I've open a new issue with a screen shot.
https://github.com/mozilla/MozStumbler/issues/441

**Comment by gpoo** [comment]
After I downgraded to 0.12.1, MozStrumbler update the locations scanned as I walk. However, it does not send any reports, neither when I stopped scanning (I had 117 locations scanned). I am going to try to wipe-out MozStumbler and start all over again. **sigh**.

**Comment by gpoo** [comment]
I did more testing. I tend to think that was something went wrong when I did the previous upgrade.

I tried to start clean, so:
1. I uninstalled MozStumbler 0.12.1 (after a force-downgrade from 0.14.0)
2. I mounted my Nexus One device (the sd-card) on my Linux box, and I searched and deleted everything that started with org.Mozilla
3. Power off
4. Power on
5. Installed 0.12.1
6. Test it with some locations. It sent 2 reports right away, and the remaining ones once I stopped scanning (~27 locations or so).
7. Upgrade to 0.14.0
8. Uncheck "Upload only on WiFi"
9. Start scanning again
10. Stopped after 54 locations scanned.  It sent the report.

So, it seems to be working fine again. I would like add another check before closing this issue: if delaying the reports to only WiFi makes any change or not.

**Comment by gpoo** [comment]
Another update:

I enabled "Upload only on WiFi" and it worked as expected. I am closing this issue and I will continue paying attention if the issue arises again, in whose case I will re-open this issue and add more details.

**Comment by cpeterso** [comment]
Thanks for debugging this problem, @gpoo.
