### ISSUE TITLE
Upload observation dialog is barely readable

### ISSUE THREAD

**Issue by pl6025** [mozilla/MozStumbler#441]
This is a screen shot from the 0.13.0 (same problem on the 0.14.0) for the report.
![screenshot-1392832731318](https://f.cloud.github.com/assets/4056260/2229413/04b7e428-9aee-11e3-8a06-18e7aa3cf0ea.png)
It's really hard to read.

**Comment by Djfe** [comment]
Then the font needs to be adjusted to the system ui because on my phone the background is white instead of grey
-> font needs to stay grey/black for this type of system ui
But for a dark one the font needs to change to a white color

**Comment by goldfndr** [comment]
![sc20140301-004628](https://f.cloud.github.com/assets/173956/2301044/fe7ab724-a11f-11e3-9a83-2703acb6f939.png)
Attached is how it looks as of 0.15.0 on my Samsung Galaxy S Continuum (SCH-I400), Android 2.2.2. It was similarly difficult to read in 0.14.0 but I didn't get a screenshot. If PR #465 made it into 0.15.0, it didn't solve.

**Comment by Djfe** [comment]
Hasn't been merged, yet -> no fix applied 0.15.0 -> you have to wait for the next update
