### ISSUE TITLE
Using android's own methods for geofencing

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#445]
What do you think about using "android.hardware.location.GeofenceHardware" for geofencing instead of our own method?
Would be better to rely on Android's own methods I think.

This way we could easily add several spots where geofencing should be active for example.
You can take a look at it here:
http://developer.android.com/reference/android/hardware/location/package-summary.html

I don't know whether this only counts for Mozstumbler then or the whole phone though.

**Comment by tamcap** [comment]
That's an API level 18.

**Comment by Djfe** [comment]
Oh you are right only on Android 4.3+
But according to this article it saves battery by stopping unneccessary requests on the hardware level:
http://readwrite.com/2013/07/24/android-43-jelly-bean-what-you-need-to-know#awesm=~owxLymoBIHARmy
EDIT:
quote:
"Android 4.3 also has some improved location and sensor capabilities, such as the ability to do "hardware geofencing" that's designed to optimize power efficiency by moving location computations to hardware rather than performing them in Android software."
EDIT2:
This is similar to #32 as it was introduced in 4.3 as well.

**Comment by tamcap** [comment]
Our geofencing implementation is dead simple. It blocks at the scanner level from ever reporting the lcocation downstream, and just moves on. Could a hardware implementation do it better - maybe. But we would probably exclude a majority of MozStumbler users who don't have the newest phones with fancy capabilities.

**Comment by Djfe** [comment]
We could make a fallback for the the software solution ;)
EDIT:
And I definitely think Google's hardware solution is better because the software doesn't need to compare your actual position with the geofenced area all the time as the hardware does that for you.
It is maybe more accurate and saves energy at the same time.

**Comment by Djfe** [comment]
So you still think this functionality is not usable until nearly everybody uses Android 4.3+ ?
(Over 90%?)

**Comment by tamcap** [comment]
I am just saying that time spent implementing a very slight improvement to an existing feature could be spent elsewhere.

**Comment by Djfe** [comment]
Good point

**Comment by crankycoder** [comment]
I'm closing this as the API level requirement is too high (API 18) and it's far from clear that it will provide us with any benefit beyond what we currently do for geofencing anyway.

**Comment by Djfe** [comment]
One advantage is that you can setup several spots for geofencing with it.
another one is that it might reduce power usage
It's an idea for future releases when almost every device supports api 18
