### ISSUE TITLE
Upload observations shows no data

### ISSUE THREAD

**Issue by Nutomic** [mozilla/MozStumbler#447]
When I'm running MozStumbler (0.14.0 from Github on Omnirom 4.4), numbers for wifi and network increase in the activity, but when I press upload, everything is zero. Additionally, once I disable the scan and restart the activity, all data is reset to zero.

Logcat shows no satellites/fixes, but at the same time, Google Maps has perfect accuracy.
Logcat:
    D/org.mozilla.mozstumbler.Scanner(30132): onGpsStatusChange - satellites: 0 fixes: 0
    D/org.mozilla.mozstumbler.Reporter(30132): Intent ignored with Subject: Scanner
    D/org.mozilla.mozstumbler.MainActivity(30111): Updating UI
    D/org.mozilla.mozstumbler.MainActivity(30111): Received a scanner intent...
    D/org.mozilla.mozstumbler.cellscanner.CellScanner(30132): Cell Scanning Timer fired
    D/org.mozilla.mozstumbler.Scanner(30132): WiFi Scanning Timer fired
    D/org.mozilla.mozstumbler.Reporter(30132): Intent ignored with Subject: Scanner
    D/org.mozilla.mozstumbler.MainActivity(30111): Updating UI
    D/org.mozilla.mozstumbler.Scanner(30132): onGpsStatusChange - satellites: 0 fixes: 0
    D/org.mozilla.mozstumbler.MainActivity(30111): Received a scanner intent...
    D/org.mozilla.mozstumbler.cellscanner.CellScanner(30132): Cell Scanning Timer fired
    D/org.mozilla.mozstumbler.Scanner(30132): WiFi Scanning Timer fired
    D/org.mozilla.mozstumbler.Reporter(30132): Intent ignored with Subject: Scanner
    D/org.mozilla.mozstumbler.MainActivity(30111): Updating UI
    D/org.mozilla.mozstumbler.Scanner(30132): onGpsStatusChange - satellites: 0 fixes: 0
    D/org.mozilla.mozstumbler.MainActivity(30111): Received a scanner intent...
    D/org.mozilla.mozstumbler.cellscanner.CellScanner(30132): Cell Scanning Timer fired
    D/org.mozilla.mozstumbler.Scanner(30132): WiFi Scanning Timer fired
    D/org.mozilla.mozstumbler.Reporter(30132): Intent ignored with Subject: Scanner
    D/org.mozilla.mozstumbler.MainActivity(30111): Updating UI
    D/org.mozilla.mozstumbler.Scanner(30132): onGpsStatusChange - satellites: 0 fixes: 0
    D/org.mozilla.mozstumbler.MainActivity(30111): Received a scanner intent...
    D/org.mozilla.mozstumbler.cellscanner.CellScanner(30132): Cell Scanning Timer fired
    D/org.mozilla.mozstumbler.Scanner(30132): WiFi Scanning Timer fired
    D/org.mozilla.mozstumbler.MainActivity(30111): Updating UI
    D/org.mozilla.mozstumbler.Scanner(30132): onGpsStatusChange - satellites: 0 fixes: 0
    D/org.mozilla.mozstumbler.Reporter(30132): Intent ignored with Subject: Scanner
    D/org.mozilla.mozstumbler.MainActivity(30111): Received a scanner intent...
    D/org.mozilla.mozstumbler.cellscanner.CellScanner(30132): Cell Scanning Timer fired
    D/org.mozilla.mozstumbler.Scanner(30132): WiFi Scanning Timer fired
    D/org.mozilla.mozstumbler.MainActivity(30111): Updating UI
    D/org.mozilla.mozstumbler.Scanner(30132): onGpsStatusChange - satellites: 0 fixes: 0
    D/org.mozilla.mozstumbler.Reporter(30132): Intent ignored with Subject: Scanner
    D/org.mozilla.mozstumbler.MainActivity(30111): Received a scanner intent...
    D/org.mozilla.mozstumbler.cellscanner.CellScanner(30132): Cell Scanning Timer fired
    D/org.mozilla.mozstumbler.Scanner(30132): WiFi Scanning Timer fired
    D/org.mozilla.mozstumbler.Reporter(30132): Intent ignored with Subject: Scanner
    D/org.mozilla.mozstumbler.MainActivity(30111): Updating UI
    D/org.mozilla.mozstumbler.Scanner(30132): onGpsStatusChange - satellites: 0 fixes: 0
    D/org.mozilla.mozstumbler.MainActivity(30111): Received a scanner intent...
    D/org.mozilla.mozstumbler.cellscanner.CellScanner(30132): Cell Scanning Timer fired
    D/org.mozilla.mozstumbler.Scanner(30132): WiFi Scanning Timer fired

Edit: The map also shows "location not found".

**Comment by cpeterso** [comment]
hi, @Nutomic, when you say _"numbers for wifi and network increase in the activity, but when I press upload, everything is zero"_, which numbers are zero? The measurements in the main UI, the "Upload Observations" windows' "Sent", or the "Upload Observations" windows' "In Queue numbers?

**Comment by Nutomic** [comment]
I made some screenshots, hope that helps:
http://i.imgur.com/eZ3LYb0.png
http://i.imgur.com/gqgVqjA.png

First is after scanning for a few seconds, second is after pressing "Upload observations immediately after.

**Comment by Djfe** [comment]
You need a working GPS connection to upload data ;)
The Mozilla location service can only guess positions based on wifis and cell towers later on if the user who scanned the data sent an accurate GPS position with it ;)

**Comment by Djfe** [comment]
In other words: it doesn't make sense to just scan wifi aps and cell towers
What do you want to do with signal strengths and id's of these  without any positional data.

**Comment by tamcap** [comment]
The GPS on your phone doesn't provide the scanner with the most basic information - hence the whole thing doesn't work. Did it work before on this ROM?

**Comment by Nutomic** [comment]
OK it seems it was a problem with GPS reception (it works when I am outside).

Is there any chance to get a warning message in this case (eg make "GPS Satellites Visible" red and/or flash it)?

**Comment by Djfe** [comment]
See #366 ;)
Issue can be closed, I think.

**Comment by Djfe** [comment]
@cpeterso you can close this, Nutomic didn't realize that you cannot get a good (first) gps connection inside of a building.

**Comment by cpeterso** [comment]
OK.
