### ISSUE TITLE
coverage map is cached

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#463]
The test map caches the coverage tiles -> I see new coverage only in another zoom level

-> are there timestamps (last tileupdate) you could compare to determine changes and force an update?
Or is it only possible to force an update/delete the coverage tile cache every time the map is opened?

The cache doesn't belong to Mozstumbler -> deleting cache in the app manager doesn't change anything

**Comment by Djfe** [comment]
I don't know why but after taking a screenshot of the map to show you what I mean the issue was gone!?
Maybe it updated itself correctly then I don't know.
I will open this issue if I recognize it again

**Comment by cpeterso** [comment]
The coverage data is not available at all map zoom levels.

**Comment by Djfe** [comment]
I know but that happened at a zoom level where it was in fact available

But it didn't update the overlaying tiles on the screen until I made a screenshot

->I saw covered streets at higher zoom levels (bigger areas) than on smaller ones which I had loaded/watched already once before I covered the streets
