### ISSUE TITLE
entries are thrown away although upload not successful

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#464]
I have problems uploading my reports:
Sometimes my phone shows the wifi symbol in the status bar but no signal strength (no white bars)
I think this could be because my phone reconnects in a certain way

it has happened to me while uploading and during that the uploading kinda stopped -> loading animation but the numbers of reports in the database doesn't go down/no uploads in that time
later on the coverage map I see that my track is incomplete and there are spots missing.

looking at the code
I guess that an ioexception has been thrown but the data was still thrown away because of temporary being false
could be something else
is it possible that there are some things in the code that could lead to the data not being uploaded if the connection stops working?

is it possible that my phone gives a HTTP 2xx Error (but no 204) during connection problems?

why do entrys get deleted if temporary is false?
->they haven't been uploaded successfully then

I tried to look at the code but cannot figure out what is going on (I'm still learning Java and have mostly experience in HTML/JS/PHP/Delphi...)
I don't have a catlog anymore (phone has been rebooted and I think that the log gets reset during reboot)

I'm using a modified CyanogenMod 11 right now (Android KitKat) on an Xperia Arc S

Maybe someone can explain me how to do a catlog of Mozstumbler only
(I only know a way to do this using root and the app System Tuner Pro and I get the whole system log...) or give me a link

I want to get this issue fixed because then I don't have to fear losing tracks anylonger
the database was a nice addition that prevents entries from being lost due to quiting the application but this seems to be rather an issue which happens during the upload

**Comment by Djfe** [comment]
example:
![image](https://f.cloud.github.com/assets/5685512/2297106/3543c660-a0a8-11e3-91c2-a05782db5306.png)
I drove the red marked way but it didn't upload all points
it may also be due to gps loss but I really don't think so

I know that I'm speculating a lot here because I don't have a log file but I hope that someone can see an issue in the code that would still fit to my descriptions

Is it hard to implement a function that collects MozStumbler logs so that you can watch/export (SD Card)/upload (for Devs) them?

**Comment by cpeterso** [comment]
@Djfe: I have seen a similar issue where my route looks like a dashed line. If you suspect the problem is related to uploading and not scanning, you can test your theory by using the "Upload only on WiFi" setting and upload when you get to a strong Wi-Fi connection.

**Comment by Djfe** [comment]
It was a strong connection but my device reconnected several times for a weird reason during the upload
Therefore I think it would be better to upload over mobile Internet instead because that connection works probably better
I will test it the next time I make a longer drive

**Comment by Djfe** [comment]
Actually there is no way, I think, that the app will receive HTTP Code 204 without the page being successfully send, right? And the server won't be the cause either. So there must be something in the code that throws entries away (maybe after a certain amount of failing tries). 
Wouldn't it better to leave the choice to the user -> stop uploading and show an alert (keep data/upload later or throw away)

**Comment by tamcap** [comment]
The problem is, there are many things that can go wrong...

Probably the most common one is `ConnectTimeoutException` (sublcass of `IOException`): right now we happily throw away the batch that hits a timeout - this will have to change. But there is like a mass of different things that can go wrong... Creating too many dialogs is also not a solution.

**Comment by tamcap** [comment]
Look at https://github.com/tamcap/MozStumbler/compare/network for the current progress I am making refactoring the network code into something more object-oriented. It's not ready for prime-time yet, but this will allow us better control of what is kept, and what is discarded.

**Comment by Djfe** [comment]
Thx for your answer ;)
The new code looks a lot better in comparison, much cleaner and easier to understand because of the object-oriented structure

Looking forward to future improvements :)

**Comment by Djfe** [comment]
Will this be fixed by #474?
I guess my requests/uploads have timed out back then so uploads ending in a 408 error code shouldn't be thrown away

But according to your description you have changed it so that none of the data will be deleted, thx for that ;)

**Comment by cpeterso** [comment]
I merged @tamcap's PR #474 so the next MozStumbler release will have the fix. Let's see if it helps.

**Comment by Djfe** [comment]
Seems to have fixed the issues -> I was able to upload entries later that failed to upload.
The scanning stopped if the upload failed but the entries didn't got deleted so I can upload if my phone's connection is less screwed up.
