### ISSUE TITLE
MozStumbler sometimes breaks WiFi

### ISSUE THREAD

**Issue by ferongr** [mozilla/MozStumbler#475]
So, I'm not sure what's the issue here, but in many cases my device (Samsung GT 5670) can end up with the WiFi in a borked state, requiring a device reboot. The issue happens after having the scanner on for a while (1hr+ ?). From that point onwards, the device refuses to connect to any WiFi network (WiFi state loops between "Connecting -> Unsuccessful -> Connecting... etc" or "Connecting -> Disconnected -> Connecting... etc")  , even after stopping the scanner, exiting MozStumbler and/or turning WiFi off and on again.

I'd hazard a guess that the WiFi scan rate (it looks like it's scanning 4 times a second) is what causes it.

**Comment by tamcap** [comment]
Any chance you could send us some adb logs?

**Comment by ferongr** [comment]
Sure, which medium do you recommend me to send the logs over (in my limited knowledge, adb error logs can have potentially privacy-sensitive information in them).

**Comment by tamcap** [comment]
They might... You are welcome to send it to me (git@tamcap.one.pl), with a caveat, I am not affiliated with Mozilla and only sometimes push some code to the repo.

**Comment by Djfe** [comment]
More likely to be a device/Rom specific issue
http://forum.xda-developers.com/showthread.php?t=1366431

You could switch to another Rom without the issue as Samsung probably won't fix the issue in their stock rom
CyanogenMod should work according to the linked thread

**Comment by ferongr** [comment]
I'm on a CM.7.2 ROM.

**Comment by Djfe** [comment]
You could try a cm 11 Rom from xda ;)
(camcorder isn't working though)
But according to the cm wiki all versions for your device are 7.2 nightly anyway so it won't make too much difference

**Comment by Djfe** [comment]
@tamcap did you get some logs already?
Anything unusual regarding the wifi?

**Comment by tamcap** [comment]
I got the logs. Will check it out when I have a free moment.

**Comment by ferongr** [comment]
Note that the device expired some time ago so it won't be producing any
more logs or verifying any fixes.

**Comment by Djfe** [comment]
So can this be closed now since your device's support ended? Or what are you referring to?

**Comment by ferongr** [comment]
Sure. I doubt there's someone enlse stuck with an armv6 device out there.

**Comment by Djfe** [comment]
Well, then you should close this issue on Github ;)

**Comment by crankycoder** [comment]
After talking with the PressureNET people, this is a bug in hardware/drivers.  It's not really the stumbler.
