### ISSUE TITLE
Dynamic statistics in notification?

### ISSUE THREAD

**Issue by goldfndr** [mozilla/MozStumbler#476]
Currently, the notification shows only the `service_scanning` text (Scanning for Wi-Fi and Cellular networks). It'd be nice to have this dynamically updated like the WiGLE stumbler, as I don't always have it in the foreground. For example,

453 locations, 1/12 Cells, 4/23 Wi-Fi

with a prefix of "Off; " if geofenced.

**Comment by Djfe** [comment]
A button for start/stop scanning would be nice as well

**Comment by cascheberg** [comment]
@goldfndr This feature is now implemented, so I think this issue should be closed.
