### ISSUE TITLE
No scans for Wifi APs (enabling wifi after scan start)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#477]
MozStumbler doesn't scan for Wifi Aps if you enable it after it started to scan

It needs to check for a working Wifi connection each scanning interval instead of only once at the button press
Or we need an intent that gets executed each time the state of the wifi connection changes.

**Comment by Djfe** [comment]
Has somebody tried to reproduce this bug, yet?
Wifi off->start scanning->wifi on->no scans for Wifi aps

**Comment by guerda** [comment]
Yes, I did. I'm currently using the latest version (0.15.0) and did the following steps:
1. Turn off Wifi
2. Start MozStumbler ( http://i.imgur.com/RCXW8aS.png , no Wifi connected)
3. Start scanning
3. Turn on Wifi (I even connect to one in my example, http://i.imgur.com/wQkAh0N.png)
4. No Wifi networks are detected
5. I stop and start scanning ( http://i.imgur.com/L2EZ0XV.png )
6. All Wifi networks are detected

**Comment by Djfe** [comment]
Thx ;)

**Comment by cpeterso** [comment]
Fixed by PR #489.

**Comment by guerda** [comment]
I can verify that this bug is fixed. 
1. Turn wifi on
2. Start scanning
3. Turn wifi off (visible wifi networks 0)
4. Turn wifi on (visible wifi networks rises)

Thank you for the work!

**Comment by Djfe** [comment]
First the newest version is 0.16.0. Second you would need to compile it for your own as the fix has been implemented after the last update...

**Comment by guerda** [comment]
I tested it with 0.16.0 today, it works.

**Comment by Djfe** [comment]
Oh wait actually the fix was included in 0.16.0 so my fault ;)
