### ISSUE TITLE
Add the current path to the map

### ISSUE THREAD

**Issue by stripTM** [mozilla/MozStumbler#478]
It would be a good idea that the path done in the session, appeared in the coverage map in a colour different from the coverage colour, for example:
http://striptm.com/ejemplos/mozilla/mozstumbler_map.png

This way it would be easy to cover areas not still tracked. In the current behaviour, the tracked areas recently covered are not displayed until the next day.

**Comment by Djfe** [comment]
Similar to #336
We need a local database that saves location entries beyond their upload to do this (#3)
