### ISSUE TITLE
Landscape mode -> no scroll

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#479]
I cannot scroll in landscape mode and therefore not access the scan button then

We need a scroll bar or move the gui elements so that they fit on the screen as a whole (by placing the button the right for example)

My device's display: 240 dpi 480x860 (or something like that not sure about that but it is around 4xx times 8xx)

**Comment by tamcap** [comment]
Scroll would be strange. But I like the button move idea.

**Comment by Djfe** [comment]
Thx for your fix ;)

**Comment by Djfe** [comment]
Actually I never recognized this until today, I think, because I normally hold my device in the other way.

I have maybe tried it once or twice in earlier versions but there was less text back then (no geofencing etc.)

I never saw the icons of the options as my device displays them only in landscape mode ;D

One idea for another change:
We could also remove the number of reports and the last upload time from the main activity as it is displayed in upload observations now.
That would free some more space on the screen and remove redundancy.

**Comment by illarionov** [comment]
It would be better to correct the layout or to fix Russian translation?

![screenshot_2014-03-10-13-14-58](https://f.cloud.github.com/assets/482800/2372110/69d5d0fa-a835-11e3-947d-74db5a4850b5.png)
![screenshot_2014-03-10-13-18-02](https://f.cloud.github.com/assets/482800/2372111/69d5dd98-a835-11e3-9a4a-3b9270ef2c8e.png)

**Comment by Djfe** [comment]
The button should have preferably a small width and its height should equal the one of the device.
The text could be turned around:
For example:
S
t
o
p

s
c
a
n
n
i
n
g

Or at least a few line-breaks if possible

**Comment by Djfe** [comment]
Experiencing the same thing with the German translation. The button overlays the last date a report has been uploaded.
There should be a different translation where you can add a line-break.
