### ISSUE TITLE
Show two markers on MapActivity: One for GPS, one for Mozilla Location Service

### ISSUE THREAD

**Issue by guerda** [mozilla/MozStumbler#484]
To get a grasp, on how precise the location service is working, the MapActivity should show an additional Marker for the GPS fix.
For this, two new variables (e.g. mLatGps, mLonGps) would be needed in src/org/mozilla/mozstumbler/MapActivity.java and filled on startup.

**Comment by garvankeeley** [comment]
This is the original idea for what is now issue #733.
