### ISSUE TITLE
Reduce size of start / stop scan button

### ISSUE THREAD

**Issue by RexWheeler** [mozilla/MozStumbler#485]
I find that it is very easy to accidentally press the start / stop scan button. Since the button is huge and extends to the screen boundaries, it can be pressed by simply grabbing the phone by the edges and inadvertently letting your fingers touch the edge of the screen. As a feature request I would like to see the size of the button reduced or some other mechanism put in place to ensure that the user actually wants to start or stop scanning.

**Comment by Djfe** [comment]
Just used mozstumbler on my Galaxy Tab 3 10.1 and the button covers pretty much half of the screen :O
