### ISSUE TITLE
Sometimes "Visible locations" number stops increasing, but not cells & WiFi

### ISSUE THREAD

**Issue by Valeryan24** [mozilla/MozStumbler#502]
Sometimes, I have a little problem using MozStumbler (the last one 3 days ago with 0.15) : I have geolocalization, GPS visible, but when I check the screen during drive, it hapens that number of "visited and registered locations" stays at the same level, without increasing, as if I had lost the position.

Cells / WiFi detection and numbers continue to be seen and increasing, and sometimes "visited places" makes a +1 so there may be a report sent but with lots of datas missing, and until I restart the program and begin a new session with re-GPS scanning, it does not work anymore.

Problem is that apart "visited place" number stagnating, there is no other way to detect a problem, GPS seems OK...

I will post later a screen og a whole area where I went, on a city I saw the problem, so from this moment it is normal there were no reports anymore, but just before I also checked on another town, places number was well increasing, and this portion of map is still empty, too, as if I was never there...

PS : I updated bug 249 but did not find how to re-open it.

Thanks !

**Comment by Djfe** [comment]
@garvankeeley lots of code got changed, I think this can be closed
@Valeryan24 are you still experiencing such a bug in 0.40.1.0?
