### ISSUE TITLE
Dual Sim not working

### ISSUE THREAD

**Issue by hoseinit** [mozilla/MozStumbler#507]
I am using the latest version of MozStumbler (v0.16.0) on my Sony Xperia E dual on android 4.1.2 CM. after running it like an hour it has found 200 WiFi APs but not a single Cell.

**Comment by Djfe** [comment]
OK so #178 definitely hasn't been fixed/implemented, yet.

**Comment by illarionov** [comment]
This should work as a normal phone with a single SIM card. @hoseinit, can you test the original firmware?

**Comment by hoseinit** [comment]
I'm afraid not, I'm new to this firmware due to the speed and CPU overclock. So I will keep using it for a while. So, I think I may contribute to some other open-source projects. I wish I could help this brilliant idea

**Comment by illarionov** [comment]
Then you may try simply to reboot the phone or temporarily disable CPU overclock.
Are you sure that the radio layer works and you can receive incoming telephone calls?

**Comment by Djfe** [comment]
Just found this:
https://code.google.com/p/android/issues/detail?id=43467
I was searching for alternative apps you could test your cell "connection" with and found an app called "cell map" which described an Android issue concerning the 3g connection (link above)

Does it work for you with 2g cell networks at least?
