### ISSUE TITLE
Minor bug -> scan always

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#517]
#493 works nice but due to #492 visible aps only shows: "0 (Wi-Fi disabled)

The checkbox in the settings is checked (system settings+mozstumbler settings) and the scanned number climbs up as well

Another bug: visible aps shows nothing since #492
While it used to show us "0" in default state (scanned aps shows "0" for example)

**Comment by illarionov** [comment]
Have you tried to restart scanning after changing the settings?

**Comment by Djfe** [comment]
Oh you are right. Haven't thought about that. 
It seems to be the case that the setting isn't applied during scanning but only once at the start.
-> disabling "scan always" during scan with wifi off leads to Mozstumbler still recognizing all wifis until I restart the scan.

The second bug is still existent though.
At application start it shows "" (-> nothing) instead of 0

**Comment by Djfe** [comment]
Another bug regarding this:
MozStumbler doesn't recognize it if the setting "allow scan always" in the system is turned off but turned on in the app.
-> 0 is shown

The same behaviour appears if a hotspot is turned on -> wifi is turned off system-wide (at least in kitkat) but the app doesn't get wifi access despite the setting "allow scan always" is turned on in the system settings (maybe #380 can be fixed together with this)

**Comment by Djfe** [comment]
Switching to airplane mode isn't recognized as well

**Comment by Djfe** [comment]
The user should be informed somehow that he needs to check the option in the system settings to allow mozstumbler to scan for Wifi Aps without the wifi being turned on
Can we open the settings in the same way we do it for the GPS alert?
