### ISSUE TITLE
Unable to use gps

### ISSUE THREAD

**Issue by stefan171** [mozilla/MozStumbler#524]
Just got a new phone: hkphone revo max8 Android 4.2.2

All stats are visible... Gps will report x amount of Gps visible yet none will be used. 

I have given the app permission to use my location. 

Cheers

**Comment by tamcap** [comment]
Could you provide us with a logcat, please?

**Comment by Djfe** [comment]
What happens if you use other GPS applications?
For example:
https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2
and if it works with this app, what happens if you switch to MozStumbler and start scanning after you had a working gps connection established?

**Comment by stefan171** [comment]
I downloaded and tried gps status. I presume the fix/sats is what we need to look at. 

It appears to say I have 20 existing sats in my location yet no fix says. 
So something is preventing apps on my phone to fix on to sats....?? 

Do you know how I can resolve this?

**Comment by stefan171** [comment]
I don't know how to provide the logcat, please let me know how I can do this

**Comment by stefan171** [comment]
Oh just to add, any apps using my gps location like Facebook or google maps appears to work fine.

**Comment by Djfe** [comment]
Maybe this helps:
http://diendan.hkphone.com.vn/forum.php?mod=viewthread&tid=53328

(searched for your device name + GPS fix/issues; the page I found seems to be Vietnamese and Google translate gives me not a good translation so I cannot say more about it; maybe you will find a solution on your own searching for issues regarding the GPS on your device)

**Comment by stefan171** [comment]
Sorry for the late response. the post you linked says on a different hkphone model you need to pay 50 cents a month to access the gps. 

For the phone I'm using, it seems the gps issue is common, most blame the mtk chip set, I think the rom is responsible. 

So this issue has nothing to do with the mozstumbler application
