### ISSUE TITLE
intelligent battery saving mode for walking and other slow moving

### ISSUE THREAD

**Issue by AdamHauner** [mozilla/MozStumbler#542]
When I take phone to outdoor trip, MozStumbler exhausts battery in several hours and in fact on just several kilometers. I have to stop MozStumbler to have some battery life for possible emergency call.

I don't know what is scanning frequency (time between two tests of available cells and wi-fi AP), but I assume that is pretty high, say about one test to several tests per one second. But when I'm walking, coordinates change for every cca 10 meters and cca 7 seconds. (Furthermore, in nature is pretty low chance to get new cell or wi-fi with every step you make.) 

So I propose to add detection of slow moving, for example averaging time between 10 last coordinate changes, and when slow moving is detected, increase interval between testing for example to a half or a third of averaged time. Of course, it have to be able to detect an end of slow moving and restore normal interval / high frequency (for example when user get on car and drive off).

**Comment by Djfe** [comment]
The idea has been brought up in #261 already.
The developers tried to use the library by Google which was part of the Google Play Store.
But there were two issues:
1st it wouldn't work on devices without the Google play store.
2nd there were issues and it didn't work properly
So the developers decided to make there own library in #333.
Since then nothing happened because other features were introduced.

**Comment by Djfe** [comment]
Two of those features are:
Upload only on Wifi, which stops mozstumbler from uploading data constantly over a mobile network.
A simple database which allows you to upload data later on, so that you can close mozstumbler in between and restart your device.

**Comment by AdamHauner** [comment]
Thank you for your comments. I notice #261 some time ago, but I didn't read comments about position detection change, I'm sorry.

Approach in #333 is based on accelerometer and rotation etc., so it could be very good for example for time when phone is sitting on the table for several hours.

I suggest simple algorithm using already collected GPS data, but I'm not sure, what is price/time of  shutting down GPS and starting it again few seconds later.

According your second comment: I'm using upload only on wi-fi and of course database, but it's not enough to maintain all day life of battery =( Maybe it's time to buy second one, but I think that every cut in battery consumption is great.

**Comment by Djfe** [comment]
Well, uploading is definitely not one of the most consuming parts of the usage of Mozstumbler, but it was one of the easiest things to do to reduce the energy usage.

As you can see in the paper I linked in #333 there is a lot we could do to reduce energy usage drastically. (by far not completely, especially when the device is moving, but in a way that you could let it run/scan throughout an average day without the need to turn it off manually if you are not moving around)

I don't think that it would be really practically to disable the gps as it can take some time to reactivate it. We could provide several profiles:
1. High energy usage: ignore movement library and concentrate on scanning (good for long drives (highway) without breaks), could be the standard profile if the device is charging (car charging cable)
2. Middle energy usage: doesn't disable GPS but disables scanning completely without movement to reduce heavy cpu usage and wifi scanning, this could be coupled with a less higher scanning interval -> every 2 seconds one scan (debatable if useful), could be default profile if the device runs on battery
3. Low energy usage: disables GPS when standing still for a certain amount of time. long scanning intervals -> every 5 seconds, gps gets reactivated if moving long enough, tries to avoid cpu wake locks by scanning for movement every (few) minutes, could be default profile if battery status below 15%

this where just some ideas what we could do to reduce energy usage but they would always go against accuracy:
other apps may use less energy but tend to report less wifis and cells especially when driving fast
so we have to find a middle and I think profiles are a good way to let the user decide what he/she wants to have
we could make the profiles even configurable and let the users set certain intervals for scanning etc. and give them advices.

**Comment by garvankeeley** [comment]
#1270 improves this significantly. Closing as I think #1284 is the next step in solving battery consumption, but if there is more actionable items from this bug we should split them out.
