### ISSUE TITLE
Blacklist code should support regular expressions

### ISSUE THREAD

**Issue by JensErat** [mozilla/MozStumbler#551]
The blacklist code for SSIDs should support regular expressions, and prefix/postfix SSIDs should be deprecated (eg. by requiring `^foo$` for new SSIDs, and slowly migrating the old ones as soon as somebody can make a statement about them).

This is important for this imaginary example (which I acutally observed in Norway, sadly I don't know any more which company it was):
- imaginary bus company "Southern Express"
- on-bus SSID `southernexpress042`
- terminal SSID `southernexpress`

We do not want to record the on-bus WIFI, thus will exclude it using `southernexpress` as pattern. Yet we _would_ want to record the terminal SSID, which gets excluded by the (too generic) prefix. The solution would be to use something like `^southernexpress[[:digit:]]{3}$` and `^southernexpress$`.

Changing the code to match regular expressions wouldn't harm the old strings, as `southernexpress` still matches `southernexpress042`.

It might also be reasonable to remove the actual blacklist from the code to some XML or JSON file, and precompile the regex matcher when reading the list, maybe even construct one large regular expression from all elements by concatenating them (`(^southernexpress[[:digit:]]{3}$|^NSB_INTERACTIVE$|...)`). This would both reduce overhead in managing and evaluating against the list.

**Comment by Djfe** [comment]
@garvankeeley fixed long ago already, I think

**Comment by garvankeeley** [comment]
I would like this also. There is a closed non-merged PR for a partial fix for this if someone wants to continue looking at it.

**Comment by cascheberg** [comment]
This can be closed as the wifi blocklist was dropped in #1418
