### ISSUE TITLE
Manual upload only of data

### ISSUE THREAD

**Issue by grrrrr** [mozilla/MozStumbler#559]
Can it be possible to have a new feature that does upload of data only when it is manually selected.

**Comment by garvankeeley** [comment]
Why/how would you use this? 
I am guessing this is for if you have selected upload only on WiFi, and you decide you want to do an upload when connected to cellular data network.

**Comment by grrrrr** [comment]
This would be one use, I also would life to visually review the numbers that would be uploaded.  This is not always possible at the moment.  By the time I get to wifi and look at phone data has already been uploaded

**Comment by tamcap** [comment]
@garvankeeley this is already possible. If you run MozStumbler in the "upload only on WiFi" mode and trigger upload manually by pressing the button, it will upload even on the cell network

**Comment by grrrrr** [comment]
@tamcap yes though I want to do this wifi when "upload only on wifi" is selected

**Comment by goldfndr** [comment]
What I've been doing to work around this is stop+exit when I get near my home AP (in the geofencing area, when numbers aren't changing anyway). But now, although running again with Wi-Fi toggled off and choosing Upload Observations reveals the In queue numbers, MozStumbler seems to be in a stuck state even after toggling Wi-Fi back on.

Ah, a while later, it is going through. I wish there was more detail, perhaps compressing stage vs upload stage, but that's probably better addressed at #518.

I'm guessing that one could alternatively disable Syncing services.

**Comment by grrrrr** [comment]
@goldfndr thanks for the suggestion.  This is not always possible as the phone may be in a bag on my back, so not quick to get to and I have to remember to stop and take it out
