### ISSUE TITLE
Not working in LG G2 Android Phone

### ISSUE THREAD

**Issue by ebarrun** [mozilla/MozStumbler#560]
The app can scan but the data are not sent having this settings and details on the phone.

![mozstumbler1](https://cloud.githubusercontent.com/assets/1598286/2826062/20397e8c-cf64-11e3-9c8d-386227f806c9.jpg)
![mozstumbler2](https://cloud.githubusercontent.com/assets/1598286/2826061/2034e322-cf64-11e3-86c2-f08a841d1dee.jpg)
![mozstumbler3](https://cloud.githubusercontent.com/assets/1598286/2826065/205e18dc-cf64-11e3-8184-ffb85bc5f2d8.jpg)
![mozstumbler4](https://cloud.githubusercontent.com/assets/1598286/2826066/20697312-cf64-11e3-8e5d-d4d8f8421728.jpg)
![mozstumbler5](https://cloud.githubusercontent.com/assets/1598286/2826064/20407570-cf64-11e3-9bd6-facc5ffb4ff7.jpg)
![version](https://cloud.githubusercontent.com/assets/1598286/2826063/203e2b94-cf64-11e3-9c56-691859bc22f0.jpg)

**Comment by tamcap** [comment]
Hey, thanks for reporting the problem. We try to make it work on all devices, but sometimes issues happen. Would you be able to capture the logcat using adb on your computer and share it with us?

**Comment by Djfe** [comment]
According to your Screenshots I guess you need to wait a little longer until you get a working GPS fix
Go outside (under the open sky!), maybe walk around a bit

You have a working GPS connection when last position/location doesn't show "-" anymore but lat/lon coordinates ;)

There are external apps like GPS status that can give you more detailed information about your GPS receiver ;)

**Comment by tamcap** [comment]
15/23 should give him a GPS coordinate pair within a second or two. I am
not sure that's it!

**Comment by Djfe** [comment]
could be a device issue, I'm experiencing similar things sometimes
but the numbers were never this big

the reason that the app isn't uploading though is that there is no data to upload as long as the device has no working gps connection -> the app links the presence of certain wifis and cells and their signal strengthes to gps coordinates
and if it doesn't receive gps coordinates it cannot upload anything as it doesn't make sense to just collect wifi or cell ids without a general location

@ebarrun does this app get a working gps position?:
https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=de
in any case take a screenshot of the app

it would be even more helpful though to get a logcat as tamcap already stated

**Comment by tamcap** [comment]
I noticed that in the screenshots the location services icon in the notification bar is grayed out. This suggests that for some reason your phone might not be reporting the location correctly.

**Comment by garvankeeley** [comment]
Closing, further action on this bug is unlikely
