### ISSUE TITLE
Search API change

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#574]
Do we need to change something in our search request?
There was a small API change regarding the server's respond to requests without an api key:
mozilla/ichnaea#183

The server returns now a JSON blob instead of an  http error: not found.

**Comment by hannosch** [comment]
@Djfe thx for bringing this up.

In short: No code change to MozStumbler is required.

Long version:

The only server side change was related to API key handling. MozStumbler is submitting an API key for both the search and submit APIs for some time and it makes sure to always submit one.

The change that happened is related to the response in case no API key is provided and this shouldn't affect MozStumbler. So far the search API returned a 200 code with a not found message, exactly the same as if everything went fine, but no result could be found.

Now you get a 400 error with a JSON blob stating that you specified no / an invalid API key (http://mozilla-ichnaea.readthedocs.org/en/latest/api/index.html#api-access-keys). This makes it possible to distinguish between the "no data" and "no / invalid key" scenarios.

The search API (and the geolocate API unused in MozStumbler) will also check the key against a list of currently a dozen known API keys.

The submit API still takes data without an API key, as the code inside Fennec hasn't been updated yet to send a key along and we don't want to loose those data submissions.
