### ISSUE TITLE
Pull SSID blocklist from web

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#581]
We should pull the blocklist from github. Periodically update based on connection preference for uploading data: wifi-only or wifi and cell.

The Updater.java has most of the code we need for doing this.

**Comment by hannosch** [comment]
Great idea. Could you make sure the blocklist is in a simple data format? Ideally the blocklist could be re-used by different implementations, like geoclue or FxStumbler in the future. First step is making sure the file is in a simple general format.

I think @cpeterso also wanted to pull out the list into its own repository, so it can be versioned / updated independently of MozStumbler.

**Comment by garvankeeley** [comment]
Could be a json array, with regex elements (my preference).

{
“ssid_blocklist": 
[
{ "pattern":"._i[Pp]hone$", "info":"Ad-hoc iphone networks" }, 
{ "pattern":".__nomap$" , "info":“Standard identifier to request SSID is ignored by scanners" }
]
}

Or, with no regex, it should specify if it is a prefix, suffix, and if it is case-sensitive. 
Or could just be newline-separated file, with a # for comment lines. 
Any preference?

**Comment by garvankeeley** [comment]
Implementation:
- have the Blocklist as a JSON file as suggested above
- parse this file to build the Blocklist logic
- update the list: when we upload data, do a separate request to a github page where the Blocklist sits, if newer, grab it

**Comment by garvankeeley** [comment]
openSourcer: since we will need a default block list, I would put the file in res/blocklists, so we can distribute the current list with the app. 
The plan is to update this file periodically of course, but if there is any problem with getting a block list the app can fallback to using the built-in block list. 
When looking for updates to the file it will look in github, in res/blocklists. Perhaps github has a way to query file dates using the REST interface, and if the date is newer, grab the new file.

**Comment by garvankeeley** [comment]
Another consideration is how the service will use it, without the client. The service is pure .java files for use in Firefox for Android. We could have a default version of this file in service/blocklist, like DefaultBlockList.java, that file would just have a string:
public static final String defaultListJSON = "{\"ssid_blocklist\":[" +
"{ \"pattern\":\"^AndroidAP._\" , \"info\":\"Mobile devices\" }," +
"{ \"pattern\":\"^(Android)| Hotspot._\" , \"info\":\"Mobile devices\" }," +
"{ \"pattern\":\"^barnacle.*\" , \"info\":\"Android tether app\" }," + etc.

This list could be a minimal list, the most important item is the _nomap.

**Comment by anishgkanchan** [comment]
I could not find any direct way to get the last update date of a file. I however found a way by which we could make out if the file was recently updated-
On directly making a search request for the file (https://api.github.com/repos/anishgkanchan/MozStumbler/contents/BlockList.txt), the size of the file is returned. So if this changes, we could update our list. But we would have to store the previous size in the app somehow to compare with the new size.

**Comment by garvankeeley** [comment]
Sorry to lead you wrong, I thought for sure an API for a version control system, would give you the _version_ of the file! That is pain. I haven't looked at the API, I am trying to think what else might be useful. Surely it would give back the SHA of a file, that at least tells you the files don't match.

**Comment by anishgkanchan** [comment]
I did check the SHA. Everytime we commit, a new SHA is generated. The API provides a list of all the commits made and from that we can attempt to search a commit for the required file. But that too is very tedious.

**Comment by garvankeeley** [comment]
https://api.github.com/repos/mozilla/MozStumbler/git/trees/master
lists the SHAs at the top level, that might be useful. We can put the blocklist.json file there so it is easy to access with the API

**Comment by anishgkanchan** [comment]
But what next should I do with that? The urls listed again give only the size of the respective module. The date is not provided.

**Comment by garvankeeley** [comment]
Could the SHA be used to track whether the file has changed?

**Comment by anishgkanchan** [comment]
I haven't found any way.

**Comment by garvankeeley** [comment]
Maybe check if the the SHA of the github blocklist is not equal to the SHA of the local blocklist?
If not equal, download the new one, save it's SHA in the prefs

**Comment by anishgkanchan** [comment]
I have a doubt in shared preferences. If we hard code in the app the initial value of the SHA in the prefs, will that not override whenever we try to update the SHA with the value of the latest Blocklist?
Or is there any other way by which the initial value of the prefs can be set?

**Comment by anishgkanchan** [comment]
Can we just not have name-value pair for sha in the json form alongside the block list in BlockList.java itself?
That way we can initialize the default value as well and update it whenever required.

**Comment by garvankeeley** [comment]
I see it working like this: we have a DefaultBlockList.java with a json string that is built in.
First time the app checks for an updated list, there is no list, so it downloads the github block list, saves its SHA in prefs.
Then, checking for updates it compares the prefs SHA to the github SHA, if different, grab the github file and save the SHA in prefs.

**Comment by anishgkanchan** [comment]
All the network-based code that I have written will be called from AsyncUploader on a separate thread. So I dont need to put my code again in an async task, right?

**Comment by garvankeeley** [comment]
correct

**Comment by anishgkanchan** [comment]
I still dont get the need of Prefs.getInstance(). I just needed the context for the getDefaultSharedPreferences(context) method.
I used getInstrumentation().getContext() in the test class and passed this context as a parameter while instantiating the BlockListDownloader class. This time no errors were generated.
I am not sure though if this is a approach.

**Comment by garvankeeley** [comment]
Compiles and runs ok, this is good, the BlockListDownloader should not extend Activity but will still need an instance of Prefs, that is why it needs Prefs.getInstance() to access the global prefs instance. All the code accesses the prefs by calling Prefs.getInstance(), you can search for examples of its usage.

**Comment by anishgkanchan** [comment]
I tested the new files properly. The new list is getting downloaded and saved a new directory. Currently the BlockList is getting downloaded from my forked project as currently there is no BlockList.txt in the main project. I'll make a pull request now.

**Comment by anishgkanchan** [comment]
I had pulled a request. A comment was made there to update the download link. I have done it. Yet theTravis CI build failed. I don't know what other changes will have to be made. Please guide.

**Comment by tamcap** [comment]
The only comment I have is to possibly redactor this to use AbstractCommunicator to keep code cleaner.

**Comment by Djfe** [comment]
Would it make sense to compress the json string using gzip?

**Comment by cpeterso** [comment]
I don't think this feature is worth the effort. The SSID blocklist is embedded in MozStumbler and we can easily push new MozStumbler updates. I think a more useful feature would be to allow power users to override or augment the embedded SSID blocklist with a text file on /sdcard. I filed issue #664 for that feature.

**Comment by Djfe** [comment]
I'm even unsure why there is such a blocklist (clientside)?
Is it embedded to save bandwidth?

We could better have such a list on ichnaea or just let the moving wifi algorithms detect it.

If the list is used on Ichnaea then all other services will take advantage of it as well.

**Comment by cpeterso** [comment]
@Djfe:  As you point out, the SSID blocklist is not strictly necessary. The server already detects APs that move (i.e. are reported in multiple locations). The stumbler's SSID blocklist reduces the amount of detection work the server has to do (because the stumbler has more information than the server, like SSIDs) and also reduces the amount of data its uploads.

**Comment by cpeterso** [comment]
I'm going to close this bug for now. I don't think this feature is worth the effort.
