### ISSUE TITLE
Discussion: web view for map

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#582]
Stumbler uses a MapView currently, instead use a WebView and have the map load from a website. The location should be changeable by the user in the app settings. This makes it easier to contribute to look and feel improvements, to try different approaches, and reduce the code in the app. Hopefully we can share the map with the services team. 

Need to specify the javascript interface the page must implement, i.e.:
showGpsPosition(lat, lng, radiusInMeters)
showGeofencing(lat1, lng1, radiusInMeters)

There are requests for more things to show on the map, these can be handled by adding more calls to the js interface.

Ideally, there can be a more interactive mapview, such as geofencing circles being set on the page, and again this would be a javascript hook to pass the geometry back to the stumbler app.

**Comment by Djfe** [comment]
Would the webview cache tiles on the sdcard like osmdroid? -> offline map

**Comment by garvankeeley** [comment]
Interesting, I didn't know we were doing that, when I have viewed the the map activity with no internet I just see an empty grid.  

By branch might be missing some fixes from master, I need to check that.

**Comment by Djfe** [comment]
Actually it is a side effect of osmdroid:
It creates a cache folder on your device's sdcard
So if you have looked up a location already, it will show the tiles it has loaded back then

One disadvantage:
The osm map won't change too much but the MLS tiles will do -> the MLS coverage overlay won't be updated on a daily basis but on something like a weekly one

So if we can cache the osm maps (but not the MLS tiles) for a certain area permanently->10km around the device's position, that would be nice

Also I'm not too sure about the web view thing itself:
1. Web view is not as performant as a native map library
2. We use a different map than the online coverage map -> it is more detailed: Street names, parks, lakes etc. are visible on the map

**Comment by Djfe** [comment]
I have listed the caching issue already #463
But I closed the issue again because I wasn't sure if the issue still exists.
Now I know it still exists. The proof I found was osmdroid folder on my sdcard containing cache tiles -> not only OSM but also MLS tiles

**Comment by Djfe** [comment]
Another reason why I wouldn't like to implement the map using webview:
https://groups.google.com/forum/#!topic/mozilla.dev.geolocation/82l40531a5w

We could use the map as our maininterface later on:
![screenshot_2014_02_13_17_34_55](https://cloud.githubusercontent.com/assets/5685512/2950258/a038d3c6-da18-11e3-8dc2-e1dd84d6a9c4.png)

It would be updated at a certain interval and show the user's location, direction, the location of Wifi APs and Cell towers around him (estimated locations) and the locations where data has been collected already (covered locations based on data which would be kept in the database even  after uploading.

**Comment by garvankeeley** [comment]
I saw this, fully agree with your design idea. The stumbler is a map application at heart, it should be map view based.
That said, what I see here could well be an online map. I understand you are saying there is caching involved in this, I haven't looked into the osmdroid caching mechanism, so if you can give me an idea of what you envision the caching mechanism would be that would be helpful. 
I could see if you start the app on wifi, we could grab a bunch of tiles at all the required zoom levels for your position, within a radius of 50 km or something. Might be a heavy download though. I saw a mention in an older thread about being explicit to the user about grabbing an offline map (maybe the user starts that action).

**Comment by Djfe** [comment]
Yes, something like that would be nice to have (cache tiles 50km around current location)

I did something similar for my app osmand:
It uses SVGs from OpenStreetMap and is a navigation app. It allows you to predownload all vector graphics for specified regions (countries, etc.) to be able to use it offline.
If you don't use the predownload feature it will download tiles from the osm server while driving using the mobile network (which can cause u wanted costs)

As @tamcap is currently working on enhancing the map, we should definitely wait for his opinion on this.

**Comment by garvankeeley** [comment]
I love OsmAnd! I have used the voice guidance many times.

**Comment by garvankeeley** [comment]
The current map view is now functional, so we don't need this for 1.0. In future may still be an option

**Comment by Djfe** [comment]
@garvankeeley is this still on your (road) map? (pun intended :D)

**Comment by garvankeeley** [comment]
We invested the time to customize OSMDroid to work for our needs, so we don't need this anymore.
