### ISSUE TITLE
Investigate battery consumption of Wifi and Cell scans

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#584]
As part of the service refactor for use in Firefox for mobile, the service will have a PASSIVE_PROVIDER mode where it no longer polls the GPS; it will wait until other apps have requested a GPS location. This should remove concerns about the battery consumption of the GPS. However, it will still perform cell and wifi scans, and the battery cost of these is not clear.

To investigate this, I added a battery drain test available through the options menu. 
https://github.com/garvankeeley/MozStumbler/tree/battery_test

It cycles through scanning cell, wifi, and sitting idle, and reports the consumption of each. 
The big limitation I find is that the OS only reports drops of 1% increments. To speed up getting test results, I run with the screen brightness at 100% and screen lock off. 

The next thing to look at is the results in the lock state, doing scans farther apart than 1sec as they are now. What my tests are not showing is the effect of scanning the cell and wifi when these services are in more of an idle state. What I would expect to see is higher cost as these services start up, or move to an active state. I suspect that consecutive scans of the cell and wifi have minimal cost after the first query, as the services are active at that point.

Here is a sample output of a test run, on the left is the time it took to drop 1%:
Tests drain of 3 states: cell scan, wifi scan, then idle. Repeats indefinitely. Reports results on each battery drop of 1%.
3.4.0-gadb2201|19|hammerhead|Nexus 5
240.1s WiFi Scans:0 Cell Scans:240 Mode:Cell
73.6s WiFi Scans:18 Cell Scans:0 Mode:WiFi
258.8s WiFi Scans:0 Cell Scans:0 Mode:Idle
236.2s WiFi Scans:0 Cell Scans:236 Mode:Cell
130.5s WiFi Scans:32 Cell Scans:0 Mode:WiFi
294.4s WiFi Scans:0 Cell Scans:0 Mode:Idle
142.6s WiFi Scans:0 Cell Scans:143 Mode:Cell
123.1s WiFi Scans:30 Cell Scans:0 Mode:WiFi
286.8s WiFi Scans:0 Cell Scans:0 Mode:Idle
139.7s WiFi Scans:0 Cell Scans:140 Mode:Cell
214.7s WiFi Scans:53 Cell Scans:0 Mode:WiFi
124.0s WiFi Scans:0 Cell Scans:0 Mode:Idle
245.2s WiFi Scans:0 Cell Scans:245 Mode:Cell
105.3s WiFi Scans:26 Cell Scans:0 Mode:WiFi
248.0s WiFi Scans:0 Cell Scans:0 Mode:Idle
162.3s WiFi Scans:0 Cell Scans:162 Mode:Cell
173.8s WiFi Scans:43 Cell Scans:1 Mode:WiFi
265.8s WiFi Scans:0 Cell Scans:0 Mode:Idle
232.7s WiFi Scans:0 Cell Scans:233 Mode:Cell
205.0s WiFi Scans:51 Cell Scans:0 Mode:WiFi
299.1s WiFi Scans:0 Cell Scans:0 Mode:Idle
247.6s WiFi Scans:0 Cell Scans:248 Mode:Cell
235.8s WiFi Scans:59 Cell Scans:0 Mode:WiFi
178.1s WiFi Scans:0 Cell Scans:0 Mode:Idle

**Comment by garvankeeley** [comment]
Results in a spreadsheet:
https://docs.google.com/spreadsheets/d/1S5WSpYZIH-NgcLSvmTvCaJaJjUNqqQCyMAVpB923LPk/edit?usp=sharing

I calculated the battery drain of constantly calling into these scanning services as:
Wifi 55% increase
Cell 19% increase

**Comment by eggpi** [comment]
Interesting experiments! A few thoughts, feel free to refute whatever doesn't look reasonable:
- Do we currently have battery usage statistics for Fennec? It would be interesting to see how its current results compare to your findings, and let's keep in mind that we ultimately want to gauge the difference between Fennec with no scanning vs. Fennec with scanning, not just scanning vs. not scanning. What I mean by this is that it just may turn out that Fennec's consumption dwarfs ours, even when it's not scanning, but this is really just a guess on my part.
- I'd be interested in also seeing results in which the phone is idle. Given that the screen is usually the biggest factor in battery consumption, I'm a little worried that keeping it on could introduce noise in the measurements, so maybe having it off could accentuate the differences we're trying to observe.
- If we adopt the suggestion of "burst" stumbling for a few minutes after getting a passive location, we may not even need to be scanning cells/wifi in the background at all times: we could perhaps get away with only starting such scans after getting a passive location, too. If this sounds reasonable to you, it could be worth doing tests to get a notion of the battery impact of that approach as well.
- It would be cool to apply a statistical test to this data, just so we're doubly-sure we're observing significant difference in power consumption under the test conditions. Something like a [Mann-Whitney](https://en.wikipedia.org/wiki/Mann-Whitney-Wilcoxon_test) test, if my statistics knowledge doesn't fail me (and it most certainly does!).

**Comment by garvankeeley** [comment]
> I'd be interested in also seeing results in which the phone is idle. Given that the screen is usually the biggest factor in battery consumption, I'm a little worried that keeping it on could introduce noise in the measurements, so maybe having it off could accentuate the differences we're trying to observe.
> 
> With the phone asleep, I found it was taking an hour between battery ticks, so it isn't a test for the impatient! I would say the screen adds a noise factor that is nearly constant, if kept at the same brightness on a single activity screen. More noise would happen while the phone is idle for an hour, and during a particular hour something in the system runs. I still want some sleep results though. 
> For apps that use the GPS, I wonder if many do GPS location during sleep. I would think running apps and the like that do tracking would do this, but not many others. 
> 
> If we adopt the suggestion of "burst" stumbling for a few minutes after getting a passive location, we may not even need to be scanning cells/wifi in the background at all times: we could perhaps get away with only starting such scans after getting a passive location, too. If this sounds reasonable to you, it could be worth doing tests to get a notion of the battery impact of that approach as well.
> 
> In the real Fennec service, it won't be scanning like I did in this test in a typical scenario. Actually, maybe it could be, if the user has a mapping app open for a long period, and it is getting a GPS at 1Hz,  that would match the scanning rate I did in the test.
> It would be cool to apply a statistical test to this data, just so we're doubly-sure we're observing significant difference in power consumption under the test conditions. Something like a Mann-Whitney test, if my statistics knowledge doesn't fail me (and it most certainly does!).
> 
> To get more data I will start with putting up an APK for more people to test with, a single 10-15 minute test run would be very helpful. My wife has a Nexus 4 I'll test with at some point this weekend.

**Comment by Djfe** [comment]
similar issues:
#542 #471 #356 #333 #261
an interesting paper about battery saving while stumbling: https://www.cs.cmu.edu/afs/cs.cmu.edu/Web/People/ishafer/pubs/localization-mswim10.pdf

What should be done as well:
1. Scan for wifi/cells only with a working gps connection
2. Split up the test map scanning and normal scanning to be able to use the test map without a working gps connection even with 1.
3. Launch/scan automatically when GPS is in use
4. There are a lot more ideas to improve battery usage in the issues above.
5. The paper linked above is really really useful as it is exactly about what we want to achieve here.

Like @guilherme-pg I think we should disable the screen while analyzing the battery consumption.

**Comment by garvankeeley** [comment]
Running in sleep mode for 12 hours:

3.4.0-gadb2201|19|hammerhead|Nexus 5
2292.7s WiFi Scans:0 Cell Scans:154 Mode:Cell
3334.2s WiFi Scans:136 Cell Scans:0 Mode:WiFi
14048.0s WiFi Scans:0 Cell Scans:0 Mode:Idle
10295.9s WiFi Scans:0 Cell Scans:272 Mode:Cell
5917.8s WiFi Scans:162 Cell Scans:0 Mode:WiFi
9918.2s WiFi Scans:0 Cell Scans:0 Mode:Idle

**Comment by garvankeeley** [comment]
Thanks for the feedback, there are requests for additional low and moderate power modes in the stumbler, which would help with a number of those issues. The immediate need is for the very low power mode for Fennec (Firefox Android). But additional power modes shouldn't be a problem to add after that (unless someone wants to take a crack at it). The motion detection is a very interesting possibility, however, Fennec's low power stumbling will initially not have that. However, Hanno has some ideas for additional heuristics to improve our scanning, for example if the GPS reported speed is above a certain threshold, don't scan for wifi.

**Comment by illarionov** [comment]
Wi-Fi scan-only mode (scan APs even when Wi-Fi is turned off), subjectively, greatly reduce power usage. I always turn Wi-Fi off now when scanning.

**Comment by garvankeeley** [comment]
I wouldn't have expected that, good to know. You find that even when not connected to wifi, having wifi on costs more battery than just wifi scanning? I would have assumed that having wifi on, and not connected, would just be performing wifi scans.

**Comment by Djfe** [comment]
@illarionov I have a question about that:
Is Mozstumbler still able to scan for Wifi networks at the same interval if I disable Wifi but use this option? Or is it reporting less Wifi networks then?

**Comment by VolMi** [comment]
@Djfe I take the freedom to respond to that: I also disable Wifi when scanning, since I "felt" the same about battery consumption. And yes, there is no drawback, as the same number of APs is reported at the same scanning frequency.
