### ISSUE TITLE
0.20 generates big data file and crashes when trying to upload data

### ISSUE THREAD

**Issue by gpoo** [mozilla/MozStumbler#591]
I had a long trip and I took collect more data.  It worked relatively fine for the first ~2000 data reports. 

Disclaimer: My Internet connection is quite bad at this moment, so I have not  been able to search properly. So, please bear with me.

At some point I got a notification of low internal space.  I had left ~20 MB.  I cleared data from some applications (like Firefox), I made ~60 MB.  MozStumbler had around 16MB, considering the history of thousands reports it should have been more than enough.

After I while I noticed that MozStumbler stopped silently to collect data. I re-started every time.  That is, until I noticed I had ~1900 pending reports and I tried to upload it manually and it crashed.

So, I enabled to upload only on WiFi and MozStumbler started to collect data continuously again. Until again I was running out of space.  This was is bad sympton, but I uninstalled several other applications to make space and continue tracking.

Long story short: MozStumbler whent from 16MB to 106MB of data in less than one day. I ran out of space and I don't know how to extract manually to inspect it.  I have 4700 observations that can't be uploaded because MozStumbler crashes.

I wish MozStumbler could store the data in the SD, like I can do with other applications.

For context: I have a Nexus 1 with Cynamodgen. I used the file manager to locate a file, with no luck.  And no luck by grepping in the source code.

In short, there are 3 problems:
- Crash when uploading a file (maybe the data storage got corrupted at some point)
- Big increase of the data file between 0.19 and 0.20 (I hardly believe it could have collected 3 times (or more) data than I had done in months)
- No possibility to store the data in an external storage where to back it up (maybe I am missing something).

**Comment by gpoo** [comment]
I noticed that the number of wiki access points is exceptionally high.

For the ~4700 observations I mentioned, there were more than 1,975,000 wifi access points.  So, I continued removing applications to make more space, and I collected again data while commuting.

The number of obvservations in the queue became 6150, with 88,765 cells and 2,251,711 wi-fi access points.  And finally, MozStumbler filled the storage in ~30 minutes. Now the data used by MozStumbler is 122MB.

While capturing data, the number of wi-fi access points scanned started to increasing slowly, in the order of dozens to hundreds. I got distracted for 10 or 20 minutes, and when I checked the summary in the upload, it has increased in more than 150,000.

My guess is that per every new data point, the whole set of data is being added as a new data. That could explain the exponential growth of data.  The place where this happened is not very populated.  And still, collecting almost 2 millions of wifi-access points in half day in Vancouver is not reasonable, and 1/4 million in between Sidney and Victoria in 30 minutes, seems quite strange, to say the least.

**Comment by gpoo** [comment]
I cannot downgrade, because it requires me to free space, likely the same to save the data.  I made around 10MB, and it was not enough :-/

**Comment by VolMi** [comment]
I also had a small trip yesterday and MozStumbler made it to >200MB data. It saved >3Mio wifi APs and the observations were about 10^5, I think where it should have been 10^3 at most.

The thing is that MozStumbler records all data from every tick (each 1s interval) as a new observation. You can see it when it's activated and you tap the upload button. You see your queue growing exuberantly there.

Hope there will be a bugfix release super soon. The ichnaea guys will probably also be pretty annoyed from the stumbler spam.

**Comment by tamcap** [comment]
I have a good idea what's causing the problem. Pushing bugfix in a few minutes, it might be a few extra hours before it's merged / new release.

**Comment by Djfe** [comment]
@gpoo for devices with low internal storage:
Try to use link2sd ;)
In the pro version you can even link data to another partition on your SD card

Maybe @hannosch should take a look at this to filter out duplicated data after this got fixed (at least I think that the reason is some sort of duplication)
