### ISSUE TITLE
Automatic update failing

### ISSUE THREAD

**Issue by sabas** [mozilla/MozStumbler#596]
I have Android 4.4.2 (Moto G), the app tells there's an update, I accept the installation, but it fails because the package has the same signature of a package already installed.
To update to 0.20.1 yesterday I had to remove and reinstall the app.
(also, the uninstall process should ask to preserve configuration?)

**Comment by Djfe** [comment]
I think, that 20.1 and 20.2 were failed releases
-> garvan accidentally messed up the version numbers
If you remove the app and install it again using the .apk from here:
http://github.com/mozilla/mozstumbler/releases
future updates should work fine ;)

**Comment by Djfe** [comment]
The changelog even says it ;) :
"Corrected signing key"

**Comment by sabas** [comment]
Sorry, I didn't came to releases because I were on the phone.. Reinstalled now!
For the `the uninstall process should ask to preserve configuration?`
I should open another issue?

**Comment by Djfe** [comment]
Probably better to open another issue instead and close this one, because the title(+description) would be missleading if you reuse this one.

**Comment by sabas** [comment]
Okay, done.

**Comment by garvankeeley** [comment]
Sorry guys for the build hassle. I have now set up an on-demand build machine on Amazon EC2 which automates the process.
