### ISSUE TITLE
Include an attributation for OSM (again)

### ISSUE THREAD

**Issue by porjo** [mozilla/MozStumbler#610]
Issue #239 dealt with this however I don't believe it went far enough. Currently there is just a link that reads _"Learn more about our mapping provider"_ which links to Mapbox, the supplier of the rendered tiles. The primary source of the raw map data is Openstreetmap and I think that deserves a specific mention on the about page, including a link to openstreetmap.org

**Comment by garvankeeley** [comment]
Thanks, we can certainly add the added attribution in the next release.

**Comment by Djfe** [comment]
@garvankeeley you should definitely do that before releasing the next version tomorrow ;)

**Comment by garvankeeley** [comment]
Will do thanks for the reminder

**Comment by Djfe** [comment]
Can be closed now. Has been introduced with 0.20.5 ;)

**Comment by porjo** [comment]
Thanks, that looks better :)
