### ISSUE TITLE
Consider mapbox SDK for map

### ISSUE THREAD

**Issue by hannosch** [mozilla/MozStumbler#620]
Mapbox has announced a new SDK based on osmdroid at https://www.mapbox.com/blog/android-sdk/ which claims various improvements.

It still supports specifying non-mapbox tile servers, so wouldn't lock us in to mapbox.

This might be interesting, if osmdroid gives us trouble or is not performant enough.

**Comment by Djfe** [comment]
Is this something different than #582?

**Comment by keverets** [comment]
Is the switch to mapbox necessary for 1.0, or just a conclusion to the discussion/investigation as to whether osmdroid will be sufficient?

**Comment by keverets** [comment]
FWIW, replacing with mapbox was fairly easy except that it doesn't yet support multiple tile layers, so the coverage display needs to not use tiles if a mapbox switch is to happen.  Right now, that means more work client-side to interpret the .png files and try to determine points/areas based on those.

**Comment by garvankeeley** [comment]
I think is just a question. Mapbox OSM is designed for max performance, but I am more interested in whether it fixes the rendering bugs. One big one is the 2nd tile layer, which it currently doesn't help us with.

**Comment by crankycoder** [comment]
I don't see any performance benefits using the latest map box demo on Android. 

The lack of layer support would cause mozstumbler to have problems. 

It's not clear at all that switching would solve any more problems than it would introduce.
