### ISSUE TITLE
Attach a scrollbar to the about page

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#621]
Since OSM is mentioned on the about page, the CC license at the bottom is cut off on my device.
I think it would make sense to define the page as scrollable.

**Comment by garvankeeley** [comment]
https://github.com/mozilla/MozStumbler/pull/644

**Comment by anishgkanchan** [comment]
I had pulled a request with the scrollbar added. However the Travis CI build failed. I deleted the branch both locally and remotely. Kindly guide me on what is to be done next.

**Comment by Djfe** [comment]
@garvankeeley this is fixed now so you can close it as well ;)
