### ISSUE TITLE
Make about page more consistent

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#622]
The link to the osm project has a different color than the one to mapbox and it is underlined.
This should be more consistent, I think.

Another thing:
Maybe we should mention the provider of our cards directly instead of only linking to their page. (the name "mapbox" should be mentioned in my opinion)

**Comment by Djfe** [comment]
Why isn't the osm string not available for translation btw.?
And why is the text and URL in a layout XML file instead of being in the about activity in the src folder like everything else?

The structure is definitely not consistent.

Other people who want to add something will be confused about this.

**Comment by garvankeeley** [comment]
Djfe, feel free to address these issues if you have time, thanks.

**Comment by pl6025** [comment]
I can do it if you confirm the syntax:
In res/layout/activity_about.xml
Line 34 android:text="Map view tiles © OpenStreetMap contributors\nhttp://www.openstreetmap.org "/>
--> android:text="@string/MapViewTiles"

In res/values/strings.xml 
Addition of:
<string name="MapViewTiles">Map view tiles © OpenStreetMap contributors\nhttp://www.openstreetmap.org </string>
