### ISSUE TITLE
Coalesce similar stumbling records

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#631]
Here is a short period of stumbling in-office.
https://drive.google.com/file/d/0B1sYPwjczMsQeVNTWjZNNnRvLXM/edit?usp=sharing

We see 70k of data that could be coalesced to a fraction of that size (<10k I would guess). Just repeated data over and over with slight variations in values. If you look at the second tab, you'll see the cell data sorted, there are only about 8 cell records. 

Need to check with services to get their opinion on how they would like this data aggregated (do we average ASUs?, if we have a 2nd cell scan that has LAC do we dispose the first?). 

Lat/Longs can be considered equal based on time and distance, scans within x minutes, within 5 meters, are the same point, use the higher accuracy position, and aggregate the scans.

**Comment by Gitschubser** [comment]
I have a question to the file.

"1","1403045268784","43.64802","-79.394373","133","23","gsm","[{""asu"":-80,""radio"":""umts"",""mnc"":720,""psc"":418,""mcc"":302},

In the line the value asu is -80.
ASU has only value from 0 to 31 or 99
The value -80 is measured in dBm!
In your api i think there is used the value "signal" for the value in dBm:

```
        "radio": "umts",
        "mcc": 123,
        "mnc": 123,
        "lac": 12345,
        "cid": 12345,
        "signal": -60
```

Another example:

"radio": "umts",
            "mcc": 123,
            "mnc": 123,
            "lac": 12345,
            "cid": 12345,
            "signal": -61,
            "asu": 26

asu =26 and signal=-61

Is this a failure in the stumbler app or in the database?

**Comment by garvankeeley** [comment]
Those values are what the stumbler is capturing

**Comment by Gitschubser** [comment]
I think there is a difference between the api and how the stumbler is capturing.

"signal": -61  value in dBm
"asu": 26       

At this link http://www.lte-anbieter.info/technik/asu.php 
you see in the table the difference between asu and signal.
The api is correct but the stumbler upload the value false?

**Comment by hannosch** [comment]
Indeed, signal is supposed to capture the dBm value. For GSM networks one can compute one from the other, for example as `(-61 - -113) / 2 == 26`. The formula is different for UMTS, CDMA and LTE. So the client shouldn't bother with this and just send either ASU or signal.

**Comment by illarionov** [comment]
Looks like that the location is reported every second, even if it has not changed. This is strange, since the constants `GPSScanner.GEO_MIN_UPDATE_TIME` and `GPSScanner.GEO_MIN_UPDATE_DISTANCE` should protect against such behavior.

**Comment by garvankeeley** [comment]
@illarionov good observation, I was actually running the test case code, so it is probably bypassing those guards. I'll take a look.

**Comment by garvankeeley** [comment]
Here is testing with min time and distance set: https://docs.google.com/spreadsheets/d/1Z9J2p28l0M7CpSHZPzDiMg7kW4ji3v7xv40pitcmErQ/edit?usp=sharing

**Comment by garvankeeley** [comment]
When we send a record like this for cell
{"asu":-70,"radio":"umts","mnc":720,"psc":418,"mcc":302},
missing the cellID, is that useful to ichneaea?

**Comment by garvankeeley** [comment]
Also we see empty cell and wifi entries in the db, that should be easy to fix.

**Comment by garvankeeley** [comment]
In passive stumbling mode we can set the collection as sparse as we need it to be so I'll close this. Not really a problem for active stumbling in MozStumbler.
