### ISSUE TITLE
Upload silently fails multiple times and the data is lost

### ISSUE THREAD

**Issue by DonTomika** [mozilla/MozStumbler#663]
I've been playing with MozStumbler in the past few days and collected about 4000 observations, from which about 1000 succeeded to upload, but the others failed and eventually got deleted. I did some experiments and it seems that uploading 4-5 observations always succeeds, but uploading more (like 100) fails most of the time, at least for me. After 3-4 retries, the data is deleted.

**Device:** HTC One SV (Android 4.2.2), using MozStumbler v0.20.5

**Network:** tried multiple Wi-Fi connections, and also cellular networks. Others apps that rely on the same connection are working fine.

**Related issues:** https://github.com/mozilla/MozStumbler/issues/546 and https://github.com/mozilla/MozStumbler/issues/651

**Logcat messages:**

```
06-29 18:53:26.781: E/org.mozilla.mozstumbler.communicator.AbstractCommunicator(6941): Couldn't compress and send data, falling back to plain-text: 
06-29 18:53:26.781: E/org.mozilla.mozstumbler.communicator.AbstractCommunicator(6941): org.mozilla.mozstumbler.communicator.AbstractCommunicator$HttpErrorException
06-29 18:53:26.781: E/org.mozilla.mozstumbler.communicator.AbstractCommunicator(6941):  at org.mozilla.mozstumbler.communicator.AbstractCommunicator.sendData(AbstractCommunicator.java:96)
06-29 18:53:26.781: E/org.mozilla.mozstumbler.communicator.AbstractCommunicator(6941):  at org.mozilla.mozstumbler.communicator.AbstractCommunicator.send(AbstractCommunicator.java:104)
06-29 18:53:26.781: E/org.mozilla.mozstumbler.communicator.AbstractCommunicator(6941):  at org.mozilla.mozstumbler.communicator.Submitter.cleanSend(Submitter.java:40)
06-29 18:53:26.781: E/org.mozilla.mozstumbler.communicator.AbstractCommunicator(6941):  at org.mozilla.mozstumbler.sync.SyncAdapter.onPerformSync(SyncAdapter.java:91)
06-29 18:53:26.781: E/org.mozilla.mozstumbler.communicator.AbstractCommunicator(6941):  at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)

06-29 18:53:27.992: E/org.mozilla.mozstumbler.communicator.Submitter(6941): Error submitting: 
06-29 18:53:27.992: E/org.mozilla.mozstumbler.communicator.Submitter(6941): org.mozilla.mozstumbler.communicator.AbstractCommunicator$HttpErrorException
06-29 18:53:27.992: E/org.mozilla.mozstumbler.communicator.Submitter(6941):     at org.mozilla.mozstumbler.communicator.AbstractCommunicator.sendData(AbstractCommunicator.java:96)
06-29 18:53:27.992: E/org.mozilla.mozstumbler.communicator.Submitter(6941):     at org.mozilla.mozstumbler.communicator.AbstractCommunicator.send(AbstractCommunicator.java:109)
06-29 18:53:27.992: E/org.mozilla.mozstumbler.communicator.Submitter(6941):     at org.mozilla.mozstumbler.communicator.Submitter.cleanSend(Submitter.java:40)
06-29 18:53:27.992: E/org.mozilla.mozstumbler.communicator.Submitter(6941):     at org.mozilla.mozstumbler.sync.SyncAdapter.onPerformSync(SyncAdapter.java:91)
06-29 18:53:27.992: E/org.mozilla.mozstumbler.communicator.Submitter(6941):     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
```

The logs reveal that the exception is caught in cleanSend and the data simply gets deleted because the retry count reaches its limit. The observations also confirm that. However, it would be interesting to know why it fails. If that helps, I will try to build MozStumbler for myself and debug it to see what causes the issue (but osmdroid is giving me headache).

**Comment by DonTomika** [comment]
I did some more testing. I tried to upload data for 102 observations. The first batch is 19659 bytes long, and it's perfetly valid JSON. A formatted version can be found here: https://gist.github.com/DonTomika/dc6bca33e7e73ea749ee

The returned HTTP response code is 400, and the response body is:

```
{"errors": [{"description": "\"0\" is not one of , wcdma, umts, lte, cdma, gsm", "name": "items.10.cell.0.radio"}]}
```

The first problematic line seems to be the 241st, where radio is "0". Then 5 more occurences follow.

Unless I'm missing something, the radio field gets its value from CellInfo.getCellRadio, and the only place where it can be set to zero is the default label of CellInfo.getCellRadioTypeName. 0 stands for TelephonyManager.NETWORK_TYPE_UNKNOWN.

I don't know in what circumstances Android reports the network type as zero. I did my testing in a residential area, so there shouldn't be any network issues. I don't think the problem is caused by my phone, but I will test with a different device tomorrow to be sure. If it is related to some specific cell towers, then it can explain the gaps in the observations in eastern Hungary, where I live (https://location.services.mozilla.com/map#9/47.6265/20.6296).

Also, here are two observations by an other app in a nearby area, maybe it can help explaining what's going on: https://gist.github.com/DonTomika/5838ff6e804eea48b244

---

Note: changing "0" to an empty string (as seen in the error message) does work, but [the docs](http://mozilla-ichnaea.readthedocs.org/en/latest/cell.html) does not mention this possibility. Is this a safe thing to do?

**Comment by hannosch** [comment]
Thanks for the detailed debugging, this is immensely helpful!

I think MozStumbler needs to add a check for NETWORK_TYPE_UNKNOWN. Without a known network type, it should just skip the record and not even store it. It could send it to the server either without a radio entry in the JSON or with an empty string as the value. But both of those would only result in the server silently dropping the record, so MozStumbler can just do that and save the bandwidth.

Without the network / radio type the other parts of the cell id aren't clearly defined. We cannot guess the radio value from the other parts, so we just drop it.

**Comment by Djfe** [comment]
This belongs to #511

**Comment by Djfe** [comment]
#606 added uploading of empty phone types.
Should empty phone types be deleted/ignored as well?

**Comment by hannosch** [comment]
@Djfe empty phone type is ok. The phone type reporting is optional. We only really need the network type of each cell entry.

**Comment by Gitschubser** [comment]
I installed v0.20.6 Beta Release and upload the data but i see that i get not more points in the leaderboard.
Maybe i lost data too.
With the old version 0.20.5 there is no problem.

**Comment by DonTomika** [comment]
That's a different issue. It is caused by the Prefs class and the PreferenceScreen using a different preferences file, so your nickname is not visibile to the sync service.

---

Unfortunately I was not able to collect any usable data with my older phone (probably because it doesn't have a sim card in it), and I have no idea what is causing these unknown cells. However, I've started to use a modified version of MozStumbler that makes sure radio is always valid, and everything is working fine since then.

**Comment by Djfe** [comment]
Actually my settings got reset when updating to 0.20.6.
I don't saw any nickname in the settings window and the geofencing coordinates got reset, too.

**Comment by garvankeeley** [comment]
Hanno, so throw away CellInfos that have NETWORK_TYPE_UNKNOWN for this member: mCellRadio 
https://github.com/mozilla/MozStumbler/blob/28782d755a00232f9f34b189d669aa455327aa71/src/org/mozilla/mozstumbler/service/scanners/cellscanner/CellInfo.java#L43

**Comment by hannosch** [comment]
@garvankeeley, yes. mCellRadio needs to be a non-empty string. If you want to add more cell validation, then you could also check for mcc to be an integer in the range of 1-999 and mnc to be an integer between 0 and 32767.

We need to know the kind of network, the country and the operator. Without those we cannot do anything with the record and will just discard it. The validation for the other parts is much more tricky, as it depends on the network type.

**Comment by garvankeeley** [comment]
Issue #681 should fix this. Added some more GUI logging to go along with this to make it easier for the user to see problems.
