### ISSUE TITLE
Move SSID blocklist from Java code to user-configurable text file on /sdcard

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#664]
(Forked from issue #581.)

Allow power users to override or augment the embedded SSID blocklist with a text file on /sdcard. Or move the entire blocklist out of Java code to a user-configurable text file on /sdcard.

**Comment by cpeterso** [comment]
@anishgkanchan, you might find this bug interesting. :)

**Comment by cpeterso** [comment]
I'm not sure what MozStumbler should do if the user has modified their local blocklist file and a new version of MozStumbler ships with an updated default blocklist. We don't want to overwrite users' customized blocklists. To start, maybe MozStumbler should keep the default blocklist (from Java code) and, if the user has added their own blocklist file on the sdcard, we can combine the two blocklists. So the user could add their own SSIDs to the blocklist, but (for this first version of this feature) they would not be able to remove any default SSIDs.

**Comment by anishgkanchan** [comment]
I'm still not clear about what exactly needs to be done here. 
Suppose we maintain the list in a txt file. Then the contents would have to be read by the app and stored in WifiBlockLists.java
And hence if the user adds some new SSIDs in the file, even they will get read by the app.
But then this would mean that every time the app starts, it will read the file and store it's SSIDs. Wouldn't this make it slow?

**Comment by cpeterso** [comment]
The app would need to read the SSID list every time it starts, but that should be pretty fast. I don't think it would cause any noticeable performance problems.

**Comment by garvankeeley** [comment]
I think this can be closed as we no longer want to do this. 
However, regex in the block list is desirable.

**Comment by anishgkanchan** [comment]
So what is to be done in it?

**Comment by garvankeeley** [comment]
@crankycoder raised concerns about the stability of introducing full regex support (performance problems on bad regex, people writing malformed regex), so I agree full regex is not the best approach.

When this bug was filed, it seemed like the block list was of active interest to users, but that interest seems to have waned.

If there is enhancements to how the block list works we should file a different bug for that.

**Comment by Djfe** [comment]
why does the performance during upload matter so much?
I mean the checks don't have to be done during scanning, right?

or is the information already used for the green and blue markers on the map? (does it check whether the wifi will be even uploaded before showing them?)
