### ISSUE TITLE
0.20.6 bug: service crashes after closing

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#668]
~30 seconds after everytime I close mozstumbler I get an error: Unfortunately Mozstumbler stopped.

looking at the system log (with Android Tuner), I see that the service is restarted after the main app is closed and then crashes with a nullpointerexception.

Probably unwanted behaviour: somehow the system tries to keep the service alive or something.

**Comment by rodmoreno** [comment]
I can confirm this problem, unfortunately I have not been able to check the log.

**Comment by garvankeeley** [comment]
Fixed by issue #673. Will do another prerelease to confirm it is ok now.
