### ISSUE TITLE
view log should show more info, use colours, better formatting

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#670]
just a blank screen

Device:
Xperia Arc S
Rom:
CarbonRom Kitkat

![screenshot_2014-07-02-15-57-40](https://cloud.githubusercontent.com/assets/5685512/3456684/571af2c2-01f1-11e4-9a7c-8c5942dab0b7.png)

**Comment by garvankeeley** [comment]
If you are outdoors with a GPS fix, do you see any text? If you never see text, I think the font might be black.

**Comment by Djfe** [comment]
Oh, I thought this was the log of the application and not a log of the stumbled data

Works then

Would be nice though if you could see the start of a new line better...

Maybe you can mark some of the text/use color/use a bold font type for the start of a new line or make a line-break

**Comment by garvankeeley** [comment]
Issue #683 added some colour, which is a start.

**Comment by crankycoder** [comment]
Closing as there's nothing actionable.  If specific items should be logged, or logged with a specific colour - let's be specific about those details.
