### ISSUE TITLE
The UI is not reset when stop scanning

### ISSUE THREAD

**Issue by rodmoreno** [mozilla/MozStumbler#685]
When I press the button to "start scanning" the entire interface is updated with information but when I stop the scan this information persists and is not reset and the old versions.

I'm using Moto G with Android 4.4.2
Since v0.20.6

**Comment by Djfe** [comment]
Happens to me as well.
Suddenly MozStumbler now keeps showing the number of connected satellites even if the scanning stopped.
Same goes for visible cells. (visible wifi aps are reset to blank though)

before the ui/service split this stuff got reset to 0/was left blank.

see:
![screenshot](https://cloud.githubusercontent.com/assets/5685512/3542591/dc1d6190-0858-11e4-8f32-b0778979a32c.png)

**Comment by Djfe** [comment]
@garvankeeley the only issue remaining from this is #974 because the UI got changed so much
you are not really able to see whether you still a new GPS position every second/10m -> it still shows satellites x, although there might be no established connection atm. (short GPS losses, aren't visible)
