### ISSUE TITLE
view log, logs are cut off by dots

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#695]
logs are cut off by dots -> often you are not able to see cells if there are too many wifis
-> pls make it so that you can toggle the entries (expand/collapse on touch)

![screenshot_2014-07-10-18-07-59](https://cloud.githubusercontent.com/assets/5685512/3542124/be565f90-0853-11e4-8621-e9da658ac435.png)

**Comment by garvankeeley** [comment]
After the first 30 or so, it starts to truncate. That is a quick workaround so the log does not get too large, it already is slow to render. The log also has a 1000 message limit. A better log would use a table and load rows on-demand from the db. Or, when we add export, the export will have the full log.

**Comment by crankycoder** [comment]
We display the full MLS blob now.
