### ISSUE TITLE
Background service crash issue (sync module)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#696]
sometimes I still get "Unfortunately MozStumbler stopped working" or something like that.
But for a different reason. The issue seems to lay within MozStumbler's sync module.
getmaxid seems to be the function

extract from system log (searched for "Moz") you have to read it from bottom to top

```
Android Tuner (logcat)
======================
I/13:46:43.151 ActivityManager(  670)
  svc   S     5289 kB: org.mozilla.mozstumbler (4706) started-services
D/13:46:35.343 org.mozilla.mozstumbler.client.MainApp( 4706)
Service connected
W/13:46:35.293 AccountManagerService(  670)
insertAccountIntoDatabase: Account {name=sync, type=org.mozilla.mozstumbler}, skipping since the account already exists
D/13:46:35.113 ActivityThread( 4706)
handleBindApplication:org.mozilla.mozstumbler
I/13:46:34.643 ActivityManager(  670)
Start proc org.mozilla.mozstumbler for service org.mozilla.mozstumbler/.service.StumblerService: pid=4706 uid=10079 gids={50079, 3003, 1028, 1015, 1023}
W/13:46:33.622 ActivityManager(  670)
Scheduling restart of crashed service org.mozilla.mozstumbler/.service.StumblerService in 1000ms
I/13:46:33.612 ActivityManager(  670)
Process org.mozilla.mozstumbler (pid 4595) has died.
E/13:46:20.629 AndroidRuntime( 4595)
    at org.mozilla.mozstumbler.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:44)
E/13:46:20.629 AndroidRuntime( 4595)
    at org.mozilla.mozstumbler.service.sync.UploadReports.uploadReports(UploadReports.java:72)
E/13:46:20.629 AndroidRuntime( 4595)
    at org.mozilla.mozstumbler.service.sync.UploadReports.getMaxId(UploadReports.java:121)
E/13:46:20.629 AndroidRuntime( 4595)
Process: org.mozilla.mozstumbler, PID: 4595
D/13:46:20.619 org.mozilla.mozstumbler.client.MainApp( 4595)
Service connected
W/13:46:20.589 AccountManagerService(  670)
insertAccountIntoDatabase: Account {name=sync, type=org.mozilla.mozstumbler}, skipping since the account already exists
D/13:46:20.449 ActivityThread( 4595)
handleBindApplication:org.mozilla.mozstumbler
I/13:46:20.189 ActivityManager(  670)
Start proc org.mozilla.mozstumbler for service org.mozilla.mozstumbler/.client.sync.SyncService: pid=4595 uid=10079 gids={50079, 3003, 1028, 1015, 1023}
```

**Comment by garvankeeley** [comment]
This is bad, thanks for the report.

**Comment by garvankeeley** [comment]
Fixed by pr #703 -I hope.

**Comment by Djfe** [comment]
will check my logs after the next update for further issues ;)

**Comment by garvankeeley** [comment]
Backed out my PR. On second reading I saw the original code was fine as-is. 
Need to look at this bug report again more closely.

**Comment by Djfe** [comment]
why is the service running in the background anyway? the activity manager schedules a restart once I exit Mozstumbler manually (close using the task manager of the system ui -> long press of home button)

normally MozStumbler should not be running in the background if the scanning is turned off
and I only get the error if I'm using something else and MozStumbler is not scanning in the background

**Comment by Moktarama** [comment]
On a Nexus 5 and 4.4.4 vanilla, I encounter exactly the same problem, with android telling me "Mozstumbler shutted off unexpectedly" on a regular basis. It happened exclusively when I was not stumbling, so it seems to be a background activity bug.

**Comment by garvankeeley** [comment]
Can you try this version https://github.com/mozilla/MozStumbler/releases/tag/v0.21.0

**Comment by Moktarama** [comment]
I installed the 0.21.0 beta two days ago, no background crash for the moment. I'll post again Here if I encounter that problem again;

**Comment by Djfe** [comment]
In 0.21.0 The sync module has been replaced with a different method so it's very likely that nobody will encounter the issue anymore, since the code has been removed.

**Comment by garvankeeley** [comment]
As @djfe mentioned, the code that was crashing is gone, so i'll close this, thanks.
