### ISSUE TITLE
scan button is to small in landscape mode

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#697]
the size of the start/stop scanning button was changed recently. But noone viewed it in landscape mode.
in landscape mode the button is split in up to 3 lines even if there is enough space for it to be in one line...

this looks pretty bad on tablets like the samsung galaxy tab 3 10.1 where the default view is landscape mode (the buttons would be at the side of the device if you use potrait mode)

But see for yourself:
Samsung Galaxy Tab 3 10.1
![screenshot_2014-07-10-10-27-48](https://cloud.githubusercontent.com/assets/5685512/3542024/89612cb2-0852-11e4-98b9-fed51b1215ca.png)

Sony Xperia Arc S
![screenshot_2014-07-10-16-30-03](https://cloud.githubusercontent.com/assets/5685512/3542026/902765a2-0852-11e4-842d-277435643e48.png)

**Comment by garvankeeley** [comment]
Your 2nd screenshot  is how it was designed, but the button needs to grow to fit the translation. The first screenshot looks ugly! It would be great if someone would contribute a tablet layout.

**Comment by Djfe** [comment]
not an issue anymore, since the map view is the default view now
