### ISSUE TITLE
duplicated logs

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#698]
sometimes logs are duplicated (after each other without the blue colored part)
![screenshot_2014-07-10-18-07-59](https://cloud.githubusercontent.com/assets/5685512/3542097/60df5dd0-0853-11e4-9a03-4f2a7cdea391.png)
![screenshot_2014-07-10-18-08-21](https://cloud.githubusercontent.com/assets/5685512/3542098/61101042-0853-11e4-8ff5-ca96d6be9f07.png)

**Comment by garvankeeley** [comment]
I think looks correct. The log shows a GPS scan, so capture is started, then 2 wifi scans. Until the next GPS scan, or http send, that represents a single entry in the db (a single StumblerBundle in the code). It would make for less clutter in the log if consecutive wifi scans just overwrite the previous ones,

**Comment by Djfe** [comment]
it is correct that the absolute same entry appears twice for the same time? (17:50:04/17:52:14)
it's not only scanning wifis but cells too
the cells are just cut off because of the character limit

**Comment by garvankeeley** [comment]
I think it is ok. For instance, in the 2nd example I would expect that the log will first show the GPS at 17:54:14, then a scan a few seconds later, then another scan a few seconds later. I'll look at my logs, I would think I would see many wifi/cell scans happening in a row until another GPS comes in.

**Comment by garvankeeley** [comment]
The log shows 'StumblerBundles' a.k.a. stumbling records in white text, so my prev. explanation is incorrect. There are 3 cases where you can get duplicate records, when scanning is stopped, when wifi/cell count is extremely high, or when no GPS has arrive for 24 hours -I think we can reduce that time :). It would be good if I added start/stop messages in the log we could see if that is what is happening here.

**Comment by Djfe** [comment]
@garvankeeley did this get fixed by crankycoders commit? #1004

**Comment by Djfe** [comment]
didn't encounter this issue anymore in the latest versions
