### ISSUE TITLE
sometimes my upload doesn't get zipped

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#699]
according to the new view log function sometimes an upload doesn't get zipped

do you know what could be the reason for that?

![screenshot_2014-07-10-18-08-21](https://cloud.githubusercontent.com/assets/5685512/3542387/65534ca2-0856-11e4-8df1-174d74f702cc.png)

is it switching to plain automatically if the first upload fails/times out?

**Comment by garvankeeley** [comment]
I see this also. If the http response fails, which can happen on a mobile device from time to time, the fallback is to resend unzipped. 
I have updated the code for this zipping/non-zipping logic and will submit a patch

**Comment by Djfe** [comment]
MozStumbler should differ between connection fails and a failing zip process...
Is that what you mean with zipping/non-zipping logic?

**Comment by garvankeeley** [comment]
Exactly

**Comment by garvankeeley** [comment]
Fixed by pr #702
