### ISSUE TITLE
StrictMode$InstanceCountViolation when device is rotated

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#7]
Every time a device is rotated, the screen configuration changes and the main activity is destroyed and recreated. A side effect is that rotating MozStumbler logs these StrictMode error messages:

```
E/StrictMode(2914): class org.mozilla.mozstumbler.MainActivity; instances=2; limit=1
E/StrictMode(2914): android.os.StrictMode$InstanceCountViolation: class org.mozilla.mozstumbler.MainActivity; instances=2; limit=1
E/StrictMode(2914):     at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
```

**Comment by dougt** [comment]
I think we're allowed to have two, not any more than that.

http://stackoverflow.com/questions/5956132/android-strictmode-instancecountviolation

However, I am not sure.

**Comment by dougt** [comment]
chris, what do you think?

**Comment by cpeterso** [comment]
I still believe this is a real issue. We're leaking MainActivity instances. Presumably MainActivity's context is being held by some callback.

**Comment by pepyakin** [comment]
I think I see, where it can happen. In `checkForUpdates` method we are closing on Context (which is `MainActivity`) instance. So we are leaking `MainActivity` at least for duration of executing `checkForUpdates` `AsyncTask` (and even further if there are really update, as we are closing again over Context in dialog click listeners).
For avoid this, I can recommend to use DialogFragments and/or https://github.com/commonsguy/cwac-updater/
