### ISSUE TITLE
Wi-Fi optimization: any negative impacts on wifi scanning?

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#701]
does the system option for wifis: wlan optimization have any negative effect on scanning/stumbling?

is the scanning rate slower? does MozStumbler recognize still wifi aps that are further away?

**Comment by garvankeeley** [comment]
Is "wlan optimization" an Android setting?

**Comment by Djfe** [comment]
yes, it is
http://www.pocketables.com/2013/10/android-tip-turn-off-wifi-optimization-if-youre-having-trouble-using-certain-apps-over-wifi.html
http://forum.xda-developers.com/nexus-4/help/wi-fi-optimization-t2039033

it's called Wi-Fi optimization though :)

the people on xda say it "slows down" your wifi connection, which is too unprecize for me :)

**Comment by crankycoder** [comment]
There's nothing actionable here and nobody is complaining yet.  :)
