### ISSUE TITLE
log failed uploads / don't delete failed uploads

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#705]
I have a question: does the log mention it if an upload fails and the data is deleted from the database?

**Comment by garvankeeley** [comment]
It wil log failed upload upload attempts, not deletion from the db after multiple failures.

**Comment by Djfe** [comment]
ok, could you pls rewrite the code so that it doesn't remove entries if it fails?
If the uploads are not valid than the server will silently drop them, so that the client removes them anyway.
So the only reason is an instable connection (low signal strength for example->the device is often disconnected)
Therefore it doesn't make sense to remove them, right?

Or have I overlooked something?

EDIT:
this has to do with:
#546

**Comment by garvankeeley** [comment]
I'll review that code to see what it does, it is pre-Fennec split code (that is, I didn't write it) but that is what I thought it did, maybe I misunderstood what it was doing.

**Comment by garvankeeley** [comment]
The code deletes after a few tries:
https://github.com/mozilla/MozStumbler/blob/master/src/org/mozilla/mozstumbler/service/sync/UploadReports.java#L207

**Comment by Djfe** [comment]
3 sounds insufficient to me.
You should either increase that number or remove it completely.

My Android Custom ROM has some issues regarding the wifi module. the device sometimes looses the connection to my wifi ap and therefore I lost reports already, which is unneccessary.

I can't think of a reason why it should make sense to delete reports just because of a bad connection.

**Comment by garvankeeley** [comment]
I agree, I don't know how this was decided

**Comment by Djfe** [comment]
@cpeterso is there a reason for `MAX_RETRY_COUNT`?

**Comment by Moktarama** [comment]
As I encountered this problem myself on a trip to a foreign country (massive data losses because of patchy Wifi connection), I can only approve the removal of the three tries' limit. 

At least, there should be a manual backup option to avoid these data losses (which, in my case, did lead to the loss of 30 000+ locations in a country that had none reported until then).

**Comment by Djfe** [comment]
I think the limit was removed in 0.21.0 already ;)
But I would like a concrete answer from @garvankeeley since he wrote the code.
If he confirms then I will close this thread.

**Comment by garvankeeley** [comment]
Correct, as 0.21.0, deletions happen only if any stored data is detected to be 4 weeks old.

**Comment by Djfe** [comment]
forgot to close this issue
