### ISSUE TITLE
Not displaying my location

### ISSUE THREAD

**Issue by naoliv** [mozilla/MozStumbler#706]
Until version 0.20.5 I was able to see a rough location when asking MozStumbler to locate me.
With 0.20.9 it keeps displaying me at the ocean onlyt (it seems to keep trying to locate, but can't see a valid location, even after waiting a lot of time)

**Comment by Djfe** [comment]
It now uses the GPS position instead of the MLS position.
Maybe there is an issue regarding that

**Comment by garvankeeley** [comment]
And the problem with GPS positions is that we only accept pure GPS position, that is the position cannot be assisted in any way by google location services. Pure GPS positions are shown in the Log Activity, so if that isn't there, then effectively the app has no position.

**Comment by Djfe** [comment]
@garvankeeley can probably be closed

**Comment by crankycoder** [comment]
@naoliv can you confirm that you are getting a position with v0.40.1.0?

**Comment by naoliv** [comment]
Yes, it's locating me now.
But just one doubt: is it using Mozilla service to locate me, Google or maybe I should be seeing both?

**Comment by crankycoder** [comment]
There's actually a lot going on in the UI, we need to have a walk through so that this is clarified, but here's what you're seeing:
- your location provided by GPS
- if you have the MLS location overlay, you will start getting red dots which indicate where MLS would have located you with only the cell and wifi data

**Comment by Djfe** [comment]
you need to turn the MLS layer on in the settings manually, it's off by default because it can consume a lot of data

**Comment by naoliv** [comment]
But I am indoor (there is no GPS lock/fix inside here) and I still can see my location:

![screenshot_2014-10-09-22-34-27](https://cloud.githubusercontent.com/assets/982338/4586769/d98e420c-501d-11e4-9b79-74da7ab36fd5.png)

Even with MLS layer enabled I can't see any red dots.
