### ISSUE TITLE
Should not scan when asked to locate

### ISSUE THREAD

**Issue by naoliv** [mozilla/MozStumbler#707]
When asking MozStumbler to locate me it also starts to scan my current location (capturing cell and everything else).

If I am asking only to be located it shouldn't also start to scan my location.
It can internally use all the available info to locate me, but should not register or save these data.

**Comment by Djfe** [comment]
That's because it uses the same code out off lazyness.
Will probably be changed in the future.
Since the last version it uses the GPS position.
But in the future it will show both: MLS and GPS.

**Comment by Djfe** [comment]
@garvankeeley not an issue anymore: mapview is main view

**Comment by crankycoder** [comment]
The UX has been changed so that the primary usage is stumbling.  Displaying the MLS locations happens in an overlay which shows where MLS would have positioned you at each of the stumbled locations.

I'm closing this as it's not relevant anymore with respect to the new UX.
