### ISSUE TITLE
Sometimes doesn't capture anything

### ISSUE THREAD

**Issue by naoliv** [mozilla/MozStumbler#708]
I am seeing something strange with MozStumbler: I used to run it together with GPS Logger (https://play.google.com/store/apps/details?id=com.mendhak.gpslogger) and Tower Collector (https://play.google.com/store/apps/details?id=info.zamojski.soft.towercollector) but saw that it wasn't capturing data sometimes.

Since both GPS Logger and Tower Collector were properly capturing data, I thought that it could be some kind of concurrence (two apps trying to access the same resource, maybe).

Then I started to use only MozStumbler but sometimes I still see the same problem: even having 11 visible GPS/Glonnas satellites, sometimes it just doesn't capture anything.
The scanned locations remains at 0, while I can see the GPS satellites, cells and wifi points being updated.

**Comment by garvankeeley** [comment]
Is there a GPS entry in the log activity in MozStumbler? I wonder if the device doesn't have a non-fused GPS location yet (Fused: using Google Location Services as assistance).

**Comment by naoliv** [comment]
The phone is a Xperia Mini Pro running Android 4.0.4, just in case.

With adb logcat this is what I see when opening MazStumbler:
http://paste.debian.net/plain/109709

And after pressing to start scanning (with wifi disabled):
http://paste.debian.net/plain/109710

With "GPS" I can only see this:
loc_eng_send_gps_status: status = 1
loc_eng_agps_data_conn_failed
loc_eng_send_gps_status: status = 4

It's also strange that I see it loading TTS stuff that I don't see with GPS Logger, for example:
http://paste.debian.net/plain/109711

**Comment by garvankeeley** [comment]
Can you check the new Log Activity in the app?

**Comment by naoliv** [comment]
The log is empty (even with 12 sattelites visible).
Should it contain info only when it acquires a position or it should be displaying something else?

**Comment by garvankeeley** [comment]
I'll have to do an update that shows more info in the log, this should be easy to figure out if I display the GPS source attribute (network/fused/GPS-only).

**Comment by Djfe** [comment]
The log should contain the same stuff that is written into the system log in my opinion.
So it would be nice if you could add that info to the log as well.

**Comment by naoliv** [comment]
Testing now it worked (like said initially, it's sporadic when it works or not).
I can see this in the log:

![screenshot_2014-07-15-13-59-43](https://cloud.githubusercontent.com/assets/982338/3588398/21ca02a0-0c43-11e4-9805-864b317e38bb.png)

The log is still empty when it doesn't work, however.

**Comment by garvankeeley** [comment]
@Djfe: The system log has way too much stuff, I would have to go through and check all the code to remove unnecessary messages. The Log Activity needs a rewrite to load its contents async to handle huge logs, it is very primitive in design ATM.

**Comment by garvankeeley** [comment]
Deleted my earlier comment, it was wrong. The correct answer is still that the log looks correct.

If there is a case where you are not getting GPS entries in the log, then we should look at that, sounds like a bug.

**Comment by Djfe** [comment]
@naoliv you say that your device is connected to 12 satellites but is it showing your current lat/lon coordinates below that number?
If not: then your GPS connection is not established. Your device is connected to a few satellites but doesn't have a gps fix, yet. -> it needs to calculate your position first before Mozstumbler receives any position of yours.

You should have (almost) free sky access for a first GPS fix because then the satellites' signals are stronger.

**Comment by naoliv** [comment]
@Djfe the problem is that I can use osmand, GPS logger and tower collector without any problem (and they can pinpoint me), while with MozStumbler it's sporadic: sometimes it works, sometimes not.

Even using MozStumbler together with another app, I can see the other program recording my location but not MozStumbler (it displays the number of satellites but it seems that it can't actually locate where I am)

**Comment by Djfe** [comment]
ah yeah sorry you said that above, sorry my fault...

forget what I said above

maybe Garvan finds a piece of code that explains this behaviour.

I'm not too familiar with the code, yet.

**Comment by garvankeeley** [comment]
https://github.com/mozilla/MozStumbler/blob/master/src/org/mozilla/mozstumbler/service/scanners/GPSScanner.java#L78

The code is quite standard, except we require 10m and 1s between GPS locations.

**Comment by Djfe** [comment]
The 10m were introduced to reduce the amount of data, I think:
#14 
the 1s was probably there before.

**Comment by crankycoder** [comment]
@naoliv is this still happening for you on v1.3.0 of the stumbler?

**Comment by naoliv** [comment]
It seems to be fixed.

**Comment by cascheberg** [comment]
@naoliv Please close this issue if the problem is fixed.

**Comment by naoliv** [comment]
My phone is dead :-( but in the last times it was working as expected. Thus closing it.
