### ISSUE TITLE
Updated Polish translation

### ISSUE THREAD

**Issue by piotrdrag** [mozilla/MozStumbler#711]
Hi, here is a patch with Polish translation update:

http://raven.fedorapeople.org/temp/0001-Updated-Polish-translation.patch

**Comment by Djfe** [comment]
you could have submitted a pull request instead ;)

but I will make one for you manually

**Comment by piotrdrag** [comment]
Thanks a lot! I need to learn how to make pull requests some day. :)

**Comment by Djfe** [comment]
oh that's fairly easy actually:
short tutorial:
fork the mozstumbler repo (top-right of this page)
download Github https://windows.github.com/
install it and log in (enter your data)
clone your forked repo of mozstumbler (left column) with the add button
click on the repo
press the gear button at the top-right
->open in explorer
make the changes to the files (for example res/values-pl/strings.xml for the polish translation)
go back to GitHub for Windows
it should show "uncomitted changes" in the history column
commit the changes by adding a short summary + (optional) a description
press the sync button (next to the gear button)
after the sync is done: go to your github fork (github.com/piotrdrag/mozstumbler) and press the compare button
create the pull request to the original project

if you want to work again on mozstumbler at a later point and need to update your local repo:
press the gear button at the top-right of github for windows and "open in git shell"
then enter the following commands into the command shell:
`git fetch upstream`
`git merge upstream/master`
now you can work on your local repo again
commit changes etc.
if you are done:
sync again
the upstream from the project plus your local changes will be synced to github
open your fork page and press compare again to create a pull request

if you have questions just ask them ;)

(of course the command-line has way more options than the github gui but it is easier to understand and works for beginners (it's definitely enough for contributing translations))

**Comment by cpeterso** [comment]
Thanks for the fixed translation, @piotrdrag! And thanks for rebasing the patch, @Djfe. :)
