### ISSUE TITLE
Points with WIFI turned off get not imported

### ISSUE THREAD

**Issue by benedetto** [mozilla/MozStumbler#716]
Recently I have made some recording tour through a rather rural area where I was roaming mostly outside of any settlements. As I did not expect to hit many WIFIs on my route and as my phone was running on battery for that time I had turned WIFI off to safe battery. Unfortunately it seems as if the 10000 points or so that I had recorded in this session have not been included into the database yet, while later recording sessions (with WIFI turned on) already are included.

Of course I cannot tell for sure if this is related to the WIFI status or to something else but WIFI was the only thing that was obviously different compared to all other recordings. Or are there other restrictions I'm possibly not aware of that can prevent data points from getting included? i could not find any documentation on this topic.

**Comment by Djfe** [comment]
Have you checked the website or the app's included map?

It might be that the app's internal map still shows the cached tiles for some reason. The website shows the current coverage correctly.

**Comment by benedetto** [comment]
The points do neither show up on the online map nor are they contained in the number of points in the leaderboard.

**Comment by Djfe** [comment]
@hannosch do you have an idea what could have caused this? Or is it rather client- than server-related?

**Comment by hannosch** [comment]
This could be both a client or a service side problem. Without any of the data that was recorded or a way to reproduce it, it's difficult to tell.

@benedetto Do you still remember when exactly you tried the data upload?

**Comment by benedetto** [comment]
The data was uploaded on last Sunday (20.7.) somewhere around 14:00 (I would guess between 13:45 and 14:20 MESZ). The upload took long enough that I saw a status window with the number of already uploaded points and the ones remaining. When all were uploaded, the window disappeared and there was no error message. Therefore I guess the upload went fine.

**Comment by Djfe** [comment]
a possible client-side reason: #705 

another idea, but very unlikely:
Maybe the client deletes records if the wifi is disabled. I don't think so, but I'm not sure (haven't checked the code).

**Comment by Djfe** [comment]
@garvankeeley can be closed now, should work, since even the map legend differs between normal/wifi-only/cell-only observations
