### ISSUE TITLE
Add option for tracking Data Usage

### ISSUE THREAD

**Issue by jahandaniyal** [mozilla/MozStumbler#728]
A lot of users are complaining about Excessive Data Usage. An option for tracking Data Usage could be a nice addition to 0.20.9.

**Comment by Djfe** [comment]
It only makes sense if it is more detailed than the one of the OS

**Comment by crankycoder** [comment]
I'm pretty sure this is largley irrelevant since we are using gzip compression now and by default, we only upload on wifi.
