### ISSUE TITLE
Location cellid/wifi indoor without GPS fix is not possible

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/MozStumbler#747]
When i inside a building and have no GPS fix or GPS is deactivated i get no position with cellid/wifi data.

**Comment by porjo** [comment]
I see this problem too. After acquiring an accurate position via GPS and collecting my local cell and wifi data, I've then uploaded that data to Mozstumbler server.  I can see my location on the map. However, as soon as I turn off GPS the location is lost and the map view becomes the middle of the Ocean: 0°E, 0°W

Does the map only use GPS?

I'm using MozStumbler Beta 0.21.0

**Comment by hannosch** [comment]
The current map does indeed only use GPS positions.

**Comment by Djfe** [comment]
In the past it used only MLS
Now it uses GPS for practical reasons (you can see where you really are)
In the future there should be two points:
One for GPS, one for MLS

**Comment by elkos** [comment]
+1 @Djfe it would be really useful to see if there are any deviations between an MLS positions track and a GPS position track.

**Comment by Djfe** [comment]
#733 is the current issue about it

**Comment by crankycoder** [comment]
Duplicate of #733
