### ISSUE TITLE
Text in map is overlapping

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/MozStumbler#748]
Text Cells: x Visible, x Scanned WiFi: x Visible, x Scanned under the map is overlapping.

**Comment by garvankeeley** [comment]
Maybe we can just show the visible counts here.

**Comment by Djfe** [comment]
I would change this to:
Cells: 4/7 Wifis: 18/40

Maybe Mozstumbler could dhow a collapsed version if the screen isn't wide enough
Landscape mode -> full text
Portrait mode -> collapsed text

**Comment by Gitschubser** [comment]
Good idea. The problem is really if the screen isn't wide enough.

**Comment by Djfe** [comment]
@crankycoder not really an issue anymore since we got icons now

**Comment by crankycoder** [comment]
Closed as the UX has changed dramatically, there's no more text to overlap. :)
