### ISSUE TITLE
Show marker for position only with valid position

### ISSUE THREAD

**Issue by Gitschubser** [mozilla/MozStumbler#751]
Show the marker for the position in the map only if a valid fix/position is available.

**Comment by Djfe** [comment]
Without GPS enabled it shows 0/0 to me, which is below Ghana in the ocean...

In my opinion mozstumbler shouldn't show the marker at 0/0 and give out an error in a toast nessage:
"No established GPS connection, yet."

**Comment by Gitschubser** [comment]
Good idea, a message that give out an error and show the marker only when the position is found (and find the position without enabled GPS, only with wifi or cellid :-) )

**Comment by garvankeeley** [comment]
This PR has some better handling of the 0/0 state:
https://github.com/mozilla/MozStumbler/pull/739
I am planning to do another beta this week, I'll land that PR, and fix the other bugs that have been reported.

**Comment by Djfe** [comment]
#706 will get fixed by this as well.
