### ISSUE TITLE
Display OpenStreetMap copyright on map view, not MozStumbler's About page

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#757]
OSM's copyright (http://www.openstreetmap.org/copyright) specifies that we need to display a copyright message on the map view itself:

_We require that you use the credit “© OpenStreetMap contributors”.  ... For a browsable electronic map, the credit should appear in the corner of the map. For example:_

![attribution_example-05e2149c0f98be0de18a06c07a5ec445](https://cloud.githubusercontent.com/assets/629193/3821001/71e2e994-1d02-11e4-8c7c-d6871f08718b.png)

**Comment by garvankeeley** [comment]
This is superseded by #773
