### ISSUE TITLE
Bug: Size element doesn't represent uploaded size

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#758]
The new site element in the upload observations page doesn't show the zipped but the total file size -> the real upload is much smaller

**Comment by garvankeeley** [comment]
for me it is showing the zipped size, can you explain what you are seeing?

**Comment by Djfe** [comment]
I have probably seen something wrong. Close.

**Comment by Djfe** [comment]
Reopened, because the issue is that the size turns 0 once the upload starts.
->doesn't represent the real size in the database during upload

**Comment by Djfe** [comment]
I don't have this kind of issue anymore since updating my os
