### ISSUE TITLE
Mapview drawing glitches

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#759]
Maybe we can use this bug for screenshots of drawing glitches with osm-droid. This is one I see after zooming. The tiles are correct in terms of data and location, but some tiles are loaded with higher level of detail. 

![screenshot_2014-08-01-12-07-48](https://cloud.githubusercontent.com/assets/5495083/3860764/8e3c4cc6-1f27-11e4-8dc7-8ef17ff4f20c.png)

**Comment by ioana-chiorean** [comment]
Hmm. I am really confused how to get the route.. I only get the blue little dots in my map.. 
I am missing something?

**Comment by narfg** [comment]
The route is only displayed in Beta 0.21.0. The recent stable release doesn't show it yet.

**Comment by garvankeeley** [comment]
To fix this problem, I had to delete /sdcard/osmdroid/*sqlite. 

Things that did not fix this:
- uninstalling the app
- deleting /sdcard/osmdroid/tiles

Since deleting the sqlite files, they have not reappeared. I have no idea why the sql was there (I assume some other OSMDroid app I installed used sql-backed tiles) or why the tiles for our app were partially managed by the sqlite db.
