### ISSUE TITLE
Stumbled locations not appearing on maps (app and web)

### ISSUE THREAD

**Issue by Moktarama** [mozilla/MozStumbler#760]
The locations I stumbled the last 3 days were transmitted as they were incremented in my leaderboard's scoreboards (and noted as transmitted by the app obviously). But : none of these stumbled locations appear on the map, be it on the website or in-app. 

I run Mozstumbler 0.20.9 on a Nexus 5 and 4.4.4 vanilla.

**Comment by Gitschubser** [comment]
I miss my stumbled locations too.

**Comment by hannosch** [comment]
This is a service side problem and tracked in mozilla/ichnaea#292.

**Comment by Moktarama** [comment]
Thanks for the answer, as long as the data is transmitted to the database it's allright, I can wait a few days for the map to be updated. I'm closing the issue.
