### ISSUE TITLE
the GPS "glitches out" at the beginning of the scanning

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#763]
Since we are now able to see the track MozStumbler records:
You can see in the following screenshot that the first scans at the beginning are garbage since the GPS values need to plateau first once the device get a GPS fix

are other people experiencing this, too?

if so, then there needs to be a timeout before a GPS position is considered valid for use

or mozstumbler would need to check functions like http://developer.android.com/reference/android/location/Location.html#getAccuracy%28%29 to determine whether the accuracy of the current location is accurate enough

of course the accuracy could also be lower if your device is covered by something or if it is in your jeans/backpack.

In this screenshot you can see what I' talking about:
![glitch](https://cloud.githubusercontent.com/assets/5685512/3907072/713e3182-22f8-11e4-81f7-19c012a12f9b.png)

the red line is where I moved approximately

**Comment by garvankeeley** [comment]
I think this approach would fix it:
- show the current gps as a dot, and connect the last point in the track to this dot
- only store track positions that are used for stumbler reports. When we actually show the track vertices as dots, this is a visual indicator to the user of where reports were made, and how frequently.

**Comment by crankycoder** [comment]
Closing this as #817 was merged

**Comment by Djfe** [comment]
Does #817 really fix this issue or does it just obscure it by only showing the points and not connecting them?

the real issue here is that Mozstumbler should ignore faulty GPS positions at the beginning of the scan/ignore faulty positions in general (ignore too unaccurate outliers)

**Comment by garvankeeley** [comment]
Sorry, I saw this as a UI bug, but it is actually a observation accuracy issue. 
I do see some wandering but the reported accuracy of the GPS still looks reasonable (by looking at the accuracy radius), so I don't see an obvious way to filter this.

**Comment by crankycoder** [comment]
I'm closing this as waiting for better GPS fixes doesn't help us in the context of collecting data for Ichnaea.  Waiting just means we aren't collecting data.  We might as well just start collecting right away.
