### ISSUE TITLE
Don't draw line connecting discontiguous tracks

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#765]
I turned stumbling on and off during a road trip. The map view drew long straight lines crossing the desert to connect discontiguous tracks that were many miles and hours apart. When drawing tracks, the map should not connect measurements that are more than X meters or Y minutes apart.

**Comment by Djfe** [comment]
Same issue I noticed and reported here: #733

It's good to have an independent issue now to keep track of it :)

**Comment by garvankeeley** [comment]
We will likely change to just drawing collection points, and not joining the lines

**Comment by crankycoder** [comment]
Closed as of #817
