### ISSUE TITLE
Remove "Always scan Wi-Fi [even when Wi-Fi is off]" setting

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#767]
There is no need to expose this setting to the user. We should always scan Wi-Fi, even when Wi-Fi is off, if the API is available. When the user starts scanning, we should scan as everything we can.

**Comment by Djfe** [comment]
The issue here: the user might not know about this setting so he doesn't activate it

Right now activating it in the mozstumbler settings opens up the system settings to set the checkbox there as well

I would rather like to see a help page first that explains the app and maybe even MLS
(someone should open up a bug for this with the milestone "for play store release" because mozstumbler definitely needs such a page before being available on the play store)

**Comment by cpeterso** [comment]
@Djfe: what Android OS version are you using? I'm using JB 4.3.1. When my "Scanning always available" system setting is disabled and I enable MozStumbler's "Always scan Wi-Fi", I get a Deny/Allow dialog asking if I would like "To improve location accuracy and for other purposes, MozStumbler wants to turn on network scanning , even when Wi-Fi is off. Allow this for all apps that want to scan?"

This dialog is not quite as bad as actually dumping the user into the system settings, but it may confuse users if the app has not prepared them for the question. Maybe we can programmatically check the "Scanning always available" system setting value and only try to always scan Wi-Fi if we know the system setting will allow us without showing the dialog.

Do you know what the default value is for the "Scanning always available" system setting? If we silently honor the system setting but its default value is off, then MozStumbler will miss the opportunity to scan more data. That said, how often is a user going to go out of their way to turn off their Wi-Fi and then try to stumble? I think we used to have a warning if Wi-Fi was off when the app started, so maybe showing Android's "Always scan?" Deny/Allow dialog is not a bad user experience.

**Comment by Djfe** [comment]
Those ideas are similar to #517

There are likely values that you could read out to find out whether mozstumbler is able to scan wifis and cells atm

But there is more than one setting (airplane + hotspot disable some stuff as well)

**Comment by Djfe** [comment]
I'm using Kitkat 4.4.2 btw.
In my opinion we should leave the setting in. It's not confusing and most of the people should be able to understand it.
a help page/entry for this is only needed if we leave this setting out and check automatically whether it is turned on in the system settings

for the value: this is what you have been looking for ;) : 
http://developer.android.com/reference/android/net/wifi/WifiManager.html#isScanAlwaysAvailable%28%29

**Comment by crankycoder** [comment]
Merged in #853
