### ISSUE TITLE
Add "Only upload measurements over Wi-Fi" option

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#77]

**Comment by cpeterso** [comment]
This feature would not be that difficult to implement. There are two parts:
1. Add a WiFi preference to PreferencesScreen.java and Prefs.java: https://github.com/mozilla/MozStumbler/blob/master/src/org/mozilla/mozstumbler/preferences/PreferencesScreen.java
2. Check the WiFi preference from NetworkUtils.isNetworkAvailable(): https://github.com/mozilla/MozStumbler/blob/master/src/org/mozilla/mozstumbler/NetworkUtils.java

**Comment by Djfe** [comment]
Introduced with #378

**Comment by gabrielbauman** [comment]
Please consider making this the default. I seem to be uploading nearly 100GB an hour when driving around town.

**Comment by Djfe** [comment]
Wifi only is implemented already
-> look at the settings ;)

For the huge amount of data: look at #408

**Comment by Djfe** [comment]
You are talking about 100mb, right?

**Comment by gabrielbauman** [comment]
Yeah sorry... MB, not GB. I see that WiFi-Only is implemented - I just thought it should be the default.

**Comment by cpeterso** [comment]
Fixed by PR #378.
