### ISSUE TITLE
Crash: MapActivity responding to CellScanner, updates on wrong thread

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#771]
E/AndroidRuntime(12504): FATAL EXCEPTION: Timer-2
E/AndroidRuntime(12504): Process: org.mozilla.mozstumbler, PID: 12504
E/AndroidRuntime(12504): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime(12504):    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6024)
E/AndroidRuntime(12504):    at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:820)
E/AndroidRuntime(12504):    at android.view.View.requestLayout(View.java:16431)
E/AndroidRuntime(12504):    at android.view.View.requestLayout(View.java:16431)
E/AndroidRuntime(12504):    at android.view.View.requestLayout(View.java:16431)
E/AndroidRuntime(12504):    at android.view.View.requestLayout(View.java:16431)
E/AndroidRuntime(12504):    at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
E/AndroidRuntime(12504):    at android.view.View.requestLayout(View.java:16431)
E/AndroidRuntime(12504):    at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
E/AndroidRuntime(12504):    at android.view.View.requestLayout(View.java:16431)
E/AndroidRuntime(12504):    at android.widget.TextView.checkForRelayout(TextView.java:6600)
E/AndroidRuntime(12504):    at android.widget.TextView.setText(TextView.java:3813)
E/AndroidRuntime(12504):    at android.widget.TextView.setText(TextView.java:3671)
E/AndroidRuntime(12504):    at android.widget.TextView.setText(TextView.java:3646)
E/AndroidRuntime(12504):    at org.mozilla.mozstumbler.client.mapview.MapActivity.formatTextView(MapActivity.java:427)
E/AndroidRuntime(12504):    at org.mozilla.mozstumbler.client.mapview.MapActivity.formatTextView(MapActivity.java:421)
E/AndroidRuntime(12504):    at org.mozilla.mozstumbler.client.mapview.MapActivity.updateUI(MapActivity.java:374)
E/AndroidRuntime(12504):    at org.mozilla.mozstumbler.client.mapview.MapActivity.access$300(MapActivity.java:49)
E/AndroidRuntime(12504):    at org.mozilla.mozstumbler.client.mapview.MapActivity$ReporterBroadcastReceiver.onReceive(MapActivity.java:113)
E/AndroidRuntime(12504):    at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
E/AndroidRuntime(12504):    at android.support.v4.content.LocalBroadcastManager.sendBroadcastSync(LocalBroadcastManager.java:278)
E/AndroidRuntime(12504):    at org.mozilla.mozstumbler.service.stumblerthread.scanners.cellscanner.CellScanner$1.run(CellScanner.java:113)
E/AndroidRuntime(12504):    at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by garvankeeley** [comment]
no longer relevant

**Comment by crankycoder** [comment]
This is related to implementing a passive stumbling mode for Android. We'll revisit this after 1.0.
