### ISSUE TITLE
"MozStumbler has stopped"

### ISSUE THREAD

**Issue by vsessink** [mozilla/MozStumbler#777]
My new Samsung s5 phone once in a while emits a dialog saying "mozstubler is gestopt" (Dutch language, country code NL), even when I did not start it before.

**Comment by vsessink** [comment]
![screenshot_2014-08-22-08-18-42](https://cloud.githubusercontent.com/assets/2970510/4021672/f86aaf2e-2afe-11e4-8c88-51cdc3ac069b.png)

**Comment by Djfe** [comment]
This has been fixed in the current Beta 0.21.0
You can download it at http://github.com/mozilla/mozstumbler/releases ;)

**Comment by sawrubh** [comment]
https://www.dropbox.com/s/m1h87vnazexz8ty/Screenshot_2014-09-02-01-07-53.png - I keep getting this message after I updated to the latest MozStumblr (0.20.9). Maybe this is the same issue.

**Comment by Djfe** [comment]
Yes it's the same.
@garvankeeley you can close this as well, since it has been fixed already.

@vsessink @sawrubh just update to 0.21.0 using the link above ;)
(the app inbuild installer doesn't update to betas)

**Comment by vsessink** [comment]
Hi, I already updated to 0.21.0, this version doesn't have the bug mentioned in this bug report, but the "stop scanning" button doesn't work anymore. Maybe it's a known bug - didn't have time to search for/file a new bug yet.

Best regards,

Valentijn

On September 2, 2014 8:17:26 PM CEST, Felix Baumann notifications@github.com wrote:

> Yes it's the same.
> @garvankeeley you can close this as well, since it has been fixed
> already.
> 
> @vsessink @sawrubh just update to 0.21.0 using the link above ;)
> (the app inbuild installer doesn't update to betas)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mozilla/MozStumbler/issues/777#issuecomment-54194431

## 

Mobiel verzonden, daarom kort.
Durgerdamstraat 29, 1507 JL Zaandam; telefoon 075-7074579

**Comment by Djfe** [comment]
it works it's just a visual glitch/bug
it's known already, and will be fixed in the next version
#761

**Comment by crankycoder** [comment]
@vsessink I've patched the stop scanning button as of #782.  I'm closing this as it's apparently been fixed in 0.21
