### ISSUE TITLE
MozStumbler on Firefox OS

### ISSUE THREAD

**Issue by Zeriuno** [mozilla/MozStumbler#780]
I guess you have been already asked about it or at least you thought about it: why isn't MozStumbler available for Firefox OS? Can we expect to see it on this platform anytime soon?

**Comment by hannosch** [comment]
@Zeriuno There is a community project working on a stumbler app for FirefoxOS (https://github.com/clochix/FxStumbler), also mentioned on https://location.services.mozilla.com/apps

**Comment by Zeriuno** [comment]
Thanks for the answer!

**Comment by ghost** [comment]
Hannosch, Will we ever see a port? The FxStumbler seems to be less user friendly than MozStumbler and also has not seen updates in months.

**Comment by hannosch** [comment]
@bkerensa Current priorities on the client side are finishing up the Fennec/Stumbler integration, polishing MozStumbler for a 1.0 release and then look at the FxOS story in Q4/2014. That might both be helping out with FxStumbler or integration stumbling into FxOS itself.

**Comment by rugk** [comment]
Any news on this? 

On https://location.services.mozilla.com/apps it now says:

> Integration of this service into Firefox OS is an ongoing process. If the specific Firefox OS device uses this service depends on a number of factors including which chipset is used in the device, which manufacturer built the device and via what partner and channel it was sold or given out.
> 
> In general client side code to talk to this service appeared in Firefox OS version 1.3T and 1.4. 

BTW I do not really get what is meant by "If the specific Firefox OS device uses this service depends on a number of factors including which chipset is used in the device, which manufacturer built the device and via what partner and channel it was sold or given out.".
If a specific FF OS device depends on <listing of some specific features/properties> it was sold? What has this to do with Mozilla Stumber?

## 

And how stable is https://github.com/clochix/FxStumbler?

/cc @clochix

**Comment by hannosch** [comment]
Stumbling support is actually built into Firefox OS starting with version 2.5. There are still not enough public web API's to build a stumbler as an application outside the OS level, so older versions of FxOS are out of luck.

FxStumbler is a prototype that shouldn't be used.

**Comment by rugk** [comment]
> Stumbling support is actually built into Firefox OS starting with version 2.5.

Oh very nice. :smiley:

**Comment by lua86** [comment]
Wasn't it just passive stumbling?

**Comment by hannosch** [comment]
Firefox OS uses the same mode we use in Firefox for Android, which is passive stumbling. That is: If any application on the device gets a GPS fix, we piggyback on this event and also collect cell and wifi information. There are additional safeguards in place to keep the overall impact on battery life and data usage low.

An active stumbling app would have been far more difficult and time consuming to build. I don't think an active stumbling app will ever happen for Firefox OS.

**Comment by rugk** [comment]
> An active stumbling app would have been far more difficult and time consuming to build. I don't think an active stumbling app will ever happen for Firefox OS.

Really? :cry: 
I mean passive stumbling is nice, but of course active stumbling is superior.

(Although: if you really want to trigger the passive stumbling you can of course just execute an app which always asks for GPS :smile:)

**Comment by Zeriuno** [comment]
> FxStumbler is a prototype that shouldn't be used.

It works well enough, though. It could be a bit slow to find your position (depending on the GPS), it could be not very precise in locating you, but it works even if Clochix thinks it should be rewritten from scratch.
