### ISSUE TITLE
Unable to pan or zoom properly the map ( android) 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/MozStumbler#781]
On Android map on Galaxy Nexus I am not able to zoom in - and keep the data. 
Drag and dropping is really hard and delayed.. 

https://www.youtube.com/watch?v=s_OTiQfr88Q

**Comment by garvankeeley** [comment]
Hi, this build will fix most of those issues https://github.com/mozilla/MozStumbler/releases/tag/v0.21.0.

**Comment by Djfe** [comment]
that was due to the fact that the map was locked to the GPS
everytime a gps fix occured the map focussed your current location again
(gps fix=GPS location refresh)

**Comment by Djfe** [comment]
@crankycoder fixed already
