### ISSUE TITLE
UI Redesign: Move Log, Upload, Leaderboard, Settings, About, to be navigable from MapActivity

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#789]
The redesign of the app is to make the map the main screen, these screens are currently accessed from the MainActivity screen which will no longer be the main activity. 
These screens need to move to be sub activities of the map view as part of our 1.0 redesign.
Also need to consider the priority of these, which should be shown on the toolbar, which should be on the options menu, which should get icons.

**Comment by Djfe** [comment]
ups wrote something for the wrong issue page here first

in #795 I described a way how to do it:
with slider page I mean something like this:
http://i.crn.com/slideshows/2014/android_kitkat/07_openFile.jpg
