### ISSUE TITLE
UI Redesign, MapActivity: Icons for Cells and WiFis instead of text

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#790]
I realize that text labels on the screen create difficulties with layouts on small screens, and localized text. Better to use icons like @keverets did for the top bar that has the GPS info.

**Comment by Djfe** [comment]
just three squares with an icon inside and something like 2/10 (for GPS, cells and wifis)

more detailed explanation is shown in the slider page then (which I described in #795 )

and we should use a different slider for zooming in and out
the one with the plus and minus symbols at the bottom of the page looks like gingerbread...
