### ISSUE TITLE
Pull geofencing code out and target a post 1.0 revision

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#791]

**Comment by Djfe** [comment]
I'm strongly against this, because I guess a lot of users might use this function and won't realize that it is missing if they update to 1.0

just leave it in until the revision

some stuff that should be changed in the revision, in my opinion:
- #786
- ~~#558~~ and #424
- ~~#445~~
- #797

**Comment by crankycoder** [comment]
@djfe - I've double checked those issues you've listed and marked #558 and #445 closed as one is a duplicate and the other is a problem with respect to minimum API level requirements.

Unfortunately, we've got limited resources to apply against the geofencing feature and we would really like to push a nice polished release for 1.0 and we are aggressively reducing scope right now to meet that goal.

Geofencing as a whole is useful feature, but we should probably go back and reconsider it as a set of smaller bugs. For one, it would be nice to be able to specify _positive_ geofences for areas that are nearby that we would like to obtain geolocation data, but we do not have any data.  That would require server side support to push down those areas to clients.

Currently, we simply have very few users who would be affected by having this feature pulled and it will help us accelerate development to get more users stumbling.

We'll bring the feature back, it's just not going to make it into 1.0.
