### ISSUE TITLE
UI Redesign: with the loss of the MainActivity, consider what stats are missing and where to show them

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#795]
For 1.0, the main activity will be the map view. We need to consider the UI impact of losing this information viewed on the MainActivity, and where else we can put any items we deem relevant.

**Comment by Djfe** [comment]
in my opinion we should use a slider from the left like the play store does (where it shows my apps, etc. and a settings button below)

there we show the upload stuff on top (sent and queue)
including the missing stats

below that a line that separates it from the buttons that open the settings, logs, leaderboard etc.

Edit:
and image from the documents app that shows such a "slider"-page as well:
http://i.crn.com/slideshows/2014/android_kitkat/07_openFile.jpg
