### ISSUE TITLE
DataStorageManager: internal cleanup, refactor stateful iteration

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#798]
During Fennec review this issue came up, should address this.

**Comment by Djfe** [comment]
@garvankeeley is this still on your to-do-list or already fixed?

**Comment by crankycoder** [comment]
It's still open.

**Comment by crankycoder** [comment]
I think this really should be a "refactor/cleanup/rewrite" of the DataStorageManager, StumblerBundle and the Reporter classes.  It's a bit of a mess in there.
