### ISSUE TITLE
Enable NMEA checks for passive stumbling

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#811]
We only check NMEA data during active stumbling.   We should be checking when Fennec is doing passive stumbling.

See: https://github.com/crankycoder/MozStumbler/commit/53f7dc68279216b555f666cec64603180b73ee1f#commitcomment-7681578

cc/ @garvankeeley

**Comment by Djfe** [comment]
@crankycoder I'm not sure whether this is even an option now since it prevented me and @gpoo from scanning properly although we don't have a fake gps

**Comment by crankycoder** [comment]
Nmea checks break stumbling on a large number of devices.

When we implemented this for active stumbling it broke common devices like the galaxy s3 using stock roms.

Let's not do that again.
