### ISSUE TITLE
For the WiFi/Cell/GPS Scanners: Replace Intent-based messaging with callbacks

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#813]
The existing system causes confusion like I discussed here:

https://github.com/crankycoder/MozStumbler/commit/d75bdf4eff95325d005fedffc869b2ffda8e2f0e#src-org-mozilla-mozstumbler-service-stumblerthread-ireporter-java-P26

**Comment by crankycoder** [comment]
The intent messaging is here to stay.  Now that the stumbler service is pulled into a separate library, we can't really rely on having a pointer hanging around to the running service.
