### ISSUE TITLE
OSMDroid: for Mozilla builds, increase the tile load thread count from 2

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#818]
This is killing the performance of the map view:
https://code.google.com/p/osmdroid/source/browse/trunk/osmdroid-android/src/main/java/org/osmdroid/tileprovider/constants/OpenStreetMapTileProviderConstants.java#48

For Mozilla builds, which use the MapBox commercial service, we should load like a web browser and use 6-8 simultaneous requests.

**Comment by crankycoder** [comment]
Moved issue to here: https://github.com/mozilla/osmdroid/issues/2
