### ISSUE TITLE
Auto-follow mode: indicate using icon that this is on/off

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#836]
This is a follow-up item from #834.
Ideally, the icon would be a different style/color when auto-following the users GPS position.

**Comment by Djfe** [comment]
This would definitely be better for a simple reason:
the GPS follow icon is not shown if there is no GPS signal
but also if the map follows the user's GPS position

if the GPS signal is there but the map doesn't follow the user's position then the button isn't shown

**Comment by Djfe** [comment]
I tested Version 1.4.0 and I like the approach there:
an empty GPS icon looks pretty nice for the follow mode being turned off

**Comment by cascheberg** [comment]
@garvankeeley This issue was fixed in #1248 and should be closed.
