### ISSUE TITLE
Slow to show first GPS location

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#858]
We should start with the last location, it takes too long for the GPS to start showing the blue dot.

**Comment by QuandHarryViste** [comment]
+1 (Android 2.x)

**Comment by Djfe** [comment]
Or MozStumbler could prefer MLS over last location over GPS for the first screen ;) (if a data connection is available(has to respect the wifi only setting)

**Comment by garvankeeley** [comment]
fixed in https://github.com/mozilla/MozStumbler/commit/571d20a3552857451af254c523634c34d31caba3
