### ISSUE TITLE
Drop API 8 (Froyo) support

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#859]
This is <1% of android users, and it isn't something we want to test on or support. 

Also, when working on UI code, API 8 is missing things that make UI coding a bit easier (although we could say that about any older android API, _anything_ that makes the UI coding easier is appreciated as we have lots of work to do there).

I believe API 10 is the next logical jump (Gingerbread)

**Comment by crankycoder** [comment]
This change went in in #864 

https://github.com/mozilla/MozStumbler/pull/864/files#diff-7ae5a9093507568eabbf35c3b0665732R46
