### ISSUE TITLE
Get rid of the Updater code for the 1.0 release

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#862]
The Play store will handle code updates of versions for us, no need to run our own updating code.

**Comment by lua86** [comment]
I do not think it whould be a good idea, as some people do not want google
play store.

**Comment by crankycoder** [comment]
@lua86 are you talking about the F-droid release?  There's a related issue with releasing the MozStumbler with unofficial Mozilla builds - the unoffical builds do not use our much faster performing tile server for maps.  

@garvank I've made pretty big changes to the build system as of landing #864.  We could split the builds into different 'flavors'.  The change would amount to adding an extra buildConfigField and having a guard around using the Updater code.

Thoughts?

**Comment by cpeterso** [comment]
@crankycoder: I think @lua86 is referring to the actual Google Play Store. @hannosch says that only 30% of MozStumbler users are using our GitHub builds, so the other 70% are likely using F-Droid or their own local builds.

I think we should follow our users' lead and:
- Remove our GitHub-based auto-updater.
- Use F-Droid to publish frequent test releases of our Free Software build flavor (no Google Play Services, no MapBox, etc). F-Droid watches our GitHub repo for new release tags and auto-builds their package from our repo. I don't think we need to do anything.
- Use Google Play Store to publish stable snapshots of our "full-featured" build flavor (that uses Google Play Services, MapBox, etc).

**Comment by elkos** [comment]
Please in case of removing the auto-updater could there be a viable way to prompt the use to either install Mozstumbler from F-Droid or Google Play? I think that some of our users (for example our top3 data contributors) might miss a crucial update ;)

**Comment by Djfe** [comment]
Pls use Google groups to distribute alphas/betas through the play store:
https://support.google.com/googleplay/android-developer/answer/3131213

Facebook practices this as well.

**Comment by crankycoder** [comment]
@elkos thanks,  that's a good point.  :-) 

We'll keep the updater code after all.  I'll tweak the build to conditionally check for updates if you get a github release. 

@cpeterson, do we have an fdroid contact as the new build is pretty different now?

**Comment by crankycoder** [comment]
Disable the updater code unless we have a release flavour set to github.

**Comment by Djfe** [comment]
there should be something like an information that an update is available even in the Google Play Store version -> it should link to the Google Play Store page so that users can update

something like:
Update | Stay on version xy

other apps like Whatsapp do this as well
not everyone has autoupdates turned on
