### ISSUE TITLE
Need to expire coverage map tiles or users won't see updates to coverage

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#877]
We seem to have over aggressive caching of tiles because of OSMDroid.   Not sure what the tile expiry policy is.

**Comment by Djfe** [comment]
I think there is no policy
At least old tiles got only updated to the newest version for me if I deleted the folder.

**Comment by garvankeeley** [comment]
Thanks @djfe, we'll have to figure some expiration policy out in the app.

**Comment by crankycoder** [comment]
I'm now very sure that #869 is being reported because of this.

I stumbled last night, and the tiles are correctly updated on the web map, but my local instance of MozStumbler was not displaying the stumbles correctly based on the blue dots on the map view.

I've captured 3 screenshots. 

This is my MozStumbler the day _after_ I've done my stumble. I've highlighted areas where I would expect to see new blue dots.

![2014-10-06_16_40_43](https://cloud.githubusercontent.com/assets/4829/4529584/b3637806-4d78-11e4-93b2-03aead7fbcd6.png)

Here is a screenshot from https://location.services.mozilla.com/map for the same area, I've highlighted areas where new blue dots are appearing as expected.

![mls_-_map](https://cloud.githubusercontent.com/assets/4829/4529614/d46697d6-4d78-11e4-98e7-48d1801bb9b2.png)

And here is my MozStumbler again, after wiping out /sdcard/osmdroid/tiles which would force MozStumbler to download new stumbling coverage maps from the server.

![2014-10-06_16_47_07](https://cloud.githubusercontent.com/assets/4829/4529631/f3b4ad8a-4d78-11e4-8a8b-4c08401da240.png)

**Comment by sekanderb** [comment]
I have stumbled on the yellow marked line which can be viewed here: https://location.services.mozilla.com/map#13/23.7198/90.3751

![Gabtoli - Babubazar Beribadh](http://s4.postimg.org/gjfv5im0t/Untitled.png)

on the yellow line, there should have blue dots. But there is not! My speed was 4km/hr on bi-cycle

**Comment by Djfe** [comment]
#869 is something completely different, because nothing shows up in the upload queue of 0.30.0

this issue here is about the expiration policy which doesn't exist, has never existed
this issue here has always existed

#869 got introduced in the latest versions by the switch from a db to a file system based db

**Comment by crankycoder** [comment]
Duplicate of #957
