### ISSUE TITLE
Add stumbler version to the server requests

### ISSUE THREAD

**Issue by hannosch** [mozilla/MozStumbler#88]
In #87 @cpeterso mentioned that we might be seeing a bug from older clients. It would be good if we'd actually be able to tell that for debugging purposes.

Currently the server sees a general "Android" user-agent string, for example:

```
"POST /v1/submit HTTP/1.1" 204 0 "-" "Dalvik/1.6.0 (Linux; U; Android 4.0.4; ZTE V790 Build/IMM76D)"
"POST /v1/submit HTTP/1.1" 204 0 "-" "Dalvik/1.6.0 (Linux; U; Android 4.1.2; GT-I8190 Build/JZO54K)"
```

Maybe we could add a `MozStumbler 0.2.1` token to the user-agent.

**Comment by cpeterso** [comment]
Fixed by PR #87.
