### ISSUE TITLE
Preferences screen: gap (line on API 10) above button-style prefs (a.k.a. move leaderboard on api 10)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#887]
Here is how it looks on API level 10, on API levels above that, there is simply added space.

This is because on API 10, the leaderboard is a button in the settings because I need somewhere quick to put it. To hide this button the pref must be in a preference group, which when left with no title, creates a space. On API 11 and up, the space is transparent, on API 10, it is not as seen in the screen shot.

![screenshot 2014-09-26 14 29 51](https://cloud.githubusercontent.com/assets/5495083/4425616/b5ebe812-45ab-11e4-957e-6a385d206d94.png)

**Comment by crankycoder** [comment]
Closing as our UI has changed significantly, and nobody is complaining about this. :)
