### ISSUE TITLE
Let's move the upload button as well as the settings

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#893]
I'd like to move the upload button and the settings to the bottom of the metrics.  

Like what Pocketcasts does:

![xxernkibiyjl2duxxqscgysm2stddjotlvcg0vnvbvi](https://cloud.githubusercontent.com/assets/4829/4443561/4a83d496-47e9-11e4-9b71-640d97144b7c.png)

**Comment by garvankeeley** [comment]
@ryanfeeley is not a fan of the current upload button either. (nor am I, but leaving as-is for 1.0).

**Comment by Djfe** [comment]
I fav this as well.
Upload + statistics in the left sidebar would look great and you can access them more easily from the map/main activity by just swiping from the left of the device.

**Comment by rodmoreno** [comment]
@crankycoder maybe this should close.

**Comment by cascheberg** [comment]
@crankycoder Reminder: This issue was fixed and should be closed.
