### ISSUE TITLE
Android Studio: jars task isn't run by "Make Project" but *is* by "Run" or "Debug"

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#902]
The gradle updateJars should be run first, then assembleDebug. For unknown reasons, Studio will only run the second task for the Make Project command, but the Run/Debug commands will run both gradle tasks.
As long as you do Run or Debug once, the jars will be downloaded and Make Project will work from then on.

**Comment by crankycoder** [comment]
I'm quite sure this is a bug in android studio,  or at least a limitation of the way "make project" works. 

As far as I can tell,  the "make project" command doesn't honor the currently selected run configuration. 

Yay android.
