### ISSUE TITLE
Disallow running the app if no GPS is found

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#903]

**Comment by garvankeeley** [comment]
I think the play store flags can take care of this

**Comment by Djfe** [comment]
What about F-droid builds?
I mean this still could get implemented but with a lower priority

**Comment by crankycoder** [comment]
@djfe I'm going to say that if you're capable enough to use f-droid, you probably know enough that you don't want to use this app without a GPS.

**Comment by Djfe** [comment]
good point :+1:

**Comment by Djfe** [comment]
seems to be fixed ;)

**Comment by Djfe** [comment]
@crankycoder #1271 not everybody using f-droid or github seems to be capable enough ^^

**Comment by crankycoder** [comment]
We've got a permission in the manifest now that forces this.

![mozilla_stumbler_-_android_apps_on_google_play](https://cloud.githubusercontent.com/assets/4829/6696601/e0a930a4-ccc0-11e4-82ba-8184df92aff5.png)
