### ISSUE TITLE
Delete "This Session" section from MetricsView

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#917]
"This Session" provides confusing information to users.  It displays the cumulative data for the current location - that is a lat/long location.  So as wifi and cell towers blink into and out of visibility, the cell and wifi counts are strictly monotonically increasing.

That's just confusing - as the numbers at the top of the mapview show the more useful number of "What's visible now".  At the least, I can be fairly certain that we're going to get a bunch of user filed bugs as the view is just confusing.  What does "this session" mean?  Why are the counts different than the mapview?

Additionally, once the wifi and cell information is uploaded, you're going to see the cumulative numbers implicitly in the total count for all time records.

Let's just remove the "This Session" number from the MetricsView.  We can then file a separate bug to better use of the space like displaying unique cells and unique wifi counts.

**Comment by garvankeeley** [comment]
I agree we need to fix this ASAP. The numbers are confusing because some are sums of repeatedly observing the same thing and some are unique instances. 

In "this session" section, I like the observation count and the data size (to know how much network i am using). The others I will remove.

**Comment by garvankeeley** [comment]
For now, lets remove Cell Towers, Wifi access points, but leave Observations, since that is not ambiguous and also reports the amount of data,

low-hanging fruit bug, i will take it
