### ISSUE TITLE
Using the new maps based interface uses too much data

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/MozStumbler#928]
I tried the new maps based interface and have consumed 30 MB in a day. If this was my personal phone it would have consumed 6% of my monthly data cap. If I stumble this much I would exceed my monthly data cap in under 17 days.

**Comment by garvankeeley** [comment]
Thanks for the report, can you screenshot this? I use it daily, but only see a few hundred kb. If I delete the map tiles folder manually, I get 2 MB or so (at which point they are cached until I manually delete the tiles folder). Maybe we can add a debug setting to delete the map tiles and we can measure this more closely.

**Comment by kbrosnan** [comment]
![screenshot_2014-10-02-16-31-01](https://cloud.githubusercontent.com/assets/250273/4500128/4af28a12-4a8c-11e4-8d3d-144701ab6e9c.png)

I traveled from MV to SF (40 miles/70 km) + some walking around (<5 miles / 10 km) and checking on lightly stumbled areas.

**Comment by garvankeeley** [comment]
Oooh crap this is a lot of map downloading. My life occurs in a 5km radius.

**Comment by cascheberg** [comment]
I tried to avoid data usage by loading and caching the map over WiFi beforehand if I knew where I was traveling to during the day. It might be helpful to have a switch to only use cached map data.

**Comment by garvankeeley** [comment]
Fixed by https://github.com/mozilla/MozStumbler/pull/936. i hope.

**Comment by kbrosnan** [comment]
I don't think this is fixed I consumed 25MB on my Nexus 5 in one day. Similar to issue #970 .

**Comment by garvankeeley** [comment]
Eeek. Were you seeing low-res tiles during that time?

**Comment by kbrosnan** [comment]
I believe so. I only had about 3 zoom levels.

**Comment by garvankeeley** [comment]
With the low-res map, there should be a toast that pops up to say the map has switched. 
For me, a 25x25 km map on low-res is < 1MB of tiles.

It is _supposed_ to switch resolution based on the wifi state, so with no wifi, it switches to low res.

**Comment by garvankeeley** [comment]
Hmm, we should make the min zoom level not so low that it shows such a big area, if I pan around at the min zoom, which is ~25x25km on my screen, I can start loading tons of tiles. We would have to re-center the map also when switching to low-res.

**Comment by garvankeeley** [comment]
Dev note: ideal quick fix would be to trick OSMDroid into thinking that tile level 13 was for zoom levels 16 and up, and zoom levels 13-15 are tile level 8 (or so).
