### ISSUE TITLE
Stumbler should default to scanning when launched

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#93]
This would streamline the user experience by removing an extra step (pressing the "Start Scanning" button). The WiGLE stumbler does this, too.

**Comment by goldfndr** [comment]
The WiGLE stumbler doesn't always do this -- it depends on whether scanning is paused on the main screen, which is saved between runs. (PREF_SCAN_RUNNING in https://github.com/wiglenet/wigle-wifi-wardriving/blob/master/src/net/wigle/wigleandroid/ListActivity.java)

**Comment by PrzemoF** [comment]
Patch submitted: https://groups.google.com/d/msg/mozilla.dev.geolocation/4zmdfRFit6U/3usekkTXbDkJ

**Comment by hfiguiere** [comment]
@PrzemoF  Attachment are stripped by the mailing list. You should submit a pull request instead.

**Comment by cascheberg** [comment]
This was fixed in #1012
