### ISSUE TITLE
700 observations stuck in queue

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/MozStumbler#930]
Using 1.0, pressing the upload button does not upload the data.

**Comment by garvankeeley** [comment]
Yikes. Can you check the Settings>Log for messages? 

@crankycoder, what build tag is this? I'll take a look and see if something was unhooked in that build.

**Comment by kbrosnan** [comment]
The log is blank. Tried pressing the upload button and re-checking the log and it is still blank.

**Comment by garvankeeley** [comment]
Can you try toggle the scanning on and off and see what happens? This should also trigger an upload (although this case will respect the Settings>Auto-upload only on Wi-Fi)

**Comment by crankycoder** [comment]
@kbrosnan Which build is this?  We've never released a 1.0 version yet.

**Comment by kbrosnan** [comment]
Via dropbox from Karl.

**Comment by kbrosnan** [comment]
This has grown to over 1300 in queue.

**Comment by garvankeeley** [comment]
Should be fixed now.

**Comment by kbrosnan** [comment]
I have not seen this on v0.40.0, seemed fairly common on the build QE was handed.
