### ISSUE TITLE
Use MapBoxTileSource for map box tile layer

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#932]
OSMDroid has a built-in tile source where we just set the API key, and it looks better than the source we are using, as it has multiple content urls.

Requires a gradle change, so, hot potato to vng.

**Comment by crankycoder** [comment]
Marked as "WONTFIX"

Mapbox's own fork of osmdroid doesn't use multiple URLs.

https://github.com/mapbox/mapbox-android-sdk/blob/mb-pages/MapboxAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java#L12
