### ISSUE TITLE
Side pannel data is blank with don't keep activites

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/MozStumbler#950]
![screenshot_2014-10-07-15-09-51](https://cloud.githubusercontent.com/assets/250273/4551252/e24a0d78-4e6e-11e4-9c73-18631e8b2ee5.png)
- Enable the Android developer options
- Select the "Do not keep activities" option
- Launch MozStumbler
- open the sidebar note the values
- Switch apps or open the Settings or Leaderboard
- open the sidebar, no data is shown

**Comment by crankycoder** [comment]
Merged in #964
