### ISSUE TITLE
Crash when trying to automatically upload data

### ISSUE THREAD

**Issue by Hugo14** [mozilla/MozStumbler#951]
Im running Android 4.3 offical rom on a Sony Xperia SP. MozStumbler crashes randomly when connected to a wifi, but not when using mobile data. Also it happens everytime I have been away for a while and I connect a wifi network. Since I have the option of upload only on wifi activated, I suspect it happens when MozStumbler tries to upload data automatically.

**Comment by garvankeeley** [comment]
Is still happening with 0.40.1?

**Comment by Hugo14** [comment]
My Mozstumbler About says it's version 0.20.9. I installed Mozstumbler from F-Droid. Could you remind whoever is in charge to update the version in that repository?

**Comment by Hugo14** [comment]
I just checked F-Droid and version 0.30.0 is available but version 0.20.9 is the prefered version. Someone should take a look at the state of Mozstumbler in that repository.

**Comment by cascheberg** [comment]
@Hugo14 F-Droid currently has the latest version 1.5.4 available. That version supports sending crash reports from within the app. Is there any reason to keep this issue open?

**Comment by Hugo14** [comment]
Nope, Ive actuallized and everything seems fine.
