### ISSUE TITLE
Store tiles in getExternalCacheDir() (with a fallback to getCacheDir())

### ISSUE THREAD

**Issue by cascheberg** [mozilla/MozStumbler#955]
It is not possible to clear the MozStumbler (v0.40.0.0) map cache without clearing all app settings, since map cache is listed as "Data".

![mozstumbler](https://cloud.githubusercontent.com/assets/3845150/4557826/bfca611c-4ed7-11e4-8349-51ae16704502.png)

**Comment by crankycoder** [comment]
Are you trying to clear the tiles because we are not properly expiring tiles or is this just a request to get button to clear all tile data?

**Comment by cascheberg** [comment]
Mainly it's just nice to be able to clear cache data.
After just checking the code and the Android API, I'd guess that you could basically replace `getFilesDir()` with `getCacheDir()` in cc0d97c100ea24349b95ffd502c5e50b16545b2e, if available. If so, I'd like to try to prepare a pull request.

**Comment by garvankeeley** [comment]
Cache Dir: By its name, I would assume the OS has control over deleting this. If so, map tiles could disappear unexpectedly. Is that the case?

A button on the developer screen to clear the cache would be a good solution as a place to try out features. The button would call delete on the tiles directory.

**Comment by cascheberg** [comment]
Yes, from the API description:

>  These files will be ones that get deleted first when the device runs low on storage. There is no guarantee when these files will be deleted. Note: you should not rely on the system deleting these files for you

Running low on storage appears to be a good reason to clear map tiles though. Or are there any problems with that? Firefox and Google Maps also seem to use this kind of caching.

**Comment by garvankeeley** [comment]
Sounds useful. I wonder why OSMDroid doesn't use this?

edit: to answer my own question 2 seconds later :), OSMDroid has a 'shared' map concept, where by design, all OSMDroid apps can share tiles.
