### ISSUE TITLE
Fix count looks good, but no pure-GPS arriving

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/MozStumbler#956]
v0.40.0

Have 13 to 20 satellites visible 0 observations.

**Comment by kbrosnan** [comment]
Nexus 5 upgraded over v0.30 and many prior releases

**Comment by garvankeeley** [comment]
Uh oh. Is this always the case? Or intermittent? Any particular steps to repro?
To clarify: you see a number next to the GPS icon (which is the number of fixes), but no collection. 
Can you see anything in the log? The log should be blank, which means no pure GPS has arrived.

**Comment by kbrosnan** [comment]
Yes on both counts. If I recall from my earlier discussions with dougt that that observations should happen when there are 6-7 fixes. I get 0 observations. Nothing in the log.

**Comment by garvankeeley** [comment]
It makes sense that with a few satellite fixes you should get pure GPS location. But, with nothing in the log, that indicates to me the app hasn't received a non-fused (a.k.a Google Location Service assisted) location. 
We should try to report this state in the app, where satellite fixes are good, but the locations are still coming as "fused".

**Comment by kbrosnan** [comment]
This is pure user error. 

I turned on a Galaxy S5 and I thought I turned on my Nexus 5 to report my commute into the office. The Galaxy S5 was reporting so I thought something serious was wrong. However must have missed the button or something in the rush to get out the door. I successfully stumbled during lunch on my Nexus 5.

**Comment by garvankeeley** [comment]
Thanks! One down.
