### ISSUE TITLE
Consider changing some key terms in the UI

### ISSUE THREAD

**Issue by hannosch** [mozilla/MozStumbler#958]
The MozStumbler UI refers to "Cell towers", "WiFi access points" and "observations".

I'd like to suggest to use "Cell networks", "WiFi networks" and "reports" instead to better match the terms used on the service side.

For the first two: We don't actually ever count physical objects like towers, but merely logical networks. In most cases one physical station supports multiple logical networks. But there are also cases like CDMA networks where one logical network is shared across multiple different cell towers.

For "observations" we have a semantic conflict with the service side. There are two different things we deal with. One is a lat/lon pair with many attached cell and wifi networks. The other is a single cell/wifi network with attached lat/lon pair.

MozStumbler calls the first thing an observation, while ichnaea calls this a report. MozStumbler doesn't have a term for the "one cell/wifi at a lat/lon" construct, but this is what ichnaea calls an observation.

Related to this you get one point on the leaderboard per "ichnaea report".

**Comment by garvankeeley** [comment]
Will change the cell and wi-fi terms. The 'observations' to 'reports' I want to discuss with UX first. Wording was more of an issue before the app was changed to be graphically-driven, now, I don't think it matters as much to the app. 
The app still lacks a walkthrough screen, or some first-time use door hangars, either of which are the hallmark of a friendly app. We need folks to know the "observations/reports" is the count in the upper right and also the dots on the map, this number is the one you want to maximize, and it increases by walking around when you have a good GPS signal. Everything else, is secondary.
