### ISSUE TITLE
"Using high/low resolution map" notification is displayed even when MozStumbler is running in the background

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#965]
Do we really need to notify the user when we're switching between high and low resolution tiles? Why does the user care? They should be accustomed to map apps swapping in different resolution tiles. :)

**Comment by garvankeeley** [comment]
The fact it was popping up all the time was a bug. We are doing another build today or tomorrow with all the little bits we missed like this.

**Comment by garvankeeley** [comment]
Need to fix the fact it shows in the background. Taking it.

**Comment by garvankeeley** [comment]
addressed as part of
https://github.com/garvankeeley/MozStumbler/commit/65d3a3037c7d89ba2aa8fc5de05a284f9049e2f9

Comment on this (the video) shows the label on the map being used to indicate low/high res:
https://github.com/mozilla/MozStumbler/pull/998#issuecomment-59134925
