### ISSUE TITLE
User agent: add android device info

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#968]

**Comment by garvankeeley** [comment]
Lets do this for today's build

**Comment by garvankeeley** [comment]
Acra uses
https://github.com/ACRA/acra/blob/f00c49d13e6302942c91b53545d847f37485ea95/src/main/java/org/acra/collector/CrashReportDataFactory.java#L182

So, this: android.os.Build.FINGERPRINT

**Comment by crankycoder** [comment]
This is covered in #971 by using System.getProperty('http.agent')
