### ISSUE TITLE
"no-map" mode

### ISSUE THREAD

**Issue by naoliv** [mozilla/MozStumbler#970]
Isn't it possible to have the old interface where no map is visible when we only want to record locations?

It would be good if MozStumbler could also avoid downloading anything (the maps) when I want only to scan locations.

**Comment by grrrrr** [comment]
Hopefully this will be an early fix.  Having just upgraded, Mozstumbler on a 20 minute drive ate through 60MB of a 250MB monthly cap.

**Comment by Djfe** [comment]
Got partially fixed now ;)
The coverage layer tiles are now down to 25% of the original filesize.
Mozilla/Ichnaea#326

**Comment by garvankeeley** [comment]
This is now an option on the developer screen, will be in the next build
