### ISSUE TITLE
no fixed/visible satellites counter anymore and no evidence of an established GPS connection

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#973]
since 0.40.0 it is not possible anymore to see the number of fixed as well as visible satellites anymore

and it is impossible to see whether the device lost the GPS connection without moving and taking a look at the map/log at the same time

**Comment by Djfe** [comment]
to point this out further:
just having a number of 3 satellites there isn't enough, the GPS needs to be established and can be lost again, but if I loose my GPS connection then the old number (for example 8 satellites) still stands next to the gps icon (the label's text is still "8")

**Comment by garvankeeley** [comment]
We could fit a fractional view there of fixes / visible
