### ISSUE TITLE
should we switch the map library? (after 1.0)

### ISSUE THREAD

**Issue by Djfe** [mozilla/MozStumbler#978]
I think after the 1.0 release we should debate about whether we keep osmdroid or switch to a different library, since it seemed to me like it produced lots of issues in the past and doesn't bring the needed performance
I heard of issues with map layers
#976, too, but it's a small issue

libraries I've found so far:
- libosmscout http://wiki.openstreetmap.org/wiki/Libosmscout
- opentouchmap http://www.opentouchmap.org/ (webview, I think)
- nutiteq www.nutiteq.com/

Nutiteq looks the most interesting to me.
It's native and supports a lot of stuff (including vector graphics).
It supports older Android versions as well as newer ones.

**Comment by Djfe** [comment]
forgot about #620 
and #582

**Comment by crankycoder** [comment]
I don't think we should bother switching at this point.  Licensing issues and technical requirements - especially on lower end devices is a problem no matter which codebase we use.
