### ISSUE TITLE
Add a paranoid logging mode

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#979]
It's sometimes difficult to reproduce errors because of a number of problems:
- Android is inconsistent.  We've seen devices that collect NMEA data, others that don't.
- ichnaea itself is also a limiting factor.  The server does a JSON schema validation, and will return a 20x success response to the client.  The user of MozStumbler has a reasonable expectation that the data is 'valid'.  However, ichnaea does other kinds of data level validation in an asynchronous worker pool which may invalidate those collections.

I propose that we add a paranoid logging mode where we simply keep all the stumble records on the filesystem so that we can analyze the raw data.  I don't see any other way of debugging problems that are happening in the ichnaea worker pool.

This preference should be defaulted to OFF as it's going to eat storage space, but we also need to have a reasonable maximum storage cap.  As it stands, we gzip all data already - so I think setting something like a 5MB collection size is reasonable.  Any larger than that and I doubt we'd be able to do any kind of analysis anyway.

**Comment by Djfe** [comment]
could you pls prepare #3 along the side so that users could later on just check a setting named "keep uploaded data to show on map/export/whatever"?

**Comment by crankycoder** [comment]
Closing this as exporting the stumble logs in #1255 and replaying them with #1191 should provide the same capability.
