### ISSUE TITLE
On/Off switch behaves weird

### ISSUE THREAD

**Issue by VolMi** [mozilla/MozStumbler#980]
I was convinced that MozStumbler 0.40+ is completely nonfunctional because of the way the on/off switch (mis)behaves:
When I _move_ the switch off-> on, nothing happens, except the switch is turned on. I just realized I have to _tap_ it, then MozStumbler is actually activated.
It's a Sumsum Galaxy S4 mini (i9195) with CM11 nightly from 10th October.

**Comment by Djfe** [comment]
I find it rather interesting that swiping that button even works :)
It's probably just the wrong listener that is used.

**Comment by crankycoder** [comment]
@VolMi can you try with a stock firmware?  The switch widget only listens for `onClick` as per the spec at: http://developer.android.com/guide/topics/ui/controls/togglebutton.html

**Comment by cascheberg** [comment]
I can reproduce this on stock Android 4.4.4, Nexus 4

**Comment by crankycoder** [comment]
Does swiping toggle switches work anywhere on your phone?  Swiping the
toggle works fine over here on a nexus 4 running stock 4.4.4.

What build number of Android do you see in "About phone"?  I have KTU84P

**Comment by cascheberg** [comment]
Same build number. For example swiping the WiFi toggle switch in the Android menu works perfectly fine.
Swiping the switch in MozStumbler looks the same, but the icons stay transparent/grey. If I then click the switch anywhere, it quickly jumps to off, then back to on, and icons turn black. Interesting is that I cannot swipe the switch to off if the app is actually running, it always automatically switches back to on after a very short time (< 1 second).
